unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group Number</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_ID__r.Name &amp; &#39;-&#39; &amp;  Member_Number_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group / Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <label>Member Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Related_Full_Membership__c.field-meta.xml
<CustomField>
    <fullName>Related_Full_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is required when the Type field equals &quot;Additional Store&quot; or &quot;Special Composite&quot;.</description>
    <inlineHelpText>This field is required when the Type field equals &quot;Additional Store&quot; or &quot;Special Composite&quot;.</inlineHelpText>
    <label>Related Full Membership</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Related 20 Group Member Account must have Type of &quot;Full Member&quot; , and Status of &quot;Active&quot;.</errorMessage>
        <filterItems>
            <field>X20_Groups_Member__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>X20_Groups_Member__c.Type__c</field>
            <operation>equals</operation>
            <value>Full Member</value>
        </filterItems>
        <filterItems>
            <field>X20_Groups_Member__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>X20_Groups_Member__c</referenceTo>
    <relationshipLabel>20 Groups Member Accounts (Related 20 Group Member Account)</relationshipLabel>
    <relationshipName>X20_Groups_Member_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date the member joined the 20 Group</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Global_Product_Service_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>(&quot;Candidate&quot;)</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Member_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Global_Product_Service_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Active - Don&#39;t Bill</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Disconnected</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
        <isActive>false</isActive>
        <label>Suspended</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <customValue>
        <fullName>Honorary</fullName>
        <isActive>false</isActive>
        <label>Honorary</label>
    </customValue>
    <masterLabel>Global Product/Service Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Member_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Candidate</fullName>
    </customValue>
    <customValue>
        <fullName>Full Member</fullName>
    </customValue>
    <customValue>
        <fullName>Special_Composite</fullName>
        <label>Special Composite</label>
    </customValue>
    <customValue>
        <fullName>Additional_Store</fullName>
        <label>Additional Store</label>
    </customValue>
    <customValue>
        <fullName>1/2 Member</fullName>
        <isActive>false</isActive>
        <label>1/2 Member</label>
    </customValue>
    <customValue>
        <fullName>Associate Member</fullName>
        <isActive>false</isActive>
        <label>Associate Member</label>
    </customValue>
    <customValue>
        <fullName>Composite Only Member</fullName>
        <isActive>false</isActive>
        <label>Composite Only Member</label>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Member</fullName>
        <isActive>false</isActive>
        <label>Member</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <masterLabel>NCM Member Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CustomerSearchServiceTests.cls
@isTest
public class CustomerSearchServiceTests {
    
    @TestSetup
    static void makeData(){
        SampleDataFactory.create20GroupAccountData();
    }

    @isTest
    static void searchByCustNameTest(){

        // Get a known good 20G member Account that was created in TestSetup above.
        X20_Groups_Member__c test20GMemberAcct = [SELECT Account__c, Account__r.Name, Account__r.ShippingPostalCode 
                                                  FROM X20_Groups_Member__c LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = test20GMemberAcct.Account__r.Name;
        searchContext.postalCode = test20GMemberAcct.Account__r.ShippingPostalCode;

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('200', resp.statusCode, 'The response was not 200 (success).');
        Assert.areNotEqual(null, resp.results);
        Assert.areEqual(1, resp.results.size());

    }
    
    // Test: Pass in a customerName and only send in the first 5 characters.  
    @isTest
    static void searchByCustNameTest_2(){

        // Get a known good 20G member Account that was created in TestSetup above.
        X20_Groups_Member__c test20GMemberAcct = [SELECT Account__c, Account__r.Name, Account__r.ShippingPostalCode 
                                                  FROM X20_Groups_Member__c LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = test20GMemberAcct.Account__r.Name;
        searchContext.postalCode = test20GMemberAcct.Account__r.ShippingPostalCode;
        searchContext.customerName = 'SOME OTHER NAME'; // This should get trimmed to 5 charaters. 
        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.'); 
        Assert.areEqual(null, resp.results);

    }
                                              
    // TEST: if(customerName.length() < 5) 'Please provide at least 5 characters for the customer name.';
    @isTest
    static void searchByCustNameTest_3(){

        // Get a known good 20G member Account that was created in TestSetup above.
        X20_Groups_Member__c test20GMemberAcct = [SELECT Account__c, Account__r.Name, Account__r.ShippingPostalCode 
                                                  FROM X20_Groups_Member__c LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = test20GMemberAcct.Account__r.Name;
        searchContext.postalCode = test20GMemberAcct.Account__r.ShippingPostalCode;
        searchContext.customerName = 'Bob'; // 
        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.'); 
        Assert.areEqual(null, resp.results);

    }

    @isTest
    static void searchByMemberNumberTest(){

        // Get a known good Account that was created in TestSetup above.
        //Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        X20_Groups_Member__c testMember = [SELECT Account__c,Group_Member_Number__c 
                                           FROM X20_Groups_Member__c 
                                           WHERE Group_Member_Number__c != null limit 1];
        
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = null;
        searchContext.postalCode = null;
        searchContext.memberNumber = testMember.Group_Member_Number__c;

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('200', resp.statusCode, 'The response was not 200 (success).');
        Assert.areNotEqual(null, resp.results);
        Assert.areEqual(1, resp.results.size());

    }
    
    // Test: 'Member Number invalid. Member number must be in the form ####-##';
    @isTest
    static void searchByMemberNumberTest_2(){

        // Get a known good Account that was created in TestSetup above.
        //Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        X20_Groups_Member__c testMember = [SELECT Account__c,Group_Member_Number__c FROM X20_Groups_Member__c WHERE Group_Member_Number__c != null limit 1];
        
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = null;
        searchContext.postalCode = null;
        //searchContext.memberNumber = testMember.Group_Member_Number__c;
        searchContext.memberNumber = '12345'; // Wrong format and length 

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.');
        Assert.areEqual(null, resp.results);

	}
    

    @isTest
    static void searchByCustomerIdTest(){

        // Get a known good Account that was created in TestSetup above.
        Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerId = testAccount.Id;
           
        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('200', resp.statusCode, 'The response was not 200 (success).');
        Assert.areNotEqual(null, resp.results);
        Assert.areEqual(1, resp.results.size());

    }
    
    // TEST: if(customerId.length() < 15); 'Invalid record id length: '
    @isTest
    static void searchByCustomerIdTest_2(){

        // Get a known good Account that was created in TestSetup above.
        Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        // searchContext.customerId = testAccount.Id;
        searchContext.customerId = '123456789'; 
           
        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.'); 
        Assert.areEqual(null, resp.results);

    }
    
    // TEST: if(postalCode.length() < 5); 'Postal code must be at 5 characters in length'
    @isTest
    static void searchByMemberNumberTest_3(){

        // Get a known good Account that was created in TestSetup above.
        //Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        X20_Groups_Member__c testMember = [SELECT Account__c,Group_Member_Number__c FROM X20_Groups_Member__c WHERE Group_Member_Number__c != null limit 1];
        
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = 'Lionel';
        searchContext.postalCode = '1234'; // Should trigger error message. postalCode is < 5.

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.');
        Assert.areEqual(null, resp.results);

	}  
    
    
   
    // TEST: BuildingNumber is provided?. 
    @isTest
    static void searchByMemberNumberTest_4(){

        // Get a known good Account that was created in TestSetup above.
        //Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        X20_Groups_Member__c testMember = [SELECT Account__c,Group_Member_Number__c FROM X20_Groups_Member__c WHERE Group_Member_Number__c != null limit 1];
        
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = 'Lionel';
        searchContext.postalCode = '12345'; 
        searchContext.buildingNumber = '12345';

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();
		
        
        System.debug('CUSTOMER SEARCH SERVICE TEST: RESPONSE STATUS CODE: ' + resp.statusCode);
        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.');
        Assert.areEqual(null, resp.results);

	}
    
      
    // TEST: BuildingNumber is NOT provided?. 
    @isTest
    static void searchByMemberNumberTest_5(){

        // Get a known good Account that was created in TestSetup above.
        //Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        X20_Groups_Member__c testMember = [SELECT Account__c,Group_Member_Number__c FROM X20_Groups_Member__c WHERE Group_Member_Number__c != null limit 1];
        
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = 'Lionel';
        searchContext.postalCode = '12345'; 
        //searchContext.buildingNumber = '12345';

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();
		
        
        System.debug('CUSTOMER SEARCH SERVICE TEST 5: RESPONSE STATUS CODE: ' + resp.statusCode);
        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.');
        Assert.areEqual(null, resp.results);

	}

    @isTest
    static void invalidSearchTest(){

        // Get a known good Account that was created in TestSetup above.
        Account testAccount = [SELECT Id, Name, ShippingPostalCode FROM Account LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = testAccount.Name;
        searchContext.postalCode = null;//testAccount.ShippingPostalCode;

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('500', resp.statusCode, 'The response should indicate an error.');
        Assert.areEqual(null, resp.results);

    }
    
    
    @isTest
    static void specialCompositeMemberIsReturnedTest(){

        // When a 20G Member of type "Special Composite" is searched for, the api will return a result.

        // Get a known good 20G member Account that was created in TestSetup above.
        X20_Groups_Member__c test20GMemberAcct = [SELECT Account__c, Account__r.Name, Account__r.ShippingPostalCode, Group_ID__c 
                                                  FROM X20_Groups_Member__c LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = test20GMemberAcct.Account__r.Name;
        searchContext.postalCode = test20GMemberAcct.Account__r.ShippingPostalCode;
        
        // Create a 20 Group Member Account (the Related Full Membership account) to bypass VR: 'Type_Field_Cannot_Be_Updated'. 
        // The user is not able to update the Type field to ‘Additional Store’ or ‘Special Composite’ 
        // without populating the ‘Related Full Membership' lookup field.
        // The 'Related Full Membership' lookup has a filter where Status = 'Active', Type = 'Full Member', and Record Id's do not match.
        X20_Groups_Member__c test20GMemberAcct2 = new X20_Groups_Member__c(
            Group_ID__c = test20GMemberAcct.Group_ID__c,
            Account__c = test20GMemberAcct.Account__c,
            Member_Number__c = 1,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addYears(3),
            Type__c = 'Full Member',
            Status__c = 'Active'
        );
        insert(test20GMemberAcct2);

        // Change the test member type to "Special Composite", and populate the lookup to pass VR for this test.
        test20GMemberAcct.Type__c = 'Special_Composite';
        test20GMemberAcct.Related_Full_Membership__c = test20GMemberAcct2.Id;
        update(test20GMemberAcct);

        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('200', resp.statusCode, 'The response was not 200 (success).');
        Assert.areNotEqual(null, resp.results);
        Assert.areEqual(1, resp.results.size());

    }
    
    @isTest
    static void candidateMemberIsReturnedTest(){

        // When a 20G Member of type "Candidate" is searched for, the api will return a result.

        // Get a known good 20G member Account that was created in TestSetup above.
        X20_Groups_Member__c test20GMemberAcct = [SELECT Account__c, Account__r.Name, Account__r.ShippingPostalCode 
                                                  FROM X20_Groups_Member__c LIMIT 1];
        CustomerSearchService.CustomerSearchContext searchContext = new CustomerSearchService.CustomerSearchContext();
        searchContext.customerName = test20GMemberAcct.Account__r.Name;
        searchContext.postalCode = test20GMemberAcct.Account__r.ShippingPostalCode;

        // Change the test member type to "Candidate" for this test.
        test20GMemberAcct.Type__c = 'Candidate';
        update(test20GMemberAcct);


        // Create a response variable to hold the results of our search method call.
        CustomerSearchService.CustomerSearchResponse resp = new CustomerSearchService.CustomerSearchResponse();

        Test.startTest();
            resp = CustomerSearchService.search(searchContext);
        Test.stopTest();

        // Did the search return the expected account as a customer result?
        Assert.areEqual('200', resp.statusCode, 'The response was not 200 (success).');
        Assert.areNotEqual(null, resp.results);
        Assert.areEqual(1, resp.results.size());

    }
    
}