unpackaged/main/default/objects/Client_Case_Relation__c/Client_Case_Relation__c.object-meta.xml
<CustomObject>
    <label>Client Case Relation</label>
    <nameField>
        <displayFormat>CCR-{00000000}</displayFormat>
        <label>Client Case Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Case Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Case_Relation__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>Client Case Relations</relationshipLabel>
    <relationshipName>Client_Case_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/clientCasesTest.cls
@isTest (SeeAllData=true)
public class clientCasesTest {
    static testMethod void TestclientCases(){
        test.startTest();
        
        id recId = [select axcessa_Store__c from Client_Case_Relation__c where axcessa_Store__c != null limit 1].axcessa_Store__c;
        list<Client_Support_Ticket__c> cases = clientCasesController.getClientCases(recId);
        
        test.stopTest();
    }
}