unpackaged/main/default/objects/Account/fields/Accounting_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Invoice_Name__c</fullName>
    <description>A field for accounting&#39;s use to add an internal name for a Company to the Invoice.</description>
    <label>Accounting Invoice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Validated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Account_Name__c</fullName>
    <description>Admin enters legal entity name here</description>
    <inlineHelpText>Admin enters legal entity name here</inlineHelpText>
    <label>Validated Account Name</label>
    <length>73</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nickname of the contact.</description>
    <inlineHelpText>Please enter the nickname of the contact</inlineHelpText>
    <label>Nickname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>to update the city go to the hotel that is listed in the hotel/Meeting Location field and update the city on the physical address</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <formula>X20_Group__r.Group_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <formula>IF(
NOT(ISBLANK( X20_Group__c )),
 X20_Group__r.Name,
IF(
NOT(ISBLANK( Proprietary_Group__c )),
 Proprietary_Group__r.Group_Number__c  ,
&quot;&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Owner__c.field-meta.xml
<CustomField>
    <fullName>Group_Owner__c</fullName>
    <formula>IF(ISBLANK(X20_Group__r.NCM_Proprietor__r.FirstName),Proprietary_Group__r.Group_Owner__r.FirstName &amp; &quot; &quot; &amp; Proprietary_Group__r.Group_Owner__r.LastName,X20_Group__r.NCM_Proprietor__r.FirstName &amp; &quot; &quot; &amp; 
X20_Group__r.NCM_Proprietor__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Owner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Proprietary_Group__c.field-meta.xml
<CustomField>
    <fullName>Proprietary_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietary Group</label>
    <referenceTo>Proprietary_Group__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State(old)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Populated with Account Physical Address.</description>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Populated with Account Physical Address Abbreviation.</description>
    <label>State</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/Proprietary_Group__c.object-meta.xml
<CustomObject>
    <label>Proprietary Group</label>
    <nameField>
        <label>Proprietary  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proprietary Groups</relationshipLabel>
    <relationshipName>Proprietary_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Special Bill</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proprietary Groups</relationshipLabel>
    <relationshipName>Proprietary_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <label>Group Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Group_Owner__c.field-meta.xml
<CustomField>
    <fullName>Group_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM Associates</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proprietary Groups (Group Owner)</relationshipLabel>
    <relationshipName>Proprietary_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Meetings_per_Year__c.field-meta.xml
<CustomField>
    <fullName>Meetings_per_Year__c</fullName>
    <label>Meetings per Year</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rate_Type__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly Fixed Dealer Rate</fullName>
            </value>
            <value>
                <fullName>Monthly Fixed Group Rate</fullName>
            </value>
            <value>
                <fullName>Monthly Rate Schedule</fullName>
            </value>
            <value>
                <fullName>Moratorium - Monthly Fixed Dealer Rate</fullName>
            </value>
            <value>
                <fullName>Moratorium - Monthly Fixed Group Rate</fullName>
            </value>
            <value>
                <fullName>Special Bill - Per Attendee</fullName>
            </value>
            <value>
                <fullName>Special Bill - Per Day</fullName>
            </value>
            <value>
                <fullName>Special Bill - Per Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/recordTypes/Monthly.recordType-meta.xml
<RecordType>
    <fullName>Monthly</fullName>
    <active>true</active>
    <label>Monthly</label>
</RecordType>

unpackaged/main/default/objects/Proprietary_Group__c/recordTypes/Quarterly.recordType-meta.xml
<RecordType>
    <fullName>Quarterly</fullName>
    <active>true</active>
    <label>Quarterly</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <description>User three alpha initials</description>
    <inlineHelpText>User three alpha initials</inlineHelpText>
    <label>Initials</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PropGroupControllerTest.cls
@isTest
public class PropGroupControllerTest {
   
    @TestSetup
    static void testSetup() {

        /* NCM Account & Contacts */
        Account ncmAccount = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Management Group').getRecordTypeId(),
            Name = 'NCM Associates',
            Validated_Account_Name__c = 'NCM Associates',
            Accounting_Invoice_Name__c = 'NCM Associates',
            Legal_Entity_Name__c = 'NCM Associates',
            AccountSource = 'Marketing', // required
            Industry = 'Other', // required
            BillingStreet = '4717 Grand Ave., Ste 500',
            BillingCity = 'Kansas City',
            BillingState = 'Missouri',
            BillingPostalCode = '64112'
        );
        insert(ncmAccount);
		
        // This section is needed to get past the Contact on Edit/Create Process Builders. 
        List<User> ncmUsers = new List<User>();
        Profile coordinatorProfile = [SELECT Id FROM Profile WHERE Name = 'NCM Coordinator'];                
        User ncmUser = new user(
            ProfileID = coordinatorProfile.Id,
            Username = 'bbillings@ncm.com',
            FirstName = 'Barney',
            LastName = 'Billings',
            Initials__c = 'BXB',
            Email = 'mdemeglio@ncmassociates.com',
            Street = '4717 Grand Ave., Ste 500',
            City = 'Kansas City',
            State = 'Missouri',
            PostalCode = '64112',
            Alias = 'test456',
            CommunityNickname = 'test456',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        ncmUsers.add(ncmUser);
            
        User ncmUser2 = new user(
            ProfileID = coordinatorProfile.Id,
            Username = 'tChavez@ncm.com',
            FirstName = 'Tommy',
            LastName = 'Chavez',
            Initials__c = 'TLC',
            Email = 'tChavez@ncmassociates.com',
            Street = '4717 Grand Ave., Ste 500',
            City = 'Kansas City',
            State = 'Missouri',
            PostalCode = '64112',
            Alias = 'test457',
            CommunityNickname = 'test457',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        ncmUsers.add(ncmUser2);
        insert(ncmUsers);

        /* NCM Contacts (Need atleast two)*/
        List<Contact> ncmContacts = new List<Contact>();
        Contact ncmContact = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId(),
            AccountId = ncmAccount.Id,
            User_ID__c = ncmUser.Id,
            FirstName = 'Barney',
            Lastname = 'Billingsly',
            Email = 'barney.billingsly@ncmassociates.com',
            MailingStreet = '4717 Grand Ave., Ste 500',
            MailingCity = 'Kansas City',
            MailingState = 'Missouri',
            MailingPostalCode = '64112', 
            Nickname__c = 'Billings', 
            Title = 'Manager'          
        );
        ncmContacts.add(ncmContact);
        
        // Has Nickname
        Contact ncmContact2 = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId(),
            AccountId = ncmAccount.Id,
            User_ID__c = ncmUser2.Id,
            FirstName = 'Tommy',
            Lastname = 'Chavez',
            Email = 'tommy.chavez@ncmassociates.com',
            MailingStreet = '4717 Grand Ave., Ste 500',
            MailingCity = 'Kansas City',
            MailingState = 'Missouri',
            MailingPostalCode = '64112', 
            Nickname__c = 'Tommynickname', 
            Title = 'Manager'          
        );
        ncmContacts.add(ncmContact2);
        insert(ncmContacts);

        String propGroupRecordTypeId = Schema.SObjectType.Proprietary_Group__c.getRecordTypeInfosByName().get('Quarterly').getRecordTypeId();
        // Create Prop Group where ncmContact is the orignal Group Owner.
        Proprietary_Group__c testPropGroup = new Proprietary_Group__c(
            RecordTypeId = propGroupRecordTypeId,
            Name = 'Central Auto Group - Proprietary Group',
            Group_Name__c = 'Central Auto Group - Proprietary Group',
            Group_Number__c = '8888',
            Group_Owner__c = ncmContact.Id, 
            Meetings_per_Year__c = 4,
            Account__c = ncmAccount.Id,
            Billing_Frequency__c = 'Quarterly',
            Contact__c = ncmContact.Id,
            Street__c = ncmAccount.BillingStreet,
            City__c = ncmAccount.BillingCity,
            State__c = ncmAccount.BillingState,
            Postal_Code__c = ncmAccount.BillingPostalCode,
            Rate_Type__c = 'Monthly Rate Schedule'
        );
        insert(testPropGroup);
      
        String retailEngagementRecType = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        List<Engagement__c> newEngagements = new List<Engagement__c>();
        
        Engagement__c testEngagement = new Engagement__c(
            RecordTypeId = retailEngagementRecType,
            Name = 'Sample Engagement 1',
            Proprietary_Group__c = testPropGroup.Id,
            Account__c = ncmAccount.Id,
            Status__c = 'Tentative',
            Engagement_Type__c = '20 Group',
            Engagement_Description__c = 'Regular',
            Engagement_Owner__c = ncmContact.Id,
            City__c = 'Dallas',
            State_pl__c = 'TX',
            Country_pl__c = 'United States',
            Engagement_Start_Date__c = System.today().addDays(10),
            Engagement_Start__c = System.today().addDays(10), 
            Engagement_End__c = System.today().addDays(20)
        );
        newEngagements.add(testEngagement);   
        insert(newEngagements);

        String engAttendeeRecordTypeId = Schema.SObjectType.Engagement_Attendee__c.getRecordTypeInfosByName().get('Institute - Training Subscription Seats').getRecordTypeId();
        
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(
            Name = 'Test Attendee',
            Account__c = ncmAccount.Id,
            Attendance_Status__c = 'Pending Class',
            Attendee_Type__c = 'Moderator',
            Engagement__c = testEngagement.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__c = ncmContact.Id,
            Contact_Email__c = ncmContact.Email,
            Financial_Data_Account__c = ncmAccount.Id,
            Financial_Data_Number__c = 'FD1232',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        insert(attendee);
    }
	
    // When the Group Owner is changed, add them as an Engagement Attendee to all the Engagements that are in the future with
    // the Status of 'Tentative’, 'Firm’, or 'Cancellation Inquiry’.
    // The old Group Owner should have their Engagement Attendee - Attendance Status changed to 'Cancelled'.
    @isTest
    static void groupOwnerChangedTest() {

        List<Contact> contacts = [SELECT Id, FirstName, LastName, Nickname__c FROM Contact ORDER BY FirstName];
        Contact oldContact = contacts[0]; // Barney
        Contact newContact = contacts[1]; // Tommy

        // Verify only one Moderator exists, and its assinged to the old Group Owner. 
        List<Engagement_Attendee__c> initialModerators = [
            SELECT Id, Contact__c, Attendance_Status__c FROM Engagement_Attendee__c WHERE Attendee_Type__c = 'Moderator'
        ];
        System.assertEquals(1, initialModerators.size(), 'There should be one initial Moderator.');
        System.assertEquals(oldContact.Id, initialModerators[0].Contact__c, 'Initial Moderator should be the old Group Owner.');

        // Update the Group Owner to the new contact
        Proprietary_Group__c propGroup = [SELECT Id, Group_Owner__c FROM Proprietary_Group__c WHERE Group_Owner__c = :oldContact.Id LIMIT 1];
        propGroup.Group_Owner__c = newContact.Id;

        Test.startTest();
            update propGroup;
        Test.stopTest();
        
        // The old one should have Attendance Status = 'Cancelled'.
        Engagement_Attendee__c cancelledAttendee = [
            SELECT Id, Contact__c, Engagement__c, Attendance_Status__c
            FROM Engagement_Attendee__c
            WHERE Contact__c =:oldContact.Id AND Attendee_Type__c = 'Moderator'LIMIT 1
        ];
        
        System.debug('Check the cancelledAttendee Attendance Status. It should be set to "Cancelled" ' + cancelledAttendee.Attendance_Status__c);
        System.assertEquals('Cancelled', cancelledAttendee.Attendance_Status__c, 'The old Group Owner/Engagement Attendee Attendance Status should be Cancelled');
        
    }
    
    // Added more Asserts to verify Collateral Name, Arrival, and Departure Dates on the newly created Attendee. 
    @isTest
    static void checkEngagementAttendeeFieldsTest() {

        List<Contact> contacts = [SELECT Id, FirstName, LastName, Nickname__c FROM Contact ORDER BY FirstName];
        Contact oldContact = contacts[0]; // Barney
        Contact newContact = contacts[1]; // Tommy 

        // Update the Group Owner to the new contact
        Proprietary_Group__c propGroup = [SELECT Id, Group_Owner__c FROM Proprietary_Group__c WHERE Group_Owner__c = :oldContact.Id LIMIT 1];
        propGroup.Group_Owner__c = newContact.Id;

        Test.startTest();
            update propGroup;
        Test.stopTest();

        // Check that the Moderator now reflects the new Group Owner
        Engagement_Attendee__c updatedModerator = [
            SELECT Id, Contact__c, Contact__r.Nickname__c, Contact__r.LastName, Collateral_Name__c, Engagement__c, 
                   Arrival__c, Departure__c, Engagement__r.Engagement_Start__c, Engagement__r.Engagement_End__c 
            FROM Engagement_Attendee__c 
            WHERE Contact__c =:newContact.Id AND Attendee_Type__c = 'Moderator'LIMIT 1
        ];
        
        // Verify the new Engagement Attendee fields match for ticket SALES - 2060. 
        System.assertEquals(updatedModerator.Collateral_Name__c, updatedModerator.Contact__r.Nickname__c + ' ' + updatedModerator.Contact__r.LastName, 'Check Collateral Name');
        System.assertEquals(updatedModerator.Engagement__r.Engagement_Start__c.addDays(-1), updatedModerator.Arrival__c, 'The new Attendee Arrival Date should be the day prior of the Engagement Start Date.');
        System.assertEquals(updatedModerator.Engagement__r.Engagement_End__c, updatedModerator.Departure__c, 'The new Attendee Departure__c Date should be the day of the Engagement End Date.');
    }

}