unpackaged/main/default/objects/Account/fields/Accounting_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Invoice_Name__c</fullName>
    <description>A field for accounting&#39;s use to add an internal name for a Company to the Invoice.</description>
    <label>Accounting Invoice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NCMI_Client_Code__c.field-meta.xml
<CustomField>
    <fullName>NCMI_Client_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary field for WinMasters integration to evaulate if the account has NCMi services</description>
    <label>NCMI Client (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Validated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Account_Name__c</fullName>
    <description>Admin enters legal entity name here</description>
    <inlineHelpText>Admin enters legal entity name here</inlineHelpText>
    <label>Validated Account Name</label>
    <length>73</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needing Validation</fullName>
                <default>true</default>
                <label>Needing Validation</label>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Credit Card Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Department__c.field-meta.xml
<CustomField>
    <fullName>NCM_Department__c</fullName>
    <label>Department (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Department</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Title__c.field-meta.xml
<CustomField>
    <fullName>NCM_Title__c</fullName>
    <label>Title (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NCM_Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NCM_Title</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/Training_Subscription__c.object-meta.xml
<CustomObject>
    <label>Training Subscription</label>
    <nameField>
        <label>Training Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Subscriptions</relationshipLabel>
    <relationshipName>Annuals_Training_SubscriptionsD_IE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Subscriptions</relationshipLabel>
    <relationshipName>Annuals_Training_Subscriptions_DIE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Fixed Ops</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

unpackaged/main/default/objects/Training_Subscription_Account__c/Training_Subscription_Account__c.object-meta.xml
<CustomObject>
    <description>Accounts authorized to enroll under a Training Subscription</description>
    <label>Training Subscription Account</label>
    <nameField>
        <label>Training Subscription Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Training_Subscription_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Billing Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Training_Subscription_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Subscription_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Training_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription__c</fullName>
    <label>Training Subscription Term</label>
    <referenceTo>Training_Subscription_Term__c</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Subscription_Sub_Accts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/Training_Subscription_Term__c.object-meta.xml
<CustomObject>
    <description>Institute Training Subscriptions terms and authorized accounts</description>
    <label>Training Subscription Term</label>
    <nameField>
        <label>Training Subscription Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Annuals_Training_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Annuals_Training_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>if(
    Term__c=&quot;Termed&quot;,
    Termination_Date__c , 
    if(
        Term__c = &quot;1 Month&quot;, 
        DATE(
            YEAR(
                ADDMONTHS(TODAY(), 1)
            ),
            MONTH(
                ADDMONTHS(TODAY(), 1)
            ),
            DAY(
                End_Date_Code__c
            )
        ),
        End_Date_Code__c 
    )
)</formula>
    <label>Current Term Ends</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/End_Date_Code__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Code__c</fullName>
    <description>This is the original 1 year End date derived from Start Date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Training_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription__c</fullName>
    <label>Training Subscription</label>
    <referenceTo>Training_Subscription__c</referenceTo>
    <relationshipLabel>Training Subscription Terms</relationshipLabel>
    <relationshipName>Training_Subscription_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/recordTypes/Monthly.recordType-meta.xml
<RecordType>
    <fullName>Monthly</fullName>
    <active>true</active>
    <label>Monthly</label>
</RecordType>

unpackaged/main/default/globalValueSets/NCM_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>BDC/Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Body Shop/Collision</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial/Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>F&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>New Car</fullName>
    </customValue>
    <customValue>
        <fullName>Parts</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Used/Pre-Owned Car</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Values for all NCM Classification Departments</description>
    <masterLabel>NCM Department</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Title.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Payable</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Receivable</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Director</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor/Consultant/Writer</fullName>
    </customValue>
    <customValue>
        <fullName>Advocate</fullName>
    </customValue>
    <customValue>
        <fullName>Area Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Office Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Service Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Director</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Billing/Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Business Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cashier</fullName>
    </customValue>
    <customValue>
        <fullName>CEO/ Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>CFO/ Chief Financial Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>CIO</fullName>
    </customValue>
    <customValue>
        <fullName>Clerk/Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Collections Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <description>Values for all NCM Classification Titles</description>
    <masterLabel>NCM Title</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TrainingSubscriptionAccountMonitor_Tests.cls
@isTest 
public class TrainingSubscriptionAccountMonitor_Tests {
    @testSetup
    static void testSetup(){
        
        // Normal Account
        Account activeAccount = new Account(
            Name = 'Active Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId(),
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            Validated_Account_Name__c = 'Sample Auto Group',
            Accounting_Invoice_Name__c = 'Sample Auto Group, Inc',
            Legal_Entity_Name__c = 'Sample Auto Group, Inc',
            AccountSource = 'Marketing', // required
            Industry = 'Auto Retail New', // required
            Franchise_s__c = 'Chevrolet',
            NumberOfEmployees = 400,
            AnnualRevenue = 30000000.00,
            NCMI_Client_Code__c = True
        );
        insert(activeAccount);

        
        
        // Primary Contact
        Contact activeContact = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId(),
            FirstName = 'Marv',
            LastName = 'Sampleton',
            Title = 'CEO',
            NCM_Department__c = 'Executive',
            NCM_Title__c = 'Owner',
            AccountId = activeAccount.Id,
            Email = 'marv.sampleton@ncmassociates.com',
            MailingStreet = '100 Automotive Way',
            MailingCity = 'Southport',
            MailingState = 'North Carolina',
            MailingPostalCode = '28461'
        );
        insert(activeContact);

        
        
        // Billing Account
        Billing_Account__c activeBillingAcct = new Billing_Account__c(
            Account__c = activeAccount.Id,
            Billing_Street__c = activeAccount.BillingStreet,
            Billing_City__c = activeAccount.BillingCity,
            Billing_State_Province__c = activeAccount.BillingState,
            Billing_Zip_Postal_Code__c = activeAccount.BillingPostalCode,
            Billing_Country__c = activeAccount.BillingCountry,
            Primary_Contact__c = activeContact.Id,
            Status__c = 'Validated'
        );
        insert(activeBillingAcct);
        

        // Add the Primary Billing Account (Finance Account) to the parent account.
        activeAccount.Primary_Billing_Account__c = activeBillingAcct.Id;
        update(activeAccount);
        
        

        Training_Subscription__c testTS1 = new Training_Subscription__c(
        	RecordTypeId = Schema.SObjectType.Training_Subscription__c.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
        	Account__c = activeAccount.Id,
            Contact__c = activeContact.Id,
            Plan__c = 'Basic',
            Start_Date__c = Date.today().addDays(-1),
            End_Date__c = Date.today().addYears(1),
            Price__c = 500.00
        );
        insert(testTS1);
        
        
        // Training Subscription Terms
        Training_Subscription_Term__c testTST1 = new Training_Subscription_Term__c(
            RecordTypeId = Schema.SObjectType.Training_Subscription_Term__c.getRecordTypeInfosByName().get('Monthly').getRecordTypeId(),
        	Account__c = activeAccount.Id,
            Contact__c = activeContact.Id,
            Start_Date__c = Date.today(),
            End_Date_Code__c = Date.today().addYears(1),
            Training_Subscription__c = testTS1.Id
        );
        insert(testTST1);
        // Training_Subscription_Term__c testTST2 = new Training_Subscription_Term__c(
        //     RecordTypeId = Schema.SObjectType.Training_Subscription_Term__c.getRecordTypeInfosByName().get('Monthly').getRecordTypeId(),
        // 	Account__c = activeAccount.Id,
        //     Contact__c = activeContact.Id,
        //     Start_Date__c = Date.today().addDays(-90),
        //     End_Date_Code__c = Date.today(),
        //     Training_Subscription__c = testTS1.Id
        // );
        // tstList.add(testTST2);
        
        // insert(tstList);
        


        // TSAs
        Training_Subscription_Account__c testTSA1 = new Training_Subscription_Account__c(
        	RecordTypeId = Schema.SObjectType.Training_Subscription_Account__c.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
        	Account__c = activeAccount.Id,
            Billing_Account__c = activeBillingAcct.Id,
            Contact__c = activeContact.Id,
            End_Date__c = Date.today().addYears(1),
            Training_Subscription__c = testTST1.Id
        );
        insert(testTSA1);

        // Training_Subscription_Account__c testTSA2 = new Training_Subscription_Account__c(
        // 	RecordTypeId = Schema.SObjectType.Training_Subscription_Account__c.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
        // 	Account__c = activeAccount.Id,
        //     Billing_Account__c = activeBillingAcct.Id,
        //     Contact__c = activeContact.Id,
        //     End_Date__c = Date.today().addYears(1),
        //     Training_Subscription__c = testTST2.Id
        // );
        // tsaList.add(testTSA2);

        // Training_Subscription_Account__c testTSA3 = new Training_Subscription_Account__c(
        // 	RecordTypeId = Schema.SObjectType.Training_Subscription_Account__c.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
        // 	Account__c = activeAccount.Id,
        //     Billing_Account__c = activeBillingAcct.Id,
        //     Contact__c = activeContact.Id,
        //     End_Date__c = Date.today().addYears(1),
        //     Training_Subscription__c = testTST3.Id
        // );
        // tsaList.add(testTSA3);
        
        // insert(tsaList);        
        
    }


    @isTest
    private static void tsaIsStartingTest(){
        
        Test.startTest();
            Database.executeBatch(new TrainingSubscriptionAccountMonitorBatch());
        Test.stopTest();

        Account acctResult = [select ncmi_client_code__c from account];
        Assert.areEqual(true, acctResult.NCMI_Client_Code__c,'NCMI Client Code should be true since the TST starts today.');   

    }
    
    
    @isTest
    private static void tsaIsEndingTest(){
        
        Account testAcct = [select id, ncmi_client_code__c from account];
        testAcct.NCMI_Client_Code__c = true;
        update(testAcct);
        
        Training_Subscription_Term__c tst = [select id from Training_Subscription_Term__c];
        tst.Start_Date__c = Date.today().addYears(-1);
        tst.End_Date_Code__c = Date.today();
        update(tst);
        
        Test.startTest();
            Database.executeBatch(new TrainingSubscriptionAccountMonitorBatch());
        Test.stopTest();

        Account acctResult = [select ncmi_client_code__c from account];
        Assert.areEqual(false, acctResult.NCMI_Client_Code__c,'NCMI Client Code should be true since the TST starts today.');   

    }
}