unpackaged/main/default/objects/Account/fields/Accounting_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Invoice_Name__c</fullName>
    <description>A field for accounting&#39;s use to add an internal name for a Company to the Invoice.</description>
    <label>Accounting Invoice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Validated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Account_Name__c</fullName>
    <description>Admin enters legal entity name here</description>
    <inlineHelpText>Admin enters legal entity name here</inlineHelpText>
    <label>Validated Account Name</label>
    <length>73</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Department__c.field-meta.xml
<CustomField>
    <fullName>NCM_Department__c</fullName>
    <label>Department (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Department</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Title__c.field-meta.xml
<CustomField>
    <fullName>NCM_Title__c</fullName>
    <label>Title (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NCM_Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NCM_Title</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Country_pl__c.field-meta.xml
<CustomField>
    <fullName>Country_pl__c</fullName>
    <defaultValue>&#39;United States&#39;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Description__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Description__c</fullName>
    <label>Engagement Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Engagement_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Variable Operations</fullName>
            </value>
            <value>
                <fullName>Fixed Operations</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>F&amp;I Department</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Regular Cycle Mtg.</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Controller</fullName>
            </value>
            <value>
                <fullName>Agenda</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20 Group</fullName>
            </value>
            <value>
                <fullName>Executive Coaching</fullName>
            </value>
            <value>
                <fullName>Group Review</fullName>
            </value>
            <value>
                <fullName>Managerial Coaching</fullName>
            </value>
            <value>
                <fullName>Special Meeting (20 Group)</fullName>
            </value>
            <value>
                <fullName>Special Meeting (Dealer)</fullName>
            </value>
            <value>
                <fullName>Special Meeting (Dealer Group)</fullName>
            </value>
            <value>
                <fullName>Special Meeting (Dealer – OEM Program)</fullName>
                <label>Special Meeting (Dealer - OEM Program)</label>
            </value>
            <value>
                <fullName>Special Meeting (Virtual SubGroup)</fullName>
            </value>
            <value>
                <fullName>Star Consulting</fullName>
            </value>
            <value>
                <fullName>Candidate Call</fullName>
            </value>
            <value>
                <fullName>NCMi</fullName>
                <isActive>false</isActive>
                <label>NCMi</label>
            </value>
            <value>
                <fullName>Professional Services</fullName>
                <isActive>false</isActive>
                <label>Professional Services - 20 Group Training</label>
            </value>
            <value>
                <fullName>Special</fullName>
                <isActive>false</isActive>
                <label>Special</label>
            </value>
            <value>
                <fullName>Standard</fullName>
                <isActive>false</isActive>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State_pl__c.field-meta.xml
<CustomField>
    <fullName>State_pl__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_pl__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/NCM_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>BDC/Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Body Shop/Collision</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial/Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>F&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>New Car</fullName>
    </customValue>
    <customValue>
        <fullName>Parts</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Used/Pre-Owned Car</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Values for all NCM Classification Departments</description>
    <masterLabel>NCM Department</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Title.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Payable</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Receivable</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Director</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor/Consultant/Writer</fullName>
    </customValue>
    <customValue>
        <fullName>Advocate</fullName>
    </customValue>
    <customValue>
        <fullName>Area Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Office Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Service Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Director</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Billing/Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Business Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cashier</fullName>
    </customValue>
    <customValue>
        <fullName>CEO/ Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>CFO/ Chief Financial Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>CIO</fullName>
    </customValue>
    <customValue>
        <fullName>Clerk/Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Collections Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <customValue>
        <fullName>President</fullName>
    </customValue>
    <description>Values for all NCM Classification Titles</description>
    <masterLabel>NCM Title</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/userAvailabilityTest.cls
@isTest 
public class userAvailabilityTest {

    @TestSetup
    static void makeData(){

        String acctRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId();
        Account parentAccount = new Account(
            RecordTypeId = acctRecType,
            Name = 'Sample Auto Group',
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            Validated_Account_Name__c = 'Sample Auto Group',
            Accounting_Invoice_Name__c = 'Sample Auto Group, Inc',
            Legal_Entity_Name__c = 'Sample Auto Group, Inc',
            AccountSource = 'Marketing', // required
            Industry = 'Auto Retail New', // required
            Franchise_s__c = 'Chevrolet;Dodge;Ford;Jeep',
            NumberOfEmployees = 400,
            AnnualRevenue = 30000000.00,
            c2g__codaAccountTradingCurrency__c = 'USD'
        );
        insert(parentAccount);
    

        // Contacts
        String contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();
        List<Contact> newContacts = new List<Contact>();

        Contact sampleContact1 = new Contact(
            RecordTypeId = contactRecType,
            FirstName = 'Marv',
            LastName = 'Sampleton',
            Title = 'CEO',
            NCM_Department__c = 'Executive',
            NCM_Title__c = 'Owner',
            AccountId = parentAccount.Id,
            Email = 'marv.sampleton@ncmassociates.com',
            MailingStreet = '100 Automotive Way',
            MailingCity = 'Southport',
            MailingState = 'North Carolina',
            MailingPostalCode = '28461'
        );
        newContacts.add(sampleContact1);

        Contact sampleContact2 = new Contact(
            RecordTypeId = contactRecType,
            FirstName = 'Fran',
            LastName = 'Sampleton',
            Title = 'President',
            NCM_Department__c = 'Executive',
            NCM_Title__c = 'President',
            AccountId = parentAccount.Id,
            Email = 'fran.sampleton@ncmassociates.com',
            MailingStreet = '100 Automotive Way',
            MailingCity = 'Southport',
            MailingState = 'North Carolina',
            MailingPostalCode = '28461'
        );
        newContacts.add(sampleContact2);
        insert(newContacts);
        
    }


    static testMethod void testGetUserAvailability() {
        Test.startTest();

        List<string> rles = userAvailabilityController.getRoles();
        userAvailabilityController.getUserAvailability('Salesforce Administrator', Datetime.now(), datetime.now().addDays(3));

        test.stopTest();
    }

    static testMethod void testAttendee() {
        
        Test.startTest();
        
        // Engagement__c eng = new Engagement__c();
        // eng.Engagement_Start__c = datetime.now();
        // eng.Engagement_End__c = Datetime.now().addDays(1);
        // insert eng;
        String retailEngagementRecType = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        List<Engagement__c> newEngagements = new List<Engagement__c>();
        Engagement__c eng = new Engagement__c(
            RecordTypeId = retailEngagementRecType,
            Name = 'Sample Engagement 1',
            Status__c = 'Tentative',
            Engagement_Type__c = '20 Group',
            Engagement_Description__c = 'Regular',
            Engagement_Start__c = datetime.now(),
            Engagement_End__c = Datetime.now().addDays(1),
            Country_pl__c = 'United States',
            State_pl__c = 'NC'
        );
        insert(eng);

        eng = userAvailabilityController.getEngagementValues(eng.Id);

        Contact testContact = [select id from contact limit 1];

        Engagement_Attendee__c att = new Engagement_Attendee__c();
        att.Engagement__c = eng.id;
        att.Contact__c = testContact.id;
        att = userAvailabilityController.upsertAtt(att);

        Test.stopTest();
        
    }

    static testMethod void cheating() {
        
        Test.startTest();
        userAvailabilityController.cheatingTests();
        Test.stopTest();

        }

}