unpackaged/main/default/objects/Account/fields/Accounting_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Invoice_Name__c</fullName>
    <description>A field for accounting&#39;s use to add an internal name for a Company to the Invoice.</description>
    <label>Accounting Invoice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Validated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Account_Name__c</fullName>
    <description>Admin enters legal entity name here</description>
    <inlineHelpText>Admin enters legal entity name here</inlineHelpText>
    <label>Validated Account Name</label>
    <length>73</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nickname of the contact.</description>
    <inlineHelpText>Please enter the nickname of the contact</inlineHelpText>
    <label>Nickname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Description__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Description__c</fullName>
    <label>Engagement Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Engagement_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Variable Operations</fullName>
            </value>
            <value>
                <fullName>Fixed Operations</fullName>
            </value>
            <value>
                <fullName>Service Advisor</fullName>
            </value>
            <value>
                <fullName>F&amp;I Department</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Regular Cycle Mtg.</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Controller</fullName>
            </value>
            <value>
                <fullName>Agenda</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Owner__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM Associates</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements (Owner)</relationshipLabel>
    <relationshipName>Engagements_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20 Group</fullName>
            </value>
            <value>
                <fullName>Executive Coaching</fullName>
            </value>
            <value>
                <fullName>Group Review</fullName>
            </value>
            <value>
                <fullName>Managerial Coaching</fullName>
            </value>
            <value>
                <fullName>Special Meeting (20 Group)</fullName>
            </value>
            <value>
                <fullName>Special Meeting (Dealer)</fullName>
            </value>
            <value>
                <fullName>Special Meeting (Dealer Group)</fullName>
            </value>
            <value>
                <fullName>Special Meeting (Dealer – OEM Program)</fullName>
                <label>Special Meeting (Dealer - OEM Program)</label>
            </value>
            <value>
                <fullName>Special Meeting (Virtual SubGroup)</fullName>
            </value>
            <value>
                <fullName>Star Consulting</fullName>
            </value>
            <value>
                <fullName>Candidate Call</fullName>
            </value>
            <value>
                <fullName>NCMi</fullName>
                <isActive>false</isActive>
                <label>NCMi</label>
            </value>
            <value>
                <fullName>Professional Services</fullName>
                <isActive>false</isActive>
                <label>Professional Services - 20 Group Training</label>
            </value>
            <value>
                <fullName>Special</fullName>
                <isActive>false</isActive>
                <label>Special</label>
            </value>
            <value>
                <fullName>Standard</fullName>
                <isActive>false</isActive>
                <label>Standard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <formula>X20_Group__r.Group_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <description>What is the Name of the Group?</description>
    <label>Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Support_Staff__c.field-meta.xml
<CustomField>
    <fullName>NCM_Support_Staff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who assists client and NCM Proprietor for this service or product</description>
    <label>Client Support Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group (Support Staff)</relationshipLabel>
    <relationshipName>X20_Group1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Shipping_Not_Required__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Not_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipping Not Required</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Group Start Date</description>
    <inlineHelpText>Group Start Date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New Group - Acquiring</fullName>
            </value>
            <value>
                <fullName>New Group - Didn&#39;t Start</fullName>
            </value>
            <value>
                <fullName>New Group - Prospecting</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>New Group - Overflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <description>User three alpha initials</description>
    <inlineHelpText>User three alpha initials</inlineHelpText>
    <label>Initials</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TwentyGroupControllerTest.cls
@isTest
public class TwentyGroupControllerTest {
   
    @TestSetup
    static void testSetup() {

      /* NCM Account & Contacts */
        Account ncmAccount = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Management Group').getRecordTypeId(),
            Name = 'NCM Associates',
            Validated_Account_Name__c = 'NCM Associates',
            Accounting_Invoice_Name__c = 'NCM Associates',
            Legal_Entity_Name__c = 'NCM Associates',
            AccountSource = 'Marketing', // required
            Industry = 'Other', // required
            BillingStreet = '4717 Grand Ave., Ste 500',
            BillingCity = 'Kansas City',
            BillingState = 'Missouri',
            BillingPostalCode = '64112'
        );
        insert(ncmAccount);
		
        // This section is needed to get past the Contact on Edit/Create Process Builders. 
        List<User> ncmUsers = new List<User>();
        Profile coordinatorProfile = [SELECT Id FROM Profile WHERE Name = 'NCM Coordinator'];                
        User ncmUser = new user(
            ProfileID = coordinatorProfile.Id,
            Username = 'bbillings@ncm.com',
            FirstName = 'Barney',
            LastName = 'Billings',
            Initials__c = 'BXB',
            Email = 'mdemeglio@ncmassociates.com',
            Street = '4717 Grand Ave., Ste 500',
            City = 'Kansas City',
            State = 'Missouri',
            PostalCode = '64112',
            Alias = 'test456',
            CommunityNickname = 'test456',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        ncmUsers.add(ncmUser);
            
        User ncmUser2 = new user(
            ProfileID = coordinatorProfile.Id,
            Username = 'tChavez@ncm.com',
            FirstName = 'Tommy',
            LastName = 'Chavez',
            Initials__c = 'TLC',
            Email = 'tChavez@ncmassociates.com',
            Street = '4717 Grand Ave., Ste 500',
            City = 'Kansas City',
            State = 'Missouri',
            PostalCode = '64112',
            Alias = 'test457',
            CommunityNickname = 'test457',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8'
        );
        ncmUsers.add(ncmUser2);
        insert(ncmUsers);

        /* NCM Contacts */
        List<Contact> ncmContacts = new List<Contact>();
        Contact ncmContact = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId(),
            AccountId = ncmAccount.Id,
            User_ID__c = ncmUser.Id,
            FirstName = 'Barney',
            Lastname = 'Billings',
            Email = 'barney.billings@ncmassociates.com',
            MailingStreet = '4717 Grand Ave., Ste 500',
            MailingCity = 'Kansas City',
            MailingState = 'Missouri',
            MailingPostalCode = '64112', 
            Nickname__c = 'Billings', 
            Title = 'Manager'          
        );
        ncmContacts.add(ncmContact);
        
        Contact ncmContact2 = new Contact(
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId(),
            AccountId = ncmAccount.Id,
            User_ID__c = ncmUser2.Id,
            FirstName = 'Tommy',
            Lastname = 'Chavez',
            Email = 'tommy.chavez@ncmassociates.com',
            MailingStreet = '4717 Grand Ave., Ste 500',
            MailingCity = 'Kansas City',
            MailingState = 'Missouri',
            MailingPostalCode = '64112', 
            Nickname__c = 'Tommynickname', 
            Title = 'Manager'          
        );
        ncmContacts.add(ncmContact2);
        insert(ncmContacts);

        // Create 20 Group where ncmContact is the orignal Group Owner.
        String twentyGroupRecType = Schema.SObjectType.Twenty_Groups__c.getRecordTypeInfosByName().get('20 Group').getRecordTypeId();
        Twenty_Groups__c test20Group = new Twenty_Groups__c(
            RecordTypeId = twentyGroupRecType,
            Status__c = 'Active',
            Start_Date__c = Date.today().addMonths(-6),
            Name = '2001',
            Group_Name__c = '2001',
            Shipping_Not_Required__c = False,
            NCM_Proprietor__c = ncmContact.Id, 
            NCM_Support_Staff__c = ncmContact.Id
        );
        insert(test20Group);

        String retailEngagementRecType = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        List<Engagement__c> newEngagements = new List<Engagement__c>();
        
        Engagement__c testEngagement = new Engagement__c(
            RecordTypeId = retailEngagementRecType,
            Name = 'Sample Engagement 1',
            X20_Group__c = test20Group.Id,
            Account__c = ncmAccount.Id,
            Status__c = 'Tentative',
            Engagement_Type__c = '20 Group',
            Engagement_Description__c = 'Regular',
            Engagement_Owner__c = ncmContact.Id,
            City__c = 'Dallas',
            State_pl__c = 'TX',
            Country_pl__c = 'United States',
            Engagement_Start_Date__c = System.today().addDays(10),
            Engagement_Start__c = System.today().addDays(10), 
            Engagement_End__c = System.today().addDays(20)
        );
        newEngagements.add(testEngagement);
        insert(newEngagements);

        String engAttendeeRecordTypeId = Schema.SObjectType.Engagement_Attendee__c.getRecordTypeInfosByName().get('Institute - Training Subscription Seats').getRecordTypeId();
        
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(
            Name = 'Test Attendee',
            Account__c = ncmAccount.Id,
            Attendance_Status__c = 'Pending Class',
            Attendee_Type__c = 'Moderator',
            Engagement__c = testEngagement.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__c = ncmContact.Id,
            Contact_Email__c = ncmContact.Email,
            Financial_Data_Account__c = ncmAccount.Id,
            Financial_Data_Number__c = 'FD1232',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        insert(attendee);

    }

    // When the Group Owner is changed, add them as an Engagement Attendee to all the Engagements that are in the future with
    // the Status of 'Tentative’, 'Firm’, or 'Cancellation Inquiry’.
    // The old Group Owner should have their Engagement Attendee - Attendance Status changed to 'Cancelled'.
    @isTest
    static void groupOwnerChangedTest() {        
        List<Contact> contacts = [SELECT Id, FirstName, LastName, Nickname__c FROM Contact]; 
        Contact oldContact = contacts[0];
        Contact newContact = contacts[1]; 
    
        // Confirm initial state
        List<Engagement_Attendee__c> initialModerators = [
            SELECT Id, Contact__c 
            FROM Engagement_Attendee__c 
            WHERE Attendee_Type__c = 'Moderator'
        ];
        System.assertEquals(1, initialModerators.size(), 'There should be one initial Moderator before the group owner change.');
        System.assertEquals(oldContact.Id, initialModerators[0].Contact__c, 'Initial Moderator should be the old Group Owner.');
    
        // Fetch group and change the owner
        Twenty_Groups__c twentyGroup = [
            SELECT Id, NCM_Proprietor__c 
            FROM Twenty_Groups__c 
            WHERE NCM_Proprietor__c = :oldContact.Id  
            LIMIT 1
        ];
        twentyGroup.NCM_Proprietor__c = newContact.Id;
    
        Test.startTest();
            update(twentyGroup);
        Test.stopTest();
    
        // The old one should have Attendance Status = 'Cancelled'.
        Engagement_Attendee__c cancelledAttendee = [
            SELECT Id, Contact__c, Engagement__c, Attendance_Status__c
            FROM Engagement_Attendee__c
            WHERE Contact__c =:oldContact.Id AND Attendee_Type__c = 'Moderator'LIMIT 1
        ];
        System.debug('Check the cancelledAttendee Attendance Status. It should be set to "Cancelled" ' + cancelledAttendee.Attendance_Status__c);
        System.assertEquals('Cancelled', cancelledAttendee.Attendance_Status__c, 'The old Group Owner/Engagement Attendee Attendance Status should be Cancelled');
    }
    
    // Added more Asserts to verify Collateral Name, Arrival, and Departure Dates on the newly created Attendee. 
    @isTest
    static void checkEngagementAttendeeFieldsTest() {

        List<Contact> contacts = [SELECT Id, FirstName, LastName, Nickname__c FROM Contact ORDER BY FirstName ASC];
        Contact oldContact = contacts[0]; // Barney
        Contact newContact = contacts[1]; // Tommy 

        // Validate initial state
        List<Engagement_Attendee__c> initialModerators = [
            SELECT Id, Contact__c FROM Engagement_Attendee__c WHERE Attendee_Type__c = 'Moderator'
        ];
        System.assertEquals(1, initialModerators.size(), 'There should be one initial Moderator.');
        System.assertEquals(oldContact.Id, initialModerators[0].Contact__c, 'Initial Moderator should be the old Group Owner.');

        // Fetch group and change the owner
        Twenty_Groups__c twentyGroup = [
            SELECT Id, NCM_Proprietor__c 
            FROM Twenty_Groups__c 
            WHERE NCM_Proprietor__c = :oldContact.Id  
            LIMIT 1
        ];
        twentyGroup.NCM_Proprietor__c = newContact.Id;
    
        Test.startTest();
            update(twentyGroup);
        Test.stopTest();

        // Check that the Moderator now reflects the new Group Owner
        Engagement_Attendee__c updatedModerator = [
            SELECT Id, Contact__c, Contact__r.Nickname__c, Contact__r.LastName, Collateral_Name__c, Engagement__c, 
                   Arrival__c, Departure__c, Engagement__r.Engagement_Start__c, Engagement__r.Engagement_End__c 
            FROM Engagement_Attendee__c 
            WHERE Contact__c =:newContact.Id AND Attendee_Type__c = 'Moderator'LIMIT 1
        ];
        
        // Verify the new Engagement Attendee fields match for ticket SALES - 2060. 
        System.assertEquals(updatedModerator.Collateral_Name__c, updatedModerator.Contact__r.Nickname__c + ' ' + updatedModerator.Contact__r.LastName, 'Check Collateral Name');
        System.assertEquals(updatedModerator.Engagement__r.Engagement_Start__c.addDays(-1), updatedModerator.Arrival__c, 'The new Attendee Arrival Date should be the day prior of the Engagement Start Date.');
        System.assertEquals(updatedModerator.Engagement__r.Engagement_End__c, updatedModerator.Departure__c, 'The new Attendee Departure__c Date should be the day of the Engagement End Date.');
    }

}