unpackaged/main/default/objects/Account/fields/Accounting_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Invoice_Name__c</fullName>
    <description>A field for accounting&#39;s use to add an internal name for a Company to the Invoice.</description>
    <label>Accounting Invoice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Validated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Account_Name__c</fullName>
    <description>Admin enters legal entity name here</description>
    <inlineHelpText>Admin enters legal entity name here</inlineHelpText>
    <label>Validated Account Name</label>
    <length>73</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Department__c.field-meta.xml
<CustomField>
    <fullName>NCM_Department__c</fullName>
    <label>Department (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Department</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Title__c.field-meta.xml
<CustomField>
    <fullName>NCM_Title__c</fullName>
    <label>Title (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NCM_Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NCM_Title</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Franchise_s__c.field-meta.xml
<CustomField>
    <fullName>Franchise_s__c</fullName>
    <label>Franchise(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Automotive_Franchises</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/NCM_Lead_Entry__c.field-meta.xml
<CustomField>
    <fullName>NCM_Lead_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCM Lead Entry</label>
    <referenceTo>NCM_Lead_Entry__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/NCM_Lead_Entry__c.object-meta.xml
<CustomObject>
    <description>Module for NCM employees to add leads they wish to have submitted to the Sales Pipeline (Lead to Opportunity)</description>
    <label>NCM Lead</label>
    <nameField>
        <label>NCM Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCM Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field searches Salesforce for an existing Account in the system and populates all of the Company Fields if found.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NCM Leads</relationshipLabel>
    <relationshipName>NCM_Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field searches Salesforce for an existing Contact in the system and populates the contact info fields with the information we already have</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NCM Leads (Contact)</relationshipLabel>
    <relationshipName>NCM_Lead_Entries1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed__c</fullName>
    <label>Contract Signed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Binary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>NCM_Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>NCM_Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed__c</fullName>
    <label>Contract Signed? (Code)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Binary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Franchise_s__c.field-meta.xml
<CustomField>
    <fullName>Franchise_s__c</fullName>
    <label>Franchise(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Automotive_Franchises</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NCM_Lead_Entry__c.field-meta.xml
<CustomField>
    <fullName>NCM_Lead_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCM Lead Entry</label>
    <referenceTo>NCM_Lead_Entry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Automotive_Franchises.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Airstream</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Alliance</fullName>
    </customValue>
    <customValue>
        <fullName>Anheuser-Busch</fullName>
    </customValue>
    <customValue>
        <fullName>Artic Cat</fullName>
        <label>Arctic Cat</label>
    </customValue>
    <customValue>
        <fullName>Aston Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Auto Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive Group</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>BMW Motorcycle</fullName>
    </customValue>
    <customValue>
        <fullName>Body Shop</fullName>
    </customValue>
    <customValue>
        <fullName>BTA</fullName>
    </customValue>
    <customValue>
        <fullName>Bugatti</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Buy Here Pay Here</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Carquest</fullName>
    </customValue>
    <customValue>
        <fullName>Car Wash</fullName>
    </customValue>
    <customValue>
        <fullName>CASE</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Culligan</fullName>
    </customValue>
    <customValue>
        <fullName>Daewoo</fullName>
    </customValue>
    <customValue>
        <fullName>Detriot Diesel</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Dorsey</fullName>
    </customValue>
    <description>Client franchises</description>
    <masterLabel>Franchise</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Binary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Yes or No picklist</description>
    <masterLabel>Binary</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>BDC/Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Body Shop/Collision</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial/Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>F&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>New Car</fullName>
    </customValue>
    <customValue>
        <fullName>Parts</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Used/Pre-Owned Car</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Values for all NCM Classification Departments</description>
    <masterLabel>NCM Department</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Title.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Payable</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Receivable</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Director</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor/Consultant/Writer</fullName>
    </customValue>
    <customValue>
        <fullName>Advocate</fullName>
    </customValue>
    <customValue>
        <fullName>Area Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Office Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Service Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Director</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Billing/Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Business Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cashier</fullName>
    </customValue>
    <customValue>
        <fullName>CEO/ Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>CFO/ Chief Financial Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>CIO</fullName>
    </customValue>
    <customValue>
        <fullName>Clerk/Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Collections Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <description>Values for all NCM Classification Titles</description>
    <masterLabel>NCM Title</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/autoConvLdTest.cls
@isTest (SeeAllData=false)
public class autoConvLdTest{
    static testMethod void autoConvLdTest() {

        String acctRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId();
        String contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();
        
        Account acct = new Account(
            RecordTypeId = acctRecType,
            Name = 'Sample Auto Group',
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            Validated_Account_Name__c = 'Sample Auto Group',
            Accounting_Invoice_Name__c = 'Sample Auto Group, Inc',
            Legal_Entity_Name__c = 'Sample Auto Group, Inc',
            AccountSource = 'Marketing', // required
            Industry = 'Auto Retail New', // required
            Franchise_s__c = 'Chevrolet;Dodge;Ford;Jeep',
            NumberOfEmployees = 400,
            AnnualRevenue = 30000000.00
        );
        insert(acct);

        Contact con = new Contact(
            RecordTypeId = contactRecType,
            FirstName = 'Marv',
            LastName = 'Sampleton',
            Title = 'CEO',
            NCM_Department__c = 'Executive',
            NCM_Title__c = 'Owner',
            AccountId = acct.Id,
            Email = 'marv.sampleton@ncmassociates.com',
            MailingStreet = '100 Automotive Way',
            MailingCity = 'Southport',
            MailingState = 'North Carolina',
            MailingPostalCode = '28461'
        );
        insert con;

        Opportunity opp = new Opportunity(
            AccountId = acct.Id,
            CloseDate = Date.today(),
            StageName = 'Closed Won',
            Contract_Signed__c = 'Yes',
            Name = 'Test Opp'
        );
        insert opp;

        NCM_Lead_Entry__c nle = new NCM_Lead_Entry__c(Account__c = acct.Id, Contact__c = con.Id);
        
        List<Lead> lds = new List<Lead>();
        //[select id from Lead where Status != 'Qualified' limit 6];
        for(Integer i = 1; i <= 6; i++) {
            Lead l = new Lead(FirstName = 'First' + i, LastName = 'Last' + i, Company = 'Test Co. ' + i, NCM_Lead_Entry__c = nle.Id);
            lds.add(l);
        }
        insert lds;        
        
        List<AutoConvertLeads.vars> vars = new List<AutoConvertLeads.vars>();
        List<NCM_Lead_Entry__c> ncmLeads = new List<NCM_Lead_Entry__c>();
        
        for(Lead ld : lds) {
            AutoConvertLeads.vars var = new AutoConvertLeads.vars();
            var.ldId = ld.Id;
            vars.add(var);
            NCM_Lead_Entry__c ncmLead = new NCM_Lead_Entry__c(
                Account__c = acct.Id,
                Contact__c = con.Id,
                First_Name__c = ld.FirstName,
                Last_Name__c = ld.LastName,
                Lead__c = ld.Id
            );
            ncmLeads.add(ncmLead);
        }
        ncmLeads[0].Opportunity__c = opp.Id;
        insert ncmLeads;

        Lead ld1 = new Lead(
            Id = ncmLeads[0].Lead__c,
            NCM_Lead_Entry__c = ncmLeads[0].Id
        );
        update ld1;

        Test.startTest();
        try{
            AutoConvertLeads.LeadConvert(vars);
        } catch(DMLException er){
            system.debug(er);
        }
        
        Test.stopTest();

        Integer oppCount = [SELECT Id FROM Opportunity WHERE StageName = 'Closed Won'].Size();
        Assert.areEqual(1, oppCount);
    }
}