unpackaged/main/default/objects/Account/fields/Accounting_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Invoice_Name__c</fullName>
    <description>A field for accounting&#39;s use to add an internal name for a Company to the Invoice.</description>
    <label>Accounting Invoice Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Validated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Validated_Account_Name__c</fullName>
    <description>Admin enters legal entity name here</description>
    <inlineHelpText>Admin enters legal entity name here</inlineHelpText>
    <label>Validated Account Name</label>
    <length>73</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/CZ_CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CZ_CustomerId__c</fullName>
    <externalId>true</externalId>
    <label>CZ CustomerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Department__c.field-meta.xml
<CustomField>
    <fullName>NCM_Department__c</fullName>
    <label>Department (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Department</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/NCM_Title__c.field-meta.xml
<CustomField>
    <fullName>NCM_Title__c</fullName>
    <label>Title (NCM Classification)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NCM_Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>NCM_Title</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/NCM_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>BDC/Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Body Shop/Collision</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial/Fleet</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Service</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>F&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>New Car</fullName>
    </customValue>
    <customValue>
        <fullName>Parts</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Speaker</fullName>
    </customValue>
    <customValue>
        <fullName>Used/Pre-Owned Car</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Values for all NCM Classification Departments</description>
    <masterLabel>NCM Department</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Title.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Payable</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Receivable</fullName>
    </customValue>
    <customValue>
        <fullName>Administration Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative Director</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor/Consultant/Writer</fullName>
    </customValue>
    <customValue>
        <fullName>Advocate</fullName>
    </customValue>
    <customValue>
        <fullName>Area Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Office Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Service Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Director</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Manager</fullName>
    </customValue>
    <customValue>
        <fullName>BDC Rep</fullName>
    </customValue>
    <customValue>
        <fullName>Billing/Clerk</fullName>
    </customValue>
    <customValue>
        <fullName>Board Member</fullName>
    </customValue>
    <customValue>
        <fullName>Branch Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Business Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cashier</fullName>
    </customValue>
    <customValue>
        <fullName>CEO/ Chief Executive Officer</fullName>
    </customValue>
    <customValue>
        <fullName>CFO/ Chief Financial Officer</fullName>
    </customValue>
    <customValue>
        <fullName>Chairman</fullName>
    </customValue>
    <customValue>
        <fullName>CIO</fullName>
    </customValue>
    <customValue>
        <fullName>Clerk/Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Collections Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <description>Values for all NCM Classification Titles</description>
    <masterLabel>NCM Title</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CZ_LoadCustomerBatch_Test.cls
@isTest
public class CZ_LoadCustomerBatch_Test {
    
    @TestSetup
    static void makeData(){

        String acctRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId();
        Account parentAccount = new Account(
            RecordTypeId = acctRecType,
            Name = 'Sample Auto Group',
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            Validated_Account_Name__c = 'Sample Auto Group',
            Accounting_Invoice_Name__c = 'Sample Auto Group, Inc',
            Legal_Entity_Name__c = 'Sample Auto Group, Inc',
            AccountSource = 'Marketing', // required
            Industry = 'Auto Retail New', // required
            Franchise_s__c = 'Chevrolet;Dodge;Ford;Jeep',
            NumberOfEmployees = 400,
            AnnualRevenue = 30000000.00,
            c2g__codaAccountTradingCurrency__c = 'USD'
        );
        insert(parentAccount);
    

        // Contacts
        String contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();
        
        Contact sampleContact1 = new Contact(
            RecordTypeId = contactRecType,
            FirstName = 'Marv',
            LastName = 'Sampleton',
            Title = 'CEO',
            NCM_Department__c = 'Executive',
            NCM_Title__c = 'Owner',
            AccountId = parentAccount.Id,
            Email = 'marv.sampleton@ncmassociates.com',
            MailingStreet = '100 Automotive Way',
            MailingCity = 'Southport',
            MailingState = 'North Carolina',
            MailingPostalCode = '28461'
        );
        insert sampleContact1;

        Billing_Account__c ba = [SELECT Id, Name, Primary_Contact__c, CZ_CustomerId__c FROM Billing_Account__c WHERE RecordType.Name = 'Billing Account' LIMIT 1];
        ba.Primary_Contact__c = sampleContact1.Id;
        update ba;
    }


    @IsTest
    static void batchTest1(){      
        
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());
        
        Test.startTest();
        CZ_LoadCustomerBatch lcb = new CZ_LoadCustomerBatch();
        Database.executeBatch(lcb);
        Test.stopTest();
        
        Billing_Account__c ba2 = [SELECT Id, Name, Primary_Contact__c, CZ_CustomerId__c FROM Billing_Account__c WHERE RecordType.Name = 'Billing Account' LIMIT 1];
        Assert.areEqual('CUS-1234', ba2.CZ_CustomerId__c);
    }

    @IsTest
    static void batchTest2(){      
        
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());
        Billing_Account__c ba = [SELECT Id, Name, Primary_Contact__c, CZ_CustomerId__c FROM Billing_Account__c WHERE RecordType.Name = 'Billing Account' LIMIT 1];
        
        Test.startTest();
        CZ_LoadCustomerBatch lcb = new CZ_LoadCustomerBatch(ba.Id);
        lcb.activateNewCustomers = true;
        Database.executeBatch(lcb);
        Test.stopTest();
        
        Billing_Account__c ba2 = [SELECT Id, Name, Primary_Contact__c, CZ_CustomerId__c FROM Billing_Account__c WHERE RecordType.Name = 'Billing Account' LIMIT 1];
        Assert.areEqual('CUS-1234', ba2.CZ_CustomerId__c);
    }

    @IsTest
    static void batchTest3(){      
        
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());
        List<Id> baList = new List<Id>();
        for(Billing_Account__c ba : [SELECT Id FROM Billing_Account__c WHERE RecordType.Name = 'Billing Account']) {
            baList.add(ba.Id);
        }
        
        Test.startTest();
        CZ_LoadCustomerBatch lcb = new CZ_LoadCustomerBatch(baList);
        Database.executeBatch(lcb);
        Test.stopTest();
        
        Billing_Account__c ba2 = [SELECT Id, Name, Primary_Contact__c, CZ_CustomerId__c FROM Billing_Account__c WHERE RecordType.Name = 'Billing Account' LIMIT 1];
        Assert.areEqual('CUS-1234', ba2.CZ_CustomerId__c);
    }
}