unpackaged/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Product_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product / Service</label>
    <referenceTo>Product_Service__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product_Service__c/Product_Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Product / Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Products_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AccountClientStatusQueueable.cls
public class AccountClientStatusQueueable implements Queueable{
    public List<Id> bpIds;
    
    public AccountClientStatusQueueable(List<Id> bpIds) {
        this.bpIds = bpIds;
    }

    public void execute(QueueableContext context) {
        System.debug('~~~AccountClientStatusQueueable::execute: ' + this.bpIds);
    
        List<Id> actIds = new List<Id>();
        for(Billing_Product__c b : [SELECT Product_Service__r.Account__c FROM Billing_Product__c WHERE Id IN :this.bpIds]) {
            actIds.add(b.Product_Service__r.Account__c);
        }
        System.debug('~~~actIds: ' + actIds);
        List<Account> acts = new List<Account>();
        Map<Id,String> statusMap = new Map<Id,String>();
        Map<Id,Integer> activeMap = new Map<Id,Integer>();

        for(Billing_Product__c bp : [SELECT Id, Product_Service__r.Account__c, Product_Service__r.Account__r.Client_Status__c,
                                        Billing_Product_Status__c, Billing_Frequency__c
                                        FROM Billing_Product__c 
                                        WHERE Product_Service__r.Account__c IN :actIds]) {
            if(bp.Product_Service__c != null) {
                statusMap.put(bp.Product_Service__r.Account__c, bp.Product_Service__r.Account__r.Client_Status__c);
                Integer count = (bp.Billing_Product_Status__c.equalsIgnoreCase('Active') 
                                && !bp.Billing_Frequency__c.equalsIgnoreCase('One-Time')) ? 1 : 0;
                if(activeMap.containsKey(bp.Product_Service__r.Account__c)) {
                    Integer newCount = activeMap.get(bp.Product_Service__r.Account__c) + count;
                    activeMap.put(bp.Product_Service__r.Account__c, newCount);
                } else {
                    activeMap.put(bp.Product_Service__r.Account__c, count);
                }
            }
        }

        for(Id actId : statusMap.keySet()) {
            if((statusMap.get(actId) == null || statusMap.get(actId).equalsIgnoreCase('Prospect')) && activeMap.get(actId) > 0) {
                acts.add(new Account(Id = actId, Client_Status__c = 'Existing'));
            } else if((statusMap.get(actId) == null || statusMap.get(actId).equalsIgnoreCase('Existing')) && activeMap.get(actId) == 0) {
                acts.add(new Account(Id = actId, Client_Status__c = 'Prospect'));
            }
        }

        if(acts.size() > 0) {
            List<Database.SaveResult> dsrList = Database.update(acts, false);
            Logger.logErrorList('AccountClientStatusQueueable', dsrList, acts);
        }
    }
}