unpackaged/main/default/objects/Account/fields/Do_not_Include_in_Collections__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Include_in_Collections__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Include in Collections</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Finance_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Finance_Contact_ID__c</fullName>
    <formula>c2g__CODAFinanceContact__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finance Contact ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The client contact that should be consulted regarding this issue, if not populated then populate the lower fields to automatically create a Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Cases (Contact)</relationshipLabel>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A detailed explanation of the issue</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Record_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/Finance_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Used to store records generated when an Invoice is 1 day past the due date and unpaid from FFA</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>AR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Receivables</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Collection_Activity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Collection Activity Client Case</errorMessage>
        <filterItems>
            <field>Client_Support_Ticket__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Collection Activity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client_Support_Ticket__c</referenceTo>
    <relationshipLabel>Accounts Receivable</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Days_Outstanding_Calc__c.field-meta.xml
<CustomField>
    <fullName>Days_Outstanding_Calc__c</fullName>
    <formula>if(

 Outstanding_Value__c &gt; 0,



TODAY() -   Invoice_Date__c,0




)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Outstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Record_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Reynolds</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Re-Opened</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Accounting</fullName>
        <isActive>false</isActive>
        <label>Waiting on Accounting</label>
    </customValue>
    <description>All statuses of records</description>
    <masterLabel>Record Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/createCollectionActivity.cls
public class createCollectionActivity implements Schedulable
{
	public void execute(SchedulableContext sc)
	{
		list<Account> accsNeedingCA = getAccsToCreate();
		List<Client_Support_Ticket__c> newClientCases = new List<Client_Support_Ticket__c>();

		for ( Account acc : accsNeedingCA )
		{
			Client_Support_Ticket__c clientCase = new Client_Support_Ticket__c(  );
			clientCase.Account__c = acc.Id;
			clientCase.Contact__c = acc.c2g__CODAFinanceContact__c;
			clientCase.Description__c = 'This Account is now in Collections. Please get all Invoices to a paid status';
			clientCase.RecordTypeId = '0124A000001NTPoQAO';
			clientCase.OwnerId = '0054A000009kI8vQAE';
			clientCase.Status__c = 'Open';
			clientCase.Name = 'CA - ' + acc.Name;

			newClientCases.add(clientCase);
		}

		if ( newClientCases.size() > 0 )
		{
			Database.insert( newClientCases, false );
		}
	}

	private static list<Account> getAccsToCreate()
	{

		List<AggregateResult> fArs = [SELECT COUNT( Id )recs, Account__c
		                              FROM Finance_Accounts_Receivable__c
		                              WHERE Days_Outstanding_Calc__c >= 35 and Invoice_Status__c<>'Discarded' and Payment_Status__c<>'Paid' and Payment_Status__c<>'Not Applicable' and Collection_Activity__c = null
		                              GROUP BY Account__c];

		set<Id> fArsAccIds = new set<Id>();
		for ( AggregateResult fAr : fArs )
		{
			fArsAccIds.add(( Id )fAr.get('Account__c'));
		}

		List<Client_Support_Ticket__c> clientCases = [SELECT Id, Account__c
		                                              FROM Client_Support_Ticket__c
		                                              WHERE recordType.Name = 'Collection Activity' and Status__c<>'Complete'];
		set<Id> ccAccIds = new set<Id>();
		for ( Client_Support_Ticket__c cc : clientCases )
		{
			ccAccIds.add(cc.Account__c);
		}

		list<Account> accs = [SELECT id, Name, c2g__CODAFinanceContact__c, Finance_Contact_ID__c
		                      FROM Account
		                      WHERE Do_not_Include_in_Collections__c = false and id in :fArsAccIds and id not in :ccAccIds
		                      ORDER BY Name
		                      LIMIT 500];
		if ( accs.size() > 0 )
		{
			return accs;
		}
		else
		{
			return null;
		}
	}
}