unpackaged/main/default/objects/Account/fields/Do_not_Include_in_Collections__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Include_in_Collections__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Include in Collections</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The client contact that should be consulted regarding this issue, if not populated then populate the lower fields to automatically create a Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Cases (Contact)</relationshipLabel>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A detailed explanation of the issue</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Record_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/Finance_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Used to store records generated when an Invoice is 1 day past the due date and unpaid from FFA</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>AR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Receivables</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Finance_Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Collection_Activity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Collection Activity Client Case</errorMessage>
        <filterItems>
            <field>Client_Support_Ticket__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Collection Activity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client_Support_Ticket__c</referenceTo>
    <relationshipLabel>Accounts Receivable</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Days_Outstanding_Calc__c.field-meta.xml
<CustomField>
    <fullName>Days_Outstanding_Calc__c</fullName>
    <formula>if(

 Outstanding_Value__c &gt; 0,



TODAY() -   Invoice_Date__c,0




)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Outstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Record_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Reynolds</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Re-Opened</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Accounting</fullName>
        <isActive>false</isActive>
        <label>Waiting on Accounting</label>
    </customValue>
    <description>All statuses of records</description>
    <masterLabel>Record Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/batchCollectionActivity.cls
global class batchCollectionActivity implements Database.Batchable<sObject>, Database.Stateful {
    global string query;
    
    global database.Querylocator start(Database.BatchableContext BC){
        query = 'select id' + 
            ' from Finance_Accounts_Receivable__c' + 
            ' where Days_Outstanding_Calc__c > 34 and Collection_Activity__c = null and Invoice_Status__c <> \'Discarded\' and Payment_Status__c <> \'Paid\'' + 
            ' and Account__r.Do_not_Include_in_Collections__c = false' +
            ' order by Account__c';
        if(test.isRunningTest()){
            query = query + ' limit 1';
        }
        Database.QueryLocator result = Database.getQueryLocator(this.query);
        return result;
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        for(Sobject obj: scope){
            Finance_Accounts_Receivable__c AR = [select id, Name, Account__c, Account__r.Name, Collection_Activity__c, Billing_Contact__c
                                                 from Finance_Accounts_Receivable__c
                                                 where id = :obj.id ];
            
            if(AR.Collection_Activity__c == null){
                crtCse(AR.Account__r.Name, AR.Account__c, AR.Billing_Contact__c, AR.Name);
            }
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
    private Client_Support_Ticket__c crtCse(string accNme, id accId, id conId, string arName){
        Client_Support_Ticket__c cse = new Client_Support_Ticket__c();
        
        cse.Account__c = accId;
        cse.Contact__c = conId;
        cse.Status__c = 'Open';
        cse.RecordTypeId = schema.SObjectType.Client_Support_Ticket__c.getRecordTypeInfosByName().get('Collection Activity').getRecordTypeId();
        cse.OwnerId = '0054A000009HatNQAS';
        
        if (accNme.length() > 75){
            accNme = accNme.left(75);
        }
        cse.Name = 'CA - ' + accNme;
        cse.Description__c = 'This Collection Activity was created by: ' + arName + 
            '. The case was created on: ' + string.valueOf(datetime.now());
        
        insert cse;
        
        return cse;
    }
}