unpackaged/main/default/objects/Account/fields/Do_not_Include_in_Collections__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Include_in_Collections__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Include in Collections</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/Finance_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Used to store records generated when an Invoice is 1 day past the due date and unpaid from FFA</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>AR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Receivables</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Collection_Activity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Collection Activity Client Case</errorMessage>
        <filterItems>
            <field>Client_Support_Ticket__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Collection Activity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client_Support_Ticket__c</referenceTo>
    <relationshipLabel>Accounts Receivable</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Days_Outstanding_Calc__c.field-meta.xml
<CustomField>
    <fullName>Days_Outstanding_Calc__c</fullName>
    <formula>if(

 Outstanding_Value__c &gt; 0,



TODAY() -   Invoice_Date__c,0




)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Outstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/relateARsCollectionActivity.cls
public class relateARsCollectionActivity{
	public class vars{
		@InvocableVariable(label = 
		'Collection Activity ID'Required = true)
		public Id caId;
		@InvocableVariable(label = 
		'Account Id'Required = true)
		public id accId;
		@InvocableVariable(label = 
		'Days Outstanding'Required = true)
		public integer daysOutstanding;
	}

	@InvocableMethod
	public static void relateToAllARs(List<vars> vars){
		list<Finance_Accounts_Receivable__c> ARs = new list<Finance_Accounts_Receivable__c>();
		list<id> accIds = new List<Id>();
		integer daysOut = vars.get(0).daysOutstanding;
		for (vars var : vars){
			accIds.add(var.accId);
		}
		list<Finance_Accounts_Receivable__c> accARs = [SELECT id, Account__c
		                                               FROM Finance_Accounts_Receivable__c 
		                                               WHERE Collection_Activity__c = null and Invoice_Status__c<>'Discarded' and Payment_Status__c<>'Paid' and Payment_Status__c<>'Not Applicable' and Account__c in :accIds and Account__r.Do_not_Include_in_Collections__c = false and Days_Outstanding_Calc__c >= :daysOut
		                                               ORDER BY Account__c];
		for (Finance_Accounts_Receivable__c fAr : accARs){
			for (vars var : vars){
				if (fAr.Account__c == var.accId){
					fAr.Collection_Activity__c = var.caId;
					ARs.add(fAr);
					break;
				}
			}
		}
		if (ARs.size() > 0){
			database.update(ARs, false);
		}
	}
}