unpackaged/main/default/objects/Account/fields/NCMI_Client_Code__c.field-meta.xml
<CustomField>
    <fullName>NCMI_Client_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary field for WinMasters integration to evaulate if the account has NCMi services</description>
    <label>NCMI Client (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/Training_Subscription_Account__c.object-meta.xml
<CustomObject>
    <description>Accounts authorized to enroll under a Training Subscription</description>
    <label>Training Subscription Account</label>
    <nameField>
        <label>Training Subscription Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Training_Subscription_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Status_Formula__c.field-meta.xml
<CustomField>
    <fullName>Status_Formula__c</fullName>
    <formula>IF( Account_Swapped_Replaced__c = TRUE, &quot;Inactive&quot;, Training_Subscription__r.Status_Formula__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Start_Date__c</fullName>
    <formula>Training_Subscription__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Term_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Termination_Date__c</fullName>
    <formula>Training_Subscription__r.End_Date_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/TrainingSubscriptionAccountMonitorBatch.cls
global class TrainingSubscriptionAccountMonitorBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
       
    private final String logTag = '[TrainingSubscriptionAccountMonitorBatch]';
    public String qry {get;set;}

    global TrainingSubscriptionAccountMonitorBatch() {
        // constructor logic
        this.qry = 'SELECT Id, Name, Account__c, Term_Termination_Date__c, Term_Start_Date__c ' + 
                'FROM Training_Subscription_Account__c ' + 
                'WHERE Term_Start_Date__c = TODAY OR Term_Termination_Date__c = TODAY';
    }

    global void execute(SchedulableContext SC) {
        TrainingSubscriptionAccountMonitorBatch batchJob = new TrainingSubscriptionAccountMonitorBatch();
        Database.executeBatch(batchJob,50);
    }

    global database.Querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(qry);
    }
    
    global void execute(Database.BatchableContext BC, List<Training_Subscription_Account__c> scope){
        System.debug(logTag + 'There are ' + scope.size() + ' records to process in this batch.');
        
        
        // Get a map of all the accounts we need to check.
        Set<Id> allAcctIdSet = new Set<Id>();
        Set<Id> tsaIdSet = new Set<Id>();

        for(Training_Subscription_Account__c tsa:scope){
            allAcctIdSet.add(tsa.Account__c);
            tsaIdSet.add(tsa.Id);
        }

        Map<Id,Account> acctMap = new Map<Id,Account>([select id, name, NCMI_Client_Code__c from account where id in :allAcctIdSet]);
        
        AggregateResult[] arResults = [SELECT Account__c, count(Id) 
                                        FROM Training_Subscription_Account__c 
                                        WHERE Account__c in :allAcctIdSet 
                                            AND Status_Formula__c = 'Active' 
                                            AND ID NOT IN :tsaIdSet
                                        GROUP BY Account__c];
        Map<Id,Integer> activeTSAMap = new Map<Id,Integer>();
        for(AggregateResult ar:arResults){
            Id acctId = (Id)ar.get('Account__c');
            activeTSAMap.put(acctId, Integer.valueOf(ar.get('expr0')) );
        }
        
        List<Account> acctsToUpdate = new List<Account>();

        for(Training_Subscription_Account__c tsa:scope){
            
            Account acct = acctMap.get(tsa.Account__c);
            
            if(tsa.Term_Start_Date__c == Date.Today()){
                System.debug('TSA starts today for ' + tsa.Name);
                // Check if the Account already has the NCMi checkbox checked.
                if(acct.NCMI_Client_Code__c == False){
                    System.debug(logTag + 'The account ' + acct.Name + ' will be updated to set NCMI Client Code to TRUE.');
                    acct.NCMI_Client_Code__c = True;
                    acctsToUpdate.add(acct);
                } else {
                    System.debug(logTag + 'The account ' + acct.Name + ' does not need to be updated, its NCMI Client Code is already checked.');
                }
            } else {
                System.debug('TSA ends today for ' + tsa.Name);
                // Check if the account has any other active TSAs.
                if(activeTSAMap.containsKey(acct.Id)){
                    System.debug(logTag + 'The account + ' + acct.Name + ' has other Active TSAs so its NCMI checkbox should remain checked (true).');
                } else {
                    if(acct.NCMI_Client_Code__c == True){
                        System.debug(logTag + 'The account ' + acct.Name + ' has no remaining Active TSAs. Its NCMI checkbox will be set to FALSE now.');
                        acct.NCMI_Client_Code__c = FALSE;
                        acctsToUpdate.add(acct);
                    } else {
                        System.debug(logTag + 'The account ' + acct.Name + ' has no remaining Active TSAs but its NCMI checkbox is already set to FALSE so there is no further action required.');
                    }
                }
            }
        }

        // Check if there are any Account records to update.
        if( !acctsToUpdate.isEmpty() ){
            System.debug(logTag + 'There are ' + acctsToUpdate.size() + ' account records to update.');
            Database.SaveResult[] saveResults = Database.update(acctsToUpdate, false);
            
            // Check for any DML errors.
            Integer i = 0;
            for(Database.SaveResult sr:saveResults){
                if( !sr.IsSuccess() ){
                    Account a = acctsToUpdate[i];
                    System.debug(logTag + 'There was a problem updating account [' + a.Name + ']. Error: ' + sr.getErrors()[0].getMessage());
                    Logger.logError(
                        logTag + 'Update Account NCMI Client Code field', 
                        'ERROR', 
                        logTag, 
                        'DML Error', 
                        sr.getErrors()[0].getMessage(), 
                        null
                    );
                }
                i++;
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug(logTag + 'Finished.');
    }
}