unpackaged/main/default/objects/Account/fields/Out_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Business__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Business</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/NCM_Authorized_Products__c.field-meta.xml
<CustomField>
    <fullName>NCM_Authorized_Products__c</fullName>
    <inlineHelpText>NCM products that this billing account is authorized to be used for payment</inlineHelpText>
    <label>NCM Authorized Products</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20 Groups</fullName>
            </value>
            <value>
                <fullName>aXcessa</fullName>
            </value>
            <value>
                <fullName>ChargeZoom BA</fullName>
            </value>
            <value>
                <fullName>Echo</fullName>
            </value>
            <value>
                <fullName>Healthcheck</fullName>
            </value>
            <value>
                <fullName>NCMi Paid Seats</fullName>
            </value>
            <value>
                <fullName>NCMi Subscription</fullName>
            </value>
            <value>
                <fullName>NCMi Training Credits</fullName>
            </value>
            <value>
                <fullName>Proprietary</fullName>
            </value>
            <value>
                <fullName>Single Member Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/billingAccountControllerTest.cls
@isTest
public class billingAccountControllerTest{
    
    @testSetup
    static void setupData(){
        SampleDataFactory.createData();
    }
    
	@isTest
	static void testBillingAccountController()
	{
		test.startTest();
		Billing_Account__c billAccount = [SELECT 
		                  Id, Account__c, NCM_Authorized_Products__c
		            FROM Billing_Account__c 
		            WHERE Account__r.Out_of_Business__c = false
		            LIMIT 1];
		list<Billing_Account__c> bAccs = billingAccountController.getBillingAccounts(billAccount.Account__c);
		Billing_Account__c bAcc = billingAccountController.getBillingAccount(bAccs.get(0).Id);
		try
		{
			billingAccountController.createBillingAccount(bAcc);
		}
		catch ( exception er )
		{
		}
		test.stopTest();
	}
}