unpackaged/main/default/objects/Account/fields/Primary_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/CZ_CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CZ_CustomerId__c</fullName>
    <externalId>true</externalId>
    <label>CZ CustomerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <description>A Custom Object to capture Exceptions and Error information.</description>
    <label>Error  Logger</label>
    <nameField>
        <displayFormat>Error - {000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/BillingAccountChargeZoomSync_Test.cls
@isTest
private class BillingAccountChargeZoomSync_Test {
    @TestSetup
    static void makeData(){
        Account act = new Account(
            Name = 'Metroville Dodge', 
            BillingStreet = '111 Main St', 
            BillingCity = 'Metroville', 
            BillingStateCode = 'NC', 
            BillingPostalCode = '27554',
            c2g__codaAccountTradingCurrency__c = 'USD'
        );
        insert(act);

        Contact joe = new Contact(
            FirstName = 'Joe',
            LastName = 'Contact',
            AccountId = act.Id,
            Email = 'joe@example.com'
        );
        insert joe;

        Id baId = [SELECT Primary_Billing_Account__c FROM Account LIMIT 1].Primary_Billing_Account__c;

        Billing_Account__c ba = new Billing_Account__c(
            Id = baId,
            Primary_Contact__c = joe.Id,
            CZ_CustomerId__c = 'CUS-1234'
        );
        update ba;
    }

    @isTest
    static void batchTest() {
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());

        Test.startTest();
            BillingAccountChargeZoomSync b = new BillingAccountChargeZoomSync();
            b.overrideDate = Date.today();
            Database.executeBatch(b, 1);
        Test.stopTest();
        
        List<Error_Logger__c> errList = [SELECT Id FROM Error_Logger__c];
        Assert.areEqual(0, errList.size());
    }

    /*@IsTest
    static void schedulableTest(){
        String CRON_EXP = '0 6 * * * ?';
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());

        Test.startTest();
        String jobId = System.schedule('Update Contacts', CRON_EXP, new BillingAccountChargeZoomSync_Schedulable());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();
    }*/
}