unpackaged/main/default/objects/Account/fields/Primary_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/NCM_Authorized_Products__c.field-meta.xml
<CustomField>
    <fullName>NCM_Authorized_Products__c</fullName>
    <inlineHelpText>NCM products that this billing account is authorized to be used for payment</inlineHelpText>
    <label>NCM Authorized Products</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20 Groups</fullName>
            </value>
            <value>
                <fullName>aXcessa</fullName>
            </value>
            <value>
                <fullName>ChargeZoom BA</fullName>
            </value>
            <value>
                <fullName>Echo</fullName>
            </value>
            <value>
                <fullName>Healthcheck</fullName>
            </value>
            <value>
                <fullName>NCMi Paid Seats</fullName>
            </value>
            <value>
                <fullName>NCMi Subscription</fullName>
            </value>
            <value>
                <fullName>NCMi Training Credits</fullName>
            </value>
            <value>
                <fullName>Proprietary</fullName>
            </value>
            <value>
                <fullName>Single Member Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Product_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Value__c</fullName>
    <formula>Product__r.Product_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NCM_Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>NCM_Product_Interest__c</fullName>
    <label>NCM Product Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Business_Unit</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NCMi_First_Contact__c.field-meta.xml
<CustomField>
    <fullName>NCMi_First_Contact__c</fullName>
    <label>First Contact</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Billing_Product__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Product</label>
    <referenceTo>Billing_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <formula>PricebookEntry.Product2.Core_Product__c</formula>
    <label>Core Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Departments</inlineHelpText>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Pending_Price__c.field-meta.xml
<CustomField>
    <fullName>Pending_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Price?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Provisioning Required?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product is related to this Dimension</description>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/NCM_Authorized_Products__c.field-meta.xml
<CustomField>
    <fullName>NCM_Authorized_Products__c</fullName>
    <description>NCM Products that this billing account is authorized to be used for payment.</description>
    <label>NCM Authorized Products</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Authorized_Products</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Value__c</fullName>
    <inlineHelpText>Value of the core product being sold.</inlineHelpText>
    <label>Product Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Record_Provisioning__c.field-meta.xml
<CustomField>
    <fullName>Record_Provisioning__c</fullName>
    <label>Flow Provisioning Path</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Core_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>aXcessa Store</fullName>
            </value>
            <value>
                <fullName>Cohort Student</fullName>
            </value>
            <value>
                <fullName>Echo</fullName>
            </value>
            <value>
                <fullName>Group Member</fullName>
            </value>
            <value>
                <fullName>NCMi Seat</fullName>
            </value>
            <value>
                <fullName>Proprietary Account</fullName>
            </value>
            <value>
                <fullName>Proprietary Group</fullName>
            </value>
            <value>
                <fullName>Proprietary Master Group</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Subscription Term Transition</fullName>
            </value>
            <value>
                <fullName>Training Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Originally added to mark certain products as automatically billed.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Candidate Composite</fullName>
            </value>
            <value>
                <fullName>Paid Seat</fullName>
            </value>
            <value>
                <fullName>GMEP</fullName>
            </value>
            <value>
                <fullName>Training Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/NCMi.recordType-meta.xml
<RecordType>
    <fullName>NCMi</fullName>
    <active>true</active>
    <description>NCM Institute</description>
    <label>NCMi</label>
</RecordType>

unpackaged/main/default/globalValueSets/NCM_Authorized_Products.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>20 Groups</fullName>
    </customValue>
    <customValue>
        <fullName>aXcessa</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcheck</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Cohort</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Paid Seats</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Training Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Proprietary</fullName>
    </customValue>
    <customValue>
        <fullName>Single Member Products</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Performance Solutions</fullName>
    </customValue>
    <masterLabel>NCM Authorized Products</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>20 Group</fullName>
    </customValue>
    <customValue>
        <fullName>aXcessa</fullName>
    </customValue>
    <customValue>
        <fullName>Business Talent Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Performance Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Echo</fullName>
    </customValue>
    <customValue>
        <fullName>General NCM</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcheck</fullName>
    </customValue>
    <customValue>
        <fullName>Leadership Development</fullName>
    </customValue>
    <customValue>
        <fullName>NCM Institute</fullName>
    </customValue>
    <customValue>
        <fullName>NCM Institute Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>OEM / Group Program</fullName>
    </customValue>
    <customValue>
        <fullName>Private 20 Group Training</fullName>
    </customValue>
    <customValue>
        <fullName>Proprietary</fullName>
    </customValue>
    <customValue>
        <fullName>Single Member Product</fullName>
    </customValue>
    <customValue>
        <fullName>Travel Solutions</fullName>
        <isActive>false</isActive>
        <label>Travel Solutions</label>
    </customValue>
    <customValue>
        <fullName>Core</fullName>
        <isActive>false</isActive>
        <label>Core</label>
    </customValue>
    <customValue>
        <fullName>Healthcheck for 20 Groups</fullName>
        <isActive>false</isActive>
        <label>Healthcheck for 20 Groups</label>
    </customValue>
    <customValue>
        <fullName>Business Management Solutions</fullName>
        <isActive>false</isActive>
        <label>Business Management Solutions</label>
    </customValue>
    <customValue>
        <fullName>TAG/DHG</fullName>
        <isActive>false</isActive>
        <label>TAG/DHG</label>
    </customValue>
    <customValue>
        <fullName>Benchmark Product/Composite</fullName>
        <isActive>false</isActive>
        <label>Benchmark Product/Composite</label>
    </customValue>
    <customValue>
        <fullName>LiveAudit</fullName>
        <isActive>false</isActive>
        <label>LiveAudit</label>
    </customValue>
    <description>All NCM Business Units</description>
    <masterLabel>NCM Business Unit</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CreateSINTrigger_Test.cls
/*
 * This class contains unit tests for validating the behavior of CreateSINTrigger.Trigger
 */
@isTest
private class CreateSINTrigger_Test {

    @TestSetup
    static void makeData(){
        User u = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        c2g__codaCompany__c co = SetCurrentCompany_TEST_DataFactory.createCurrentCompany(
            'NCM Associates, Inc.',
            u,
            null,
            true,
            '12345'
        );

        Id gla = [SELECT Id FROM c2g__codaGeneralLedgerAccount__c LIMIT 1].Id;
        
        Account act = new Account(
            Name = 'Metroville Dodge', 
            BillingStreet = '111 Main St', 
            BillingCity = 'Metroville', 
            BillingStateCode = 'NC', 
            BillingPostalCode = '27554',
            c2g__codaAccountTradingCurrency__c = 'USD',
            c2g__CODAAccountsReceivableControl__c = gla
        );
        insert(act);

        Contact joe = new Contact(
            FirstName = 'Joe',
            LastName = 'Contact',
            AccountId = act.Id,
            Email = 'joe@example.com'
        );
        insert(joe);

        Id baId = [SELECT Primary_Billing_Account__c FROM Account LIMIT 1].Primary_Billing_Account__c;

        Billing_Account__c ba = new Billing_Account__c(
            Id = baId,
            Primary_Contact__c = joe.Id
        );
        update(ba);

        c2g__codaDimension1__c dim1 = new c2g__codaDimension1__c(Name = 'Test Dim 1', 
            c2g__ReportingCode__c = '7000'
            );
        insert(dim1);

        c2g__codaDimension2__c dim2 = new c2g__codaDimension2__c(Name = 'Test Dim 2', 
            c2g__ReportingCode__c = System.Label.NCMiDim2Name
            );
        insert(dim2);
        
        Product2 prod = new Product2(Name = 'Test Product', 
                                Product_Value__c = 10, 
                                Dimension_1__c = dim1.Id, 
                                c2g__CODASalesRevenueAccount__c = gla,
                                IsActive = true,
                                NCM_Authorized_Products__c = 'NCMi Paid Seats',
                                Core_Product__c = true,
                                Record_Provisioning__c = 'NCMi Seat',
                                Type__c = 'Paid Seat');
        insert(prod);

        Id pricebookId = Test.getStandardPricebookId();

        PricebookEntry pbe = new PricebookEntry(
            IsActive = true,
            UnitPrice = 99.99,
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id
        );
        insert(pbe);

        Id cur = [SELECT Id FROM c2g__codaAccountingCurrency__c WHERE Name = 'USD'].Id;

        Campaign camp = new Campaign(Name = 'Test Camp');
        insert(camp);

        Opportunity op = new Opportunity(Name = 'test opp',
                                        NCM_Product_Interest__c = 'NCM Institute',
                                        CloseDate = Date.today(),
                                        NCMi_First_Contact__c = Date.today(),
                                        StageName = 'Pending Sale',
                                        AccountId = act.Id,
                                        Billing_Account__c = ba.Id,
                                        LeadSource = 'Employee Refferal',
                                        CampaignId = camp.Id,
                                        Pricebook2Id = Test.getStandardPricebookId());
        insert(op);

        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = op.Id,
                                                            Product2Id = prod.Id,
                                                            Quantity = 1,
                                                            UnitPrice = 100.00,
                                                            Description = 'Joe - 1/15/24',
                                                            Pending_Price__c = true);
        insert(oli);

        insert(new Billing_Product__c(Product__c = prod.Id, 
                                        Opportunity__c = op.Id,
                                        Billing_Frequency__c = 'One-Time',
                                        Billing_Account__c = ba.Id,
                                        Billing_Product_Status__c = 'Active',
                                        Next_Billing_Date__c = Date.today()));

    }

    @isTest
    static void createSINTriggerTest() {
        Id x = [SELECT Id FROM Opportunity LIMIT 1].Id;
        Id y = [SELECT Id FROM Billing_Account__c LIMIT 1].Id;
        Test.startTest();
        Id userId = UserInfo.getUserId();
        Database.SaveResult dsr = EventBus.publish(new Create_SIN__e(OpportunityId__c = x, SalespersonId__c = userId, BillingAccountId__c = y));
        Test.stopTest();
        Assert.isTrue(dsr.isSuccess());
        EventBusSubscriber ebs = [SELECT Name, Position, Retries, LastError FROM EventBusSubscriber WHERE Topic='Create_SIN__e' AND Type='ApexTrigger'];
        Assert.areEqual(1, ebs.Position);
        OpportunityLineItem oppLI = [SELECT Id, Invoiced__c FROM OpportunityLineItem LIMIT 1];
        Assert.isTrue(oppLI.Invoiced__c);
    }
}