unpackaged/main/default/objects/Account/fields/Primary_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The NCM Employee&#39;s Dimension 2 record in Financial Force</inlineHelpText>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <description>Indicates if all the line items for this opportunity have been invoiced.</description>
    <formula>IF( Line_Item_Not_Invoiced__c = 0, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if all the line items for this opportunity have been invoiced.</inlineHelpText>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Next_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Invoice_Date__c</fullName>
    <label>Next Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <formula>IF(Invoiced__c == true, false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Recurring_Status__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Status__c</fullName>
    <label>Recurring Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Recurring</fullName>
                <default>true</default>
                <label>Not Recurring</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Departments</inlineHelpText>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>NCM Employee</inlineHelpText>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_3__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Marketing Tactic</inlineHelpText>
    <label>Dimension 3</label>
    <referenceTo>c2g__codaDimension3__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_4__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>20 Group Meeting</inlineHelpText>
    <label>Dimension 4</label>
    <referenceTo>c2g__codaDimension4__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Recurring_Payment__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring Payment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product is related to this Dimension</description>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recurring_Invoice_Settings__c/Recurring_Invoice_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>User for Batch Invoice Configuration</description>
    <label>Recurring Invoice Settings</label>
</CustomObject>

unpackaged/main/default/objects/Recurring_Invoice_Settings__c/fields/BatchMonitorUserId__c.field-meta.xml
<CustomField>
    <fullName>BatchMonitorUserId__c</fullName>
    <label>BatchMonitorUserId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Recurring_Invoice_Settings__c/fields/Chain_Batches__c.field-meta.xml
<CustomField>
    <fullName>Chain_Batches__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chain Batches</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Recurring_Invoice_Settings__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BatchCreateInvoiceTest.cls
@isTest(seeAllData = true)
private class BatchCreateInvoiceTest
{
	@isTest(SeeAllData = true)
	static void batchCreateTester() {
		user u = [SELECT Id
		          FROM User
		          WHERE IsActive = true AND Id IN 
		                 (SELECT c2g__User__c
		                  FROM c2g__codaUserCompany__c)
		          ORDER BY LastName DESC
		          LIMIT 1];

		system.runas(u) {
			// Need a product configured to work with FF create Invoice action
			Product2[] sfproducts = [SELECT Id
			                         FROM Product2
			                         WHERE IsActive = true AND c2g__CODASalesRevenueAccount__c <> null
			                         LIMIT 1];
			Product2 validProduct;
			if(sfproducts <> null && sfproducts.size() > 0) {
				validProduct = sfproducts[0];
			}
			System.assert(validproduct <> null, 'A salesforce product with FF Sales Revenue Account is required to run this test');

			Recurring_Invoice_Settings__c ncm = Recurring_Invoice_Settings__c.getValues( 'NCM Settings' );
			ncm.debug__c = true;
			User user = [SELECT Id
			             FROM User
			             WHERE IsActive = true AND Id IN 
			                    (SELECT c2g__User__c
			                     FROM c2g__codaUserCompany__c)
			             ORDER BY LastName DESC
			             LIMIT 1];
			ncm.BatchMonitorUserId__c = user.Id;
			ncm.Chain_Batches__c = true;
			update ncm;

			/* Get the standard pricebook  */
			Pricebook2 standardPB = [SELECT Id, 
			                                IsStandard
			                         FROM Pricebook2
			                         WHERE IsStandard = true];

			/* Setup PriceBook Entry */
			PricebookEntry pbe;
			List<PricebookEntry> pbeList = [SELECT Pricebook2Id, 
			                                       Product2Id, 
			                                       UnitPrice, 
			                                       isActive
			                                FROM PricebookEntry
			                                WHERE Pricebook2Id = :standardPB.Id AND Product2Id = :sfproducts[0].id
			                                LIMIT 1];
			if(pbeList != null && !pbeList.isEmpty()) {
				pbe = pbeList[0];
			} else {
				pbe = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = sfproducts[0].id, UnitPrice = 500, isActive = true);
				insert pbe;
			}

			List<c2g__codaCompany__c> ffCompanyList = new List<c2g__codaCompany__c>();
			ffCompanyList = [SELECT Name, 
			                        Id, 
			                        CreatedDate
			                 FROM c2g__codaCompany__c
			                 ORDER BY CreatedDate ASC
			                 LIMIT 1];
			Id ffCompanyId = ffCompanyList[0].Id;
			System.Debug('ffCompanyId : ' + ffCompanyId);

			// Correctly configured Contact
			Id gla = [SELECT Id FROM c2g__codaGeneralLedgerAccount__c LIMIT 1].Id;
       		Account account = new Account(name = 'uniqueVal',
                                        billingStreet = '120 Birmingham Drive, Suite ',
                                        billingCity = 'San Diego',
                                        billingState = 'California',
                                        billingPostalCode = '92007',
                                        billingCountry = 'United States',
                                        shippingStreet = '120 Birmingham Drive, Suite ',
                                        shippingCity = 'San Diego',
                                        shippingPostalCode = '92007',
                                        shippingState = 'California',
                                        shippingCountry = 'United States',
                                        c2g__CODAAccountsReceivableControl__c = gla
                                        );
			insert account;
			Contact contact = new Contact(firstname = 'uniqueVal',
                                        lastname = 'ApexTest',
                                        email = 'uniqueVal' + '@apextest.com',
                                        mailingStreet = '120 Birmingham Drive, Suite ',
                                        mailingCity = 'San Diego',
                                        mailingPostalCode = '92007',
                                        mailingState = 'California',
                                        mailingCountry = 'United States',
                                        otherStreet = '120 Birmingham Drive, Suite ',
                                        otherCity = 'San Diego',
                                        otherState = 'California',
                                        otherPostalCode = '92007',
                                        otherCountry = 'United States',
										accountId = account.Id);
			insert contact;
			account = [SELECT id, 
			                  Primary_Billing_Account__c
			           FROM Account
			           WHERE Id = :account.id];
			Billing_Account__c bAcc = new Billing_Account__c(Id = account.Primary_Billing_Account__c, Primary_Contact__c = contact.Id);
			update bAcc;
			Opportunity opportunity = new Opportunity(Name = 'BatchTestOpp', Type = 'BatchTestOpp', Description = 'BatchTestOpp', Recurring_Status__c = 'Active', Period__c = 'Month', Frequency__c = 1, Next_Invoice_Date__c = Date.Today(), AccountId = account.Id, StageName = 'Prospecting', CloseDate = Date.Today());
			insert opportunity;
			OpportunityLineItem lineItem = new OpportunityLineItem(PricebookEntryId = pbe.Id, Ready_To_Invoice__c = true, OpportunityId = opportunity.Id, Quantity = 1, TotalPrice = 100);
			insert lineItem;
			Opportunity.StageName = 'Closed Won';
			update Opportunity;
			System.Debug('opportunity : ' + opportunity);
			System.Debug([SELECT Id, 
			                     Name, 
			                     Description, 
			                     Ready_To_Invoice__c, 
			                     Recurring_Status__c, 
			                     AccountId, 
			                     Account.c2g__CODAFinanceContact__c, 
			                     Next_Invoice_Date__c, 
			                     Period__c, 
			                     Frequency__c, 
			                     (SELECT Id, 
			                             Product2Id, 
			                             Description, 
			                             Dimension_1__c, 
			                             Dimension_2__c, 
			                             Dimension_3__c, 
			                             Dimension_4__c, 
			                             Quantity, 
			                             UnitPrice, 
			                             Recurring_Payment__c, 
			                             Ready_To_Invoice__c, 
			                             Invoiced__c
			                      FROM OpportunityLineItems
			                      WHERE Ready_To_Invoice__c = True)
			              FROM Opportunity
			              WHERE Recurring_Status__c = 'Active' AND Next_Invoice_Date__c = TODAY AND Name = 'BatchTestOpp']);
			Test.startTest();
			//Check Results
			try
			{
				BatchCreateInvoice batch = new BatchCreateInvoice();
				Database.executeBatch(batch, 1);
			}
			catch ( Exception er )
			{

			}
			Test.stopTest();
		}
	}

}