unpackaged/main/default/objects/Account/fields/Primary_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needing Validation</fullName>
                <default>true</default>
                <label>Needing Validation</label>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Credit Card Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/Healthcheck_Instance__c.object-meta.xml
<CustomObject>
    <label>Healthcheck Instance</label>
    <nameField>
        <label>Healthcheck Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Healthcheck Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/Healthcheck_Store__c.field-meta.xml
<CustomField>
    <fullName>Healthcheck_Store__c</fullName>
    <label>Healthcheck Store</label>
    <referenceTo>Healthcheck_Store__c</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/Originating_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Originating_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/X20_Groups__c.field-meta.xml
<CustomField>
    <fullName>X20_Groups__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Groups</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Instance__c/fields/X20_Groups_Member__c.field-meta.xml
<CustomField>
    <fullName>X20_Groups_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Groups Member</label>
    <referenceTo>X20_Groups_Member__c</referenceTo>
    <relationshipLabel>Healthcheck Instances</relationshipLabel>
    <relationshipName>Healthcheck_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Store__c/Healthcheck_Store__c.object-meta.xml
<CustomObject>
    <label>Healthcheck Store</label>
    <nameField>
        <label>Healthcheck Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Healthcheck Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Healthcheck_Store__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Healthcheck Stores</relationshipLabel>
    <relationshipName>Healthcheck_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Store__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Healthcheck Stores</relationshipLabel>
    <relationshipName>Healthcheck_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Store__c/fields/Originating_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Originating_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Healthcheck Stores</relationshipLabel>
    <relationshipName>Healthcheck_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Healthcheck_Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>20 Group Only - Do Not Use for Proprietary/Benchmark</inlineHelpText>
    <label>Group Id</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Opportunities (Group Id)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Healthcheck_Store__c.field-meta.xml
<CustomField>
    <fullName>Healthcheck_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Healthcheck Store</label>
    <referenceTo>Healthcheck_Store__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group Number</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Global_Product_Service_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Global_Product_Service_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Active - Don&#39;t Bill</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Disconnected</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
        <isActive>false</isActive>
        <label>Suspended</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <customValue>
        <fullName>Honorary</fullName>
        <isActive>false</isActive>
        <label>Honorary</label>
    </customValue>
    <masterLabel>Global Product/Service Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/createHealthcheckInstances.cls
public class createHealthcheckInstances {
    public class vars {
        @InvocableVariable(label='Group Id' Required=true)
        public id grpId;
        @InvocableVariable(label='Opportunity Id' Required=true)
        public id oppId;
    }
    
    @InvocableMethod
    public static void createInstances(List<vars> vars){
        list<Healthcheck_Instance__c> hlthInsts = new list<Healthcheck_Instance__c>();
        for (vars var : vars){
            list<X20_Groups_Member__c> mems = [select id, Account__c, Member_Name__c, Account__r.Name, Account__r.Primary_Billing_Account__c
                                                from X20_Groups_Member__c 
                                                where Group_ID__c = :var.grpId and Status__c = 'Active'];
            for (X20_Groups_Member__c mem : mems){
                list<Healthcheck_Store__c> hlthStrLst = [select id from Healthcheck_Store__c where Account__c = :mem.Account__c];
                Healthcheck_Store__c hlthStr;
                if (hlthStrLst.size() > 0){
                    hlthStr = hlthStrLst.get(0);
                } else{
                    hlthStr = new Healthcheck_Store__c();
                    hlthStr.Account__c = mem.Account__c;
                    hlthStr.Contact__c = mem.Member_Name__c;
                    hlthStr.Name = mem.Account__r.Name;
                    insert hlthStr;
                }
                
                Healthcheck_Instance__c hlthInst = new Healthcheck_Instance__c();
                hlthInst.Account__c = mem.Account__c;
                hlthInst.Billing_Account__c = mem.Account__r.Primary_Billing_Account__c;
                hlthInst.Contact__c = mem.Member_Name__c;
                hlthInst.Healthcheck_Store__c = hlthStr.id;
                hlthInst.Name = mem.Account__r.Name;
                hlthInst.Originating_Opportunity__c = var.oppId;
                hlthInst.RecordTypeId = Schema.SObjectType.Healthcheck_Instance__c.getRecordTypeInfosByName().get('20 Group').getRecordTypeId();
                hlthInst.X20_Groups__c = var.grpId;
                hlthInst.X20_Groups_Member__c = mem.id;
                
                hlthInsts.add(hlthInst);
            }
        }
        
        if(hlthInsts.size() > 0){
            List<database.SaveResult> srList = database.insert(hlthInsts);
            for(database.SaveResult sr : srList){
                if(sr.isSuccess()){
                    system.debug('Successfully created Instance. ID:' + sr.getId());
                } else{
                    for(database.Error er : sr.getErrors()){
                        system.debug('Issue creating Instance:' + er.getMessage());
                    }
                }
            }
        }
    }
}