unpackaged/main/default/objects/Account/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nickname of the contact.</description>
    <inlineHelpText>Please enter the nickname of the contact</inlineHelpText>
    <label>Nickname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>to update the city go to the hotel that is listed in the hotel/Meeting Location field and update the city on the physical address</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State(old)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Age_Group__c.field-meta.xml
<CustomField>
    <fullName>Age_Group__c</fullName>
    <label>Age Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Teen</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <label>Arrival</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <description>Engagement Attendee Type</description>
    <label>Attendee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Participant</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Co-Member</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Engagement Support</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Guest Presenter</fullName>
            </value>
            <value>
                <fullName>Industry Professional</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Moderator</fullName>
            </value>
            <value>
                <fullName>NCM Guest</fullName>
            </value>
            <value>
                <fullName>NCM Resource</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Associate Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Populated with Account Physical Address.</description>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Collateral_Name__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Name__c</fullName>
    <label>Collateral Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Populated with Account Physical Address Abbreviation.</description>
    <label>State</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New Group - Acquiring</fullName>
            </value>
            <value>
                <fullName>New Group - Didn&#39;t Start</fullName>
            </value>
            <value>
                <fullName>New Group - Prospecting</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>New Group - Overflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TwentyGroupController.cls
// Derrick Chavez: 6.11.2025; SALES-1195,2096
// If a Moderator (Group Owner) is updated on a TwentyGroup, then the system will automatically change 
// the previous Group Owner, and add the new Group Owner to all future Engagements with a status of 'Tentative’, 'Firm’, or 'Cancellation Inquiry’.
// Instead of replacing the old Attendee, it will set the Attendance Status to 'Cancelled'. 
public class TwentyGroupController {
    
    public static void handleGroupOwnerChange(List<Twenty_Groups__c> newList, Map<Id,Twenty_Groups__c> oldMap) {

        // Create two maps to track the previous Group Owner Contact ID and the new Group Owner Conact ID. 
        Map<Id, Id> oldGroupOwnerMap = new Map<Id,Id>();
        Map<Id, Id> newGroupOwnerMap = new Map<Id,Id>();
        
        // Identify changes to the Group Owner (NCM_Proprietary__c).
        for(Twenty_Groups__c twentyGroup : newList) {
            Id oldGroupOwnerId = oldMap.get(twentyGroup.Id).NCM_Proprietor__c;
            Id newGroupOwnerId = twentyGroup.NCM_Proprietor__c;
            
            // If Group Owner is changed, then add both values to the maps. 
            if(oldGroupOwnerId != newGroupOwnerId) {
                if(oldGroupOwnerId != null) {
                    oldGroupOwnerMap.put(twentyGroup.Id, oldGroupOwnerId); // track which Attendee (Group Owner) to set to 'Cancelled'. 
                }
                if(newGroupOwnerId != null) {
                    newGroupOwnerMap.put(twentyGroup.Id, newGroupOwnerId); // track which Attendee (Group Owner), needs to be created. 
                }
            }            
        }

        // Add all the Keys (Twenty Group Ids) to a Set, then pass into each method to get the Engagements.
        Set<Id> groupIds = new Set<Id>();
        groupIds.addAll(oldGroupOwnerMap.keySet());
        groupIds.addAll(newGroupOwnerMap.keySet());
        System.debug('handleGroupOwnerChange:: groupIds: ' + groupIds);

        if(groupIds.isEmpty()) return;
        
        // Get the future Engagements and cancel Engagement Attendees. 
        List<Engagement__c> engagementsToUpdate = getFutureEngagements(groupIds);
        System.debug('handleGroupOwnerChange :: engagementsToUpdate: ' + engagementsToUpdate);
        if(!oldGroupOwnerMap.isEmpty()) {
            cancelModeratorAttendees(engagementsToUpdate, oldGroupOwnerMap);
        }
        // Get the the relavant future Engagements and add Engagement Attendees. 
        List<Engagement__c> engagementsToAdd = getRelavantFutureEngagements(groupIds);
        if(!newGroupOwnerMap.isEmpty()) {
            addModeratorAttendees(engagementsToAdd, newGroupOwnerMap);
        }      
    }

    private static List<Engagement__c> getFutureEngagements(Set<Id> groupIds) {

        List<Engagement__c> engagements = [
            SELECT Id, Name, X20_Group__c, Engagement_Start_Date__c, Engagement_Start__c, Status__c
            FROM Engagement__c
            WHERE X20_Group__c IN :groupIds AND Engagement_Start_Date__c > TODAY
        ];
        
        System.debug('TwentyGroupController.getFutureEngagements: engagements ' + engagements);
        return engagements;
    }

    private static List<Engagement__c> getRelavantFutureEngagements(Set<Id> groupIds) {

        List<Engagement__c> engagements = [
            SELECT Id, Name, X20_Group__c, Engagement_Start_Date__c,Engagement_Start__c, Engagement_End__c, Status__c
            FROM Engagement__c
            WHERE X20_Group__c IN :groupIds AND Engagement_Start_Date__c > TODAY 
            AND Status__c IN ('Tentative', 'Firm', 'Cancellatiion Inquiry')
        ];
        
        System.debug('TwentyGroupController.getRelavantFutureEngagements: engagements ' + engagements);
        return engagements;
    }

    // Delete previous Group Owner on Engagement Attendees with Type of 'Moderator'.
    private static void cancelModeratorAttendees(List<Engagement__c> engagements, Map<Id, Id> oldGroupOwnerMap) {
		
        if (engagements == null || engagements.isEmpty()) {
            System.debug('TwentyGroupController.cancelModeratorAttendees :: No engagements provided to cancelModeratorAttendees.');
            return;
    	}
        
        // Create a map to relate each Engagement to it's related Twenty Group.
        Map<Id, Id> engagementToGroup = new Map<Id, Id>();
        for(Engagement__c eng : engagements) {            
            engagementToGroup.put(eng.Id, eng.X20_Group__c);
        }
        
        // Get all Moderator Attendees for the engagements. 
        List<Engagement_Attendee__c> attendees = [
            SELECT Id, Name, Engagement__c, Attendee_Type__c, Contact__c 
            FROM Engagement_Attendee__c 
            WHERE Engagement__c IN :engagementToGroup.keySet() 
            AND Attendee_Type__c = 'Moderator'
        ];

        System.debug('TwentyGroupController.cancelModeratorAttendees: ' + attendees);
        List<Engagement_Attendee__c> attendeesToUpdate = new List<Engagement_Attendee__c>();

        // Remove the Attendees whose Contact matches the old Group Owner.
        for(Engagement_Attendee__c ea : attendees) {
            Id twentyGroupId = engagementToGroup.get(ea.Engagement__c); // Get the related Twenty Group Id for the current Engagement.
            Id oldGroupOwnerId = oldGroupOwnerMap.get(twentyGroupId); // Get the old Group Owner Id.
            
            if(oldGroupOwnerId == null) continue;

            if(oldGroupOwnerId == ea.Contact__c) {
                ea.Attendance_Status__c = 'Cancelled';
                attendeesToUpdate.add(ea);
            }
        }

        if(!attendeesToUpdate.isEmpty()) {
            System.debug('TwentyGroupController.cancelModeratorAttendees :: attendeesToUpdate: ' + attendeesToUpdate);
            List<Database.SaveResult> results = Database.update(attendeesToUpdate, false);
            Logger.logErrorList('TwentyGroupController.cancelModeratorAttendees', results, attendeesToUpdate);
           // update(attendeesToUpdate);
        }       
    }

    // Add new Engagement Attendees with Type of 'Moderator', and other fields.
    private static void addModeratorAttendees(List<Engagement__c> engagements, Map<Id, Id> newGroupOwnerMap) {

        // Create a map to relate each Engagement to it's related Twenty Group.
        Map<Id, Id> engagementToGroup = new Map<Id, Id>();
        for(Engagement__c eng : engagements) {            
            engagementToGroup.put(eng.Id, eng.X20_Group__c);
        }

        // Get all Moderator Attendees for the engagements. 
        List<Engagement_Attendee__c> attendees = [
            SELECT Id, Name, Engagement__c, Attendee_Type__c, Contact__c, Collateral_Name__c 
            FROM Engagement_Attendee__c 
            WHERE Engagement__c IN :engagementToGroup.keySet() 
            AND Attendee_Type__c = 'Moderator'
        ];

        // Get Group Owner Ids to get the related Account Info. newPropOwnerMap(TwentyGroupId, GroupOwnerId/ContactId)        
        Set<Id> groupOwnerIds = new Set<Id>(newGroupOwnerMap.values()); // Cast the returned List to a Set. 

        Map<Id, Contact> contactMap = new Map<Id, Contact>([
            SELECT Id, FirstName, LastName, Nickname__c, AccountId, Account.ShippingCity, Account.ShippingStateCode 
            FROM Contact
            WHERE Id IN :groupOwnerIds
        ]);
        
        System.debug('TwentyGroupController.addModeratorAttendees:: contactMap: ' + contactMap);
        List<Engagement_Attendee__c> attendeesToCreate = new List<Engagement_Attendee__c>();
        
        // Loop through each Engagement to create a new Moderator Attendee. 
        for(Engagement__c eng : engagements) {
            Id twentyGroupId = eng.X20_Group__c; // Get the related Twenty Group Id for the current Engagement.
            Id newGroupOwnerId = newGroupOwnerMap.get(twentyGroupId); // Get the new Group Owner Id for this Twenty Group. 

            // Skip if no valid Group Owner is assigned or not found in the Contact map.
            if(newGroupOwnerId == null || !contactMap.containsKey(newGroupOwnerId)) {
                continue;
            }
            // Get the current Contact record.
            Contact con = contactMap.get(newGroupOwnerId);

            // Create the new Engagement Attendee record. 
            Engagement_Attendee__c newAttendee = new Engagement_Attendee__c();
            newAttendee.Contact__c = con.Id;
            newAttendee.Account__c = con.AccountId;
            newAttendee.Attendee_Type__c = 'Moderator';
            newAttendee.Engagement__c = eng.Id;
            newAttendee.City__c = con.Account.ShippingCity;
            newAttendee.State__c = con.Account.ShippingStateCode;  
            newAttendee.Age_Group__c = 'Adult';
            newAttendee.Arrival__c = eng.Engagement_Start__c.addDays(-1);
            newAttendee.Departure__c = eng.Engagement_End__c;
            newAttendee.Attendance_Status__c = 'Confirmed';
            if(!String.isBlank(con.Nickname__c)) {
                newAttendee.Collateral_Name__c = con.Nickname__c + ' ' + con.LastName;
            } else {
                newAttendee.Collateral_Name__c = con.FirstName + ' ' + con.LastName;
            }
            attendeesToCreate.add(newAttendee);            
        }
        
        if(!attendeesToCreate.isEmpty()) {
            System.debug('TwentyGroupController.addModeratorAttendees :: attendeesToCreate: ' + attendeesToCreate);
            List<Database.SaveResult> results = Database.insert(attendeesToCreate, false);
            Logger.logErrorList('TwentyGroupController.addModeratorAttendees', results, attendeesToCreate);
            //insert(attendeesToCreate);
        }
    }

}