unpackaged/main/default/objects/Account/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Owner__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM Associates</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements (Owner)</relationshipLabel>
    <relationshipName>Engagements_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <formula>IF(
NOT(ISBLANK( X20_Group__c )),
 X20_Group__r.Name,
IF(
NOT(ISBLANK( Proprietary_Group__c )),
 Proprietary_Group__r.Group_Number__c  ,
&quot;&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_End__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/X20_Groups_Member__c.field-meta.xml
<CustomField>
    <fullName>X20_Groups_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Groups Member Account</label>
    <referenceTo>X20_Groups_Member__c</referenceTo>
    <relationshipLabel>Engagement Attendance</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group Number</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <description>Field label change based on business request</description>
    <formula>Owner_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Owner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>(&quot;Candidate&quot;)</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Member_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/NCM_Member_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Candidate</fullName>
    </customValue>
    <customValue>
        <fullName>Full Member</fullName>
    </customValue>
    <customValue>
        <fullName>Special_Composite</fullName>
        <label>Special Composite</label>
    </customValue>
    <customValue>
        <fullName>Additional_Store</fullName>
        <label>Additional Store</label>
    </customValue>
    <customValue>
        <fullName>1/2 Member</fullName>
        <isActive>false</isActive>
        <label>1/2 Member</label>
    </customValue>
    <customValue>
        <fullName>Associate Member</fullName>
        <isActive>false</isActive>
        <label>Associate Member</label>
    </customValue>
    <customValue>
        <fullName>Composite Only Member</fullName>
        <isActive>false</isActive>
        <label>Composite Only Member</label>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Member</fullName>
        <isActive>false</isActive>
        <label>Member</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <masterLabel>NCM Member Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EngagementEndCandidateApprovalTask.cls
public with sharing class EngagementEndCandidateApprovalTask {

    @InvocableMethod(label='Generate Candidate Approval Tasks' description='For any 20G Candidates in the meeting, create an approval task for the group owner.' category='Engagement')
    public static void createCandidateApprovalTasks( List<List<Engagement__c>> engagementList) {

        final String logTag = '[createCandidateApprovalTasks]';
        Engagement__c eng = engagementList[0][0];
        System.debug(logTag + 'Engagement: ' + eng.Name + ' - ' + eng.Engagement_End_Date__c);

        Set<Id> memberIdSet = new Set<Id>();
        for(Engagement_Attendee__c att : [select id, X20_Groups_Member__c from Engagement_Attendee__c WHERE Engagement__c = :eng.Id AND Attendance_Status__c = 'Confirmed' AND X20_Groups_Member__r.Type__c = 'Candidate']){
            memberIdSet.add(att.X20_Groups_Member__c);
        }
        System.debug(logTag + 'There are ' + memberIdSet.size() + ' confirmed candidate attendee members for this engagement (' + eng.Id + ').');

        List<X20_Groups_Member__c> twentyGroupMembers = [SELECT 
                                                    Id, 
                                                    Name, 
                                                    Group_ID__c,
                                                    Group_ID__r.Name,
                                                    Group_Id__r.NCM_Proprietor__c,
                                                    Group_Id__r.NCM_Proprietor__r.Email,
                                                    Group_Id__r.NCM_Proprietor__r.User_Id__c
                                                   FROM X20_Groups_Member__c 
                                                   WHERE Id IN :memberIdSet];

        
        if(!twentyGroupMembers.isEmpty()){
            System.debug(logTag + 'There are ' + twentyGroupMembers.size() + ' 20 Group Member candidates to process for Engagement ' + eng.Id);
            String candApprRecType = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Candidate Approval').getRecordTypeId();
            List<Task> newTasks = new List<Task>();
            Map<Id,X20_Groups_Member__c> memberMap = new Map<Id,X20_Groups_Member__c>();

            for(X20_Groups_Member__c grpMember:twentyGroupMembers){
                
                memberMap.put(grpMember.Id, grpMember);

                Task newTask = new Task(
                    RecordTypeId = candApprRecType,
                    WhatId = grpMember.Id,
                    WhoId = grpMember.Group_Id__r.NCM_Proprietor__c, //eng.Engagement_Owner__c,
                    OwnerId = grpMember.Group_Id__r.NCM_Proprietor__r.User_Id__c,
                    Subject = 'Moderator Candidate Approval/Rejection: ' + grpMember.Name,
                    ActivityDate = eng.Engagement_End_Date__c.addDays(2),
                    X20_Group__c = grpMember.Group_ID__c,
                    Group_Number__c = grpMember.Group_ID__r.Name,
                    Membership_20G__c = grpMember.Id,
                    Engagement__c = eng.Id
                );
                newTasks.add(newTask);
                

            }

            

            if(!newTasks.isEmpty()){
                System.debug(logTag + 'Creating ' + newTasks.size() + ' new Task records.');
                Database.SaveResult[] lsr = Database.insert(newTasks, false);
                List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
            
                Integer i = 0;
                for(Database.SaveResult sr:lsr){
                    Task t = newTasks[i];

                    if(!sr.isSuccess()){
                        // Error inserting task.
                        System.debug(logTag + 'There was a problem inserting the new Task record for ' + t.WhatId + '. Reason: ' + sr.getErrors()[0].getMessage());
                    } else {
                        System.debug(logTag + 'Task created for member ' + t.Membership_20G__c + ' for (whoId) ' + t.whoId + ', (ownerId) ' + t.OwnerId);
                
                        X20_Groups_Member__c memberInfo = memberMap.get(t.Membership_20G__c);
                        Messaging.SingleEmailMessage taskEmail = createTaskEmail(t, memberInfo);
                        emailsToSend.add(taskEmail);
                    }

                    i++;
                }


                if(!emailsToSend.isEmpty()){
                    System.debug(logTag + 'Sending ' + emailsToSend.size() + ' task notification emails..');
                    Messaging.sendEmail(emailsToSend);
                }


            } else {
                System.debug(logTag + 'No new tasks will be inserted.');
            }
        } else {
            System.debug(logTag + 'There are no 20 Group Member candidates to process for Engagement ' + eng.Id);
        }

    }


    private static Messaging.SingleEmailMessage createTaskEmail(Task tsk, X20_Groups_Member__c member){

        Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
		emailMsg.setToAddresses(new List<String>{tsk.whoId});
		emailMsg.setReplyTo('salesforceadmin@ncmassociates.com');
		emailMsg.setSenderDisplayName('NCM Task Assignment');
		emailMsg.setSubject('Candidate Approval Task Assigned for ' + tsk.Group_Number__c);

		String recordlink = URL.getOrgDomainUrl().toExternalForm() + '/' + tsk.Id;
        String body = '<p style="font-size:18px;color:blue;font-weight:bold;">New Task</p><p>' + 
                      '<b>20 Group Member Account: </b>' + member.Name + '<br/>' + 
                      '<b>Due Date: </b>' + tsk.ActivityDate + '<br/><br/>' + 
                      'For more details, click the following link:<br/><a href=\'' + recordlink + '\'>Approval Task for ' + tsk.Group_Number__c + '</a></p>';
		emailMsg.setHtmlBody(body);

        return emailMsg;

    }

    /*
    private static Messaging.SingleEmailMessage createTaskEmail(Task tsk, String modEmail, String candidateName, String groupName){

        Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
		emailMsg.setToAddresses(new List<String>{modEmail});
		emailMsg.setReplyTo('salesforceadmin@ncmassociates.com');
		emailMsg.setSenderDisplayName('Candidate Approval Task Assigned for ' + groupName);
		emailMsg.setSubject('Candidate Approval Task Assigned for ' + groupName);

		string body = 'A Candidate Approval Task has been created for you to approve or reject the following candidate: <br/>';
		body = body + 'Candidate: ' + candidateName;
		body = body + 'Task: ' + '/' + tsk.Id;
		emailMsg.setHtmlBody(body);

        return emailMsg;

    }
    */

}