unpackaged/main/default/objects/Account/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>to update the city go to the hotel that is listed in the hotel/Meeting Location field and update the city on the physical address</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Confirmed_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel/Meeting Location</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hotel,NCM Client,NCM Management Group</value>
        </filterItems>
        <filterItems>
            <field>Account.Out_of_Business__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagements_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Engagements_Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagements Checklist</label>
    <referenceTo>Engagements_Checklist__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Owner__c.field-meta.xml
<CustomField>
    <fullName>Group_Owner__c</fullName>
    <formula>IF(ISBLANK(X20_Group__r.NCM_Proprietor__r.FirstName),Proprietary_Group__r.Group_Owner__r.FirstName &amp; &quot; &quot; &amp; Proprietary_Group__r.Group_Owner__r.LastName,X20_Group__r.NCM_Proprietor__r.FirstName &amp; &quot; &quot; &amp; 
X20_Group__r.NCM_Proprietor__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Owner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Proprietary_Group__c.field-meta.xml
<CustomField>
    <fullName>Proprietary_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietary Group</label>
    <referenceTo>Proprietary_Group__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Reception_Date__c.field-meta.xml
<CustomField>
    <fullName>Reception_Date__c</fullName>
    <label>Reception Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State(old)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagements_Checklist__c/Engagements_Checklist__c.object-meta.xml
<CustomObject>
    <description>Temporary object to maintain task checklists for Consulting Engagements - set to be a future feature of the NCMi/Retail Solutions engines.</description>
    <label>Engagements Checklist</label>
    <nameField>
        <label>Engagements Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagements_Checklist__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Engagements_Checklist__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>NCM Engagement the Checklist is for</inlineHelpText>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagements Checklist</relationshipLabel>
    <relationshipName>Engagements_Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagements_Checklist__c/fields/Engagement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End_Date__c</fullName>
    <label>Engagement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagements_Checklist__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Engagements_Checklist__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>20 Group is no longer active.</errorMessage>
        <filterItems>
            <field>Twenty_Groups__c.Delete_Date__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements Checklist</relationshipLabel>
    <relationshipName>Engagements_Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/Proprietary_Group__c.object-meta.xml
<CustomObject>
    <label>Proprietary Group</label>
    <nameField>
        <label>Proprietary  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Meeting_Support_Contact__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Support_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NCM Employee who assists client and NCM Proprietor for this service or product</description>
    <label>Meeting Support Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proprietary Groups (Meeting Support Contact)</relationshipLabel>
    <relationshipName>Proprietary_Groups4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Support_Staff__c.field-meta.xml
<CustomField>
    <fullName>Support_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Support Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM Associates</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proprietary Groups (Support Staff)</relationshipLabel>
    <relationshipName>Proprietary_Groups2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Meeting_Support_Contact__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Support_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NCM Employee who assists client and NCM Proprietor for this service or product</description>
    <label>Meeting Support Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Groups (Meeting Support Contact)</relationshipLabel>
    <relationshipName>X20_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Support_Staff__c.field-meta.xml
<CustomField>
    <fullName>NCM_Support_Staff__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who assists client and NCM Proprietor for this service or product</description>
    <label>Client Support Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group (Support Staff)</relationshipLabel>
    <relationshipName>X20_Group1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New Group - Acquiring</fullName>
            </value>
            <value>
                <fullName>New Group - Didn&#39;t Start</fullName>
            </value>
            <value>
                <fullName>New Group - Prospecting</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>New Group - Overflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/EngagementService.cls
@RestResource(urlMapping='/Engagements/*')
global with sharing class EngagementService {
    
    @HttpGet
    global static EngagementModel.EngagementResponse getEngagementsByGroupNumber() {
        
        // Prepare the response
        EngagementModel.EngagementResponse resp = new EngagementModel.EngagementResponse();
        
        // Parse the group account number
        RestRequest request = RestContext.request;
        String groupNumber = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        System.debug('Group Number: ' + groupNumber);

        if( String.isNotBlank(groupNumber) ){
            groupNumber = String.escapeSingleQuotes(groupNumber); // SOQL Injection Attack protection.

            List<Engagement__c> engagementResults = [SELECT 
                                                        Engagements_Checklist__c,
                                                        Engagement_End_Date__c,
                                                        Engagement_Start_Date__c,
                                                        City__c,
                                                        Confirmed_Hotel__r.Name, 
                                                        Confirmed_Hotel__r.ShippingStreet, 
                                                        Confirmed_Hotel__r.ShippingCity,
                                                        Confirmed_Hotel__r.ShippingState,
                                                        Confirmed_Hotel__r.ShippingStateCode,
                                                        Confirmed_Hotel__r.ShippingPostalCode,
                                                        Confirmed_Hotel__r.ShippingCountryCode,
                                                        Confirmed_Hotel__r.Phone, 
                                                        Confirmed_Hotel__r.Fax, 
                                                        Confirmed_Hotel__r.Website,
                                                        Reception_Date__c, 
                                                        State__c,
                                                        Status__c,
                                                        X20_Group__c,
                                                        X20_Group__r.Name,
                                                        X20_Group__r.Meeting_Support_Contact__r.Email,
                                                        X20_Group__r.Meeting_Support_Contact__r.Name,
                                                        Proprietary_Group__c,
                                                        Proprietary_Group__r.Name,
                                                        Proprietary_Group__r.Meeting_Support_Contact__r.Email,
                                                        Proprietary_Group__r.Meeting_Support_Contact__r.Name, 
                                                        X20_Group__r.NCM_Support_Staff__r.Email, 
                                                        X20_Group__r.NCM_Support_Staff__r.Name,  
                                                        X20_Group__r.NCM_Proprietor__r.Email, 
                                                        X20_Group__r.NCM_Proprietor__r.Name, 
                                                        Proprietary_Group__r.Support_Staff__r.Name,
                                                        Proprietary_Group__r.Support_Staff__r.Email,
                                                        Proprietary_Group__r.Group_Owner__r.Name,
                                                        Proprietary_Group__r.Group_Owner__r.Email,
                                                        Room_Block_Cut_off__c
                                                    FROM Engagement__c
                                                    WHERE (X20_Group__r.Name = :groupNumber OR Proprietary_Group__r.Group_Number__c = :groupNumber)
                                                        AND Engagement_End_Date__c >= TODAY
                                                        AND Status__c IN ('Firm','Tentative')
                                                    ORDER BY Engagement_Start_Date__c // This Order By is being used for the Next Meeting Info. Do not change. 
                                                    ];



            if(engagementResults.isEmpty()){
                resp.status = 'Error';
                resp.statusCode = '500';
                resp.message = 'No Engagement results found for group number ' + groupNumber;
            } else {
                resp.status = 'Success';
                resp.statusCode = '200';
                resp.message = engagementResults.size() + ' Engagement results found for group number ' + groupNumber;
                resp.groupNumber = groupNumber;
                resp.moderatorName = engagementResults[0].X20_Group__c != null ? engagementResults[0].X20_Group__r.NCM_Proprietor__r.Name : engagementResults[0].Proprietary_Group__r.Group_Owner__r.Name;
                resp.moderatorEmail = engagementResults[0].X20_Group__c != null ? engagementResults[0].X20_Group__r.NCM_Proprietor__r.Email : engagementResults[0].Proprietary_Group__r.Group_Owner__r.Email;
                resp.clientSupportName = engagementResults[0].X20_Group__c != null ? engagementResults[0].X20_Group__r.NCM_Support_Staff__r.Name : engagementResults[0].Proprietary_Group__r.Support_Staff__r.Name;
                resp.clientSupportEmail = engagementResults[0].X20_Group__c != null ? engagementResults[0].X20_Group__r.NCM_Support_Staff__r.Email : engagementResults[0].Proprietary_Group__r.Support_Staff__r.Email;
                resp.meetingSupportContactName = engagementResults[0].X20_Group__c != null ? engagementResults[0].X20_Group__r.Meeting_Support_Contact__r.Name : engagementResults[0].Proprietary_Group__r.Meeting_Support_Contact__r.Name;
                resp.meetingSupportContactEmail = engagementResults[0].X20_Group__c != null ? engagementResults[0].X20_Group__r.Meeting_Support_Contact__r.Email : engagementResults[0].Proprietary_Group__r.Meeting_Support_Contact__r.Email; 

                // Next Meeting Info. SALES-1614
                Date nextDate = null;
                String nextLocation = null;
                Date nextReservationDate = null;
                for( Engagement__c engagement :engagementResults) {  
                    if(engagement.Engagement_Start_Date__c > Date.Today()) {
                        nextDate = engagement.Engagement_Start_Date__c;
                        nextLocation = engagement.Confirmed_Hotel__r.Name;
                        nextReservationDate = engagement.Room_Block_Cut_off__c;
                        break;    
                    }
                }
                resp.nextMeetingDate = nextDate;
                resp.nextMeetingLocation = nextLocation;
                resp.nextHotelReservationDue = nextReservationDate;

                List<EngagementModel.Engagement> engagementList = new List<EngagementModel.Engagement>();
                for(Engagement__c eng:engagementResults){

                    String city = eng.Confirmed_Hotel__r.ShippingCity == null ? eng.City__c : eng.Confirmed_Hotel__r.ShippingCity;
                    String state = eng.Confirmed_Hotel__r.ShippingStateCode == null ? eng.State__c : eng.Confirmed_Hotel__r.ShippingStateCode;

                    EngagementModel.Engagement engModel = new EngagementModel.Engagement();
                    engModel.engagementId = eng.Id;
                    engModel.startDate = eng.Engagement_Start_Date__c;
                    engModel.endDate = eng.Engagement_End_Date__c;
                    engModel.receptionDate = eng.Reception_Date__c != null ? date.newinstance(eng.Reception_Date__c.year(), eng.Reception_Date__c.month(), eng.Reception_Date__c.day()) : null;
                    engModel.status = eng.Status__c;
                    engModel.checklistId = eng.Engagements_Checklist__c;
                    engModel.confirmedHotel = eng.Confirmed_Hotel__r.Name;
                    engModel.hotelPhone = eng.Confirmed_Hotel__r.Phone;
                    engModel.hotelFax = eng.Confirmed_Hotel__r.Fax;
                    engModel.hotelWebsite = eng.Confirmed_Hotel__r.Website;
                    engModel.hotelStreet = eng.Confirmed_Hotel__r.ShippingStreet; 
                    engModel.hotelCity = city;// eng.Confirmed_Hotel__r.ShippingCity;
                    engModel.hotelState = state; //eng.Confirmed_Hotel__r.ShippingStateCode;
                    engModel.hotelZipCode = eng.Confirmed_Hotel__r.ShippingPostalCode;
                    engModel.hotelCountry = eng.Confirmed_Hotel__r.ShippingCountryCode;
                    engagementList.add(engModel);
                }                      
                resp.engagements = engagementList;
            }

        } else {
            resp.status = 'Error';
            resp.statusCode = '500';
            resp.message = 'Missing parameter: groupNumber.';
        }

        return resp;
    }

    

    private static String getHotelAddress(Account hotelAccount){
        if(hotelAccount != null){
            return hotelAccount.ShippingStreet + ', ' + hotelAccount.ShippingCity + ', ' + hotelAccount.ShippingState + ' ' + hotelAccount.ShippingPostalCode + ' ' + hotelAccount.ShippingCountry;
        } else {
            return '';
        }
    }
    
}