unpackaged/main/default/objects/Account/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Owner__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM Associates</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements (Owner)</relationshipLabel>
    <relationshipName>Engagements_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_End__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <formula>IF(
    NOT(ISBLANK(X20_Groups_Member__c)),
    X20_Groups_Member__r.Member_Number_Code__c,
    IF(
        NOT(ISBLANK(Proprietary_Account__c)),
        Proprietary_Account__r.Member_Number_Code__c,
        &quot;&quot;
    )
)</formula>
    <label>Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/X20_Groups_Member__c.field-meta.xml
<CustomField>
    <fullName>X20_Groups_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Groups Member Account</label>
    <referenceTo>X20_Groups_Member__c</referenceTo>
    <relationshipLabel>Engagement Attendance</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Group Start Date</description>
    <inlineHelpText>Group Start Date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New Group - Acquiring</fullName>
            </value>
            <value>
                <fullName>New Group - Didn&#39;t Start</fullName>
            </value>
            <value>
                <fullName>New Group - Prospecting</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>New Group - Overflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/X20_Group_Member_Contact__c.object-meta.xml
<CustomObject>
    <label>20 Group Member Contact</label>
    <nameField>
        <label>20 Group Member Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Group Member Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group Member Contacts</relationshipLabel>
    <relationshipName>X20_Group_Member_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/fields/Contact_Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Contact_Active_Date__c</fullName>
    <label>Contact Active Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <formula>X20_Group__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <label>Member Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>20 Group Member Contacts</relationshipLabel>
    <relationshipName>X20_Group_Member_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/fields/X20_Groups_Member__c.field-meta.xml
<CustomField>
    <fullName>X20_Groups_Member__c</fullName>
    <label>20 Groups Member</label>
    <referenceTo>X20_Groups_Member__c</referenceTo>
    <relationshipLabel>20 Group Member Contacts</relationshipLabel>
    <relationshipName>X20_Group_Member_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group Number</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Member_Email__c.field-meta.xml
<CustomField>
    <fullName>Member_Email__c</fullName>
    <inlineHelpText>Email member wishes to use for communication for this 20 Group membership</inlineHelpText>
    <label>Member Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <label>Member Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <description>Field label change based on business request</description>
    <formula>Owner_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Owner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date the member joined the 20 Group</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Global_Product_Service_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>(&quot;Candidate&quot;)</defaultValue>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Member_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Global_Product_Service_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Active - Don&#39;t Bill</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Disconnected</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
        <isActive>false</isActive>
        <label>Suspended</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <customValue>
        <fullName>Honorary</fullName>
        <isActive>false</isActive>
        <label>Honorary</label>
    </customValue>
    <masterLabel>Global Product/Service Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Member_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Candidate</fullName>
    </customValue>
    <customValue>
        <fullName>Full Member</fullName>
    </customValue>
    <customValue>
        <fullName>Special_Composite</fullName>
        <label>Special Composite</label>
    </customValue>
    <customValue>
        <fullName>Additional_Store</fullName>
        <label>Additional Store</label>
    </customValue>
    <customValue>
        <fullName>1/2 Member</fullName>
        <isActive>false</isActive>
        <label>1/2 Member</label>
    </customValue>
    <customValue>
        <fullName>Associate Member</fullName>
        <isActive>false</isActive>
        <label>Associate Member</label>
    </customValue>
    <customValue>
        <fullName>Composite Only Member</fullName>
        <isActive>false</isActive>
        <label>Composite Only Member</label>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Member</fullName>
        <isActive>false</isActive>
        <label>Member</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <masterLabel>NCM Member Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EngagementEndCandidateApprovalTask_Tests.cls
@isTest
public class EngagementEndCandidateApprovalTask_Tests {
    
    @TestSetup
    static void makeData(){

        SampleDataFactory.create20GroupAccountData();
                
        // Query for the Twenty Group created by SampleDataFactory.
        Twenty_Groups__c test20Group = [SELECT Id, Name, NCM_Proprietor__c FROM Twenty_Groups__c LIMIT 1];
        Id twentyGroupId = test20Group.Id;

        // Query for the record that was created on  line 8 for the Billing NCM Billing Contact Id.
        Id ncmBillingContactId = test20Group.NCM_Proprietor__c;

        // Get the Engagement Record Type for Retail Solutions.
        Id engagementRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        
        // Call the method from SampleDataFactory and pass in values created above. 
        SampleDataFactory.createEngagement_20G(twentyGroupId, engagementRecTypeId, ncmBillingContactId); 

        Engagement__c testEngagement = [select id, Name, Engagement_End_Date__c, Engagement_Owner__c from Engagement__c order by CreatedDate DESC LIMIT 1];

        // Add some Candidates to the Engagement
        Account candidateAcct = new Account(
            Name = 'Sample Porsche of Plainville',
            BillingStreet = '111 Main St', 
            BillingCity = 'Metroville', 
            BillingStateCode = 'NC', 
            BillingPostalCode = '27554'
        );
        insert(candidateAcct);

        Contact candContact = new Contact(
            AccountId = candidateAcct.Id, 
            FirstName = 'Bob', 
            LastName = 'Jones', 
            Email = 'bob.jones@noemail.com',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId(),
            MailingStreet = '4717 Grand Ave., Ste 500',
            MailingCity = 'Kansas City',
            MailingState = 'Missouri',
            MailingPostalCode = '64112'
        );
        insert(candContact);

        X20_Groups_Member__c candidateMember = new X20_Groups_Member__c(
            Group_ID__c = twentyGroupId,
            Account__c = candidateAcct.Id,
            Member_Number__c = 4,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addYears(3),
            Type__c = 'Candidate',
            Status__c = 'Submitted'
        );
        insert(candidateMember);

        X20_Group_Member_Contact__c candMemContact = new X20_Group_Member_Contact__c(
            X20_Group__c = twentyGroupId,
            X20_Groups_Member__c = candidateMember.Id,
            Contact__c = candContact.Id,
            Member_Email__c = candContact.Email,
            Contact_Active_Date__c = Date.today(),
            Contact_Status__c = 'Active',
            Contact_Type__c = 'Member'
        );
        insert(candMemContact);

        Engagement_Attendee__c candidateAtt = new Engagement_Attendee__c(
            Contact__c = candContact.Id,
            Account__c = candidateAcct.Id,
            X20_Groups_Member__c = candidateMember.Id,
            Name = candContact.Name,
            Engagement__c = testEngagement.Id,
            Arrival__c = Datetime.now().addDays(30),
            Departure__c = Datetime.now().addDays(34),
            Attendance_Status__c = 'Confirmed',
            Attendee_Type__c = 'Member',
            Attendee_Notes__c = 'Test'
        );
        insert(candidateAtt);

    }


    @isTest
    static void test1(){

        List<Engagement_Attendee__c> attList = [select id, name,X20_Groups_Member__r.Name, Attendance_Status__c, Engagement__r.Name from Engagement_Attendee__c];
        for(Engagement_Attendee__c att:attList){
            System.debug('Attendee: ' + att.Name + ' - ' + att.X20_Groups_Member__r.Name + ' - ' + att.Engagement__r.Name);
        }
        
        Engagement__c testEng = [select id, name, Engagement_Owner__c, Engagement_End_Date__c from Engagement__c limit 1];
        List<List<Engagement__c>> inputList = new List<List<Engagement__c>>();
        List<Engagement__c> engList = new List<Engagement__c>();
        engList.add(testEng);
        inputList.add(engList);
         
        // Get the 20 Group moderator user
        
        
        Test.startTest();
            EngagementEndCandidateApprovalTask.createCandidateApprovalTasks(inputList);
        Test.stopTest();

        List<Task> taskResults = [select id, whoId, whatId from Task];// where createddate = TODAY];
        Assert.areEqual(2,taskResults.size());

    }

}