unpackaged/main/default/objects/Product2/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Provisioning Required?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Level_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Name__c</fullName>
    <label>Level 1 Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Locked_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Locked_Frequency__c</fullName>
    <inlineHelpText>If defined here, the billing frequency will be pre-populated when a Billing Product is being setup.</inlineHelpText>
    <label>Locked Frequency?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Meetings_Included__c.field-meta.xml
<CustomField>
    <fullName>Meetings_Included__c</fullName>
    <description>Used to track whether a group is receiving the engagements purchased.</description>
    <label>Meetings Included</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Shipped_Product__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/billingTemplateTest.cls
@isTest(SeeAllData = true)
public class billingTemplateTest
{
	@isTest
	static void testBillingTemplate()
	{
		test.startTest();
		PricebookEntry pbe = [SELECT 
		                            Product2Id, 
		                            Product2.Name, 
									Product2.displayURL, 
									Product2.Locked_Frequency__c, 
									Product2.Core_Product__c, 
									Product2.Meetings_Included__c,
									Product2.Shipped_Product__c,
									Product2.Level_1_Name__c,
									Pricebook2Id, 
		                            Id, 
		                            UnitPrice
		                      FROM PricebookEntry 
		                      WHERE IsActive = TRUE
		                      LIMIT 1];
		pbe.Product2.displayURL = 'http://www.ncm.com';
		pbe.Product2.Core_Product__c = true;
		pbe.Product2.Locked_Frequency__c = 'One Time';
		billingTemplate billTemp = new billingTemplate(  );
		billTemp = new billingTemplate( pbe );
		boolean isValid = billingTemplate.isValid(billTemp);
		test.stopTest();
	}
}