unpackaged/main/default/objects/Product2/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Provisioning Required?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Level_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Name__c</fullName>
    <label>Level 1 Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Level_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Name__c</fullName>
    <label>Level 2 Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Locked_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Locked_Frequency__c</fullName>
    <inlineHelpText>If defined here, the billing frequency will be pre-populated when a Billing Product is being setup.</inlineHelpText>
    <label>Locked Frequency?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Meetings_Included__c.field-meta.xml
<CustomField>
    <fullName>Meetings_Included__c</fullName>
    <description>Used to track whether a group is receiving the engagements purchased.</description>
    <label>Meetings Included</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Shipped_Product__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/productController.cls
public without sharing class productController
{
	@AuraEnabled(cacheable=true)
	public static list<verticalNavigationSection> getProductSections(string sectionsWhereClause){
		try {
			string query = 'SELECT Id, Product2.RecordType.Name, Product2.Level_1_Name__c ';
			query = query + 'FROM PricebookEntry ';
			query = query + 'WHERE ' + sectionsWhereClause + ' AND Product2.Level_1_Name__c <> NULL ';
			query = query + 'ORDER BY Product2.RecordType.Name,Product2.Level_1_Name__c ';
			list<PricebookEntry> PBEs = Database.query(query);
			if (PBEs.size() >0) {
				
				list<verticalNavigationSection> navSecs = new list<verticalNavigationSection>();
				string recTypeName = PBEs.get(0).Product2.RecordType.Name;
				string lev1;
				list<verticalNavigationSection.sectionItem> sectionItems = new list<verticalNavigationSection.sectionItem>();

				for (PricebookEntry pbe : PBEs) {
					if (recTypeName <> pbe.Product2.RecordType.Name ) {
						
						verticalNavigationSection navSec = new verticalNavigationSection(recTypeName, sectionItems);
						navSecs.add(navSec);
						
						recTypeName = pbe.Product2.RecordType.Name;
						lev1 = pbe.Product2.Level_1_Name__c;

						string itemValue = recTypeName + ';' + lev1;
						verticalNavigationSection.sectionItem secItm = new verticalNavigationSection.sectionItem(lev1, itemValue);

						sectionItems = new list<verticalNavigationSection.sectionItem>();
						sectionItems.add(secItm);

					} else if(lev1 <> pbe.Product2.Level_1_Name__c){
						
						lev1 = pbe.Product2.Level_1_Name__c;
						string itemValue = recTypeName + ';' + lev1;

						verticalNavigationSection.sectionItem secItm = new verticalNavigationSection.sectionItem(lev1, itemValue);
						sectionItems.add(secItm);

					}
				}

				verticalNavigationSection navSec = new verticalNavigationSection(recTypeName, sectionItems);
				navSecs.add(navSec);

				return navSecs;
			} else{
				list<verticalNavigationSection> navSecs = new list<verticalNavigationSection>();
				return navSecs;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled(cacheable=true)
	public static list<productGroup> getProducts(string productsWhereClause){
		try {
			List<productGroup> prodGroup = new List<productGroup>();

			string query = 'SELECT Id, UnitPrice, Product2.Name, Product2.Level_1_Name__c, Product2.Level_2_Name__c, Product2.ProductCode, Product2.DisplayUrl, ';
			query = query + 'Product2.Description, Product2.Locked_Frequency__c, Product2.Core_Product__c, Pricebook2Id ';
			query = query + 'FROM PricebookEntry ';
			query = query + 'WHERE ' + productsWhereClause + ' ';
			query = query + 'ORDER BY Product2.Level_2_Name__c, Product2.Name ';
			list<PricebookEntry> PBEs = Database.query(query);

			if ( PBEs.size() > 0 )
			{
				String lev2 = PBEs.get(0).Product2.Level_2_Name__c;
				List<PricebookEntry> pbeList = new List<PricebookEntry>();
				for ( PricebookEntry pbe : PBEs )
				{
					if ( pbe.Product2.Level_2_Name__c == lev2 )
					{
						pbeList.add(pbe);
					}
					else
					{
						productGroup prodGrp = new productGroup( lev2, pbeList );
						prodGroup.add(prodGrp);

						pbeList = new List<PricebookEntry>();
						pbelist.add(pbe);
						lev2 = pbe.Product2.Level_2_Name__c;
					}
				}

				productGroup prodGrp = new productGroup( lev2, pbeList );
				prodGroup.add(prodGrp);
				return prodGroup;

			} else {
				return new List<productGroup>();
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled(cacheable=true)
	public static list<billingTemplate> convertPBEtoBillingTemplate(List<PricebookEntry> pbes)
	{
		List<billingTemplate> billTemps = new List<billingTemplate>();
		for ( PricebookEntry pbe : pbes )
		{
			billTemps.add(new billingTemplate( pbe ));
		}
		return billTemps;
	}

	@AuraEnabled(cacheable=true)
	public static list<billingTemplate> convertPBEtoBillingTemplate(List<String> pbeIds)
	{		
		List<PricebookEntry> pbes = [
			SELECT
				Id, 
				UnitPrice, 
				Product2.Name, 
				Product2.Level_1_Name__c, 
				Product2.Level_2_Name__c, 
				Product2.ProductCode, 
				Product2.DisplayUrl, 
				Product2.Description, 
				Product2.Locked_Frequency__c, 
				Product2.Core_Product__c, 
				Pricebook2Id,
				Product2.Meetings_Included__c,
				Product2.Shipped_Product__c
			FROM PricebookEntry
			WHERE Id IN :pbeIds
		];
		List<billingTemplate> billTemps = new List<billingTemplate>();
		for ( PricebookEntry pbe : pbes )
		{
			billTemps.add(new billingTemplate( pbe ));
		}
		return billTemps;
	}
}