unpackaged/main/default/objects/Product2/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Provisioning Required?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Level_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Name__c</fullName>
    <label>Level 1 Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Locked_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Locked_Frequency__c</fullName>
    <inlineHelpText>If defined here, the billing frequency will be pre-populated when a Billing Product is being setup.</inlineHelpText>
    <label>Locked Frequency?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Meetings_Included__c.field-meta.xml
<CustomField>
    <fullName>Meetings_Included__c</fullName>
    <description>Used to track whether a group is receiving the engagements purchased.</description>
    <label>Meetings Included</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Shipped_Product__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/billingTemplate.cls
public class billingTemplate {
	@AuraEnabled public string productName { get; set; }
	@AuraEnabled public string productURL { get; set; }
	@AuraEnabled public string productId { get; set; }
	@AuraEnabled public string displayURL { get; set; }
    
    @AuraEnabled public string frequency { get; set; }
    @AuraEnabled public boolean flowProvisioning { get; set; }

	@AuraEnabled public string pbId { get; set; }
	@AuraEnabled public string pbeId { get; set; }

	@AuraEnabled public Decimal listPrice { get; set; }
	@AuraEnabled public Decimal salePrice { get; set; }
	@AuraEnabled public Decimal quantity { get; set; }

	@AuraEnabled public string lineDescription { get; set; }
	@AuraEnabled public string billingNotes { get; set; }
	@AuraEnabled public string discountReason { get; set; }
    @AuraEnabled public string level1Name { get; set; }
	@AuraEnabled public Boolean shippedProduct { get; set; }

	@AuraEnabled public Integer meetingsIncluded {get; set;}

    public static boolean isValid(billingTemplate billTemp){
        if(
            billTemp.productId != null &&
            billTemp.pbId != null &&
            billTemp.quantity != null &&
            billTemp.salePrice != null
        ){
            return true;
        } else{
            return false;
        }
    }

	public billingTemplate() {
	}

	public billingTemplate(PricebookEntry pbe) {
		System.debug('billingTemplate Method is running');
		this.productName = pbe.Product2.Name;
		this.productURL = '/' + pbe.Product2Id;
		this.productId = pbe.Product2Id;
		this.shippedProduct = pbe.Product2.Shipped_Product__c;

		if(pbe.Product2.displayURL != null) {
			this.displayURL = pbe.Product2.displayURL;
		}
        if(pbe.Product2.Locked_Frequency__c != null){
            this.frequency = pbe.Product2.Locked_Frequency__c;
        }
        if(pbe.Product2.Core_Product__c){
            this.flowProvisioning = true;
        }

		this.pbId = pbe.Pricebook2Id;
		this.pbeId = pbe.Id;
		this.listPrice = pbe.UnitPrice;
		this.salePrice = pbe.UnitPrice;
		this.quantity = 1;
		this.level1Name = pbe.Product2.Level_1_Name__c;
		this.meetingsIncluded = Integer.valueOf(pbe.Product2.Meetings_Included__c);
	}

}