unpackaged/main/default/objects/Product2/fields/CZ_ItemId__c.field-meta.xml
<CustomField>
    <fullName>CZ_ItemId__c</fullName>
    <externalId>true</externalId>
    <label>CZ ItemId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Last_CZ_Sync__c.field-meta.xml
<CustomField>
    <fullName>Last_CZ_Sync__c</fullName>
    <description>The last date/time this product was synced over to ChargeZoom.</description>
    <inlineHelpText>The last date/time this product was synced over to ChargeZoom.</inlineHelpText>
    <label>Last CZ Sync</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/sendIemToCZQueueable.cls
public with sharing class sendIemToCZQueueable implements Queueable, Database.AllowsCallouts{
    public Map<Id,PaymentModel.CZCreateItem> items;
    public sendIemToCZQueueable(Map<Id,PaymentModel.CZCreateItem> items) {
        this.items = items;
    }

    public void execute(QueueableContext context) {
        //convert keyset to list and get the first Id
        List<Id> prodIdList = new List<Id>(items.keySet());
        Id prodId = prodIdList[0];
        try {
            System.debug('~~~prodId: ' + prodId);
            PaymentModel.CZCreateItem item = items.remove(prodId);
            ChargeZoomUtility czu = new ChargeZoomUtility();
            PaymentModel.CZCreateItemResponse itmRsp = czu.createItem(item);
            //if(item.itemId == null) {
                Product2 p = new Product2(
                    CZ_ItemId__c = itmRsp.data.ListId,
                    Id = prodId,
                    Last_CZ_Sync__c = DateTime.now()
                );
                update p;
            //}
        } catch (Exception ex) {
            Logger.logErrorEvent('sendIemToCZQueueable', null, UserInfo.getName(), ex.getTypeName(), ex.getMessage(), ex.getStackTraceString(), prodId);
        }

        //if there are still items in the map, then loop through the queueable again
        //unless this is a test.
        if(items.size() > 0 && !Test.isRunningTest()) {
            System.enqueueJob(new sendIemToCZQueueable(items));
        }
        
    }
}