unpackaged/main/default/objects/Product2/fields/CZ_ItemId__c.field-meta.xml
<CustomField>
    <fullName>CZ_ItemId__c</fullName>
    <externalId>true</externalId>
    <label>CZ ItemId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product is related to this Dimension</description>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Value__c</fullName>
    <inlineHelpText>Value of the core product being sold.</inlineHelpText>
    <label>Product Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/CZ_LoadProductsBatch_Test.cls
@isTest
public with sharing class CZ_LoadProductsBatch_Test {
    @isTest
    public static void testLoadProducts() {
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());
        c2g__codaDimension1__c d1 = new c2g__codaDimension1__c(Name = 'Test Dim1', c2g__ReportingCode__c = 'TD1');
        insert d1;
        Product2 p = new Product2(Name = 'test product', Description = 'test description', Product_Value__c = -50, IsActive = true, Dimension_1__c = d1.Id);
        insert p;
        Test.startTest();
        Id pid;
        CZ_LoadProductsBatch lpb = new CZ_LoadProductsBatch(pid);
        database.executebatch(lpb);
        Test.stopTest();
        Product2 p2 = [SELECT Id, CZ_ItemId__c FROM Product2 LIMIT 1];
        Assert.areEqual('PRO-1234567899', p2.CZ_ItemId__c);
    }
}