unpackaged/main/default/objects/Product2/fields/CZ_ItemId__c.field-meta.xml
<CustomField>
    <fullName>CZ_ItemId__c</fullName>
    <externalId>true</externalId>
    <label>CZ ItemId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product is related to this Dimension</description>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Last_CZ_Sync__c.field-meta.xml
<CustomField>
    <fullName>Last_CZ_Sync__c</fullName>
    <description>The last date/time this product was synced over to ChargeZoom.</description>
    <inlineHelpText>The last date/time this product was synced over to ChargeZoom.</inlineHelpText>
    <label>Last CZ Sync</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Locked_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Locked_Frequency__c</fullName>
    <inlineHelpText>If defined here, the billing frequency will be pre-populated when a Billing Product is being setup.</inlineHelpText>
    <label>Locked Frequency?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Value__c</fullName>
    <inlineHelpText>Value of the core product being sold.</inlineHelpText>
    <label>Product Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>Production_Run_Type__c</fullName>
    <label>Production Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>New Proprietary Member</fullName>
            </value>
            <value>
                <fullName>Special Composite</fullName>
            </value>
            <value>
                <fullName>Retail Ops</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>PTA</fullName>
            </value>
            <value>
                <fullName>Trend</fullName>
            </value>
            <value>
                <fullName>FIDO</fullName>
            </value>
            <value>
                <fullName>PPP</fullName>
            </value>
            <value>
                <fullName>PAR</fullName>
            </value>
            <value>
                <fullName>Three-Year Comp</fullName>
            </value>
            <value>
                <fullName>CIP - Org Meeting</fullName>
            </value>
            <value>
                <fullName>Retail Ops Proprietary</fullName>
            </value>
            <value>
                <fullName>HealthCheck</fullName>
            </value>
            <value>
                <fullName>ConSept New Member</fullName>
            </value>
            <value>
                <fullName>ConSept New Proprietary Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Shipped_Product__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Product2ChargeZoomSync_Tests.cls
@IsTest
public class Product2ChargeZoomSync_Tests {
    @TestSetup
    static void makeData(){
        
        // Sample Dimensions and Products
        c2g__codaDimension1__c testDimension1 = new c2g__codaDimension1__c(
            Name = 'Test Dimension1',
            c2g__ReportingCode__c = '2000',
            Conductor_CC_Email__c = 'mdemeglio@ncmassociates.com'
        );
        insert(testDimension1);

        // 20G Quarterly Product and Shipping
        List<Product2> testProducts = new List<Product2>();
        Product2 test20GroupQuarterlyProduct = new Product2(
            IsActive = true,
            RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('20 Groups').getRecordTypeId(),
            Name = '20 Group Quarterly Product',
            Dimension_1__c = testDimension1.Id,
            Product_Value__c = 500.00,
            Production_Run_Type__c = 'Not Applicable',
            Family = '20 Groups',
            Locked_Frequency__c = 'Quarterly',
            Shipped_Product__c = True, // Required for trigger entry criteria!
            CZ_ItemId__c = 'PRO-111'
        );
        insert(test20GroupQuarterlyProduct);

    }


    @isTest 
    private static void batchUpdatesCZTest(){
        // Identify the Mock class
        Test.setMock(HttpCalloutMock.class, new CZCalloutMock());
        Product2ChargeZoomSync syncJob = new Product2ChargeZoomSync();

        Test.startTest();
            Database.executeBatch( syncJob );
        Test.stopTest();

        List<Product2> updatedProductResults = [select id, name, Last_CZ_Sync__c from Product2 where Last_CZ_Sync__c = today];
        Assert.areEqual(1, updatedProductResults.size());
    }

}