unpackaged/main/default/objects/Product2/fields/Level_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Name__c</fullName>
    <label>Level 1 Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Level_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Level_2_Name__c</fullName>
    <label>Level 2 Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Object_Structure__c.field-meta.xml
<CustomField>
    <fullName>Object_Structure__c</fullName>
    <label>Object Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>20 Group</fullName>
            </value>
            <value>
                <fullName>aXcessa</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Healthcheck</fullName>
            </value>
            <value>
                <fullName>Program</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Objects_Added_From__c.field-meta.xml
<CustomField>
    <fullName>Objects_Added_From__c</fullName>
    <label>Objects Added From</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Object_Structure__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20 Group Member Account</fullName>
            </value>
            <value>
                <fullName>20 Groups</fullName>
            </value>
            <value>
                <fullName>aXcessa Group</fullName>
            </value>
            <value>
                <fullName>aXcessa Store</fullName>
            </value>
            <value>
                <fullName>Echo Store</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Engagement Attendee</fullName>
            </value>
            <value>
                <fullName>Healthcheck Instance</fullName>
            </value>
            <value>
                <fullName>Healthcheck Store</fullName>
            </value>
            <value>
                <fullName>NCM Program</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Proprietary Account</fullName>
            </value>
            <value>
                <fullName>Proprietary Group</fullName>
            </value>
            <value>
                <fullName>Proprietary Master Group</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Training Credit</fullName>
            </value>
            <value>
                <fullName>Training Subscription</fullName>
            </value>
            <value>
                <fullName>Training Subscription Account</fullName>
            </value>
            <value>
                <fullName>Training Subscription Term</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/productControllerTest.cls
@isTest(SeeAllData = true)
public class productControllerTest
{
	@isTest
	static void testProductController()
	{
		test.startTest();
		id pbId = [SELECT 
		                 Id
		           FROM Pricebook2 
		           WHERE IsStandard = true].id;
		list<PricebookEntry> pbes = [SELECT 
		                                   Id, 
		                                   Product2Id
		                             FROM PricebookEntry 
		                             WHERE Product2.IsActive = true and IsActive = true and Pricebook2Id = :pbId
		                             LIMIT 200];
		Product2 prod = new Product2(  );
		List<Product2> prods = new list<Product2>();
		prod.Id = pbes.get(0).Product2Id;
		prod.Object_Structure__c = 'All';
		prod.Objects_Added_From__c = 'Opportunity';
		prod.Level_1_Name__c = 'Test';
		prod.Level_2_Name__c = 'Test';
		prods.add(prod);
		Id prodId = prod.Id;
		Product2 prod2 = new Product2(  );
		for ( PricebookEntry pbe : pbes )
		{
			if ( prodId != pbe.Product2Id )
			{
				prod2.id = pbe.Product2Id;
				prod2.Object_Structure__c = 'All';
				prod2.Objects_Added_From__c = 'Opportunity';
				prod2.Level_1_Name__c = 'Test';
				prod2.Level_2_Name__c = 'Test 2';
			}
		}
		prods.add(prod2);
		update prods;
		list<productGroup> prodGrps = productController.getProducts('Product2.Objects_Added_From__c = \'Opportunity\'');
		Try
		{
			List<billingTemplate> billTemps = productController.convertPBEtoBillingTemplate(pbes);
		}
		catch ( exception er )
		{
		}
		test.stopTest();
	}

	@isTest
	private static void testGetProductSections() {
		List<verticalNavigationSection> lst = productController.getProductSections('Id != null');
		Assert.isNotNull(lst, 'Should not return a null list');
	}

	@IsTest
	static void testConvertPBEtoBillingTemplate(){
		List<String> pbeIds = new List<String>();
		for (PricebookEntry pbe : [SELECT Id FROM PricebookEntry LIMIT 5]) {
			pbeIds.add(pbe.Id);
		}
		List<billingTemplate> lst = productController.convertPBEtoBillingTemplate(pbeIds);
		Assert.areEqual(pbeIds.size(), lst.size(), 'returned list should be same size as parameter list');
		
	}
}