unpackaged/main/default/objects/Lead/fields/NCM_Lead_Entry__c.field-meta.xml
<CustomField>
    <fullName>NCM_Lead_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCM Lead Entry</label>
    <referenceTo>NCM_Lead_Entry__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/NCM_Lead_Entry__c.object-meta.xml
<CustomObject>
    <description>Module for NCM employees to add leads they wish to have submitted to the Sales Pipeline (Lead to Opportunity)</description>
    <label>NCM Lead</label>
    <nameField>
        <label>NCM Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NCM Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field searches Salesforce for an existing Account in the system and populates all of the Company Fields if found.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NCM Leads</relationshipLabel>
    <relationshipName>NCM_Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field searches Salesforce for an existing Contact in the system and populates the contact info fields with the information we already have</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NCM Leads (Contact)</relationshipLabel>
    <relationshipName>NCM_Lead_Entries1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed__c</fullName>
    <label>Contract Signed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Binary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>NCM_Lead_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/NCM_Lead_Entry__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <label>Institute</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed__c</fullName>
    <label>Contract Signed? (Code)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Binary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DocuSign_Sent__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Sent__c</fullName>
    <label>DocuSign Sent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DocuSign_Signed__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Signed__c</fullName>
    <label>DocuSign Signed</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NCM_Lead_Entry__c.field-meta.xml
<CustomField>
    <fullName>NCM_Lead_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NCM Lead Entry</label>
    <referenceTo>NCM_Lead_Entry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/axcessa.recordType-meta.xml
<RecordType>
    <fullName>axcessa</fullName>
    <active>true</active>
    <businessProcess>axcessa</businessProcess>
    <description>For axcessa opportunities</description>
    <label>axcessa</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Healthcheck.recordType-meta.xml
<RecordType>
    <fullName>Healthcheck</fullName>
    <active>true</active>
    <businessProcess>Healthcheck</businessProcess>
    <label>Healthcheck</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/LiveAudit.recordType-meta.xml
<RecordType>
    <fullName>LiveAudit</fullName>
    <active>true</active>
    <businessProcess>Software Solutions</businessProcess>
    <label>LiveAudit</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Proprietary.recordType-meta.xml
<RecordType>
    <fullName>Proprietary</fullName>
    <active>true</active>
    <businessProcess>Proprietary</businessProcess>
    <label>Proprietary</label>
</RecordType>

unpackaged/main/default/globalValueSets/Binary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Yes or No picklist</description>
    <masterLabel>Binary</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AutoConvertLeads.cls
Public class AutoConvertLeads{
    
    public class vars {
        @InvocableVariable(label='Lead Id' Required=true)
        public id ldId;
    }
    
    @InvocableMethod
    public static void LeadConvert(List<vars> vars){
        
        list<id> LeadIds = new list<id>();
        for (vars var : vars){
            LeadIds.add(var.ldId);
        }
        list<Lead> lds = [select id, Name, NCM_Lead_Entry__r.Account__c, NCM_Lead_Entry__r.Contact__c, NCM_Lead_Entry__r.Opportunity__c 
                          from Lead 
                          where id in :LeadIds
                         ];
        
        LeadStatus CLeadStatus = [select Id, MasterLabel FROM LeadStatus WHERE IsConverted=true Limit 1];
        List<Database.LeadConvert> MassLeadconvert = new List<Database.LeadConvert>();
        
        for(Lead ld: lds){
            Database.LeadConvert Leadconvert = new Database.LeadConvert();
            Leadconvert.setLeadId(ld.id);                
            Leadconvert.setConvertedStatus(CLeadStatus.MasterLabel);
            
            if(ld.NCM_Lead_Entry__r.Account__c != null){
                LeadConvert.accountid = ld.NCM_Lead_Entry__r.Account__c;
            }
            
            if(ld.NCM_Lead_Entry__r.Contact__c != null){
                LeadConvert.contactid = ld.NCM_Lead_Entry__r.Contact__c;
            }
            
            if(ld.NCM_Lead_Entry__r.Opportunity__c != null){
                LeadConvert.opportunityid = ld.NCM_Lead_Entry__r.Opportunity__c;
            } else{
                Leadconvert.setOpportunityName('Auto Converted Lead');
            }
            
            Leadconvert.bypassaccountdedupecheck = true;
            Leadconvert.bypasscontactdedupecheck = true;
            MassLeadconvert.add(Leadconvert);
        }
        
        List<Database.LeadConvertResult> lcrs = new List<Database.LeadConvertResult>();
        if (!MassLeadconvert.isEmpty()) {
            lcrs = Database.convertLead(MassLeadconvert, false);
        }
        
        id NCMiRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('NCM Institute').getRecordTypeId();
        list<Opportunity> opps = new list<Opportunity>();
        
        for (Database.LeadConvertResult lcr : lcrs){
            if(lcr.isSuccess()){
                id oppId = lcr.getOpportunityId();
                id conId = lcr.getContactId();
                
                Opportunity opp = [select id, OwnerId, NCM_Lead_Entry__c, NCM_Lead_Entry__r.OwnerId, AccountId, Campaign.Name, Contract_Signed__c, RecordType.Name 
                                   from Opportunity 
                                   where id = :oppId];
                Contact con = [select id, Name from Contact where id = :conId];
                
                if(opp.Contract_Signed__c == 'Yes'){
                    opp.DocuSign_Sent__c = date.today();
                    opp.DocuSign_Signed__c = date.today();
                    if(opp.RecordType.Name == 'NCM Institute'){
                        opp.StageName = 'Validating Dates';
                    } else if (opp.RecordType.Name == '20 Groups' || opp.RecordType.Name == 'Proprietary'){
                        opp.StageName = 'Application Sent';
                    } else if (opp.RecordType.Name == 'axcessa' || opp.RecordType.Name == 'Healthcheck' || opp.RecordType.Name == 'LiveAudit'){
                        opp.StageName = 'Contract Received';
                    }
                } else if (opp.RecordType.Name == 'NCM Institute'){
                    opp.StageName = 'Validating Benefits';
                }
                
                opps.add(opp);
            }
        }
        
        if (!opps.isEmpty()) {
            update opps;
        }
    }
}