unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture - defines classes</description>
    <label>Course</label>
    <nameField>
        <label>Course</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Composite_PTA__c.field-meta.xml
<CustomField>
    <fullName>Composite_PTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Composite &amp; PTA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>Course ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Educational_Program__c.field-meta.xml
<CustomField>
    <fullName>Educational_Program__c</fullName>
    <label>Educational Program</label>
    <referenceTo>Educational_Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course__c/recordTypes/OnSite.recordType-meta.xml
<RecordType>
    <fullName>OnSite</fullName>
    <active>true</active>
    <label>OnSite</label>
</RecordType>

unpackaged/main/default/objects/Educational_Program__c/Educational_Program__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture</description>
    <label>Educational Program</label>
    <nameField>
        <label>Educational Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educational Program</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Educational_Program__c/fields/Area_of_Focus__c.field-meta.xml
<CustomField>
    <fullName>Area_of_Focus__c</fullName>
    <label>Area of Focus</label>
    <referenceTo>Area_of_Focus__c</referenceTo>
    <relationshipLabel>Educational Program</relationshipLabel>
    <relationshipName>Educational_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Campus_Room__c.field-meta.xml
<CustomField>
    <fullName>Campus_Room__c</fullName>
    <label>Campus Room</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Campus_Room</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Country_pl__c.field-meta.xml
<CustomField>
    <fullName>Country_pl__c</fullName>
    <defaultValue>&#39;United States&#39;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <formula>Course__r.Course_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State_pl__c.field-meta.xml
<CustomField>
    <fullName>State_pl__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_pl__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_End__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/EngagementWelcomeEmailsBatchTest.cls
@isTest
private class EngagementWelcomeEmailsBatchTest {

    @testSetup
    static void testSetup() {
 
        Account financialAccount = new Account(
            Name = 'Test Financial Account', 
            ShippingPostalCode = '12345'
        );
        insert(financialAccount);
        
        Contact contact = new Contact(
            FirstName = 'Firstname', 
            LastName = 'Lastname', 
            Email = 'test@example.com'
        );
        insert(contact);

        Area_of_Focus__c focus = new Area_of_Focus__c(
            Name = 'Test Focus Area'
        );
        insert(focus);

        Educational_Program__c program = new Educational_Program__c(
            Name = 'Test Program', 
            Area_of_Focus__c = focus.Id
        );
        insert(program);

        Course__c course = new Course__c(
            Name = 'Test Course',
            Course_ID__c = '123456789',
            Educational_Program__c = program.Id,
            Composite_PTA__c = true
        );
        insert(course);
        
        String offsiteRecordTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('NCM Institute Class - Offsite').getRecordTypeId();
        String onsiteRecordTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('NCM Institute Class - Onsite').getRecordTypeId();
        List<Engagement__c> newEngagements = new List<Engagement__c>();
                
        Engagement__c engagement = new Engagement__c(
            Name = 'Test Engagement',
            Account__c = financialAccount.Id,
            Country_pl__c = 'United States',
            State_pl__c = 'TX',
            RecordTypeId = offsiteRecordTypeId,
            Engagement_Start_Date__c = System.today().addDays(5),
            Engagement_Start__c = System.today().addDays(5),
            Engagement_End_Date__c = System.today().addDays(15),
            Engagement_End__c = System.today().addDays(15),
            Course__c  = course.Id, 
            Status__c = 'Firm',
            Campus_Room__c = 'Offsite',
            Location_Times__c = 'Location_Times__c',
            Class_Requirements__c = 'Class_Requirements__c',
            Travel_Lodging_Instructions__c = 'Travel_Lodging_Instructions__c'
        );
        newEngagements.add(engagement);
                       
        Engagement__c engagement1 = new Engagement__c(
            Name = 'Test Engagement1',
            Account__c = financialAccount.Id,
            Country_pl__c = 'United States',
            State_pl__c = 'TX',
            RecordTypeId = onsiteRecordTypeId,
            Engagement_Start_Date__c = System.today().addDays(5),
            Engagement_Start__c = System.today().addDays(5),
            Engagement_End_Date__c = System.today().addDays(15),
            Engagement_End__c = System.today().addDays(15),
            Course__c  = course.Id,
            Status__c = 'Firm',
            Campus_Room__c = '4th Floor - Central A',
            Location_Times__c = 'Location_Times__c',
            Class_Requirements__c = 'Class_Requirements__c',
            Travel_Lodging_Instructions__c = 'Travel_Lodging_Instructions__c',
            Homework__c = 'Homework__c'
        );
        newEngagements.add(engagement1);
        insert(newEngagements);
        
        // Need this RecordType to get access to the 'Registration Confirmed' Attendance Status value.
        String engAttendeeRecordTypeId = Schema.SObjectType.Engagement_Attendee__c.getRecordTypeInfosByName().get('Institute - Paid Seat').getRecordTypeId();
        List<Engagement_Attendee__c> newAttendees = new List<Engagement_Attendee__c>();
        
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(
            Name = 'Test Attendee',
            Account__c = financialAccount.Id,
            Attendance_Status__c = 'Registration Confirmed',
            Engagement__c = engagement.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__r = contact,
            Contact_Email__c = contact.Email,
            Financial_Data_Account__c = financialAccount.Id,
            Financial_Data_Number__c = 'FD123',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        newAttendees.add(attendee);
        
        Engagement_Attendee__c attendee1 = new Engagement_Attendee__c(
            Name = 'Test Attendee',
            Account__c = financialAccount.Id,
            Attendance_Status__c = 'Registration Confirmed',
            Engagement__c = engagement1.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__r = contact,
            Contact_Email__c = contact.Email,
            Financial_Data_Account__c = financialAccount.Id,
            Financial_Data_Number__c = 'FD123',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        newAttendees.add(attendee1);
        insert(newAttendees);
        
        // Files needed for the Send Welcome Emails test. 
        List<ContentVersion> contentVersionList = new List<ContentVersion>();
        ContentVersion welcomeLetter = new ContentVersion(
            Title = 'NCM Welcome Letter 3 7 23',
            VersionData = Blob.valueOf('Sample PDF Data'),
            PathOnClient = 'NCM Welcome Letter 3 7 23.pdf',
            IsMajorVersion = true
        );
        contentVersionList.add(welcomeLetter);
        
        ContentVersion emailLogo = new ContentVersion(
            Title = 'NCM_Email_Logo',
            VersionData = Blob.valueOf('Sample Logo Data'),
            PathOnClient = 'NCM_Email_Logo.pdf',
            IsMajorVersion = true
        );
        contentVersionList.add(emailLogo);
        insert(contentVersionList);
        
        ContentVersion contentVersionWelcomeLetter = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Title = 'NCM Welcome Letter 3 7 23' LIMIT 1];       
        ContentVersion contentVersionEmailLogo = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Title = 'NCM_Email_Logo' LIMIT 1];
       
        List<ContentDocumentLink> contentDocumentList = new List<ContentDocumentLink>();                                                                     
        ContentDocumentLink welcomeLink = new ContentDocumentLink(
        	ContentDocumentId = contentVersionWelcomeLetter.ContentDocumentId,
            LinkedEntityId = engagement.Id,  
            ShareType = 'V', 
            Visibility = 'AllUsers'
        );
        contentDocumentList.add(welcomeLink);
        
        ContentDocumentLink logoLink = new ContentDocumentLink(
        	ContentDocumentId = contentVersionEmailLogo.ContentDocumentId,
            LinkedEntityId = engagement.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        contentDocumentList.add(logoLink); 
        insert(contentDocumentList);                                          
    }
    
    @isTest
    static void testWelcomeEmails() {   
                
        List<Engagement__c> engagements = [SELECT Id, Status__c, RecordType.DeveloperName, Engagement_Start__c, Engagement_End__c, Course__r.Name, Name, Welcome_Email_Sent__c, Homework__c,
                                                  Engagement_Start_Date__c, Engagement_End_Date__c,Location_Times__c, Campus_Room__c, Class_Requirements__c, Travel_Lodging_Instructions__c
                                           FROM Engagement__c];
        
        Test.startTest();
        	EngagementInstituteWelcomeEmailsBatch batchJob = new EngagementInstituteWelcomeEmailsBatch();
        	batchJob.execute(null, engagements);
        Test.stopTest();
        
        Assert.isTrue(!engagements.isEmpty(), 'Execute method complete');
        Engagement__c engagement = [select Id, Name, Welcome_Email_Sent__c From Engagement__c Where Id IN :engagements LIMIT 1 ];        
        System.debug('EngagementWelcomeEmailsBatchTest.testWelcomeEmails:: Welcome_Email_Sent__c: ' + engagement.Welcome_Email_Sent__c);
        // Assert the Welcome Email Sent field is NOT null. 
        System.Assert(engagement.Welcome_Email_Sent__c != null, 'Welcome Email Sent should be populated after batch is processed.');
    }
    
    @isTest
    static void testScheduledExecution() {        
        Test.startTest();        
            EngagementInstituteWelcomeEmailsBatch batchJob = new EngagementInstituteWelcomeEmailsBatch();
            String jobId = System.schedule('Test Job', '0 0 12 * * ?', batchJob);        
        Test.stopTest();     
        
        Assert.isNotNull(jobId, 'Scheduled job should be created successfully.');
    }
    
}