unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture - defines classes</description>
    <label>Course</label>
    <nameField>
        <label>Course</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Available_Seats__c.field-meta.xml
<CustomField>
    <fullName>Available_Seats__c</fullName>
    <formula>Capacity__c - Current_Registrations__c - On_Hold_Seats__c - Attendees_Participated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Overbook_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Overbook_Remaining__c</fullName>
    <label>Overbook Remaining</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Waitlist__c.field-meta.xml
<CustomField>
    <fullName>Waitlist__c</fullName>
    <label>Waitlist- Deprecated</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/courseController.cls
public with sharing class courseController
{
	@AuraEnabled
	public static List<Engagement__c> getSessions(id crseId, boolean includeNotAvailable)
	{
		List<Engagement__c> engs;
		string whereStatement = ' WHERE Course__c = \'' + crseId + '\'';
		whereStatement = whereStatement + ' AND Engagement_End__c >= TODAY';
		if ( !includeNotAvailable )
		{
			whereStatement = whereStatement + ' AND (Available_Seats__c > 0 OR Overbook_Remaining__c > 0) ';
		}
		DescribeSObjectResult describeResult = Engagement__c.getSObjectType(  ).getDescribe();
		List<String> fieldNames = new List<String>(describeResult.fields.getMap().keySet());
		String query = ' SELECT ' + String.join( fieldNames, ', ' ) + ' FROM ' + describeResult.getName() + whereStatement + ' ORDER BY Engagement_Start__c ASC, Available_Seats__c DESC, Waitlist__c ASC';
		engs = Database.query(query);
		return engs;
	}
}