unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture - defines classes</description>
    <label>Course</label>
    <nameField>
        <label>Course</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Composite_PTA__c.field-meta.xml
<CustomField>
    <fullName>Composite_PTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Composite &amp; PTA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Country_pl__c.field-meta.xml
<CustomField>
    <fullName>Country_pl__c</fullName>
    <defaultValue>&#39;United States&#39;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>This is the specific email the contact wants to have all correspondence regarding this engagement sent to</inlineHelpText>
    <label>Attendee Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account for which the attendee will use financial data from</inlineHelpText>
    <label>Financial Data Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees (Financial Data Account)</relationshipLabel>
    <relationshipName>Engagement_Attendees2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Notes__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Notes__c</fullName>
    <label>Financial Data Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Number__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Number__c</fullName>
    <inlineHelpText>Group-Member #</inlineHelpText>
    <label>Financial Data Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Last_Time_Rescheduled__c.field-meta.xml
<CustomField>
    <fullName>Last_Time_Rescheduled__c</fullName>
    <label>Last Time Rescheduled</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Registration_Received__c.field-meta.xml
<CustomField>
    <fullName>Registration_Received__c</fullName>
    <label>Registration Received</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/EngagementAttendeeUtilityReportBatch.cls
global class EngagementAttendeeUtilityReportBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    
    global Integer attendeeSize = 0; // variable to determine if no records need to be processed. 
    // Key: Engagement Name, Value: CSV content (header + data rows)
    global Map<String, String> usEngagementMap = new Map<String, String>();
    global Map<String, String> caEngagementMap = new Map<String, String>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('EngagementAttendeeUtilityReportBatch Start is Running!');

        return Database.getQueryLocator(
            [SELECT Id, 
                    Name,
                    Attendance_Status__c,  
                    Engagement__r.Name,  
                    Engagement__r.RecordType.Name, 
                    Engagement__r.Country_pl__c,
                    Contact__r.Name,  
                    Contact_Email__c, // Contact Email / Attendee Email
                    Financial_Data_Account__r.Name, // Account: Account Name / Financial Data Account
                    Financial_Data_Account__r.ShippingPostalCode, // Account: Shipping Zip/Postal Code / Financial Data Account Zip 
                    Financial_Data_Number__c,  
                    Financial_Data_Notes__c,
                    Last_Time_Rescheduled__c,  
                    Registration_Received__c                             
            FROM    Engagement_Attendee__c
            WHERE   Attendance_Status__c = 'Registration Confirmed'
            AND     Engagement__r.RecordType.Name LIKE 'NCM Institute Class%' 
            AND     Engagement__r.Course__r.Composite_PTA__c = true
            AND (
                (
            		(Engagement__r.Country_pl__c = 'United States' OR Engagement__r.Country_pl__c = '')                        
                	AND Engagement__r.Engagement_Start_Date__c > NEXT_N_DAYS:7 
                	AND Engagement__r.Engagement_Start_Date__c <= NEXT_N_DAYS:35  
			    	)
                OR 
                	(
                    Engagement__r.Country_pl__c = 'Canada'
                    AND     Engagement__r.Engagement_Start_Date__c > NEXT_N_DAYS:7 
                    AND     Engagement__r.Engagement_Start_Date__c <= NEXT_N_DAYS:42
                    )
                )                 
            ]);        
    } 

    global void execute(Database.BatchableContext BC, List<Engagement_Attendee__c> attendees) {
        System.debug('EngagementAttendeeUtilityReportBatch Execute is Running!');
        attendeeSize = 1;
        
        // Generate CSV content
        for(Engagement_Attendee__c attendee : attendees) {
            String csvHeader;
            String engagementName = attendee.Engagement__r.Name;
            Boolean isVirtualTraining = attendee.Engagement__r.RecordType.Name.contains('Virtual Training');
           
            if(isVirtualTraining) {
                csvHeader = 'Account: Account Name,Account: Shipping Zip/Postal Code,Contact,Contact Email,Financial Data Number,Financial Data Notes,Registration Received,Engagement: Engagement Name,Last Time Rescheduled\n';         
            } else {
                csvHeader = 'Financial Data Account,Financial Data Account Zip,Contact,Attendee Email,Financial Data Number,Financial Data Notes,Registration Received,Engagement: Engagement Name,Last Time Rescheduled\n';
            }   
        
            String csvRow = '"' + attendee.Financial_Data_Account__r.Name + '","' + attendee.Financial_Data_Account__r.ShippingPostalCode + '","' + attendee.Contact__r.Name + '","' + attendee.Contact_Email__c + '","' +
                                + attendee.Financial_Data_Number__c  + '","' + attendee.Financial_Data_Notes__c + '","' + attendee.Registration_Received__c + '","' + attendee.Engagement__r.Name + '","' + attendee.Last_Time_Rescheduled__c + '"' + '\n';
			
            // Append to the engagement-specific CSV
            // If the Engagement is new, then add the header + row to usEngagementMap.
            // If the Engagement already exists, then append only the row to the existing CSV data.            
            if(attendee.Engagement__r.Country_pl__c == 'Canada') {
            	if(!caEngagementMap.containsKey(engagementName)) {
                	caEngagementMap.put(engagementName, csvHeader + csvRow);
                } else {
                	caEngagementMap.put(engagementName, caEngagementMap.get(engagementName) + csvRow);
                }
            } else {
				if(!usEngagementMap.containsKey(engagementName)) {
                	usEngagementMap.put(engagementName, csvHeader + csvRow);
                } else {
                usEngagementMap.put(engagementName, usEngagementMap.get(engagementName) + csvRow);
                }            
            }
        }        
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('EngagementAttendeeUtilityReportBatch has Finished!');  
        System.debug('EngagementAttendeeUtilityReportBatch usEngagementMap: ' + usEngagementMap);
        System.debug('EngagementAttendeeUtilityReportBatch caEngagementMap: ' + caEngagementMap);
        
        if(!usEngagementMap.isEmpty()) {
        	sendEmail(usEngagementMap, 'US', 'notEmpty'); 
        } else {
            sendEmail(usEngagementMap, 'US', 'Empty');
        }
        if(!caEngagementMap.isEmpty()) {
        	sendEmail(caEngagementMap, 'CA', 'notEmpty');     
        } else {
            sendEmail(caEngagementMap, 'CA', 'Empty');
        }   
        String myLabelValue = System.Label.Master_Data_Service_NCMi_Email;
        List<String> toAddresses = new List<String>();  
        
        for(String email :myLabelValue.split(',')) {
        	toAddresses.add(email.trim());
        }        
        if(attendeeSize == 0) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            	email.setSubject('NCMi Utility CSV Report');
             	email.setPlainTextBody('No Engagements meet the criteria for this week.');
                email.setToAddresses(toAddresses); 
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});            
        }
    }
	
    // Create private variable to use for test coverage
    @TestVisible()
    private static Messaging.SingleEmailMessage testEmail; 
    
    // Send email with multiple attachments
    @TestVisible()
    private void sendEmail(Map<String, String> engagementCsvMap, String country, String mapVal) {
        System.debug('EngagementAttendeeUtilityReportBatch sendEmail is Running!');
        System.debug('engagementCsvMap: ' + engagementCsvMap);

        String myLabelValue = System.Label.Master_Data_Service_NCMi_Email;
        List<String> toAddresses = new List<String>();        
        for(String email :myLabelValue.split(',')) {
        	toAddresses.add(email.trim());
        }
        
        // Create a CSV attachment for each engagement
        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
        for (String engagementName : engagementCsvMap.keySet()) {
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFilename(engagementName.replaceAll('[^a-zA-Z0-9_-]', '_') + '.csv'); // replace special chars with '_'
            attachment.setBody(Blob.valueOf(engagementCsvMap.get(engagementName)));
            attachment.setContentType('text/csv');
            attachments.add(attachment);
        }         
        System.debug('Attachments.size: ' + attachments.size());
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        if(country == 'US' || String.isBlank(country)) {
            email.setSubject('NCMi Utility CSV - US');
            if(mapVal == 'Empty') {  
                email.setPlainTextBody('No Engagements meet the criteria for this week.');
                email.setToAddresses(toAddresses); 
            } else {
            	email.setPlainTextBody('Attached are the scheduled NCMi Utility CSV - US reports, one per Engagement.');
                email.setToAddresses(toAddresses);  
                email.setFileAttachments(attachments);
            }            
            testEmail = email;          
        } else if(country == 'CA') {
            email.setSubject('NCMi Utility CSV - CA');
            if(mapVal == 'Empty') {  
                email.setPlainTextBody('No Engagements meet the criteria for this week.');
                email.setToAddresses(toAddresses);  
            } else {
            	email.setPlainTextBody('Attached are the scheduled NCMi Utility CSV - CA reports, one per Engagement.');
                email.setToAddresses(toAddresses);  
                email.setFileAttachments(attachments);
            }
            testEmail = email;
        }     
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
    }

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new EngagementAttendeeUtilityReportBatch(), 200);
    }

}