unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture - defines classes</description>
    <label>Course</label>
    <nameField>
        <label>Course</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Composite_PTA__c.field-meta.xml
<CustomField>
    <fullName>Composite_PTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Composite &amp; PTA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Country_pl__c.field-meta.xml
<CustomField>
    <fullName>Country_pl__c</fullName>
    <defaultValue>&#39;United States&#39;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>This is the specific email the contact wants to have all correspondence regarding this engagement sent to</inlineHelpText>
    <label>Attendee Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account for which the attendee will use financial data from</inlineHelpText>
    <label>Financial Data Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees (Financial Data Account)</relationshipLabel>
    <relationshipName>Engagement_Attendees2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Notes__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Notes__c</fullName>
    <label>Financial Data Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Number__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Number__c</fullName>
    <inlineHelpText>Group-Member #</inlineHelpText>
    <label>Financial Data Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Last_Time_Rescheduled__c.field-meta.xml
<CustomField>
    <fullName>Last_Time_Rescheduled__c</fullName>
    <label>Last Time Rescheduled</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Registration_Received__c.field-meta.xml
<CustomField>
    <fullName>Registration_Received__c</fullName>
    <label>Registration Received</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/EngagementAttendeeUtilityReportQueueable.cls
// Derrick: SALES-1677/1843, 2/26/2025. Send CSV Email with attachement when Attendance Status criteria are met on Engagement_Attendee__c and Engagement__c.
public class EngagementAttendeeUtilityReportQueueable implements Queueable {

    private String newId;
    private String status;
    private String oldEngId;
    
    public EngagementAttendeeUtilityReportQueueable(String newId, String oldEngId, String status) {
        this.newId = newId;
        this.status = status;
        this.oldEngId = oldEngId;
    }

    public void execute(QueueableContext context) {
        System.debug('EngagementAttendeeUtilityReportQueueable.execute newID is: ' + newId);
        System.debug('EngagementAttendeeUtilityReportQueueable.execute oldEngId is: ' + oldEngId);
		
        if(status != 'Rebooking') {
        	sendUtilityReport(newId, status);    
        } else if(status == 'Rebooking' && oldEngId != null) {
            sendUtilityReportRebooking(oldEngId, status);
        } 
    }
       
    private static void sendUtilityReport(String attendeeId, String status) {
        System.debug('EngagementAttendeeUtilityReportQueueable.sendUtilityReport is running.');
        
        Engagement_Attendee__c attendee = getEngagementAttendee(attendeeId);        
        if(attendee == null) {
        	System.debug('EngagementAttendeeUtilityReportQueueable.sendUtilityReport:: No Matching engagement attendee found for ID: ' + attendeeId);
            return;
        }       
        List<Engagement_Attendee__c> attendees = getAttendeesForEngagement(attendee.Engagement__c);
        if(attendees.isEmpty()) {
            System.debug('EngagementAttendeeUtilityReportQueueable.sendUtilityReport:: No Matching attendees with engagements found.');
            return;
        }
        Boolean isVirtualTraining = attendee.Engagement__r.RecordType.Name.contains('Virtual Training'); 
        String csvContent = generateCsvContent(attendees, isVirtualTraining);
        sendEmail(attendee, csvContent, attendee.Engagement__r.Name, attendee.Engagement__r.Country_pl__c, status);  
    }
    
    private static void sendUtilityReportRebooking(String oldEngId, String status) {
        System.debug('EngagementAttendeeUtilityReportQueueable.sendUtilityReportRebooking is running.');
        
        Engagement_Attendee__c attendee = getAttendeeByEngagement(oldEngId);        
        if(attendee == null) {
            System.debug('EngagementAttendeeUtilityReportQueueable.sendUtilityReportRebooking:: No Matching engagement attendee found for ID: ' + oldEngId);
            return;
        }        
        List<Engagement_Attendee__c> attendees = getAttendeesForEngagement(attendee.Engagement__c);
        if(attendees.isEmpty()) {
            System.debug('EngagementAttendeeUtilityReportQueueable.sendUtilityReportRebooking:: No Matching attendees with engagements found.');
            return;
        }
        Boolean isVirtualTraining = attendee.Engagement__r.RecordType.Name.contains('Virtual Training'); 
        String csvContent = generateCsvContent(attendees, isVirtualTraining);
        sendEmail(attendee, csvContent, attendee.Engagement__r.Name, attendee.Engagement__r.Country_pl__c, status); 
    }
    
    private static Engagement_Attendee__c getEngagementAttendee(String attendeeId) {
        Engagement_Attendee__c attendee = [SELECT Id, Engagement__r.Name, Engagement__r.RecordType.Name, Engagement__r.Country_pl__c, Contact__r.Name, Contact_Email__c
                                           FROM Engagement_Attendee__c WHERE Id =:attendeeId LIMIT 1];
        return attendee;
    }
    
    // for 'Rebooking' you need the oldEngId to get the correct Engagement_Attendees. Query using the oldEngId, instead of newId.
    // reason being is when an attendee status gets updated to 'Rebooking', the engagement gets changed to a 'NCMi Rebooking' engagement. 
    // 'NCMi Rebooking' is not a real engagement, but more of a holding record, so you need to capture the engagement record before it gets changed to get the attendees. 
    private static Engagement_Attendee__c getAttendeeByEngagement(String oldEngagementId) {
        Engagement_Attendee__c attendee = [SELECT Id, Engagement__r.Name, Engagement__r.RecordType.Name, Engagement__r.Country_pl__c, Contact__r.Name, Contact_Email__c
                                           FROM Engagement_Attendee__c WHERE Engagement__c =:oldEngagementId LIMIT 1];
        return attendee;
    }
    
    // get all the Attendees that are 'Registration Confirmed' and the related Engagement. 
    private static List<Engagement_Attendee__c> getAttendeesForEngagement(String engagementId) {
        List<Engagement_Attendee__c> attendees = 
                        [SELECT Id, Name, Attendance_Status__c, Engagement__r.Name, Engagement__r.RecordType.Name,
                                Engagement__r.Country_pl__c, Contact__r.Name, Contact_Email__c,
                                Financial_Data_Account__r.Name, Financial_Data_Account__r.ShippingPostalCode,
                                Financial_Data_Number__c, Financial_Data_Notes__c, Last_Time_Rescheduled__c,                                                                                         
                                Registration_Received__c, Engagement__r.Engagement_Start_Date__c, Engagement__r.Engagement_Start__c                                                                                       
                        FROM    Engagement_Attendee__c
                        WHERE   Engagement__c = :engagementId
                        AND     Attendance_Status__c = 'Registration Confirmed' // only want to send attendees in this status. 
                        AND     Engagement__r.RecordType.Name LIKE 'NCM Institute Class%' 
                        AND     Engagement__r.Course__r.Composite_PTA__c = true
                        AND (
                                (
                                (Engagement__r.Country_pl__c = 'United States' OR Engagement__r.Country_pl__c = '')                        
                                AND Engagement__r.Engagement_Start_Date__c > NEXT_N_DAYS:7 
                                AND Engagement__r.Engagement_Start_Date__c <= NEXT_N_DAYS:35  
                                )
                            OR 
                                (
                                (Engagement__r.Country_pl__c = 'Canada')
                                AND Engagement__r.Engagement_Start_Date__c > NEXT_N_DAYS:7 
                                AND Engagement__r.Engagement_Start_Date__c <= NEXT_N_DAYS:42
                                )
                           ) ];                 
        return attendees;
    }
    
    private static String generateCsvContent(List<Engagement_Attendee__c> attendees, Boolean isVirtualTraining) {
		String csvHeader;                
        if(isVirtualTraining) {
            csvHeader = 'Account: Account Name,Account: Shipping Zip/Postal Code,Contact,Contact Email,Financial Data Number,Financial Data Notes,Registration Received,Engagement: Engagement Name,Last Time Rescheduled\n';         
        } else {
            csvHeader = 'Financial Data Account,Financial Data Account Zip,Contact,Attendee Email,Financial Data Number,Financial Data Notes,Registration Received,Engagement: Engagement Name,Last Time Rescheduled\n';
        }           
        String csvContent = csvHeader;

        // Generate CSV content
        for(Engagement_Attendee__c ea : attendees) {
            String csvRow = '"' + ea.Financial_Data_Account__r.Name + '","' + ea.Financial_Data_Account__r.ShippingPostalCode + '","' + ea.Contact__r.Name + '","' + ea.Contact_Email__c + '","' +
                            + ea.Financial_Data_Number__c  + '","' + ea.Financial_Data_Notes__c + '","' + ea.Registration_Received__c + '","' + ea.Engagement__r.Name + '","' + ea.Last_Time_Rescheduled__c + '"' + '\n';
            
            csvContent += csvRow;            
        }      
        return csvContent;        
    }
   
    @TestVisible()
    private static void sendEmail(Engagement_Attendee__c attendee, String csvContent, String engagementName, String country, String status) {
        System.debug('EngagementAttendeeUtilityReportQueueable.sendEmail is running!');
        
        String myLabelValue = System.Label.Master_Data_Service_NCMi_Email;
        List<String> toAddresses = new List<String>();          
        for(String email :myLabelValue.split(',')) {
        	toAddresses.add(email.trim());
        }
        
        String displayContact = 'Contact Name: ' + attendee.Contact__r.Name + ',' + ' Contact Email: ' + attendee.Contact_Email__c + ' has been updated.';
        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();  
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFilename(engagementName.replaceAll('[^a-zA-Z0-9_-]', '_') + '.csv'); // replace special chars with '_'
            attachment.setBody(Blob.valueOf(csvContent));
            attachment.setContentType('text/csv');
            attachments.add(attachment);
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        if(country == 'United States' || String.isBlank(country)) {
            if(status == 'Registration Confirmed') {
            	email.setSubject('Registration Update - NCMi Utility CSV - US');
            	email.setPlainTextBody('Attached are the scheduled NCMi Utility CSV - US Engagements.' + '\n' + displayContact);                
            } else if(status != 'Registration Confirmed') {
                email.setSubject('Cancellation Update - NCMi Utility CSV - US');
                email.setPlainTextBody('Attached are the scheduled NCMi Utility CSV - US Engagements.');               
            }
        } else if(country == 'Canada') {
            if(status == 'Registration Confirmed') {
                email.setSubject('Registration Update - NCMi Utility CSV - CA');
            	email.setPlainTextBody('Attached are the scheduled NCMi Utility CSV - Canada Engagements.'+ '\n' + displayContact);       
            } else if(status != 'Registration Confirmed') {
                email.setSubject('Cancellation Update - NCMi Utility CSV - CA');
            	email.setPlainTextBody('Attached are the scheduled NCMi Utility CSV - Canada Engagements.');       
            } 
        }         
        email.setToAddresses(toAddresses);  
        email.setFileAttachments(attachments);
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
    }
    
}