unpackaged/main/default/objects/Area_of_Focus__c/Area_of_Focus__c.object-meta.xml
<CustomObject>
    <label>Area of Focus</label>
    <nameField>
        <label>Area of Focus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Area of Focus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture - defines classes</description>
    <label>Course</label>
    <nameField>
        <label>Course</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Composite_PTA__c.field-meta.xml
<CustomField>
    <fullName>Composite_PTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Composite &amp; PTA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>Course ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Educational_Program__c.field-meta.xml
<CustomField>
    <fullName>Educational_Program__c</fullName>
    <label>Educational Program</label>
    <referenceTo>Educational_Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Course__c/recordTypes/OnSite.recordType-meta.xml
<RecordType>
    <fullName>OnSite</fullName>
    <active>true</active>
    <label>OnSite</label>
</RecordType>

unpackaged/main/default/objects/Educational_Program__c/Educational_Program__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture</description>
    <label>Educational Program</label>
    <nameField>
        <label>Educational Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educational Program</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Educational_Program__c/fields/Area_of_Focus__c.field-meta.xml
<CustomField>
    <fullName>Area_of_Focus__c</fullName>
    <label>Area of Focus</label>
    <referenceTo>Area_of_Focus__c</referenceTo>
    <relationshipLabel>Educational Program</relationshipLabel>
    <relationshipName>Educational_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Country_pl__c.field-meta.xml
<CustomField>
    <fullName>Country_pl__c</fullName>
    <defaultValue>&#39;United States&#39;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <formula>Course__r.Course_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>This is the specific email the contact wants to have all correspondence regarding this engagement sent to</inlineHelpText>
    <label>Attendee Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account for which the attendee will use financial data from</inlineHelpText>
    <label>Financial Data Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees (Financial Data Account)</relationshipLabel>
    <relationshipName>Engagement_Attendees2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Notes__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Notes__c</fullName>
    <label>Financial Data Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Financial_Data_Number__c.field-meta.xml
<CustomField>
    <fullName>Financial_Data_Number__c</fullName>
    <inlineHelpText>Group-Member #</inlineHelpText>
    <label>Financial Data Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Last_Time_Rescheduled__c.field-meta.xml
<CustomField>
    <fullName>Last_Time_Rescheduled__c</fullName>
    <label>Last Time Rescheduled</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Registration_Received__c.field-meta.xml
<CustomField>
    <fullName>Registration_Received__c</fullName>
    <label>Registration Received</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/EngagementAttendeeUtilityReportBatchTest.cls
@isTest
private class EngagementAttendeeUtilityReportBatchTest {

    @testSetup
    static void testSetup() {
 
        Account financialAccount = new Account(
            Name = 'Test Financial Account', 
            ShippingPostalCode = '12345'
        );
        insert(financialAccount);
        
        Contact contact = new Contact(
            FirstName = 'Firstname', 
            LastName = 'Lastname', 
            Email = 'test@example.com'
        );
        insert(contact);

        Area_of_Focus__c focus = new Area_of_Focus__c(
            Name = 'Test Focus Area'
        );
        insert(focus);

        Educational_Program__c program = new Educational_Program__c(
            Name = 'Test Program', 
            Area_of_Focus__c = focus.Id
        );
        insert(program);

        Course__c course = new Course__c(
            Name = 'Test Course',
            Course_ID__c = '123456789',
            Educational_Program__c = program.Id,
            Composite_PTA__c = true
        );
        insert(course);
        
        String engRecordTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('NCM Institute Class - Onsite').getRecordTypeId();
        System.debug('Engagement Record Type Id: ' + engRecordTypeId );
        List<Engagement__c> newEngagements = new List<Engagement__c>();
        
        Engagement__c engagement = new Engagement__c(
            Name = 'Test Engagement',
            Account__c = financialAccount.Id,
            Country_pl__c = 'United States',
            RecordTypeId = engRecordTypeId,
            Engagement_Start_Date__c = System.today().addDays(10),
            Course__c  = course.Id
        );
        newEngagements.add(engagement);
        
        String engRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('NCM Institute Class - Live Session Virtual Training').getRecordTypeId();
        System.debug('Engagement Record Type Id: ' + engRecTypeId);
               
        Engagement__c engagement1 = new Engagement__c(
            Name = 'Test Engagement1',
            Account__c = financialAccount.Id,
            Country_pl__c = '',
            RecordTypeId = engRecTypeId,
            Engagement_Start_Date__c = System.today().addDays(10),
            Course__c  = course.Id
        );
        newEngagements.add(engagement1);
        
        Engagement__c engagement2 = new Engagement__c(
            Name = 'Test Engagement2',
            Account__c = financialAccount.Id,
            Country_pl__c = 'Canada',
            RecordTypeId = engRecordTypeId,
            Engagement_Start_Date__c = System.today().addDays(20),
            Course__c  = course.Id
        );
        newEngagements.add(engagement2);
		
		Engagement__c engagement3 = new Engagement__c(
            Name = 'Test Engagement3',
            Account__c = financialAccount.Id,
            Country_pl__c = 'Canada',
            RecordTypeId = engRecTypeId,
            Engagement_Start_Date__c = System.today().addDays(20),
            Course__c  = course.Id
        );
        newEngagements.add(engagement3);
        insert(newEngagements);
        
        // Need this RecordType to get access to the 'Registration Confirmed' Attendance Status value.
        String engAttendeeRecordTypeId = Schema.SObjectType.Engagement_Attendee__c.getRecordTypeInfosByName().get('Institute - Training Subscription Seats').getRecordTypeId();
        List<Engagement_Attendee__c> newAttendees = new List<Engagement_Attendee__c>();
        
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(
            Name = 'Test Attendee',
            Account__c = financialAccount.Id,
            Attendance_Status__c = 'Registration Confirmed',
            Engagement__c = engagement.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__r = contact,
            Contact_Email__c = contact.Email,
            Financial_Data_Account__c = financialAccount.Id,
            Financial_Data_Number__c = 'FD123',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        newAttendees.add(attendee);
        
        Engagement_Attendee__c attendee1 = new Engagement_Attendee__c(
            Name = 'Test Attendee',
            Account__c = financialAccount.Id,
            Attendance_Status__c = 'Registration Confirmed',
            Engagement__c = engagement1.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__r = contact,
            Contact_Email__c = contact.Email,
            Financial_Data_Account__c = financialAccount.Id,
            Financial_Data_Number__c = 'FD123',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        newAttendees.add(attendee1);
        
        Engagement_Attendee__c attendee2 = new Engagement_Attendee__c(
            Name = 'Test Attendee2',
            Account__c = financialAccount.Id,
            Attendance_Status__c = 'Registration Confirmed',
            Engagement__c = engagement2.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__r = contact,
            Contact_Email__c = contact.Email,
            Financial_Data_Account__c = financialAccount.Id,
            Financial_Data_Number__c = 'FD123',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        newAttendees.add(attendee2);
        
        Engagement_Attendee__c attendee3 = new Engagement_Attendee__c(
            Name = 'Test Attendee3',
            Account__c = financialAccount.Id,
            Attendance_Status__c = 'Registration Confirmed',
            Engagement__c = engagement3.Id,
            RecordTypeId = engAttendeeRecordTypeId,
            Contact__r = contact,
            Contact_Email__c = contact.Email,
            Financial_Data_Account__c = financialAccount.Id,
            Financial_Data_Number__c = 'FD123',
            Financial_Data_Notes__c = 'Test Notes',
            Registration_Received__c = System.today()
        );
        newAttendees.add(attendee3);
        insert(newAttendees);
    }
    
    @isTest
    static void testNotVirtualTraining() {

        List<Engagement_Attendee__c> attendees = [SELECT Id, 
                                                  		 Name, 
                                                         Contact__r.Name,
                                                         Contact_Email__c,
                                                         Engagement__r.Name, 
                                                         Engagement__r.RecordType.Name,
                                                         Engagement__r.Country_pl__c,
                                                         Financial_Data_Account__r.Name,
                                                         Financial_Data_Account__r.ShippingPostalCode,                                               
                                                         Financial_Data_Number__c,
                                                         Financial_Data_Notes__c,
                                                         Last_Time_Rescheduled__c,
                                                         Registration_Received__c                                                  
                                                  FROM   Engagement_Attendee__c];
        
        Test.startTest();
        	EngagementAttendeeUtilityReportBatch batchJob = new EngagementAttendeeUtilityReportBatch();
        	batchJob.execute(null, attendees);
        Test.stopTest();

        Assert.isTrue(!attendees.isEmpty(), 'Execute method complete');
    }

    @isTest
    static void testVirtualTraining() {

        List<Engagement_Attendee__c> attendees = [SELECT Id, 
                                                  		 Name, 
                                                         Contact__r.Name,
                                                         Contact_Email__c,
                                                         Engagement__r.Name, 
                                                         Engagement__r.RecordType.Name,
                                                         Engagement__r.Country_pl__c,
                                                         Financial_Data_Account__r.Name,
                                                         Financial_Data_Account__r.ShippingPostalCode,                                               
                                                         Financial_Data_Number__c,
                                                         Financial_Data_Notes__c,
                                                         Last_Time_Rescheduled__c,
                                                         Registration_Received__c                                                  
                                                  FROM   Engagement_Attendee__c];
        
        Test.startTest();
        	EngagementAttendeeUtilityReportBatch batchJob = new EngagementAttendeeUtilityReportBatch();
        	batchJob.execute(null, attendees);
        Test.stopTest();
        
        Assert.isTrue(!attendees.isEmpty(), 'Execute method complete');
    }
    
    @isTest
    static void testScheduledExecution() {
        
        Test.startTest();        
            EngagementAttendeeUtilityReportBatch batchJob = new EngagementAttendeeUtilityReportBatch();
            String jobId = System.schedule('Test Job', '0 0 12 * * ?', batchJob);        
        Test.stopTest();
        
        Assert.isNotNull(jobId, 'Scheduled job should be created successfully.');
    }
    
    @isTest
    static void testSendEmailUS() {
        
        Map<String, String> engagementCsvMap = new Map<String, String>();
        engagementCsvMap.put('Test Engagement US', 'Test CSV Content');
        
        Test.startTest();
            EngagementAttendeeUtilityReportBatch testBatch = new EngagementAttendeeUtilityReportBatch();
            testBatch.sendEmail(engagementCsvMap, 'US', 'Empty');
        Test.stopTest();

        Assert.areEqual(EngagementAttendeeUtilityReportBatch.testEmail.getSubject(), 'NCMi Utility CSV - US');     
    }
    
    @isTest
    static void testSendEmailCA() {
        
        Map<String, String> engagementCsvMap = new Map<String, String>();
        engagementCsvMap.put('Test Engagement CA', 'Test CSV Content');
        
        Test.startTest();
            EngagementAttendeeUtilityReportBatch testBatch = new EngagementAttendeeUtilityReportBatch();
            testBatch.sendEmail(engagementCsvMap, 'CA', 'Empty');
        Test.stopTest();

        Assert.areEqual(EngagementAttendeeUtilityReportBatch.testEmail.getSubject(), 'NCMi Utility CSV - CA');     
    }
    
}