unpackaged/main/default/objects/Area_of_Focus__c/Area_of_Focus__c.object-meta.xml
<CustomObject>
    <label>Area of Focus</label>
    <nameField>
        <label>Area of Focus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Area of Focus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture - defines classes</description>
    <label>Course</label>
    <nameField>
        <label>Course</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Course__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>Course ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Course__c/fields/Educational_Program__c.field-meta.xml
<CustomField>
    <fullName>Educational_Program__c</fullName>
    <label>Educational Program</label>
    <referenceTo>Educational_Program__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Educational_Program__c/Educational_Program__c.object-meta.xml
<CustomObject>
    <description>NCMI Architecture</description>
    <label>Educational Program</label>
    <nameField>
        <label>Educational Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educational Program</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Educational_Program__c/fields/Area_of_Focus__c.field-meta.xml
<CustomField>
    <fullName>Area_of_Focus__c</fullName>
    <label>Area of Focus</label>
    <referenceTo>Area_of_Focus__c</referenceTo>
    <relationshipLabel>Educational Program</relationshipLabel>
    <relationshipName>Educational_Program</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Country_pl__c.field-meta.xml
<CustomField>
    <fullName>Country_pl__c</fullName>
    <defaultValue>&#39;United States&#39;</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <formula>Course__r.Course_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/CourseName__c.field-meta.xml
<CustomField>
    <fullName>CourseName__c</fullName>
    <formula>Course__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CourseName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State_pl__c.field-meta.xml
<CustomField>
    <fullName>State_pl__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_pl__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement__c/recordTypes/Institute.recordType-meta.xml
<RecordType>
    <fullName>Institute</fullName>
    <active>true</active>
    <description>NCMi classes performed in Kansas City headquarters location</description>
    <label>NCM Institute Class - Onsite</label>
</RecordType>

unpackaged/main/default/classes/DateTimeFormatterTest.cls
@isTest
public with sharing class DateTimeFormatterTest {
    @TestSetup
    static void makeData(){
        RecordType vt = [SELECT Id 
                        FROM RecordType 
                        WHERE sObjectType='Course__c' 
                        AND Name = 'Virtual Training' 
                        LIMIT 1];

        RecordType lsvt = [SELECT Id 
                        FROM RecordType 
                        WHERE sObjectType='Engagement__c' 
                        AND Name = 'NCM Institute Class - Live Session Virtual Training' 
                        LIMIT 1];                

        Area_of_Focus__c aof = new Area_of_Focus__c(Name = 'Sample Area of Focus');
        insert aof;

        Educational_Program__c  ep = new Educational_Program__c(
            Name = 'Sample Educational Program',
            Area_of_Focus__c = aof.Id);
        insert ep;

        Course__c crs = new Course__c(
            Name = 'Test Course', 
            RecordTypeId = vt.Id,
            Course_Id__c = 'test1',
            Educational_Program__c = ep.Id);
        insert crs;

        Engagement__c eng = new Engagement__c(
            Name = 'Test Engagement',
            RecordTypeId = lsvt.Id,
            Course__c = crs.Id,
            Engagement_Start__c = Datetime.newInstanceGMT(2008, 12, 1, 18, 00, 00),
            Engagement_End__c = Datetime.newInstanceGMT(2008, 12, 1, 19, 15, 00),
            State_pl__c = 'NC',
            Country_pl__c = 'United States'
        );
        insert eng;
    }
    @isTest
    static void DateTimeFormatterTest() {
        List<Engagement__c> eng = [SELECT Id, Engagement_End__c, Engagement_Start__c, CourseName__c
                            FROM Engagement__c];
        List<String> x = DateTimeFormatter.createRow(eng);
        Assert.areEqual('<tr><td style="border: 1px solid black;">Test Course</th><td style="border: 1px solid black;">12/01/2008</th><td style="border: 1px solid black;">12:00 PM CST</th><td style="border: 1px solid black;">1:15 PM CST</th></tr>', x[0]);
    }
    @isTest
    static void DateTimeFormatterDSTTest() {
        List<Engagement__c> eng = [SELECT Id, Engagement_End__c, Engagement_Start__c, CourseName__c
                            FROM Engagement__c];
        eng[0].Engagement_Start__c = eng[0].Engagement_Start__c.addMonths(6);
        eng[0].Engagement_End__c = eng[0].Engagement_End__c.addMonths(6);
        List<String> x = DateTimeFormatter.createRow(eng);
        Assert.areEqual('<tr><td style="border: 1px solid black;">Test Course</th><td style="border: 1px solid black;">06/01/2009</th><td style="border: 1px solid black;">1:00 PM CST</th><td style="border: 1px solid black;">2:15 PM CST</th></tr>', x[0]);
    }
    @isTest
    static void nullTest() {
        List<String> x = DateTimeFormatter.createRow(new List<Engagement__c>());
        Assert.isNull(x);
    }
}