unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <inlineHelpText>Only complete if meeting has a contract</inlineHelpText>
    <label>Hotel Contract Cancelled</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>to update the city go to the hotel that is listed in the hotel/Meeting Location field and update the city on the physical address</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State(old)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account_City_State__c.field-meta.xml
<CustomField>
    <fullName>Account_City_State__c</fullName>
    <formula>Account__r.BillingCity + &quot;, &quot; + TEXT(Account__r.BillingStateCode)</formula>
    <label>Account City/State</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <label>Arrival</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <description>Engagement Attendee Type</description>
    <label>Attendee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Participant</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Co-Member</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Engagement Support</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Guest Presenter</fullName>
            </value>
            <value>
                <fullName>Industry Professional</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Moderator</fullName>
            </value>
            <value>
                <fullName>NCM Guest</fullName>
            </value>
            <value>
                <fullName>NCM Resource</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Associate Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Populated with Account Physical Address.</description>
    <label>City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Collateral_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Collateral_First_Name__c</fullName>
    <formula>LEFT( Collateral_Name__c ,  FIND(&quot; &quot;, Collateral_Name__c) - 1 )</formula>
    <label>Collateral First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Collateral_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Last_Name__c</fullName>
    <formula>MID(Collateral_Name__c, FIND( &quot; &quot;, Collateral_Name__c), LEN(Collateral_Name__c))</formula>
    <label>Collateral Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Collateral_Name__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Name__c</fullName>
    <label>Collateral Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <formula>IF(
    NOT(ISBLANK(X20_Groups_Member__c)),
    X20_Groups_Member__r.Member_Number_Code__c,
    IF(
        NOT(ISBLANK(Proprietary_Account__c)),
        Proprietary_Account__r.Member_Number_Code__c,
        &quot;&quot;
    )
)</formula>
    <label>Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Registration_Received__c.field-meta.xml
<CustomField>
    <fullName>Registration_Received__c</fullName>
    <label>Registration Received</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Populated with Account Physical Address Abbreviation.</description>
    <label>State</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/Proprietary_Account__c.object-meta.xml
<CustomObject>
    <label>Proprietary Account</label>
    <nameField>
        <label>Proprietary Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proprietary Accounts</relationshipLabel>
    <relationshipName>Proprietary_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proprietary Accounts</relationshipLabel>
    <relationshipName>Proprietary_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <label>Member Number</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EngagementManagement.cls
public without sharing class EngagementManagement {

    @AuraEnabled(Cacheable = true)
    public static List<Engagement_Attendee__c> getAttendees(String engagementId){

      System.debug('EngagementManagement.getAttendees:engagementId >> ' + engagementId);

      List<Engagement_Attendee__c> attendees = [
        SELECT
            Id,
            Name,
            Contact__r.Name,
            Contact__r.FirstName,
            Contact__r.LastName,
            RecordType.Name,
            Attendee_Type__c,
            Registration_Received__c, // Date (Hidden Field for all Profiles, default value = TODAY() )
            Cancellation_Date__c,
            Attendance_Status__c, // Added 'Removed' to the Status to soft delete Attendee. 
            Account__r.Name,
            Arrival__c, // Date/Time ( 2023-08-23T15:32:00.000+0000 )
            Departure__c, // Date/Time ( 2023-08-23T15:32:00.000+0000 )
            // Account_City_State__c, // Formula Field
            City__c, 
            State__c,
            Collateral_Name__c,
            Collateral_First_Name__c,
            Collateral_Last_Name__c,
            Member_Number__c,
            In_Meeting_Room__c,
            Title__c,
            Winmaster_Member_Name__c,
            Hotel_Confirmed__c,
            Hotel_Confirmation_Number__c,
            Primary_Attendee_Code__c, 
            X20_Groups_Member__c,
            X20_Groups_Member__r.WinMaster_Member_Name__c,
            Proprietary_Account__c,
            Proprietary_Account__r.Group_Number__c,
            Proprietary_Account__r.WinMaster_Member_Name__c,
            X20_Groups_Member__r.Group_ID__r.Name
        FROM
            Engagement_Attendee__c
        WHERE
            Engagement__c = :engagementId AND Attendance_Status__c != 'Removed'
            Order By Member_Number__c, Primary_Attendee_Code__c
        ]; 
        System.debug('EngagementManagement.getAttendees:count >> ' + attendees.size());
        
        return attendees;
    } 

    @AuraEnabled(Cacheable = true)
    public static List<Engagement_Attendee__c> getActivityAttendence(String activityId) {

      System.debug('EngagementManagement.getActivityAttendence:activityId >> ' + activityId);
      
      List<Engagement_Attendee__c> newAttendees = [
        SELECT
            Id,
            Name,
            Engagement__c
        FROM
            Engagement_Attendee__c
        WHERE
            Attendance_Status__c NOT IN ('Removed', 'Not Attending')
            AND Engagement__c IN 
                (SELECT Engagement__c FROM Engagement_Activity__c WHERE Id = :activityId)
            AND Id NOT IN
                (SELECT Engagement_Attendee__c FROM Activity_Participation__c WHERE Engagement_Activity__c = :activityId)
        ]; 
        
        System.debug('EngagementManagement.getActivityAttendence:count >> ' + newAttendees.size());

        return newAttendees;
    }
}