unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <label>Meeting</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/In_Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting_Room__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Meeting Room</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ActivityParticipationUtility.cls
public with sharing class ActivityParticipationUtility {
    public static void meetingRoom(List<Activity_Participation__c> aPs) {
        //Create a set of the Engagement Attendee Ids for the Activity Participations that were
        //created, edited or deleted. I don't believe Edited will ever happen, but included just 
        //in case something wierd ever happens.
        Set<Id> eaSet = new Set<Id>();
        for(Activity_Participation__c ap : aPs) {
            eaSet.add(ap.Engagement_Attendee__c);
        }

        //Query the Engagement Attendee records and loop through them to see if the In Meeting Room
        //checkbox should be changed.
        List<Engagement_Attendee__c> easToUpdate = new List<Engagement_Attendee__c>();
        if(eaSet.size() > 0) {
            for(Engagement_Attendee__c ea : [SELECT Id, In_Meeting_Room__c,
                                                (SELECT Id FROM Activity_Participation__r WHERE Engagement_Activity__r.RecordType.Name = 'Meeting')
                                            FROM Engagement_Attendee__c
                                            WHERE Id IN :eaSet]) {
                if(ea.Activity_Participation__r.size() > 0 && !ea.In_Meeting_Room__c) {
                    easToUpdate.add(new Engagement_Attendee__c(id = ea.Id, In_Meeting_Room__c = true));
                } else if(ea.Activity_Participation__r.size() == 0 && ea.In_Meeting_Room__c) {
                    easToUpdate.add(new Engagement_Attendee__c(id = ea.Id, In_Meeting_Room__c = false));
                }
            }
        }

        if(easToUpdate.size() > 0) {
            List<Database.SaveResult> dsrList = Database.update(easToUpdate, false);
            Logger.logErrorList('ActivityParticipationUtility::meetingRoom', dsrList, easToUpdate);
        }
    }
}