unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Total_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Participants__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Total Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/NCM_Arrival__c.field-meta.xml
<CustomField>
    <fullName>NCM_Arrival__c</fullName>
    <label>NCM Arrival</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/NCM_Departure__c.field-meta.xml
<CustomField>
    <fullName>NCM_Departure__c</fullName>
    <label>NCM Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Rooms_From__c.field-meta.xml
<CustomField>
    <fullName>Rooms_From__c</fullName>
    <label>Room Nights From</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Rooms_To__c.field-meta.xml
<CustomField>
    <fullName>Rooms_To__c</fullName>
    <label>Room Nights To</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_End__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>RM-{00000000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room__c/fields/ADA_Rooms__c.field-meta.xml
<CustomField>
    <fullName>ADA_Rooms__c</fullName>
    <label>ADA Rooms</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <formula>CASE(
WEEKDAY( Room_Date__c ),
1, &quot;Sunday&quot;,
2, &quot;Monday&quot;,
3, &quot;Tuesday&quot;,
4, &quot;Wednesday&quot;,
5, &quot;Thursday&quot;,
6, &quot;Friday&quot;,
&quot;Saturday&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day of Week</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/Meeting_Day__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meeting Day?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/NCM_On_Site__c.field-meta.xml
<CustomField>
    <fullName>NCM_On_Site__c</fullName>
    <label>NCM On Site</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/Premium_Rooms__c.field-meta.xml
<CustomField>
    <fullName>Premium_Rooms__c</fullName>
    <label>Premium Rooms</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/Room_Date__c.field-meta.xml
<CustomField>
    <fullName>Room_Date__c</fullName>
    <label>Room Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room__c/fields/Run_of_House__c.field-meta.xml
<CustomField>
    <fullName>Run_of_House__c</fullName>
    <label>Run of House</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/engagementControllers.cls
public class engagementControllers {
    
    public class vars {
        @InvocableVariable(label='Engagement' Required=true)
        public Engagement__c eng;
        @InvocableVariable(label='Member Count')
        public Integer memCnt;
    }
    
    @InvocableMethod
    public static list<list<Room__c>> getRooms(List<vars> vars){
        list<list<Room__c>> roomsRet = new list<list<Room__c>>();
        
        for(vars var : vars){
            list<Room__c> delRms = new list<Room__c>();
            list<Room__c> rms = [select id, Room_Date__c, Meeting_Day__c, Day_of_Week__c, ADA_Rooms__c, NCM_On_Site__c, Premium_Rooms__c, Run_of_House__c
                                    from Room__c 
                                    where Engagement__c = :var.eng.id
                                    order by Room_Date__c
                                ];
            
            integer lngth = var.eng.Rooms_From__c.daysBetween(var.eng.Rooms_To__c);
            for(integer i = 0; i <= lngth; i++){
                date currentDate = var.eng.Rooms_From__c.addDays(i);

                boolean alreadyExists = false;

                boolean meetingDay = false;
                if(currentDate >= var.eng.Engagement_Start_Date__c && currentDate <= var.eng.Engagement_End_Date__c){
                    meetingDay = true;
                }

                boolean ncmOnSite = false;
                if(currentDate >= var.eng.NCM_Arrival__c && currentDate < var.eng.NCM_Departure__c){
                    ncmOnSite = true;
                }

                if(rms.size() > 0){
                    for (Room__c rm : rms){
                        if (rm.Room_Date__c == currentDate){
                            alreadyExists = true;
                            if(meetingDay && !rm.Meeting_Day__c){
                                rm.Meeting_Day__c = true;
                            }
                            if(ncmOnSite && rm.NCM_On_Site__c < 1){
                                rm.NCM_On_Site__c = 1;
                            }
                            break;
                        }
                        if(rm.Room_Date__c > currentDate){
                            break;
                        }
                    }
                }

                if(!alreadyExists){
                    Room__c rm = new Room__c();

                    rm.Engagement__c = var.eng.Id;
                    rm.Room_Date__c = currentDate;
                    rm.ADA_Rooms__c = 0;
                    rm.Premium_Rooms__c = 0;

                    if (var.memCnt > 0){
                        rm.Run_of_House__c = var.memCnt;
                    } else{
                        rm.Run_of_House__c = 0;
                    }
                    if(meetingDay){
                        rm.Meeting_Day__c = true;
                    }
                    if(ncmOnSite){
                        rm.NCM_On_Site__c = 1;
                    } else{
                        rm.NCM_On_Site__c = 0;
                    }

                    rms.add(rm);
                }
            }

            upsert rms;

            for (Room__c rm : rms){
                if(rm.Room_Date__c < var.eng.Rooms_From__c || rm.Room_Date__c > var.eng.Rooms_To__c){
                    delRms.add(rm);
                }
            }
            if(delRms.size() > 0){
                delete delRms;
            }

            rms = [select id, Room_Date__c, Meeting_Day__c, Day_of_Week__c, ADA_Rooms__c, NCM_On_Site__c, Premium_Rooms__c, Run_of_House__c
                        from Room__c 
                        where Engagement__c = :var.eng.id
                        order by Room_Date__c
                    ];
            
            roomsRet.add(rms);
        }
        
        return roomsRet;
    }

    @AuraEnabled
    public static void updateRooms(List<Room__c> rms){
        update rms;
    }

    @AuraEnabled
    public static List<Room__c> getRoomsForEngagement(id engId){
        List<Room__c> rms = [select id, Room_Date__c, Meeting_Day__c, Day_of_Week__c, ADA_Rooms__c, NCM_On_Site__c, Premium_Rooms__c, Run_of_House__c 
            from Room__c 
            where Engagement__c = :engId 
            order by Room_Date__c];
            
        return rms;
    }

    @AuraEnabled
    public static list<Activity_Participation__c> getAttendeeParticipation(id attId){
        list<Activity_Participation__c> ptcs = new list<Activity_Participation__c>();
        Engagement_Attendee__c att = [select id, Engagement__c, 
                                            (select id, Engagement_Activity__c, Engagement_Activity__r.name, Total_Number_of_Participants__c 
                                                from Activity_Participation__r
                                            ) 
                                        from Engagement_Attendee__c 
                                        where id = :attId];

        list<Engagement_Activity__c> acts = [select id, name from Engagement_Activity__c where Engagement__c = :att.Engagement__c order by Start__c desc];
        for(Engagement_Activity__c act : acts){

            boolean needsPtc = true;
            for (Activity_Participation__c ptc : att.Activity_Participation__r){
                if (ptc.Engagement_Activity__c == act.id){
                    needsPtc = false;
                    ptcs.add(ptc);
                    break;
                }
            }

            if(needsPtc){
                Activity_Participation__c ptc = new Activity_Participation__c();
                ptc.Engagement_Activity__c = act.id;
                ptc.Engagement_Attendee__c = att.id;
                ptc.Total_Number_of_Participants__c = 0;
                ptcs.add(ptc);
            }
        }

        upsert ptcs;
        ptcs = [select id, Engagement_Activity__c, Engagement_Activity__r.name, Total_Number_of_Participants__c 
                from Activity_Participation__c 
                where Engagement_Attendee__c = :att.id
                order by Engagement_Activity__r.name];

        return ptcs;
    }

    @AuraEnabled
    public static list<Activity_Participation__c> getActivityParticipation(id actId){
        list<Activity_Participation__c> ptcs = [select id, Total_Number_of_Participants__c, Engagement_Attendee__r.Name
                                                from Activity_Participation__c 
                                                where Engagement_Activity__c = :actId
                                                order by Engagement_Attendee__r.Name];

        return ptcs;
    }

    @AuraEnabled
    public static void upsertParticipation(list<Activity_Participation__c> ptcs){
        list<Activity_Participation__c> delPtcs = new list<Activity_Participation__c>();
        for (integer i = 0; i < ptcs.size(); i){
            boolean remove = true;
            Activity_Participation__c ptc = ptcs.get(i);
            if (ptc.Total_Number_of_Participants__c > 0){
                remove = false;
            }

            if(remove){
                ptcs.remove(i);

                if(ptc.id != null){
                    delPtcs.add(ptc);
                }
            } else{
                i++;
            }
        }

        database.upsert(ptcs, false);

        if(delPtcs.size() > 0){
            database.delete(delPtcs, false);
        }
    }

}