unpackaged/main/default/objects/Finance_Accounts_Receivable__c/Finance_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Used to store records generated when an Invoice is 1 day past the due date and unpaid from FFA</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>AR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Outstanding_Value__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Value__c</fullName>
    <label>Outstanding Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Link</label>
    <referenceTo>c2g__codaInvoice__c</referenceTo>
    <relationshipName>Finance_Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/batchSINarReconcileTest.cls
@isTest (SeeAllData = true)
public class batchSINarReconcileTest {
    public static testMethod void TestbatchSINarReconcile() {
		test.startTest();

        user usr = [select id from User where alias = 'sfadmin' limit 1];

        system.runAs(usr){
            Finance_Accounts_Receivable__c AR = [select id, Sales_Invoice__c 
                                                 from Finance_Accounts_Receivable__c 
                                                 where Sales_Invoice__r.c2g__InvoiceStatus__c = 'Complete' and Sales_Invoice__r.c2g__PaymentStatus__c <> 'Paid' 
                                                 limit 1];

            AR.Outstanding_Value__c = 0;
            update AR;

            batchSINarReconcile batchBrd = new batchSINarReconcile();
            database.executebatch(batchBrd,1);
        }
    }
}