unpackaged/main/default/objects/Finance_Accounts_Receivable__c/Finance_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Used to store records generated when an Invoice is 1 day past the due date and unpaid from FFA</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>AR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Outstanding_Out_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Out_of_Sync__c</fullName>
    <formula>Outstanding_Value__c  &lt;&gt;  Sales_Invoice__r.c2g__OutstandingValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Out of Sync (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Link</label>
    <referenceTo>c2g__codaInvoice__c</referenceTo>
    <relationshipName>Finance_Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/batchSINarReconcile.cls
global class batchSINarReconcile implements Database.Batchable<SObject>,Database.Stateful, Database.AllowsCallouts {
    global string query;

    global database.Querylocator start(Database.BatchableContext BC){
        this.query = 'select id, Sales_Invoice__c from Finance_Accounts_Receivable__c ' +
                     'where Outstanding_Out_of_Sync__c = true ';
        
        if(test.isRunningTest()){
            this.query = this.query + 'limit 1';
        } else{
            this.query = this.query + 'limit 1000';
        }

        Database.QueryLocator result = Database.getQueryLocator(this.query);
        return result;
    }

    global void execute(Database.BatchableContext BC,List<sObject> scope){
        list<c2g__codaInvoice__c> slsInvs = new list<c2g__codaInvoice__c>();
        for(Sobject obj: scope){
            Finance_Accounts_Receivable__c AR = (Finance_Accounts_Receivable__c)obj;

            c2g__codaInvoice__c SIN = new c2g__codaInvoice__c();
            SIN.id = ar.Sales_Invoice__c;
            slsInvs.add(SIN);
        }
        Database.SaveResult[] resultInv = Database.update(slsInvs);
    }

    global void finish(Database.BatchableContext BC) {

    }
}