unpackaged/main/default/objects/axcessa_Group__c/axcessa_Group__c.object-meta.xml
<CustomObject>
    <label>aXcessa Group</label>
    <nameField>
        <label>aXcessa Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/axcessa_Group__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Group__c</fullName>
    <label>aXcessa Group</label>
    <referenceTo>axcessa_Group__c</referenceTo>
    <relationshipLabel>aXcessa Stores</relationshipLabel>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Store_Status__c.field-meta.xml
<CustomField>
    <fullName>Store_Status__c</fullName>
    <formula>IF( 
    AND(Disconnected_Program__c &gt; TODAY(),Disconnected_Program__c &lt; (Today()+45)),


       &quot;Disconnecting&quot;,
         
      


    IF( 
        Disconnected_Program__c &lt;= TODAY(), 
        &quot;Inactive&quot;,
        IF(
            OR(
                Training_Complete__c &gt; TODAY(),
                ISBLANK( Training_Complete__c )
            ),
            &quot;Provisioning&quot;,
            IF(
                NOT( ISBLANK( Parent_Instance__c ) ),
                &quot;Shared Instance&quot;,
                &quot;Active&quot;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Client_Case_Relation__c/Client_Case_Relation__c.object-meta.xml
<CustomObject>
    <label>Client Case Relation</label>
    <nameField>
        <displayFormat>CCR-{00000000}</displayFormat>
        <label>Client Case Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Case Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Case_Relation__c/fields/axcessa_Group__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Group</label>
    <referenceTo>axcessa_Group__c</referenceTo>
    <relationshipLabel>Client Case Relations</relationshipLabel>
    <relationshipName>Client_Case_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Case_Relation__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>Client Case Relations</relationshipLabel>
    <relationshipName>Client_Case_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Case_Relation__c/fields/Client_Case__c.field-meta.xml
<CustomField>
    <fullName>Client_Case__c</fullName>
    <label>Client Case</label>
    <referenceTo>Client_Support_Ticket__c</referenceTo>
    <relationshipLabel>Client Case Relations</relationshipLabel>
    <relationshipName>Client_Case_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Group__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Group</label>
    <referenceTo>axcessa_Group__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Client_Case__c.field-meta.xml
<CustomField>
    <fullName>Client_Case__c</fullName>
    <displayFormat>CS-{0000000}</displayFormat>
    <inlineHelpText>System generated case number</inlineHelpText>
    <label>Case #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/cseRelAxcEXT.cls
public class cseRelAxcEXT {
    private ApexPages.StandardController stdController;
    public id cseId;
    public Client_Support_Ticket__c cse;
    public list<wRel> wRels;
    
    public cseRelAxcEXT(apexpages.standardcontroller stdController){
        this.stdController = stdController;
        cseId = ApexPages.currentPage().getParameters().get('id');
        getcse();
    }
    
    public Client_Support_Ticket__c getcse(){
        if (cse == null){            
            DescribeSObjectResult describeResult = Client_Support_Ticket__c.getSObjectType().getDescribe();
            List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            String query =
                ' SELECT ' +
                String.join( fieldNames, ',' ) +
                ' FROM ' +
                describeResult.getName() +
                ' where id = \'' + cseId + '\'';
            cse = Database.query( query );
        }
        return cse;
    }
    
    public list<wRel> getwRels(){
        if (wRels == null){
            wRels = new list<wRel>();
            list<axcessa_Platform_Engagement__c> strs;
            
            DescribeSObjectResult describeResult = axcessa_Platform_Engagement__c.getSObjectType().getDescribe();
            List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            String query =
                ' SELECT ' +
                String.join( fieldNames, ',' ) +
                ' FROM ' +
                describeResult.getName() +
                ' where axcessa_Group__c = \'' + cse.axcessa_Group__c + '\' and Store_Status__c <> \'Inactive\' order by Name';
            
            Try{
                strs = Database.query( query );
            } catch (exception er){
                system.debug(er);
                strs = new list<axcessa_Platform_Engagement__c>();
            }
            
            for (axcessa_Platform_Engagement__c str : strs){
                wRels.add(new wRel(cse, str));
            }
        }
        return wRels;
    }
    
    public PageReference slctAll(){
        for (wRel rel : wRels){
            rel.selected = true;
        }
        return null;
    }
    
    public PageReference unslctAll(){
        for (wRel rel : wRels){
            rel.selected = false;
        }
        return null;
    }
    
    public PageReference updRel() {
        list<Client_Case_Relation__c> addRels = new list<Client_Case_Relation__c>();
        list<Client_Case_Relation__c> delRels = new list<Client_Case_Relation__c>();
        
        for (wRel rel : wRels) {
            List<Client_Case_Relation__c> rels = [select id 
                                                  from Client_Case_Relation__c 
                                                  where Client_Case__c = :rel.cse.id and axcessa_Store__c = :rel.str.id];
            
            if (rel.selected == true && rels.size() == 0) {
                Client_Case_Relation__c nRel = new Client_Case_Relation__c();
                nRel.Client_Case__c = cseId;
                nRel.axcessa_Group__c = rel.str.axcessa_Group__c;
                nRel.axcessa_Store__c = rel.str.id;
                
                addRels.add(nRel);
            } else if (rel.selected == false && rels.size() != 0) {
                for (Client_Case_Relation__c delRel : rels){
                    delRels.add(delRel);
                }
            }
        }
        
        boolean isSuccess = true;
        if (addRels.size() > 0){
            try {
                insert addRels;
            } catch(Exception er){
                isSuccess = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,string.valueof(er)));
            }
        }
        if (delRels.size() > 0){
            try {
                delete delRels;
            } catch(Exception er){
                isSuccess = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,string.valueof(er)));
            }
        }
        
        if (isSuccess){
            PageReference pgRef = new PageReference('/' + cseId);   
            pgRef.setRedirect(true);
            return pgRef;
        } else {
            return null;
        }
    }
    
    public class wRel{
        public boolean selected {get; set;}
        public Client_Support_Ticket__c cse {get; set;}
        public axcessa_Platform_Engagement__c str {get; set;}
        
        public wRel(Client_Support_Ticket__c cse, axcessa_Platform_Engagement__c str) {
            this.cse = cse;
            this.str = str;
            List<Client_Case_Relation__c> rels = [select id 
                                                  from Client_Case_Relation__c 
                                                  where Client_Case__c = :cse.Id and axcessa_Store__c = :str.id];
            if (rels.size() > 0) {
                selected = true;
            } else {
                selected = false;
            }
            
        }
    }
}