unpackaged/main/default/objects/axcessa_Group__c/axcessa_Group__c.object-meta.xml
<CustomObject>
    <label>aXcessa Group</label>
    <nameField>
        <label>aXcessa Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/axcessa_Group__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Group__c</fullName>
    <label>aXcessa Group</label>
    <referenceTo>axcessa_Group__c</referenceTo>
    <relationshipLabel>aXcessa Stores</relationshipLabel>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Store_Status__c.field-meta.xml
<CustomField>
    <fullName>Store_Status__c</fullName>
    <formula>IF( 
    AND(Disconnected_Program__c &gt; TODAY(),Disconnected_Program__c &lt; (Today()+45)),


       &quot;Disconnecting&quot;,
         
      


    IF( 
        Disconnected_Program__c &lt;= TODAY(), 
        &quot;Inactive&quot;,
        IF(
            OR(
                Training_Complete__c &gt; TODAY(),
                ISBLANK( Training_Complete__c )
            ),
            &quot;Provisioning&quot;,
            IF(
                NOT( ISBLANK( Parent_Instance__c ) ),
                &quot;Shared Instance&quot;,
                &quot;Active&quot;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Group__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Group</label>
    <referenceTo>axcessa_Group__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/createCaseRelationsTest.cls
@isTest (SeeAllData=true)
public class createCaseRelationsTest {
    static testMethod void TestcreateCaseRelations(){
        
        createCaseRelations.vars var = new createCaseRelations.vars();
        var.cseId = [select id from Client_Support_Ticket__c limit 1].id;
        var.objNme = 'axcessa_Platform_Engagement__c';
        var.soqlWhere = 'axcessa_Group__c = \'' + 
            [select axcessa_Group__c from axcessa_Platform_Engagement__c where Store_Status__c = 'ACTIVE' limit 1].axcessa_Group__c + 
            '\' and Store_Status__c = \'ACTIVE\'';
        var.childFldNme = 'axcessa_Store__c';
        
        List<createCaseRelations.vars> vars = new List<createCaseRelations.vars>();
        vars.add(var);
        
        test.startTest();
        try{
            createCaseRelations.createCaseRelations(vars);
        } catch(exception er){
            system.debug(er);
        }
        test.stopTest();
    }
}