unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Main_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/axcessa_Platform_Engagement__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Platform_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/axcessaBillProdTest.cls
@isTest (SeeAllData=true)
public class axcessaBillProdTest {
    static testMethod void TestaxcessaBillProd(){
        axcessa_Platform_Engagement__c axcCem = [select id 
                                                 from axcessa_Platform_Engagement__c 
                                                 where Main_Product__c <> null 
                                                 limit 1];
        
        Test.startTest();
        
        axcessaBillProd.vars var = new axcessaBillProd.vars();
        var.axcId = axcCem.id;
        
        list<Billing_Product__c> bProds = [select id from Billing_Product__c where axcessa_Platform_Engagement__c = :axcCem.id];
        
        List<axcessaBillProd.vars> vars = new List<axcessaBillProd.vars>();
        vars.add(var);
        
        try{
            axcessaBillProd.addUpdBProd(vars);
        } catch(Exception er){
            system.debug(er);
        }
        
        if (bProds.size() > 0){
            delete bProds;
        }
        
        try{
            axcessaBillProd.addUpdBProd(vars);
        } catch(Exception er){
            system.debug(er);
        }
        
        Test.stopTest();
    }
}