unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Data_Updated__c.field-meta.xml
<CustomField>
    <fullName>Data_Updated__c</fullName>
    <label>Data Updated</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Last_Login_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Login_Date__c</fullName>
    <label>Last Login Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Last_Month_Report_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_Month_Report_Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Last Month Report Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Last_Month_User_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_Month_User_Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Last Month User Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Need_to_Recalculate_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Need_to_Recalculate_Metrics__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need to Recalculate Metrics?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Reynolds_axcessa_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Reynolds_axcessa_Group_Id__c</fullName>
    <label>Reynolds aXcessa Group Id (Code)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Reynolds_Customer_ID_CIF__c.field-meta.xml
<CustomField>
    <fullName>Reynolds_Customer_ID_CIF__c</fullName>
    <description>RR unique customer (store) ID</description>
    <inlineHelpText>RR unique customer (store) ID</inlineHelpText>
    <label>Reynolds Customer ID (CIF)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Reynolds_Store_ID__c.field-meta.xml
<CustomField>
    <fullName>Reynolds_Store_ID__c</fullName>
    <description>RR store internal store ID</description>
    <inlineHelpText>RR store internal store ID</inlineHelpText>
    <label>Reynolds Store ID</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Reynolds_Store_Name__c.field-meta.xml
<CustomField>
    <fullName>Reynolds_Store_Name__c</fullName>
    <inlineHelpText>Name Reynolds uses for this store</inlineHelpText>
    <label>Reynolds Store Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/YTD_AVG_Report_Count__c.field-meta.xml
<CustomField>
    <fullName>YTD_AVG_Report_Count__c</fullName>
    <label>YTD AVG Report Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/YTD_AVG_User_Count__c.field-meta.xml
<CustomField>
    <fullName>YTD_AVG_User_Count__c</fullName>
    <label>YTD AVG User Count</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/YTD_Report_Count__c.field-meta.xml
<CustomField>
    <fullName>YTD_Report_Count__c</fullName>
    <label>YTD Report Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/YTD_User_Count__c.field-meta.xml
<CustomField>
    <fullName>YTD_User_Count__c</fullName>
    <label>YTD User Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/aXcessa_Store_Metric__b.object-meta.xml
<CustomObject>
    <label>aXcessa Store Metric</label>
    <pluralLabel>aXcessa Store Metrics</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/aXcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>aXcessa_Store__c</fullName>
    <label>aXcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>aXcessa Store Metrics</relationshipLabel>
    <relationshipName>aXcessa_Store_Metrics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <label>CIF</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Data_Date__c.field-meta.xml
<CustomField>
    <fullName>Data_Date__c</fullName>
    <label>Data Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <label>Installed?</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Last_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Login__c</fullName>
    <label>Last Login</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/NCM__c.field-meta.xml
<CustomField>
    <fullName>NCM__c</fullName>
    <label>NCM?</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Reports_Count__c.field-meta.xml
<CustomField>
    <fullName>Reports_Count__c</fullName>
    <label>Reports Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <label>Store Id</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Store_Name__c.field-meta.xml
<CustomField>
    <fullName>Store_Name__c</fullName>
    <label>Store Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Users_Count__c.field-meta.xml
<CustomField>
    <fullName>Users_Count__c</fullName>
    <label>Users Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/batchAxcessaMetricCalculation.cls
public class batchAxcessaMetricCalculation implements Database.Batchable<sObject>
{
	public Datetime firstOfYear;

	public Integer ytdDivisor;

	public Database.QueryLocator start(Database.BatchableContext BC)
	{
		firstOfYear = datetime.newInstance(Date.Today(  ).year(), 1, 1);
		if ( Date.today(  ).addMonths(-1).month() == 12 )
		{
			ytdDivisor = 1;
		}
		else
		{
			ytdDivisor = Date.today(  ).addMonths(-1).month();
		}

		String query = 'SELECT Id, Reynolds_Customer_ID_CIF__c, Reynolds_Store_ID__c, Reynolds_axcessa_Group_Id__c, Reynolds_Store_Name__c, Last_Login_Date__c ';
		query = query + 'FROM axcessa_Platform_Engagement__c ';
		query = query + 'WHERE Need_to_Recalculate_Metrics__c = TRUE ';

		if ( Test.isRunningTest() )
		{
			query = query + 'LIMIT 1';
		}

		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<sObject> scope)
	{
		List<axcessa_Platform_Engagement__c> aXcessaStores = new list<axcessa_Platform_Engagement__c>();

		for ( sobject s : scope )
		{
			axcessa_Platform_Engagement__c aXcessaStore = ( axcessa_Platform_Engagement__c )s;

			List<aXcessa_Store_Metric__b> storeMetrics = new List<aXcessa_Store_Metric__b>();
			if ( Test.isRunningTest() )
			{
				aXcessa_Store_Metric__b testMetric = new aXcessa_Store_Metric__b(  );
				testMetric.aXcessa_Store__c = aXcessaStore.Id;
				testMetric.CIF__c = '0000000';
				testMetric.Data_Date__c = Datetime.now().addMonths(-1);
				testMetric.Group__c = '1111111';
				testMetric.Installed__c = 1;
				testMetric.Last_Login__c = Datetime.now().addMonths(-1);
				testMetric.NCM__c = 1;
				testMetric.Reports_Count__c = 1500;
				testMetric.Store_Id__c = '2222222';
				testMetric.Store_Name__c = 'Test Store';
				testMetric.Users_Count__c = 2600;

				storeMetrics.add(testMetric);
				testMetric.Data_Date__c = testMetric.Data_Date__c.addMonths(-1);
				testMetric.Last_Login__c = testMetric.Last_Login__c.addMonths(-1);
				testMetric.Reports_Count__c = 1501;
				testMetric.Users_Count__c = 2601;
				storeMetrics.add(testMetric);

				aXcessaStore.Reynolds_Customer_ID_CIF__c = null;
				aXcessaStore.Reynolds_Store_ID__c = null;
				aXcessaStore.Reynolds_axcessa_Group_Id__c = null;
				aXcessaStore.Reynolds_Store_Name__c = null;
				aXcessaStore.Last_Login_Date__c = null;
			}
			else
			{
				storeMetrics = [SELECT aXcessa_Store__c, CIF__c, Data_Date__c, Group__c, Installed__c, Last_Login__c, NCM__c, Reports_Count__c, Store_Id__c, Store_Name__c, Users_Count__c
				                FROM aXcessa_Store_Metric__b
				                WHERE aXcessa_Store__c = :aXcessaStore.Id
				                ORDER BY aXcessa_Store__c, Data_Date__c DESC
				                LIMIT 12];
			}

			Integer monthCount = 1;
			Decimal ytdReports = 0;
			Decimal ytdUsers = 0;
			for ( aXcessa_Store_Metric__b strMetric : storeMetrics )
			{
				if ( aXcessaStore.Reynolds_Customer_ID_CIF__c == null )
				{
					aXcessaStore.Reynolds_Customer_ID_CIF__c = strMetric.CIF__c;
				}
				if ( aXcessaStore.Reynolds_Store_ID__c == null )
				{
					aXcessaStore.Reynolds_Store_ID__c = strMetric.Store_Id__c;
				}
				if ( aXcessaStore.Reynolds_axcessa_Group_Id__c == null )
				{
					aXcessaStore.Reynolds_axcessa_Group_Id__c = strMetric.Group__c;
				}
				if ( aXcessaStore.Reynolds_Store_Name__c == null )
				{
					aXcessaStore.Reynolds_Store_Name__c = strMetric.Store_Name__c;
				}
				if ( aXcessaStore.Last_Login_Date__c < strMetric.Last_Login__c )
				{
					aXcessaStore.Last_Login_Date__c = Date.valueOf(strMetric.Last_Login__c);
				}

				system.debug(firstOfYear);
				if ( strMetric.Data_Date__c >= firstOfYear )
				{
					ytdReports = ytdReports + strMetric.Reports_Count__c;
					ytdUsers = ytdUsers + strMetric.Users_Count__c;
				}

				if ( monthCount == 1 )
				{
					aXcessaStore.Last_Month_Report_Count__c = strMetric.Reports_Count__c;
					aXcessaStore.Last_Month_User_Count__c = strMetric.Users_Count__c;
				}
				else if ( monthCount == 2 )
				{
					aXcessaStore.Last_Month_Report_Count__c = strMetric.Reports_Count__c;
					aXcessaStore.Last_Month_User_Count__c = strMetric.Users_Count__c;
				}

				monthCount = monthCount + 1;
			}

			aXcessaStore.YTD_Report_Count__c = ytdReports;
			aXcessaStore.YTD_User_Count__c = ytdUsers;

			if ( ytdReports > 0 )
			{
				aXcessaStore.YTD_AVG_Report_Count__c = ytdReports / ytdDivisor;
			}
			else
			{
				aXcessaStore.YTD_AVG_Report_Count__c = 0;
			}
			if ( ytdUsers > 0 )
			{
				aXcessaStore.YTD_AVG_User_Count__c = ytdUsers / ytdDivisor;
			}
			else
			{
				aXcessaStore.YTD_AVG_User_Count__c = 0;
			}

			aXcessaStore.Need_to_Recalculate_Metrics__c = false;
			aXcessaStore.Data_Updated__c = Date.today(  );

			aXcessaStores.add(aXcessaStore);
		}

		System.debug(aXcessaStores);
		Database.SaveResult[] SRs = Database.update( aXcessaStores, false );
		for ( Database.SaveResult sr : SRs )
		{
			if ( sr.isSuccess() )
			{
				System.debug('Success on: ' + sr.getId());
			}
			else
			{
				System.debug(sr.getErrors());
			}
		}
	}

	public void finish(Database.BatchableContext BC)
	{
	}
}