unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Store_Status__c.field-meta.xml
<CustomField>
    <fullName>Store_Status__c</fullName>
    <formula>IF( 
    AND(Disconnected_Program__c &gt; TODAY(),Disconnected_Program__c &lt; (Today()+45)),


       &quot;Disconnecting&quot;,
         
      


    IF( 
        Disconnected_Program__c &lt;= TODAY(), 
        &quot;Inactive&quot;,
        IF(
            OR(
                Training_Complete__c &gt; TODAY(),
                ISBLANK( Training_Complete__c )
            ),
            &quot;Provisioning&quot;,
            IF(
                NOT( ISBLANK( Parent_Instance__c ) ),
                &quot;Shared Instance&quot;,
                &quot;Active&quot;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/recordTypes/axcessa.recordType-meta.xml
<RecordType>
    <fullName>axcessa</fullName>
    <active>true</active>
    <label>axcessa</label>
</RecordType>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needing Validation</fullName>
                <default>true</default>
                <label>Needing Validation</label>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Credit Card Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/Billing_Configuration__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Billing Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Billing_Product_WHERE__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_WHERE__c</fullName>
    <label>Billing Product WHERE</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Configurations</relationshipLabel>
    <relationshipName>Billing_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/One_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>One Time Run? (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Recurring_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Day__c</fullName>
    <label>Recurring Day</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_CEM__c.field-meta.xml
<CustomField>
    <fullName>Split_on_CEM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on CEM?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Split_on_Dim_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on Dim 2?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/axcessa_Platform_Engagement__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Platform_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The NCM Employee&#39;s Dimension 2 record in Financial Force</inlineHelpText>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/billingProductDailyTest.cls
@isTest(SeeAllData = true)
public class billingProductDailyTest{
	public static testMethod void testBilling(){
		Test.startTest();
		user u = 
		[
			SELECT Id
			FROM User
			WHERE 
				IsActive = true AND 
				Id IN 
				(
					SELECT UserId
					FROM UserPackageLicense
					WHERE PackageLicense.NamespacePrefix = 'c2g'
				) AND 
				Id IN 
				(
					SELECT c2g__User__c
					FROM c2g__codaUserCompany__c
				)
			ORDER BY LastName DESC
			LIMIT 1
		];
		system.runas(u){
			List<String> fieldNames = new List<String>(Billing_Product__c.getSObjectType().getDescribe().fields.getMap().keySet());
			String query = ' SELECT ' + String.join(fieldNames, ', ') + ' FROM Billing_Product__c WHERE Dimension_1__r.Name like \'8000-axcessa\' and Dimension_2__c != null limit 1';
			Billing_Product__c bProd = Database.query(query);
			bProd.Billing_Product_Status__c = 'Active';
			bProd.Next_Billing_Date__c = date.today().addDays( - 1);
			list<Billing_Product__c> bProds = new list<Billing_Product__c>();
			bProds.add(bProd);
			bProd = bProd.clone();
			bProd.axcessa_Platform_Engagement__c = 
			[
				SELECT Id
				FROM axcessa_Platform_Engagement__c 
				WHERE Store_Status__c = 'Active'
				LIMIT 1
			].id;
			bProds.add(bProd);
			bProd = bProd.clone();
			bProd.Dimension_2__c = 
			[
				SELECT Id
				FROM c2g__codaDimension2__c 
				WHERE name like '%Stephen Clark%'
				LIMIT 1
			].id;
			bProds.add(bProd);
			upsert bProds;
			Billing_Account__c bAcc = 
			[
				SELECT id
				FROM Billing_Account__c 
				WHERE id = :bProd.Billing_Account__c
			];
			bAcc.Status__c = 'Validated';
			try{
				update bAcc;
			} catch (exception er){
				bAcc.Primary_Contact__c = 
				[
					SELECT Id
					FROM Contact 
					WHERE Name LIKE 'Stephen Clark'
					LIMIT 1
				].Id;
				update bAcc;
			}
			Billing_Configuration__c bConfig = new Billing_Configuration__c();
			bConfig.Dimension_1__c = 
			[
				SELECT id
				FROM c2g__codaDimension1__c 
				WHERE Name LIKE '8000-axcessa'
				LIMIT 1
			].id;
			bConfig.Split_on_Dim_2__c = true;
			bConfig.Split_on_CEM__c = true;
			bConfig.One_Time_Run__c = true;
			bConfig.Recurring_Day__c = date.today().day();
			bConfig.Billing_Product_WHERE__c = 'WHERE Dimension_1__c = \'' + bConfig.Dimension_1__c + '\'';
			insert bConfig;
			BillingProductDaily testSche = new BillingProductDaily();
			testSche.execute(null);
		}
		Test.stopTest();
	}
}