unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Store_Status__c.field-meta.xml
<CustomField>
    <fullName>Store_Status__c</fullName>
    <formula>IF( 
    AND(Disconnected_Program__c &gt; TODAY(),Disconnected_Program__c &lt; (Today()+45)),


       &quot;Disconnecting&quot;,
         
      


    IF( 
        Disconnected_Program__c &lt;= TODAY(), 
        &quot;Inactive&quot;,
        IF(
            OR(
                Training_Complete__c &gt; TODAY(),
                ISBLANK( Training_Complete__c )
            ),
            &quot;Provisioning&quot;,
            IF(
                NOT( ISBLANK( Parent_Instance__c ) ),
                &quot;Shared Instance&quot;,
                &quot;Active&quot;
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/cseRelAxcTest.cls
@isTest (SeeAllData = true)
public class cseRelAxcTest {
    public static testMethod void TestcseRelAxc() {
        test.startTest();
        PageReference pageRef = Page.caseRelateAxcessa;
        Test.setCurrentPage(pageRef);
        
        Client_Support_Ticket__c cse = [select id from Client_Support_Ticket__c where axcessa_Store__r.Store_Status__c = 'Active' limit 1];
        ApexPages.currentPage().getParameters().put('id', cse.id);

        apexpages.standardcontroller stdController = new ApexPages.StandardController(cse);
        cseRelAxcEXT controller = new cseRelAxcEXT(stdController);
        
        controller.getcse();
        controller.getwRels();
        
        controller.unslctAll();
        controller.slctAll();
        
        controller.updRel();
        
        test.stopTest();
    }
}