unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Need_to_Recalculate_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Need_to_Recalculate_Metrics__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need to Recalculate Metrics?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/batchAxcessaMetricCalculationTest.cls
@isTest(SeeAllData = true)
public class batchAxcessaMetricCalculationTest
{
	@IsTest
	static void testBatchAxcessaMetricCalculation()
	{
		axcessa_Platform_Engagement__c pe = [SELECT Id FROM axcessa_Platform_Engagement__c LIMIT 1];
		pe.Need_to_Recalculate_Metrics__c = true;
		update pe;
		
		User contextuser = [SELECT Id
		                    FROM User
		                    WHERE Profile.Name = 'System Administrator' AND IsActive = TRUE
		                    LIMIT 1];

		Test.startTest();
		System.runAs(contextuser)
		{
			batchAxcessaMetricCalculation batchable = new batchAxcessaMetricCalculation(  );
			Database.executeBatch(batchable, 1);
		}
		Test.stopTest();
	}
}