unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Main_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>axcessa_Platform_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Mobile_Fee__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Fee__c</fullName>
    <inlineHelpText>Initial contractual amount</inlineHelpText>
    <label>Mobile Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/fields/Monthly_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Fee__c</fullName>
    <inlineHelpText>Initial contractual amount</inlineHelpText>
    <label>Monthly Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/axcessa_Platform_Engagement__c/recordTypes/axcessa.recordType-meta.xml
<RecordType>
    <fullName>axcessa</fullName>
    <active>true</active>
    <label>axcessa</label>
</RecordType>

unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/axcessa_Platform_Engagement__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Platform_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Recurring_Billing_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Billing_Day__c</fullName>
    <label>Recurring Billing Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Write_to_Opp__c.field-meta.xml
<CustomField>
    <fullName>Write_to_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Write to Opp? (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product is related to this Dimension</description>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/axcessa.recordType-meta.xml
<RecordType>
    <fullName>axcessa</fullName>
    <active>true</active>
    <label>axcessa</label>
</RecordType>

unpackaged/main/default/classes/axcessaBillProd.cls
public class axcessaBillProd {
    public class vars {

        @InvocableVariable(label='axcessa CEM' Required=true)
        public Id axcId;
        
    }
    
    @InvocableMethod
    public static void addUpdBProd(List<vars> vars){
        list<Billing_Product__c> bProds = new list<Billing_Product__c>();
        list<axcessa_Platform_Engagement__c> axcCems = new list<axcessa_Platform_Engagement__c>();
        id pbId = [select id from Pricebook2 where IsStandard = true].id;
        
        id ax1_5 = [select id from Product2 where Name = 'FEES - AXCESSA (1-5 STORES)' limit 1].id;
        PriceBookEntry pbe1_5 = [select id, UnitPrice, Product2id from PriceBookEntry where Product2Id = :ax1_5 and Pricebook2id = :pbId];
        
        id ax6_14 = [select id from Product2 where Name = 'FEES - AXCESSA (6+ STORES)' limit 1].id;
        PriceBookEntry pbe6_14 = [select id, UnitPrice, Product2id from PriceBookEntry where Product2Id = :ax6_14 and Pricebook2id = :pbId];
        
        id ax15 = [select id from Product2 where Name = 'FEES - AXCESSA (15+ STORES)' limit 1].id;
        PriceBookEntry pbe15 = [select id, UnitPrice, Product2id from PriceBookEntry where Product2Id = :ax15 and Pricebook2id = :pbId];
        
        integer day = date.today().day();
        integer month;
        integer year;
        date bDate;
        if (day > 15){
            month = date.today().addMonths(1).month();
            year = date.today().addMonths(1).year();
        } else {
            month = date.today().month();
            year = date.today().year();
        }
        bDate = date.valueOf(year + '-' + month + '-25');
        
        for (vars var : vars){
            axcessa_Platform_Engagement__c axcCem = [select id, Monthly_Fee__c, Billing_Account__c, Dimension_1__c, Dimension_2__c, 
                                                     	Main_Product__c, Mobile_Fee__c 
                                                     from axcessa_Platform_Engagement__c 
                                                     where id = :var.axcId];
            boolean hsBprod = false;
            list<Billing_Product__c> varBprods = [select id, Product__c from Billing_Product__c where axcessa_Platform_Engagement__c = :var.axcId];
            for (Billing_Product__C bProd : varBprods){
                if (bProd.Product__c == axcCem.Main_Product__c){
                    hsBprod = true;
                       
                    PriceBookEntry pbe = new PriceBookEntry();
                    if (axcCem.Main_Product__c == ax1_5){
                        pbe = pbe1_5;
                    } else if (axcCem.Main_Product__c == ax6_14){
                        pbe = pbe6_14;
                    } else if (axcCem.Main_Product__c == ax15){
                        pbe = pbe15;
                    } 
                       
                    if (pbe.UnitPrice < axcCem.Monthly_Fee__c){
                        axcCem.Monthly_Fee__c = pbe.UnitPrice;
                        axcCems.add(axcCem);
                    }
                       
                    bProds.add(updBprod(bProd, axcCem, pbe, bDate));
                } else if (bProd.Product__c == ax1_5 || bProd.Product__c == ax6_14 || bProd.Product__c == ax15){
                       bProd.Billing_Product_Status__c = 'Inactive';
                       bProds.add(bProd);
                }
            }
            if (!hsBprod){
                PriceBookEntry pbe = new PriceBookEntry();
                if (axcCem.Main_Product__c == ax1_5){
                    pbe = pbe1_5;
                } else if (axcCem.Main_Product__c == ax6_14){
                    pbe = pbe6_14;
                } else if (axcCem.Main_Product__c == ax15){
                    pbe = pbe15;
                }
                
                if (pbe.UnitPrice < axcCem.Monthly_Fee__c){
                    axcCem.Monthly_Fee__c = pbe.UnitPrice;
                    axcCems.add(axcCem);
                }
                
                Billing_Product__c bProd = new Billing_Product__c();
                
                bProds.add(updBprod(bProd, axcCem, pbe, bDate));
            }
        }
        
        upsert bProds;
        upsert axcCems;
    }
    
    private static Billing_Product__c updBprod(Billing_Product__c bProd, axcessa_Platform_Engagement__c axcCem, PriceBookEntry pbe, date bDate){
        
        bProd.Billing_Product_Status__c = 'Active';                       
        
        bProd.Product__c = pbe.Product2Id;
        bProd.Value__c = axcCem.Monthly_Fee__c;
        bProd.Billing_Account__c = axcCem.Billing_Account__c;
        bProd.axcessa_Platform_Engagement__c = axcCem.id;
        bProd.Next_Billing_Date__c = bDate;
        bProd.Dimension_1__c = axcCem.Dimension_1__c;
        bProd.Dimension_2__c = axcCem.Dimension_2__c;                       
        
        bProd.Billing_Frequency__c = 'Monthly';
        bProd.Billing_Product_Status__c = 'Waiting on Sign Off';
        bProd.Recurring_Billing_Day__c = 25;
        bProd.Write_to_Opp__c = false;
        
        return bProd;
    }
    
}