unpackaged/main/default/objects/axcessa_Platform_Engagement__c/axcessa_Platform_Engagement__c.object-meta.xml
<CustomObject>
    <description>When an axcessa customer is onboarded this is the record in which Software Solutions will manage the client</description>
    <label>aXcessa Store</label>
    <nameField>
        <label>aXcessa Store</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>aXcessa Stores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Case_Relation__c/Client_Case_Relation__c.object-meta.xml
<CustomObject>
    <label>Client Case Relation</label>
    <nameField>
        <displayFormat>CCR-{00000000}</displayFormat>
        <label>Client Case Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Case Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Case_Relation__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>Client Case Relations</relationshipLabel>
    <relationshipName>Client_Case_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Case_Relation__c/fields/Client_Case__c.field-meta.xml
<CustomField>
    <fullName>Client_Case__c</fullName>
    <label>Client Case</label>
    <referenceTo>Client_Support_Ticket__c</referenceTo>
    <relationshipLabel>Client Case Relations</relationshipLabel>
    <relationshipName>Client_Case_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/axcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>axcessa_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>axcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Client_Case__c.field-meta.xml
<CustomField>
    <fullName>Client_Case__c</fullName>
    <displayFormat>CS-{0000000}</displayFormat>
    <inlineHelpText>System generated case number</inlineHelpText>
    <label>Case #</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/clientCasesController.cls
public class clientCasesController {
    
    @AuraEnabled
    public static list<Client_Support_Ticket__c> getClientCases(id recId){
        list<Client_Support_Ticket__c> clientCases;
        
        DescribeSObjectResult describeResult = Client_Support_Ticket__c.getSObjectType().getDescribe();
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =
            ' SELECT ' +
            String.join( fieldNames, ', ' ) +
            ' FROM ' +
            describeResult.getName();
        
        string objName = string.valueof(recId.getSobjectType());
        list<id> ccrIds;
        if (objName == 'axcessa_Platform_Engagement__c'){
            ccrIds = getCCRId(recId, 'axcessa_Store__c');
            query = query + ' WHERE axcessa_Store__c = \'' + recId + '\' or id IN :ccrIds';
        }
         
        query = query + ' Order By LastModifiedDate desc';
        clientCases = Database.query( query );
        
        return clientCases;
    }
    
    private static list<id> getCCRId(id recId, string fldNme){
        list<id> ccrIds = new list<id>();
        
        String query = ' SELECT Client_Case__c from Client_Case_Relation__c where ' + fldNme + ' = :recId';
        list<Client_Case_Relation__c> ccrs = Database.query( query );
        for (Client_Case_Relation__c ccr : ccrs){
            ccrIds.add(ccr.Client_Case__c);
        }
        
        return ccrIds;
    }
}