unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Training_Subscription_Account__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Subscription Account</label>
    <referenceTo>Training_Subscription_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/Training_Subscription__c.object-meta.xml
<CustomObject>
    <label>Training Subscription</label>
    <nameField>
        <label>Training Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Account__c/Training_Subscription_Account__c.object-meta.xml
<CustomObject>
    <description>Accounts authorized to enroll under a Training Subscription</description>
    <label>Training Subscription Account</label>
    <nameField>
        <label>Training Subscription Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Training_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription__c</fullName>
    <label>Training Subscription Term</label>
    <referenceTo>Training_Subscription_Term__c</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Subscription_Sub_Accts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/Training_Subscription_Term__c.object-meta.xml
<CustomObject>
    <description>Institute Training Subscriptions terms and authorized accounts</description>
    <label>Training Subscription Term</label>
    <nameField>
        <label>Training Subscription Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>IF(
    Status_Formula__c = &quot;Inactive&quot;,
    &quot;Termed&quot;,
    RecordType.Name 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Training_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription__c</fullName>
    <label>Training Subscription</label>
    <referenceTo>Training_Subscription__c</referenceTo>
    <relationshipLabel>Training Subscription Terms</relationshipLabel>
    <relationshipName>Training_Subscription_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Transitioned_to_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Transitioned_to_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transitioned to Monthly?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BillingProductsForTermedTST.cls
global class BillingProductsForTermedTST implements Database.Batchable<SObject>, Schedulable{
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        String ACTIVE = 'Active';
        String TERMED = 'Termed';
        String ONETIME = 'One-Time';
        String queryString = 'SELECT Id, Name FROM Billing_Product__c WHERE Billing_Product_Status__c = \''
        + ACTIVE + '\' AND Billing_Frequency__c != \'' + ONETIME + '\' AND Training_Subscription_Account__c != null' +
        ' AND Training_Subscription_Account__r.Training_Subscription__r.Term__c = \'' + TERMED + 
        '\' AND Training_Subscription_Account__r.Training_Subscription__r.Transitioned_to_Monthly__c = false';
        System.debug('~~~queryString: ' + queryString);
        return Database.getQueryLocator(queryString);
    }

    global void execute(Database.BatchableContext BC, List<Billing_Product__c> scope) { 
        Id bpId;
        try{
            for(Billing_Product__c bp : scope) {
                bp.Billing_Product_Status__c = 'Inactive';
                bpId = bp.Id;
            }
            List<Database.SaveResult> dsrList = Database.update(scope, false);
            Logger.logErrorList('BillingProductsForTermedTST', dsrList, scope);
        } catch (Exception ex) {
            Logger.logException('BillingProductsForTermedTST', bpId, ex);
        }
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('BillingProductsForTermedTST::finish');
    }

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new BillingProductsForTermedTST());
    }
}