unpackaged/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cohort__c/fields/Available_Seats__c.field-meta.xml
<CustomField>
    <fullName>Available_Seats__c</fullName>
    <formula>Capacity__c - ( Number_of_Students__c + Graduated_Students__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Capacity - (# of students + # of graduated students)</inlineHelpText>
    <label>Available Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Cohort__c/fields/Cancelled_Students__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Students__c</fullName>
    <label>Cancelled Students</label>
    <summaryFilterItems>
        <field>Cohort_Student__c.Status__c</field>
        <operation>equals</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Cohort_Student__c.Cohort__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Cohort__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <description>The maximum number of cohort students allowed.</description>
    <inlineHelpText>The maximum number of cohort students allowed.</inlineHelpText>
    <label>Capacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Cohort__c/fields/Graduated_Students__c.field-meta.xml
<CustomField>
    <fullName>Graduated_Students__c</fullName>
    <label>Graduated Students</label>
    <summaryFilterItems>
        <field>Cohort_Student__c.Status__c</field>
        <operation>equals</operation>
        <value>Graduated</value>
    </summaryFilterItems>
    <summaryForeignKey>Cohort_Student__c.Cohort__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Cohort__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning Plan</label>
    <referenceTo>Learning_Plan__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Cohort__c/fields/Number_of_Students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Students__c</fullName>
    <label>Number of Students</label>
    <summaryFilterItems>
        <field>Cohort_Student__c.Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>Cohort_Student__c.Cohort__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Learning_Plan__c/Learning_Plan__c.object-meta.xml
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CohortController.cls
public with sharing class CohortController {
    
    @AuraEnabled
    public static List<Cohort__c> getOpenCohorts(String recType){
        
        List<Cohort__c> results = new List<Cohort__c>();
        try {
            results = [SELECT 
                        Id,
                        Name,
                        Start_Date__c,
                        End_Date__c,
                        Available_Seats__c,
                        Cancelled_Students__c,
                        Capacity__c,
                        Graduated_Students__c,
                        Learning_Plan__c,
                        Number_of_Students__c
                        FROM Cohort__c
                        WHERE (Start_Date__c = THIS_MONTH OR Start_Date__c > TODAY) 
                            AND Available_Seats__c > 0
                       		AND RecordTypeId = :recType
                        ORDER BY Start_Date__c];
            return results;
        } catch (Exception e) {
            //Logger.logError('CohortController', 'Error', UserInfo.getUserName(), 'Apex', e.getMessage(), e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
}