unpackaged/main/default/objects/Proprietary_Account__c/Proprietary_Account__c.object-meta.xml
<CustomObject>
    <label>Proprietary Account</label>
    <nameField>
        <label>Proprietary Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proprietary Accounts</relationshipLabel>
    <relationshipName>Proprietary_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_Number__c &amp; &quot;-&quot; &amp;   Member_Number_Code__c</formula>
    <label>Group Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Don&#39;t Bill</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_ID__r.Name &amp; &#39;-&#39; &amp;  Member_Number_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group / Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Global_Product_Service_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Global_Product_Service_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Active - Don&#39;t Bill</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Disconnected</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
        <isActive>false</isActive>
        <label>Suspended</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <customValue>
        <fullName>Honorary</fullName>
        <isActive>false</isActive>
        <label>Honorary</label>
    </customValue>
    <masterLabel>Global Product/Service Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/GroupAccountServiceTests.cls
@isTest
public with sharing class GroupAccountServiceTests {
    
    @TestSetup
    static void setup(){
        SampleDataFactory.createData();
    }

    @isTest
    static void twentyGroupMemberSearch(){
        
        X20_Groups_Member__c test20GroupMember = [SELECT Id, Account__r.Name, Group_Member_Number__c, Status__c FROM X20_Groups_Member__c LIMIT 1];
        System.debug('Test 20 Group Member: ' + test20GroupMember.Group_Member_Number__c);
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = '/services/apexrest/GroupAccount/' + test20GroupMember.Group_Member_Number__c;  //Request URL
        req.httpMethod = 'GET';//HTTP Request Type
        RestContext.request = req;
        RestContext.response= res;
        GroupAccountResponse result;
        
        Test.startTest();
            result = GroupAccountService.getAccountInfo();
        Test.stopTest();

        System.debug('Test Result: ' + result);
        Assert.isNotNull(result);
        Assert.areEqual('Success', result.status);
        Assert.areEqual('200', result.statusCode);
        Assert.areEqual('20 Group', result.groupType);
        Assert.areEqual(test20GroupMember.Account__r.Name, result.accountName);

    }

    @isTest
    static void benchmarkingGroupMemberSearch(){
        
        Proprietary_Account__c testGroupMember = [SELECT Id, Account__r.Name, Group_Member_Number__c, Status__c FROM Proprietary_Account__c LIMIT 1];
        System.debug('Test Benchmarking Group Member: ' + testGroupMember.Group_Member_Number__c);
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = '/services/apexrest/GroupAccount/' + testGroupMember.Group_Member_Number__c;  //Request URL
        req.httpMethod = 'GET';//HTTP Request Type
        RestContext.request = req;
        RestContext.response= res;
        GroupAccountResponse result;
        
        Test.startTest();
            result = GroupAccountService.getAccountInfo();
        Test.stopTest();

        System.debug('Test Result: ' + result);
        Assert.isNotNull(result);
        Assert.areEqual('Success', result.status);
        Assert.areEqual('200', result.statusCode);
        Assert.areEqual('Benchmarking Group', result.groupType);
        Assert.areEqual(testGroupMember.Account__r.Name, result.accountName);

    }


    @isTest
    static void invalidMemberSearch(){

        // When a group member number is sent to the API, the service should return no results and a 500 status code.
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        String bogusNumber = '9999-00'; // A group member number that doesn't exist in the system.
        req.requestURI = '/services/apexrest/GroupAccount/'+bogusNumber;  //Request URL with BAD group member number.
        req.httpMethod = 'GET';//HTTP Request Type
        RestContext.request = req;
        RestContext.response= res;
        GroupAccountResponse result;
        
        Test.startTest();
            result = GroupAccountService.getAccountInfo();
        Test.stopTest();

        System.debug('Test Result: ' + result);
        Assert.isNotNull(result);
        Assert.areEqual('Error', result.status);
        Assert.areEqual('500', result.statusCode);
        Assert.areEqual('No results found for group account number ' + bogusNumber, result.message);
        
    }
}