unpackaged/main/default/objects/Proprietary_Account__c/Proprietary_Account__c.object-meta.xml
<CustomObject>
    <label>Proprietary Account</label>
    <nameField>
        <label>Proprietary Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proprietary Accounts</relationshipLabel>
    <relationshipName>Proprietary_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_Number__c &amp; &quot;-&quot; &amp;   Member_Number_Code__c</formula>
    <label>Group Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Don&#39;t Bill</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_ID__r.Name &amp; &#39;-&#39; &amp;  Member_Number_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group / Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Global_Product_Service_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Global_Product_Service_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Active - Don&#39;t Bill</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Disconnected</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Suspended</fullName>
        <isActive>false</isActive>
        <label>Suspended</label>
    </customValue>
    <customValue>
        <fullName>Co-Member</fullName>
        <isActive>false</isActive>
        <label>Co-Member</label>
    </customValue>
    <customValue>
        <fullName>Honorary</fullName>
        <isActive>false</isActive>
        <label>Honorary</label>
    </customValue>
    <masterLabel>Global Product/Service Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/GroupAccountService.cls
@RestResource(urlMapping='/GroupAccount/*')
global with sharing class GroupAccountService {
    
    @HttpGet
    global static GroupAccountResponse getAccountInfo() {
        
        // Prepare the response
        GroupAccountResponse resp = new GroupAccountResponse();

        // Parse the group account number
        RestRequest request = RestContext.request;
        String memberNumber = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        System.debug('Member Number: ' + memberNumber);

        // Determine if 20 Group or Proprietary/Benchmarking Group number
        if( String.isNotBlank(memberNumber) ){
            memberNumber = String.escapeSingleQuotes(memberNumber); // SOQL Injection Attack protection.

            String webQuery = 'SELECT id, Name, Account__c, Account__r.Name, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Account__r.ShippingCountry, Group_Member_Number__c ' + 
                              'FROM X20_Groups_Member__c ' + 
                              'WHERE Status__c = \'Active\' and Group_Member_Number__c = :memberNumber';
            List<X20_Groups_Member__c> twentyGroupResults = Database.query(webQuery);
            /*list<X20_Groups_Member__c> twentyGroupResults = [SELECT id, Name, Account__c, Account__r.Name, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Account__r.ShippingCountry, Group_Member_Number__c  
                                                             FROM X20_Groups_Member__c 
                                                             WHERE Status__c = 'Active' and Group_Member_Number__c = :memberNumber];
            */
            if( !twentyGroupResults.isEmpty() ){
                System.debug('Member Number [' + memberNumber + '] belongs to a 20 Group Member');
                resp.statusCode = '200';
                resp.message = twentyGroupResults.size() + ' results found for group account number ' + memberNumber;
                resp.status = 'Success';
                X20_Groups_Member__c member = twentyGroupResults[0];
                resp.groupType = '20 Group';
                resp.groupMemberNumber = memberNumber;
                resp.accountName = member.Account__r.Name;
                resp.street = member.Account__r.ShippingStreet;
                resp.city = member.Account__r.ShippingCity;
                resp.state = member.Account__r.ShippingState;
                resp.zipCode = member.Account__r.ShippingPostalCode;
                resp.country = member.Account__r.ShippingCountry;
            } else {
                String propQuery =  'SELECT Id, Name, Account__c, Account__r.Name, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Account__r.ShippingCountry, Group_Member_Number__c ' + 
                                    'FROM Proprietary_Account__c ' + 
                                    'WHERE Status__c = \'Active\' and Group_Member_Number__c = :memberNumber';
                List<Proprietary_Account__c> propAcctResults = Database.query(propQuery);
                if( !propAcctResults.isEmpty() ){
                    System.debug('Member Number [' + memberNumber + '] is a Proprietary Account.');
                    resp.statusCode = '200';
                    resp.message = propAcctResults.size() + ' results found for group account number ' + memberNumber;
                    resp.status = 'Success';
                    Proprietary_Account__c member = propAcctResults[0];
                    resp.groupType = 'Benchmarking Group';
                    resp.groupMemberNumber = memberNumber;
                    resp.accountName = member.Account__r.Name;
                    resp.street = member.Account__r.ShippingStreet;
                    resp.city = member.Account__r.ShippingCity;
                    resp.state = member.Account__r.ShippingState;
                    resp.zipCode = member.Account__r.ShippingPostalCode;
                    resp.country = member.Account__r.ShippingCountry;
                } else {
                    System.debug('Member Number not found: ' + memberNumber);
                    resp.statusCode = '500';
                    resp.message = 'No results found for group account number ' + memberNumber;
                    resp.status = 'Error';
                }
            }
        }

        


        return resp;

    }
}