unpackaged/main/default/objects/Proprietary_Account__c/Proprietary_Account__c.object-meta.xml
<CustomObject>
    <label>Proprietary Account</label>
    <nameField>
        <label>Proprietary Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Proprietary Accounts</relationshipLabel>
    <relationshipName>Proprietary_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_Number__c &amp; &quot;-&quot; &amp;   Member_Number_Code__c</formula>
    <label>Group Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account__c/fields/Statement_Translation_Type__c.field-meta.xml
<CustomField>
    <fullName>Statement_Translation_Type__c</fullName>
    <label>Statement Translation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Statement_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>20 Groups Member Accounts</relationshipLabel>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Number__c</fullName>
    <formula>Group_ID__r.Name &amp; &#39;-&#39; &amp;  Member_Number_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group / Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Statement_Translation_Type__c.field-meta.xml
<CustomField>
    <fullName>Statement_Translation_Type__c</fullName>
    <label>Statement Translation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Statement_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Financial_Statement_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A_BUSCH</fullName>
    </customValue>
    <customValue>
        <fullName>ACURA</fullName>
    </customValue>
    <customValue>
        <fullName>ARNET</fullName>
    </customValue>
    <customValue>
        <fullName>AUDI</fullName>
    </customValue>
    <customValue>
        <fullName>AUTO_AUCTION</fullName>
    </customValue>
    <customValue>
        <fullName>AUTO_RECYCLING</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOMASTER</fullName>
    </customValue>
    <customValue>
        <fullName>AVB_1</fullName>
    </customValue>
    <customValue>
        <fullName>BEER_WHSL</fullName>
    </customValue>
    <customValue>
        <fullName>BENTLEY</fullName>
    </customValue>
    <customValue>
        <fullName>BETTER_BUSINESS</fullName>
    </customValue>
    <customValue>
        <fullName>BHPH_FIXED</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>BMW_MOTORCYCLE</fullName>
    </customValue>
    <customValue>
        <fullName>BTA_1</fullName>
    </customValue>
    <customValue>
        <fullName>BUICK</fullName>
    </customValue>
    <customValue>
        <fullName>BUY_PAY_HERE</fullName>
    </customValue>
    <customValue>
        <fullName>CA_ACURA</fullName>
    </customValue>
    <customValue>
        <fullName>CA_AUDI</fullName>
    </customValue>
    <customValue>
        <fullName>CA_BMW</fullName>
    </customValue>
    <customValue>
        <fullName>CA_CHEVROLET</fullName>
    </customValue>
    <customValue>
        <fullName>CA_CHRYSLER</fullName>
    </customValue>
    <customValue>
        <fullName>CA_COLLISION</fullName>
    </customValue>
    <customValue>
        <fullName>CA_FORD</fullName>
    </customValue>
    <customValue>
        <fullName>CA_GENESIS</fullName>
    </customValue>
    <customValue>
        <fullName>CA_HARLEY</fullName>
    </customValue>
    <customValue>
        <fullName>CA_HONDA</fullName>
    </customValue>
    <customValue>
        <fullName>CA_HYUNDAI</fullName>
    </customValue>
    <customValue>
        <fullName>CA_INFINITI</fullName>
    </customValue>
    <customValue>
        <fullName>CA_KIA</fullName>
    </customValue>
    <masterLabel>Financial Statement Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/GroupMemberUtility.cls
public with sharing class GroupMemberUtility {
    @InvocableMethod(Label='Get Also')
    public static List<String> getAlso(List<String> AcctId) {
        String alsos = '';
        Account a = [SELECT Id, Name, 
                        (SELECT Id, Group_Member_Number__c, Statement_Translation_Type__c FROM X20_Groups_Members__r), 
                        (SELECT Id, Group_Member_Number__c, Statement_Translation_Type__c FROM Proprietary_Accounts__r) 
                    FROM Account
                    WHERE Id =  :AcctId[0]];
        for(X20_Groups_Member__c gm : a.X20_Groups_Members__r) {
            alsos += gm.Group_Member_Number__c + ' ' + gm.Statement_Translation_Type__c + '\n';
        }
        for(Proprietary_Account__c pa : a.Proprietary_Accounts__r) {
            alsos += pa.Group_Member_Number__c + ' ' + pa.Statement_Translation_Type__c + '\n';
        }
        alsos = alsos.removeEnd('\n');
        alsos = alsos.abbreviate(255);
        return new List<String>{alsos};
    }
}