unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MarkAsAttendedEngagementController.cls
public with sharing class MarkAsAttendedEngagementController
{
    public ApexPages.StandardSetController ssc {get; private set;}
    public List<Engagement_Attendee__c> Attendees;
    public string previouspage;
    
    public MarkAsAttendedEngagementController(ApexPages.StandardSetController controller) {
        previouspage  = ApexPages.currentPage().getParameters().get('retURL');
        ssc = controller;
        System.Debug (controller.getSelected());
        System.Debug (controller.getSelected().size());
        if (ssc.getSelected().size() > 0)
        {
            Attendees = ssc.getSelected();
            for(Engagement_Attendee__c attendee : Attendees )
            {
                attendee.Attendance_Status__c = 'Attended';
            }
        }
    }
    
    public PageReference Save()
    {
        update Attendees;
        ApexPages.Action action = new ApexPages.Action('{!cancel}');
        return action.Invoke(); // Redirects to the previous page.
    }
}