unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Support_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Record_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/Finance_Accounts_Receivable__c.object-meta.xml
<CustomObject>
    <description>Used to store records generated when an Invoice is 1 day past the due date and unpaid from FFA</description>
    <label>Accounts Receivable</label>
    <nameField>
        <label>AR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Receivables</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_Accounts_Receivable__c/fields/Collection_Activity__c.field-meta.xml
<CustomField>
    <fullName>Collection_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Must be a Collection Activity Client Case</errorMessage>
        <filterItems>
            <field>Client_Support_Ticket__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Collection Activity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Client_Support_Ticket__c</referenceTo>
    <relationshipLabel>Accounts Receivable</relationshipLabel>
    <relationshipName>Accounts_Receivable</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Record_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Reynolds</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Re-Opened</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Accounting</fullName>
        <isActive>false</isActive>
        <label>Waiting on Accounting</label>
    </customValue>
    <description>All statuses of records</description>
    <masterLabel>Record Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/relateARsCollectionActivityTest.cls
@isTest(SeeAllData = true)
public class relateARsCollectionActivityTest{
	static testMethod void TestrelateARsCollectionActivity(){
		test.startTest();
		Client_Support_Ticket__c cse = [select id, Account__c
		                                from Client_Support_Ticket__c 
		                                where Status__c = 'In Progress'
		                                limit 1];
		list<Finance_Accounts_Receivable__c> ARs = [select id
		                                            from Finance_Accounts_Receivable__c 
		                                            where Collection_Activity__c = :cse.Id];
		for (Finance_Accounts_Receivable__c AR : ARs){
			ar.Collection_Activity__c = null;
		}
		update ARs;
		relateARsCollectionActivity.vars var = new relateARsCollectionActivity.vars();
		var.caId = cse.id;
		var.accId = cse.Account__c;
		var.daysOutstanding = 35;
		List<relateARsCollectionActivity.vars> vars = new List<relateARsCollectionActivity.vars>();
		vars.add(var);
		try{
			relateARsCollectionActivity.relateToAllARs(vars);
		} catch (exception er){
			system.debug(er);
		}
		test.stopTest();
	}
}