unpackaged/main/default/objects/Client_Support_Ticket__c/Client_Support_Ticket__c.object-meta.xml
<CustomObject>
    <description>NCM Client Support ticketing object</description>
    <label>Client Case</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Client_Support_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Record_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Record_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Reynolds</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Re-Opened</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Ongoing</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Accounting</fullName>
        <isActive>false</isActive>
        <label>Waiting on Accounting</label>
    </customValue>
    <description>All statuses of records</description>
    <masterLabel>Record Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/createCollectionActivityTest.cls
@isTest(SeeAllData = true)
public class createCollectionActivityTest
{
	public static testMethod void TestcreateCollectionActivity()
	{
		Test.startTest();
        user u = 
		[
			SELECT Id
			FROM User
			WHERE 
				IsActive = true AND 
				Id IN 
				(
					SELECT UserId
					FROM UserPackageLicense
					WHERE PackageLicense.NamespacePrefix = 'c2g'
				) AND 
				Id IN 
				(
					SELECT c2g__User__c
					FROM c2g__codaUserCompany__c
				)
			ORDER BY LastName DESC
			LIMIT 1
		];

		System.runAs(u){
			Try{
				Client_Support_Ticket__c clientCase = 
				[
					SELECT Id
					FROM Client_Support_Ticket__c
					WHERE 
						Status__c = 'Open' AND 
						RecordTypeId = '0124A000001NTPoQAO'
					LIMIT 1
				];
				Database.delete( clientCase );
			} Catch (exception er){
				system.debug(er);
			}

			createCollectionActivity testSche = new createCollectionActivity(  );
			testSche.execute(null);

		}
		test.stopTest();
	}
}