unpackaged/main/default/objects/CZ_WebHook__e/CZ_WebHook__e.object-meta.xml
<CustomObject>
    <label>CZ_WebHook</label>
    <pluralLabel>CZ_WebHooks</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CZ_WebHook__e/fields/amount_with_out_surcharge__c.field-meta.xml
<CustomField>
    <fullName>amount_with_out_surcharge__c</fullName>
    <label>amount_with_out_surcharge</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/surcharge_amount_value__c.field-meta.xml
<CustomField>
    <fullName>surcharge_amount_value__c</fullName>
    <label>surcharge_amount_value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/tnxAmount__c.field-meta.xml
<CustomField>
    <fullName>tnxAmount__c</fullName>
    <label>tnxAmount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/tnxID__c.field-meta.xml
<CustomField>
    <fullName>tnxID__c</fullName>
    <label>tnxID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/tnxInvoiceId__c.field-meta.xml
<CustomField>
    <fullName>tnxInvoiceId__c</fullName>
    <label>tnxInvoiceId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/tnxInvoiceRef__c.field-meta.xml
<CustomField>
    <fullName>tnxInvoiceRef__c</fullName>
    <label>tnxInvoiceRef</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/tnxStatus__c.field-meta.xml
<CustomField>
    <fullName>tnxStatus__c</fullName>
    <label>tnxStatus</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CZ_WebHook__e/fields/tnxType__c.field-meta.xml
<CustomField>
    <fullName>tnxType__c</fullName>
    <label>tnxType</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CZWebhook__c/CZWebhook__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CZWebhook</label>
</CustomObject>

unpackaged/main/default/objects/CZWebhook__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webhook_Log__c/Webhook_Log__c.object-meta.xml
<CustomObject>
    <label>ChargeZoom Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Webhook Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChargeZoom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Webhook_Log__c/fields/ChargeZoomId__c.field-meta.xml
<CustomField>
    <fullName>ChargeZoomId__c</fullName>
    <externalId>true</externalId>
    <label>ChargeZoom Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webhook_Log__c/fields/data__c.field-meta.xml
<CustomField>
    <fullName>data__c</fullName>
    <label>data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/ChargeZoomWHService.cls
@RestResource(urlMapping='/ChargeZoom/*')
global class ChargeZoomWHService {
    
    @HttpPost
    global static void processPayment() {
        String secret = CZWebhook__c.getInstance().Token__c;
        RestRequest req = RestContext.request;
        RestResponse resp = RestContext.response;
        
        //check for correct token 
        if(req.headers.containsKey('Token') && req.headers.get('Token') == secret) {
            System.debug('Authenticated');
            System.debug(req.remoteAddress);
        } else {
            resp.statusCode = 401;
            resp.responseBody = Blob.valueOf('{"status":"error","message":"Not Authorized"}');
            return;
        }

        //log webhook payload
        Webhook_Log__c whl = new Webhook_Log__c();
        try {
            String reqBody = req.requestBody.toString();
            
            whl.source__c = 'ChargeZoomWHService';
            whl.data__c = reqBody;
            
            CZ_WebhookPayload pl = (CZ_WebhookPayload) JSON.deserializeStrict(reqBody, CZ_WebhookPayload.class);
            whl.ChargeZoomId__c = pl.data.tnxID;
            resp.statusCode = 200;
            resp.responseBody = Blob.valueOf('Success');

            //Create list of possible success messages from custom label
            List<String> successes = System.Label.CZSuccesses.toUpperCase().split(',');
            List<String> successes2 = new List<String>();
            for(String s : successes) {
                successes2.add(s.normalizeSpace());
            }

            //check if not a successful payment
            if(!pl.data.tnxType.equalsIgnoreCase('Sale') || !successes2.contains(pl.data.tnxStatus.toUpperCase())) {
                return;
            }
            CZ_WebHook__e whEvent = convertToEvent(pl.data);            

            //check if a webhook with the same txId has been processed or not.            
            String qry = 'SELECT Id FROM Webhook_Log__c WHERE ChargeZoomId__c = \'' + pl.data.tnxID + '\'';
            System.debug('~~~qry: ' + qry);

            List<Webhook_Log__c> existing = Database.query(qry);
            System.debug('~~~existing: ' + existing);

            if(existing.isEmpty()) {
                Database.SaveResult dsr = EventBus.publish(whEvent);
                if(!dsr.isSuccess()) {
                    resp.statusCode = 400;
                    resp.responseBody = Blob.valueOf('{"error": "' + dsr.getErrors()[0].getMessage() + '"}');
                    System.debug(dsr.getErrors()[0].getMessage());
                    whl.source__c ='Bad Webhook';
                }
            }            
        } catch (Exception ex) {
            resp.statusCode = 400;
            resp.responseBody = Blob.valueOf('{"error": "' + ex.getMessage() + '"}');
            System.debug(ex.getMessage());
            whl.source__c ='Bad Webhook';
        }
        insert(whl);
    }

    private static CZ_WebHook__e convertToEvent(CZTransactionData tran) {
        PaymentModel.CZTnxCustFields custFields = new PaymentModel.CZTnxCustFields();
            if(tran.tnxCustomDataFields != null) {
                custFields = (PaymentModel.CZTnxCustFields) JSON.deserialize(tran.tnxCustomDataFields, PaymentModel.CZTnxCustFields.class);            
            } 
            CZ_WebHook__e whEvent = new CZ_WebHook__e();
            whEvent.tnxAmount__c = tran.tnxAmount;
            whEvent.tnxID__c = tran.tnxID;
            //Since we are only sending successful transactions to this method, Change the status to match what ApplyPaymentsBatch is expecting.
            whEvent.tnxStatus__c = 'Success'; 
            whEvent.tnxType__c = tran.tnxType;
            whEvent.tnxInvoiceId__c = String.isNotBlank(custFields.invoice_number) ? custFields.invoice_number : tran.tnxInvoiceId; 
            whEvent.tnxInvoiceRef__c = tran.tnxInvoiceRef;
            whEvent.amount_with_out_surcharge__c = custFields.amount_with_out_surcharge;
            whEvent.surcharge_amount_value__c = custFields.surcharge_amount_value;
            return whEvent;
    }

    global class CZ_WebhookPayload {
        global String type {get;set;}
        global CZTransactionData data {get;set;}
    }

    global class CZTransactionData {
        global String tnxID {get;set;}
        global Decimal tnxAmount {get;set;}
        global String tnxDate {get;set;}
        global String tnxStatus {get;set;}
        global String tnxCustomerId {get;set;}
        global String tnxType {get;set;}
        global String tnxGateway {get;set;}
        global String tnxGatewayId {get;set;}
        global Integer tnxPaymentMethod {get;set;}
        global String tnxInvoiceId {get;set;}
        global String tnxInvoiceRef {get;set;}
        global Integer tnxMerchantId {get;set;}
        global String tnxCustomDataFields {get;set;}
        global String id {get;set;}
    }
    
}