unpackaged/main/default/objects/Opportunity/fields/Contract_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Months__c</fullName>
    <label>Contract Months</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <description>Monthly Recurring Revenue</description>
    <inlineHelpText>Monthly Recurring Revenue</inlineHelpText>
    <label>MRR</label>
    <summarizedField>OpportunityLineItem.MRR__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NRR__c.field-meta.xml
<CustomField>
    <fullName>NRR__c</fullName>
    <description>Non-Recurring Revenue</description>
    <inlineHelpText>Non-Recurring Revenue</inlineHelpText>
    <label>NRR</label>
    <summarizedField>OpportunityLineItem.NRR__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TCV__c.field-meta.xml
<CustomField>
    <fullName>TCV__c</fullName>
    <description>Total Contract Value</description>
    <inlineHelpText>Total Contract Value</inlineHelpText>
    <label>TCV</label>
    <summarizedField>OpportunityLineItem.TCV__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Contract_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Months__c</fullName>
    <label>Contract Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/MRR__c.field-meta.xml
<CustomField>
    <fullName>MRR__c</fullName>
    <label>MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/NRR__c.field-meta.xml
<CustomField>
    <fullName>NRR__c</fullName>
    <label>NRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Locked_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Locked_Frequency__c</fullName>
    <inlineHelpText>If defined here, the billing frequency will be pre-populated when a Billing Product is being setup.</inlineHelpText>
    <label>Locked Frequency?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PopulateOppProdRevFields.cls
global class PopulateOppProdRevFields implements Database.Batchable<SObject>{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            'SELECT Id, Quantity, UnitPrice, Contract_Months__c, Product2.Locked_Frequency__c FROM OpportunityLineItem WHERE ' +
            'Opportunity.IsClosed = false OR Opportunity.CreatedDate = THIS_YEAR' 
        ); 
    }

    global void execute(Database.BatchableContext BC, List<OpportunityLineItem> scope) {
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        for(OpportunityLineItem oli : scope) {
            OpportunityLineItem newOLI = new OpportunityLineItem(Id = oli.Id);
            if(oli.Product2.Locked_Frequency__c == 'Monthly') {
                newOLI.MRR__c = oli.UnitPrice * oli.Quantity;
            } else if(oli.Product2.Locked_Frequency__c == 'Quarterly') {
                newOLI.MRR__c = oli.UnitPrice * oli.Quantity / 3;
            }
            if(oli.Product2.Locked_Frequency__c != 'Monthly' && oli.Product2.Locked_Frequency__c != 'Quarterly') {
                newOLI.NRR__c = oli.UnitPrice * oli.Quantity;
            }
            if(oli.Contract_Months__c != null) {
                newOLI.TCV__c = newOLI.MRR__c * oli.Contract_Months__c;
            }
            if(newOLI.MRR__c != null || newOLI.NRR__c != null || newOLI.TCV__c != null) {
                oliList.add(newOLI);
            }

            if(oliList.size() > 0) {
                List<Database.SaveResult> dsrList = Database.update(oliList, false);
                Logger.logErrorList('PopulateOppProdRevFields', dsrList, oliList); 
            }
        }
    } 
    
    global void finish(Database.BatchableContext BC) {}
}