unpackaged/main/default/objects/Opportunity/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>20 Group Only - Do Not Use for Proprietary/Benchmark</inlineHelpText>
    <label>Group Id</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Opportunities (Group Id)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/X20_Groups_Member__c.object-meta.xml
<CustomObject>
    <description>Member card for 20 Group members</description>
    <label>20 Group Member Account</label>
    <nameField>
        <label>20 Group Member Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups Member Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group Number</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>X20_Groups_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Groups_Member__c/fields/Part_of_Executive_Committee__c.field-meta.xml
<CustomField>
    <fullName>Part_of_Executive_Committee__c</fullName>
    <label>Part of Executive Committee?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Binary</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Binary.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Yes or No picklist</description>
    <masterLabel>Binary</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/createContactRolesTest.cls
@isTest (SeeAllData=true)
public class createContactRolesTest {
    static testMethod void TestcreateContactRoles(){
        Opportunity opp = [select id from Opportunity limit 1];
        X20_Groups_Member__c mem = [select id, Group_ID__c from X20_Groups_Member__c where Part_of_Executive_Committee__c = 'Yes' limit 1];
        
        createContactRoles.vars var = new createContactRoles.vars();
        var.oppId = opp.id;
        var.objNme = 'X20_Groups_Member__c';
        var.soqlWhere = 'Group_ID__c = \'' + mem.Group_ID__c + '\' and Part_of_Executive_Committee__c = \'Yes\' ';
        var.conFldNme = 'Member_Name__c';
        var.roleType = '';
        
        List<createContactRoles.vars> vars = new List<createContactRoles.vars>();
        vars.add(var);
        
        Test.startTest();
        
        try{
            createContactRoles.createConRoles(vars);
        } catch(Exception er){
            system.debug(er);
        }
        
        Test.stopTest();
    }
}