unpackaged/main/default/objects/Opportunity/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <description>Indicates if all the line items for this opportunity have been invoiced.</description>
    <formula>IF( Line_Item_Not_Invoiced__c = 0, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if all the line items for this opportunity have been invoiced.</inlineHelpText>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OEM_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>OEM_Account_ID__c</fullName>
    <formula>OEM_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OEM Account ID (Code)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <formula>IF(Invoiced__c == true, false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/createFFinvoiceTest.cls
@isTest (SeeAllData = true)
public class createFFinvoiceTest {
	public static testMethod void testCreateFFinvoice() {
        test.startTest();
        PageReference pageRef = Page.createFFinvoice;
        Test.setCurrentPage(pageRef);
        
        OpportunityLineItem oppLnItm = [select id, OpportunityId 
                                        from OpportunityLineItem 
                                        where Invoiced__c = false and Ready_to_Invoice__c = true and Opportunity.OEM_Account_ID__c = null and Opportunity.Owner.IsActive = true
                                       	limit 1];
        opportunity opp = [select id from opportunity where id = :oppLnItm.OpportunityId];
        ApexPages.currentPage().getParameters().put('id', opp.id);

        apexpages.standardcontroller stdController = new ApexPages.StandardController(opp);
        createFFinvoiceEXT controller = new createFFinvoiceEXT(stdController);
        
        list<OpportunityLineItem> lnItms = controller.getoppLnItms();
        controller.createInvoice();
        delete lnItms;
        controller.createInvoice();
        test.stopTest();
    }
}