unpackaged/main/default/objects/Opportunity/fields/NCMi_Paid_Seat__c.field-meta.xml
<CustomField>
    <fullName>NCMi_Paid_Seat__c</fullName>
    <description>How many NCMi Paid Seats are on this Opportunity</description>
    <label>NCMi Paid Seat</label>
    <summaryFilterItems>
        <field>OpportunityLineItem.NCMi_Paid_Seat2__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <formula>PricebookEntry.Product2.Core_Product__c</formula>
    <label>Core Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Departments</inlineHelpText>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/NCMi_Paid_Seat2__c.field-meta.xml
<CustomField>
    <fullName>NCMi_Paid_Seat2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>populated by automation with the value of the formula field NCMi Paid Seat</description>
    <label>NCMi Paid Seat</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/NCMi_Paid_Seat__c.field-meta.xml
<CustomField>
    <fullName>NCMi_Paid_Seat__c</fullName>
    <formula>OR(
   ISPICKVAL( PricebookEntry.Product2.Type__c , &#39;Paid Seat&#39;),
   ISPICKVAL( PricebookEntry.Product2.Type__c , &#39;GMEP&#39;),
   ISPICKVAL( PricebookEntry.Product2.Type__c , &#39;Training Credits&#39;)
)</formula>
    <label>NCMi Paid Seat</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Core_Product__c.field-meta.xml
<CustomField>
    <fullName>Core_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow Provisioning Required?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/CZ_ItemId__c.field-meta.xml
<CustomField>
    <fullName>CZ_ItemId__c</fullName>
    <externalId>true</externalId>
    <label>CZ ItemId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Product is related to this Dimension</description>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Locked_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Locked_Frequency__c</fullName>
    <inlineHelpText>If defined here, the billing frequency will be pre-populated when a Billing Product is being setup.</inlineHelpText>
    <label>Locked Frequency?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/NCM_Authorized_Products__c.field-meta.xml
<CustomField>
    <fullName>NCM_Authorized_Products__c</fullName>
    <description>NCM Products that this billing account is authorized to be used for payment.</description>
    <label>NCM Authorized Products</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NCM_Authorized_Products</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Value__c.field-meta.xml
<CustomField>
    <fullName>Product_Value__c</fullName>
    <inlineHelpText>Value of the core product being sold.</inlineHelpText>
    <label>Product Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>Production_Run_Type__c</fullName>
    <label>Production Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Seminar</fullName>
            </value>
            <value>
                <fullName>New Member</fullName>
            </value>
            <value>
                <fullName>New Proprietary Member</fullName>
            </value>
            <value>
                <fullName>Special Composite</fullName>
            </value>
            <value>
                <fullName>Retail Ops</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>PTA</fullName>
            </value>
            <value>
                <fullName>Trend</fullName>
            </value>
            <value>
                <fullName>FIDO</fullName>
            </value>
            <value>
                <fullName>PPP</fullName>
            </value>
            <value>
                <fullName>PAR</fullName>
            </value>
            <value>
                <fullName>Three-Year Comp</fullName>
            </value>
            <value>
                <fullName>CIP - Org Meeting</fullName>
            </value>
            <value>
                <fullName>Retail Ops Proprietary</fullName>
            </value>
            <value>
                <fullName>HealthCheck</fullName>
            </value>
            <value>
                <fullName>ConSept New Member</fullName>
            </value>
            <value>
                <fullName>ConSept New Proprietary Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Record_Provisioning__c.field-meta.xml
<CustomField>
    <fullName>Record_Provisioning__c</fullName>
    <label>Flow Provisioning Path</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Core_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>aXcessa Store</fullName>
            </value>
            <value>
                <fullName>Cohort Student</fullName>
            </value>
            <value>
                <fullName>Echo</fullName>
            </value>
            <value>
                <fullName>Group Member</fullName>
            </value>
            <value>
                <fullName>NCMi Seat</fullName>
            </value>
            <value>
                <fullName>Proprietary Account</fullName>
            </value>
            <value>
                <fullName>Proprietary Group</fullName>
            </value>
            <value>
                <fullName>Proprietary Master Group</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Subscription Term Transition</fullName>
            </value>
            <value>
                <fullName>Training Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Shipped_Product__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped Product?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/NCMi.recordType-meta.xml
<RecordType>
    <fullName>NCMi</fullName>
    <active>true</active>
    <description>NCM Institute</description>
    <label>NCMi</label>
</RecordType>

unpackaged/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/NCM_Authorized_Products.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>20 Groups</fullName>
    </customValue>
    <customValue>
        <fullName>aXcessa</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcheck</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Cohort</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Paid Seats</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>NCMi Training Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Proprietary</fullName>
    </customValue>
    <customValue>
        <fullName>Single Member Products</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Performance Solutions</fullName>
    </customValue>
    <masterLabel>NCM Authorized Products</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OpportunityProductTrigger_Test.cls
@isTest
private class OpportunityProductTrigger_Test {
    @TestSetup
    private static void makeData() {
        Account act = new Account(Name = 'Test Account');
        insert(act);

        Id pricebookId = Test.getStandardPricebookId();
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opp', 
            AccountId = act.Id, 
            StageName = 'Pending Sale',
            CloseDate = Date.today(),
            Pricebook2Id = pricebookId
        );
        insert(opp);

        c2g__codaDimension1__c testDimension1 = new c2g__codaDimension1__c(
            Name = 'Test Dimension1',
            c2g__ReportingCode__c = '2000'//,
            //Conductor_CC_Email__c = 'mdemeglio@ncmassociates.com'
        );
        insert(testDimension1);
        
        Product2 prod = new Product2(
            IsActive = true,
            RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('NCMi').getRecordTypeId(),
            Name = 'Test NCMi Seat Product',
            Dimension_1__c = testDimension1.Id,
            Product_Value__c = 500.00,
            Production_Run_Type__c = 'Not Applicable',
            Family = 'NCM Institute',
            Locked_Frequency__c = 'Quarterly',
            Shipped_Product__c = True, // Required for trigger entry criteria!
            CZ_ItemId__c = 'PRO-111',
            Core_Product__c = true,
            Record_Provisioning__c = 'NCMi Seat',
            NCM_Authorized_Products__c = 'NCMi Paid Seats'
        );
        insert(prod);

        PricebookEntry pbe = new PricebookEntry(
            IsActive = true,
            UnitPrice = 99.99,
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id
        );
        insert(pbe);

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 100.00
        );
        insert(oli);
        OpportunityLineItem oliQueried = [SELECT Id, NCMi_Paid_Seat2__c FROM OpportunityLineItem LIMIT 1];
        System.debug('Line Item Paid Seat: ' +  oliQueried.NCMi_Paid_Seat2__c);
        Opportunity oppQueried = [SELECT Id, NCMi_Paid_Seat__c FROM Opportunity LIMIT 1];
        System.debug('Opportunity Paid Seat: ' +  oppQueried.NCMi_Paid_Seat__c);
    }


    @isTest
    static void deleteTest() {
        delete([SELECT Id FROM OpportunityLineItem LIMIT 1]);
        List<OpportunityLineItem> olis = [SELECT Id FROM OpportunityLineItem];
        Assert.areEqual(0, olis.size());
    }

    @isTest
    static void deleteTest2() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.StageName = 'Invoice Sent';
        update(opp);
        List<OpportunityLineItem> olis = [SELECT Id FROM OpportunityLineItem];
        try {
            delete(olis[0]);
        } catch (Exception ex) {
            System.debug('ex.getTypeName: ' + ex.getTypeName());
            Assert.areEqual('System.DmlException', ex.getTypeName());
        }        
    }

    @isTest
    static void changeTest() {
        OpportunityLineItem oli = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        oli.Quantity = 2;
        update(oli);
        OpportunityLineItem oli2 = [SELECT Id, Quantity FROM OpportunityLineItem LIMIT 1];
        Assert.areEqual(2, oli2.Quantity);
    }

    @isTest
    static void changeTest2() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.StageName = 'Invoice Sent';
        update(opp);
        OpportunityLineItem oli = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        try {
            oli.Quantity = 2;
            update(oli);
        } catch (Exception ex) {
            System.debug('ex.getTypeName: ' + ex.getTypeName());
            Assert.areEqual('System.DmlException', ex.getTypeName());
        }        
    }
}