unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/Billing_Configuration__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Billing Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Billing_Product_WHERE__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_WHERE__c</fullName>
    <label>Billing Product WHERE</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Custom_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Custom_Invoice_Date__c</fullName>
    <label>Custom Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Invoice_Description__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Description__c</fullName>
    <label>Invoice Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/One_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>One Time Run? (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Recurring_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Day__c</fullName>
    <label>Recurring Day</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_CEM__c.field-meta.xml
<CustomField>
    <fullName>Split_on_CEM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on CEM?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Split_on_Dim_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on Dim 2?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/Billing_Configuration_Detail__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration Detail</label>
    <nameField>
        <displayFormat>BCD-{0000000000}</displayFormat>
        <label>Billing Configuration Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configuration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Billing_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Billing_Configuration__c</fullName>
    <label>Billing Configuration</label>
    <referenceTo>Billing_Configuration__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/CEM_Id__c.field-meta.xml
<CustomField>
    <fullName>CEM_Id__c</fullName>
    <label>CEM Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_URL__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_URL__c</fullName>
    <formula>&quot;/&quot; &amp; Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Product URL (Code)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/CEM_Id__c.field-meta.xml
<CustomField>
    <fullName>CEM_Id__c</fullName>
    <formula>Product_Service__r.CM_Id__c</formula>
    <label>CM Id (Code)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/CEM_Name__c.field-meta.xml
<CustomField>
    <fullName>CEM_Name__c</fullName>
    <formula>Product_Service__r.CM_Name__c</formula>
    <label>CM Name (Code)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1_Name__c</fullName>
    <formula>Dimension_1__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 1 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2_Name__c</fullName>
    <formula>Dimension_2__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 2 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_3_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3_Name__c</fullName>
    <formula>Dimension_3__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 3 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_4_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4_Name__c</fullName>
    <formula>Dimension_4__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 4 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <formula>Quantity__c *  Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/billingConfigurationController.cls
public with sharing class billingConfigurationController
{
	//  returns an Aggregate list of billing accounts to the lightning component. Currently aggregates the count of billing products and the sum of the total value
	//  these are iterated over in the list on the left for the billing accounts to help identify irregularities
	@AuraEnabled
	public static List<AggregateResult> getBillAccs(string billProdWhere)
	{
		string query = 'SELECT SUM(Total_Value__c)total, COUNT(Id)recs, Billing_Account__c, Billing_Account__r.Name ';
		query = query + 'FROM Billing_Product__c ';
		query = query + billProdWhere;
		query = query + 'GROUP BY Billing_Account__c , Billing_Account__r.Name ';
		query = query + 'ORDER BY Billing_Account__r.Name ';
		System.debug('BILLING CONFIGURATOR QUERY: ' + query);
		
		List<AggregateResult> bAccs = Database.query(query);
		if ( bAccs.size() > 0 )
		{
			return bAccs;
		}
		else
		{
			return null;
		}
	}

	//  when the user clicks the select button on a bAcc Card, it will pass the bAccId to the parent component.
	//  It returns the Billing Account with all the appropriate billing products to be displayed
	@AuraEnabled
	public static Billing_Account__c getSelectedBillAcc(id bAccId, string billProdWhere)
	{
		string query = 'SELECT Name, Id, Primary_Contact__c, Primary_Contact__r.Name, Billing_Street__c, Billing_City__c, Billing_State_Province__c, Billing_Country__c, Billing_Zip_Postal_Code__c, ';
		query = query + '(SELECT Name, Id, Billing_Frequency__c, CEM_Id__c, CEM_Name__c, Description__c, Quantity__c, Total_Value__c, Value__c, Billing_Product_URL__c, Product_Name__c, Dimension_1_Name__c, Dimension_2_Name__c, Dimension_3_Name__c, Dimension_4_Name__c ';
		query = query + 'FROM Billing_Products__r ';
		query = query + billProdWhere + ') ';
		query = query + 'FROM Billing_Account__c ';
		query = query + 'WHERE Id = \'' + bAccId + '\'';
		Billing_Account__c bAcc = Database.query(query);
		return bAcc;
	}

	//  this method will run the accounting bridge batch manually
	//  taking the values provided it will create the temporary billing configuration record and the temporary billing configuration detail records
	//  this will return the batch Id of the scheduled batch
	@AuraEnabled
	public static string runManualBatch(string billProdWhere, Boolean splitDim2, Boolean splitCEM, Date invDate, string invDesc)
	{

		List<Billing_Configuration__c> delBConfigs = new List<Billing_Configuration__c>();
		delBConfigs = [SELECT Id
		               FROM Billing_Configuration__c];
		if ( delBConfigs.size() > 0 )
		{
			Database.delete( delBConfigs, FALSE );
		}

		Billing_Configuration__c billingConfig = new Billing_Configuration__c(  );
		billingConfig.One_Time_Run__c = true;
		billingConfig.Recurring_Day__c = Date.today(  ).day();
		billingConfig.Billing_Product_WHERE__c = billProdWhere;
		billingConfig.Split_on_Dim_2__c = splitDim2;
		billingConfig.Split_on_CEM__c = splitDim2;
		billingConfig.Invoice_Description__c = invDesc;
		if ( invDate != Date.today(  ) && invDate != null )
		{
			billingConfig.Custom_Invoice_Date__c = invDate;
		}
		insert billingConfig;
		List<Billing_Configuration__c> bConfigs = new List<Billing_Configuration__c>();
		bConfigs.add(billingConfig);
		list<Billing_Configuration_Detail__c> bConfigDets = billingProductDaily.createBillConfigDets(bConfigs);
		Id batchId;
		if ( bConfigDets.size() > 0 && !test.isRunningTest() )
		{
			insert bConfigDets;
			batchAccountingBridge batchBrd = new batchAccountingBridge(  );
			batchId = Database.executebatch(batchBrd, 1);
		}
		return batchId;
	}

	//  this method returns the status and numbers of the batch. it is called continuously when it is showing the monitor screen after running the manual batch
	@AuraEnabled
	public static AsyncApexJob getBatchStatus(Id batchId)
	{
		AsyncApexJob aaj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors, ExtendedStatus, MethodName, CreatedBy.Name, CreatedDate
		                    FROM AsyncApexJob
		                    WHERE ID = :batchId];
		return aaj;
	}
}