unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/batchBillingProductConversionTest.cls
@isTest(SeeAllData = true)
public class batchBillingProductConversionTest
{
	public static testMethod void TestbatchBillingProductConversion()
	{
		Test.startTest();

		user u = [SELECT id
		          FROM User
		          WHERE id in (SELECT UserId
		                       FROM UserPackageLicense
		                       WHERE PackageLicense.NamespacePrefix = 'c2g')
				  AND Profile.Name = 'NCM Accounting'
		          LIMIT 1];

		System.runas(u)
		{

			Billing_Product__c bProd;
			try
			{
				bProd = [SELECT Id, Dimension_1__c, Billing_Account__c
				         FROM Billing_Product__c
				         WHERE Next_Billing_Date__c <= TODAY and Billing_Product_Status__c = 'Active' and Dimension_1__c<>null and Billing_Account__c<>null
				         LIMIT 1];
			}
			catch ( Exception er )
			{
				system.debug(er);
				bProd = [SELECT Id, Dimension_1__c, Billing_Account__c
				         FROM Billing_Product__c
				         WHERE Billing_Product_Status__c = 'Active' and Dimension_1__c<>null and Billing_Account__c<>null
				         LIMIT 1];
				bProd.Next_Billing_Date__c = Date.today(  ).addDays(-1);
				Database.update( bProd );
			}

			list<Billing_Product__c> bProds = [SELECT Id
			                                   FROM Billing_Product__c
			                                   WHERE Next_Billing_Date__c <= TODAY and Billing_Product_Status__c = 'Active' and Billing_Account__c = :bProd.Billing_Account__c and id<> :bProd.Id];

			for ( Billing_Product__c bPrd : bProds )
			{
				bPrd.Billing_Product_Status__c = 'Inactive';
			}
			update bProds;

			DescribeSObjectResult describeResult = Billing_Product__c.getSObjectType().getDescribe();
			List<String> fieldNames = new List<String>(describeResult.fields.getMap().keySet());
			string qry = 
				' SELECT ' + String.join(fieldNames, ', ')+' FROM ' + describeResult.getName()+' WHERE Next_Billing_Date__c <= :tDay and Billing_Product_Status__c = \'Active\' and' + 
				' Billing_Account__c = \'' + bProd.Billing_Account__c + '\' and' + 
				' Dimension_1__c = \'' + bProd.Dimension_1__c + '\'';

			accountingBridgeControllers accBrdCon = new accountingBridgeControllers(  );
			c2g__codaInvoice__c inv = accBrdCon.createInvoice(bProd.Billing_Account__c, Date.Today(  ), null, null);
			insert inv;

			batchBillingProductConversion batchBprod = new batchBillingProductConversion( qry, true, inv.id );
			database.executebatch(batchBprod, 50);
		}
		test.stopTest();
	}
}