unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Expense__c/Engagement_Expense__c.object-meta.xml
<CustomObject>
    <label>Engagement Expense</label>
    <nameField>
        <displayFormat>EXP-{YYYY}{MM}{DD}:{00000000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Payable_Account__c.field-meta.xml
<CustomField>
    <fullName>Payable_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payable Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Account__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Payable Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/payableBridgeTest.cls
@IsTest
public with sharing class payableBridgeTest{
    
    @testSetup
    static void setupData(){
        SampleDataFactory.createData();
    }
    
	static testMethod void testPayableBridge(){

		Test.startTest();

		User usr = [select id
		            from User
		            where Profile.Name = 'System Administrator' AND isActive = True
		            limit 1];
		System.runAs(usr)
		{

			List<AggregateResult> aggResults = payableBridge.getPayAccs(null, null, 'None');
			string payAccId;
			if ( aggResults != null )
			{
				payAccId = ( string )aggResults.get(0).get('Payable_Account__c');
			}
			else
			{
				payAccId = [select 
				                  id
				            from Billing_Account__c
				            where recordType.Name = 'Payable Account'
				            limit 1].id;
			}

			id dim1Id = [SELECT 
			                   Id
			             FROM c2g__codaDimension1__c
			             LIMIT 1].Id;
			id dim2Id = [SELECT 
			                   Id
			             FROM c2g__codaDimension2__c
			             LIMIT 1].Id;

			Billing_Account__c payAcc = payableBridge.getPayAcc(payAccId);
			c2g__codaPurchaseInvoice__c pin = payableBridge.buildPIN(payAcc);
			List<Engagement_Expense__c> exps = payableBridge.getExpenses(payAccId, null, null, 'None');
			if ( exps == null || exps.size() > 0 )
			{
				exps = new List<Engagement_Expense__c>();
				Engagement_Expense__c exp = new Engagement_Expense__c(  );
				exp.Dimension_1__c = dim1Id;
				exp.Dimension_2__c = dim2Id;
				exps.add(exp);
			}


			try
			{
				payableBridge.createPIN(pin, exps, true);
			}
			catch ( Exception er )
			{
				system.debug(er);
			}

		}
		Test.stopTest();
	}
}