unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needing Validation</fullName>
                <default>true</default>
                <label>Needing Validation</label>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Credit Card Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The NCM Employee&#39;s Dimension 2 record in Financial Force</inlineHelpText>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>to update the city go to the hotel that is listed in the hotel/Meeting Location field and update the city on the physical address</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country(old)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Dimension_4__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 4</label>
    <referenceTo>c2g__codaDimension4__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State(old)</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/Engagement_Expense__c.object-meta.xml
<CustomObject>
    <label>Engagement Expense</label>
    <nameField>
        <displayFormat>EXP-{YYYY}{MM}{DD}:{00000000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1_Name__c</fullName>
    <formula>Dimension_1__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 1 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2_Name__c</fullName>
    <formula>Dimension_2__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 2 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_3__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 3</label>
    <referenceTo>c2g__codaDimension3__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_3_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3_Name__c</fullName>
    <formula>Dimension_3__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 3 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_4__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 4</label>
    <referenceTo>c2g__codaDimension4__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Dimension_4_Name__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4_Name__c</fullName>
    <formula>Dimension_4__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 4 Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Discarded__c.field-meta.xml
<CustomField>
    <fullName>Discarded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use this if the expense needs to be denoted as invalid for any reason.</inlineHelpText>
    <label>Discarded?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Expense_URL__c.field-meta.xml
<CustomField>
    <fullName>Expense_URL__c</fullName>
    <formula>&quot;/&quot; &amp;  Id</formula>
    <label>Expense URL</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/General_Ledger_ID__c.field-meta.xml
<CustomField>
    <fullName>General_Ledger_ID__c</fullName>
    <label>General Ledger ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/GL_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Name__c</fullName>
    <label>GL Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Payable_Account__c.field-meta.xml
<CustomField>
    <fullName>Payable_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payable Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Account__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Payable Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Payable_Invoice_Expense_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payable_Invoice_Expense_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payable Invoice Expense Line Item</label>
    <referenceTo>c2g__codaPurchaseInvoiceExpenseLineItem__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Payment_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type_Name__c</fullName>
    <label>Payment Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/payableBridge.cls
public with sharing class payableBridge
{
	@AuraEnabled
	public static List<AggregateResult> getPayAccs(date fromDate, date toDate, string pymtMethod)
	{
		string expWhere = formulateWhere(fromDate, toDate, pymtMethod);

		string qry = 'SELECT SUM(Amount__c) total, COUNT(Id) recs, Payable_Account__c, Payable_Account__r.Name';
		qry = qry + ' FROM Engagement_Expense__c';
		qry = qry + expWhere;
		qry = qry + ' GROUP BY Payable_Account__c, Payable_Account__r.Name';

		list<AggregateResult> aggResults = Database.query(qry);
		if ( aggResults.size() > 0 )
		{
			return aggResults;
		}
		else
		{
			return null;
		}
	}

	@AuraEnabled
	public static Billing_Account__c getPayAcc(string recId)
	{
		Billing_Account__c payAcc;
		try
		{
			payAcc = [select 
			                id, 
			                Name, Account__c, 
			                Primary_Contact__c, 
			                Primary_Contact__r.Name, Billing_Street__c, 
			                Billing_City__c, 
			                Billing_State_Province__c, 
			                Billing_Country__c, 
			                Billing_Zip_Postal_Code__c
			          from Billing_Account__c 
			          where id = :recId];
		}
		catch ( exception er )
		{
			system.debug(er);
		}

		if ( payAcc != null )
		{
			return payAcc;
		}
		else
		{
			return null;
		}
	}

	@AuraEnabled
	public static List<Engagement_Expense__c> getExpenses(string payAccId, date fromDate, date toDate, string pymtMethod)
	{
		string expWhere = formulateWhere(fromDate, toDate, pymtMethod);
		expWhere = expWhere + ' AND Payable_Account__c = :payAccId';

		string qry = 'select id, Name, Expense_URL__c, Expense_Description__c, Amount__c,';
		qry = qry + ' Transaction_Date__c, GL_Name__c, General_Ledger_Id__c, Engagement__c,';
		qry = qry + ' Dimension_1__c, Dimension_1_Name__c, Dimension_2__c, Dimension_2_Name__c,';
		qry = qry + ' Dimension_3__c, Dimension_3_Name__c, Dimension_4__c, Dimension_4_Name__c';
		qry = qry + ' from Engagement_Expense__c' + expWhere;

		List<Engagement_Expense__c> exps = Database.query(qry);

		if ( exps.size() > 0 )
		{
			return exps;
		}
		else
		{
			return null;
		}
	}

	@AuraEnabled
	public static c2g__codaPurchaseInvoice__c buildPIN(Billing_Account__c payAcc)
	{
		c2g__codaPurchaseInvoice__c PIN = new c2g__codaPurchaseInvoice__c(  );

		PIN.c2g__Account__c = payAcc.Account__c;
		PIN.Primary_Contact__c = payAcc.Primary_Contact__c;
		PIN.Payable_Account__c = payAcc.id;
		PIN.c2g__InvoiceDate__c = date.today(  );

		PIN.Street__c = payAcc.Billing_Street__c;
		PIN.City__c = payAcc.Billing_City__c;
		PIN.State__c = payAcc.Billing_State_Province__c;
		PIN.Country__c = payAcc.Billing_Country__c;
		PIN.Postal_Code__c = payAcc.Billing_Zip_Postal_Code__c;

		string tmeZne = UserInfo.getTimeZone().toString();
		string nme = Datetime.now().format('YYMM:HH', tmeZne)+' ' + payAcc.Name;

		PIN.c2g__AccountInvoiceNumber__c = nme.left(25);

		return PIN;
	}

	@AuraEnabled
	public static list<id> createPIN(c2g__codaPurchaseInvoice__c pin, List<Engagement_Expense__c> exps, boolean updatePayAcc)
	{
		integer batchLimit = 20;

		for ( Engagement_Expense__c exp : exps )
		{
			if ( exp.Dimension_1__c == null || exp.Dimension_2__c == null )
			{
				throw new AuraHandledException('Not all Expenses have Dimension 1 & 2. Please ensure they are all populated and try creating again.');
			}
		}

		if ( updatePayAcc == true )
		{
			updatePayAcc( pin, pin.Payable_Account__c );
		}

		try
		{
			insert pin;
		}
		catch ( DmlException er )
		{
			System.debug(er);
			throw new AuraHandledException(er.getMessage());
		}

		List<c2g__codaPurchaseInvoiceExpenseLineItem__c> lnItms = createLnItems(exps, pin.Id);

		list<id> retIds = new list<Id>();
		retIds.add(pin.Id);
		if ( lnItms.size() <= batchLimit )
		{
			try
			{
				insert lnItms;
			}
			catch ( DmlException er )
			{
				System.debug(er);
				throw new AuraHandledException(er.getMessage());
			}
		}
		else
		{
			batchPINexpLines btchLines = new batchPINexpLines( lnItms );
			id batchId = Database.executebatch(btchLines, batchLimit);
			retIds.add(batchId);
			system.debug(retIds);
		}

		return retIds;
	}

	@AuraEnabled
	public static AsyncApexJob getBatchStatus(Id batchId)
	{
		AsyncApexJob aaj = [SELECT 
		                          Id, 
		                          Status, 
		                          JobItemsProcessed, 
		                          TotalJobItems, 
		                          NumberOfErrors, 
		                          ExtendedStatus, 
		                          MethodName, 
		                          CreatedBy.Name, CreatedDate
		                    FROM AsyncApexJob 
		                    WHERE ID = :batchId];

		return aaj;
	}

	private static void updatePayAcc(c2g__codaPurchaseInvoice__c PIN, id payAccId)
	{
		Billing_Account__c payAcc = new Billing_Account__c(  );

		payAcc.id = payAccId;
		payAcc.Billing_Street__c = PIN.Street__c;
		payAcc.Billing_City__c = PIN.City__c;
		payAcc.Billing_State_Province__c = PIN.State__c;
		payAcc.Billing_Country__c = PIN.Country__c;
		payAcc.Billing_Zip_Postal_Code__c = PIN.Postal_Code__c;

		update payAcc;
	}

	private static List<c2g__codaPurchaseInvoiceExpenseLineItem__c> createLnItems(List<Engagement_Expense__c> exps, id pinId)
	{
		List<c2g__codaPurchaseInvoiceExpenseLineItem__c> lnItms = new List<c2g__codaPurchaseInvoiceExpenseLineItem__c>();

		for ( Engagement_Expense__c exp : exps )
		{
			c2g__codaPurchaseInvoiceExpenseLineItem__c lnItm = new c2g__codaPurchaseInvoiceExpenseLineItem__c(  );

			lnItm.c2g__PurchaseInvoice__c = pinId;
			lnItm.Engagement_Expense__c = exp.id;

			lnItm.c2g__GeneralLedgerAccount__c = exp.General_Ledger_Id__c;
			lnItm.Transaction_Date__c = exp.Transaction_Date__c;
			lnItm.c2g__NetValue__c = exp.Amount__c;
			lnItm.c2g__LineDescription__c = exp.Expense_Description__c;

			lnItm.c2g__Dimension1__c = exp.Dimension_1__c;
			lnItm.c2g__Dimension2__c = exp.Dimension_2__c;
			lnItm.c2g__Dimension3__c = exp.Dimension_3__c;
			lnItm.c2g__Dimension4__c = exp.Dimension_4__c;

			lnitms.add(lnItm);
		}

		return lnItms;
	}

	private static string formulateWhere(date fromDate, date toDate, string pymtMethod)
	{
		string expWhere = ' WHERE Payable_Invoice_Expense_Line_Item__c = NULL AND Discarded__c = FALSE ';
		expWhere = expWhere + ' AND Payable_Account__c != NULL and Payable_Account__r.Status__c = \'Validated\'';

		if ( fromDate != null )
		{
			expWhere = expWhere + ' AND Transaction_Date__c >= :fromDate';
		}
		if ( toDate != null )
		{
			expWhere = expWhere + ' AND Transaction_Date__c <= :toDate';
		}
		if ( pymtMethod != 'None' )
		{
			expWhere = expWhere + ' AND Payment_Type_Name__c = :pymtMethod';
		}

		return expWhere;
	}
}