unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/bAccCrtInvTest.cls
@isTest(SeeAllData = true)
public class bAccCrtInvTest
{
	public static testMethod void testBilling()
	{
		Test.startTest();

		PageReference pageRef = Page.bAccCreateInvoice;
		Test.setCurrentPage(pageRef);

		Billing_Product__c bProd = [SELECT id, Billing_Account__c
		                            FROM Billing_Product__c
		                            WHERE Dimension_1__r.Name like '8000-axcessa'
		                            LIMIT 1];
		Billing_Account__c bAcc = [SELECT id
		                           FROM Billing_Account__c
		                           WHERE id = :bProd.Billing_Account__c];

		ApexPages.currentPage().getParameters().put('id', bAcc.id);
		apexpages.standardcontroller stdController = new ApexPages.StandardController( bAcc );

		bAccCrtInvEXT controller = new bAccCrtInvEXT( stdController );

		controller.getbAcc();
		controller.getfBprod();
		controller.fBprod.Dimension_1__c = [SELECT id
		                                    FROM c2g__codaDimension1__c
		                                    WHERE name like '8000-axcessa'
		                                    LIMIT 1].id;

		controller.fltr();
		controller.slctAll();
		controller.unslctAll();
		controller.advAll();
		controller.unadvAll();

		controller.getbProds();

		controller.bProds.get(0).selected = true;
		controller.bProds.get(0).advance = true;
		controller.crt();

		controller.setcstInvDate(Date.today(  ).addDays(-1));
		controller.getcstInvDate();

		test.stopTest();
	}
}