unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needing Validation</fullName>
                <default>true</default>
                <label>Needing Validation</label>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Credit Card Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/Billing_Configuration__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Billing Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Billing_Product_WHERE__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_WHERE__c</fullName>
    <label>Billing Product WHERE</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Configurations</relationshipLabel>
    <relationshipName>Billing_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/One_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>One Time Run? (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Recurring_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Day__c</fullName>
    <label>Recurring Day</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_CEM__c.field-meta.xml
<CustomField>
    <fullName>Split_on_CEM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on CEM?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Split_on_Dim_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on Dim 2?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/Billing_Configuration_Detail__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration Detail</label>
    <nameField>
        <displayFormat>BCD-{0000000000}</displayFormat>
        <label>Billing Configuration Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configuration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Billing_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Billing_Configuration__c</fullName>
    <label>Billing Configuration</label>
    <referenceTo>Billing_Configuration__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/CEM_Id__c.field-meta.xml
<CustomField>
    <fullName>CEM_Id__c</fullName>
    <label>CEM Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/CEM_Id__c.field-meta.xml
<CustomField>
    <fullName>CEM_Id__c</fullName>
    <formula>Product_Service__r.CM_Id__c</formula>
    <label>CM Id (Code)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/billingProductDaily.cls
public class billingProductDaily implements Schedulable{
	public final date tDay = date.today();
	public void execute(SchedulableContext sc){
		integer dy = tDay.day();
		list<Billing_Configuration__c> bConfigs = [select id, Dimension_1__c, One_Time_Run__c, Split_on_CEM__c, Split_on_Dim_2__c, Billing_Product_WHERE__c
		                                           from Billing_Configuration__c 
		                                           where Recurring_Day__c = :dy];
		if (bConfigs != null){
			list<Billing_Configuration_Detail__c> bConfigDets = createBillConfigDets(bConfigs);
			if (bConfigDets.size() > 0 && !test.isRunningTest()){
				insert bConfigDets;
				batchAccountingBridge batchBrd = new batchAccountingBridge();
				database.executebatch(batchBrd, 1);
			}
		}
	}

	public static list<Billing_Configuration_Detail__c> createBillConfigDets(list<Billing_Configuration__c> bConfigs){
		list<Billing_Configuration_Detail__c> bConfigDets = new list<Billing_Configuration_Detail__c>();
		for (Billing_Configuration__c bConfig : bConfigs){
			string query = 'SELECT id, name, ';
			query = query + '( SELECT id, name, Dimension_1__c, Dimension_2__c, CEM_Id__c ';
			query = query + 'FROM Billing_Account__c.Billing_Products__r ';
			query = query + bConfig.Billing_Product_WHERE__c + ') ';
			query = query + 'FROM Billing_Account__c ';
			query = query + 'WHERE Status__c = \'Validated\' AND Id IN ';
			query = query + '(SELECT Billing_Account__c ';
			query = query + 'FROM Billing_Product__c ';
			query = query + bConfig.Billing_Product_WHERE__c + ')';
			list<Billing_Account__c> bAccs = Database.query(query);
			for (Billing_Account__c bAcc : bAccs){
				id dim2;
				id cemId;
				Billing_Configuration_Detail__c bConfigDet = crtDet(bConfig, bAcc.id);
				for (Billing_Product__c bProd : bAcc.Billing_Products__r){
					if (bConfig.Split_on_Dim_2__c || bConfig.Split_on_CEM__c){
						if (dim2 == null){
							dim2 = bProd.Dimension_2__c;
							cemId = bProd.CEM_Id__c;
						}
						if ((dim2 != bProd.Dimension_2__c && bConfig.Split_on_Dim_2__c) || (cemId != bProd.CEM_Id__c && bConfig.Split_on_CEM__c)){
							if (bConfig.Split_on_Dim_2__c){
								bConfigDet.Dimension_2__c = dim2;
							}
							if (bConfig.Split_on_CEM__c){
								bConfigDet.CEM_Id__c = cemId;
							}
							bConfigDets.add(bConfigDet);
							bConfigDet = crtDet(bConfig, bAcc.id);
							dim2 = bProd.Dimension_2__c;
							cemId = bProd.CEM_Id__c;
						}
					}


					if (!bConfig.Split_on_Dim_2__c && !bConfig.Split_on_CEM__c){
						break;
					}
				}
				if (!bConfig.Split_on_Dim_2__c && !bConfig.Split_on_CEM__c){
					bConfigDets.add(bConfigDet);
				}
			}
		}
		return bConfigDets;
	}

	private static Billing_Configuration_Detail__c crtDet(Billing_Configuration__c bConfig, id bAccId){
		Billing_Configuration_Detail__c det = new Billing_Configuration_Detail__c();
		det.Billing_Configuration__c = bConfig.id;
		det.Billing_Account__c = bAccId;
		return det;
	}
}