unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needing Validation</fullName>
                <default>true</default>
                <label>Needing Validation</label>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Credit Card Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/Billing_Configuration__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Billing Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Billing_Product_WHERE__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_WHERE__c</fullName>
    <label>Billing Product WHERE</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Custom_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Custom_Invoice_Date__c</fullName>
    <label>Custom Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Configurations</relationshipLabel>
    <relationshipName>Billing_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Invoice_Description__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Description__c</fullName>
    <label>Invoice Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/One_Time_Run__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>One Time Run? (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Recurring_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Day__c</fullName>
    <label>Recurring Day</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration__c/fields/Split_on_Dim_2__c.field-meta.xml
<CustomField>
    <fullName>Split_on_Dim_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Split on Dim 2?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/Billing_Configuration_Detail__c.object-meta.xml
<CustomObject>
    <label>Billing Configuration Detail</label>
    <nameField>
        <displayFormat>BCD-{0000000000}</displayFormat>
        <label>Billing Configuration Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Configuration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Billing_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Billing_Configuration__c</fullName>
    <label>Billing Configuration</label>
    <referenceTo>Billing_Configuration__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Configuration_Detail__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Configuration Details</relationshipLabel>
    <relationshipName>Billing_Configuration_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/batchAccountingBridgeTest.cls
@isTest(SeeAllData = true)
public class batchAccountingBridgeTest
{
	public static testMethod void testStandardBridge()
	{
		Test.startTest();

		user u = getUser();
		System.runas(u)
		{
			Billing_Product__c bProd = setupEnv('8000');
			Billing_Configuration__c bConfig = new Billing_Configuration__c();

			bConfig.Dimension_1__c = bProd.Dimension_1__c;
			bConfig.One_Time_Run__c = true;
			bConfig.Split_on_Dim_2__c = true;
			bConfig.Recurring_Day__c = date.today().day();
			bConfig.Billing_Product_WHERE__c = 
				'WHERE Next_Billing_Date__c <= TODAY AND Dimension_1__c = \'' + 
				bProd.Dimension_1__c + 
				'\' AND Billing_Product_Status__c = \'Active\' ' + 
				' AND Billing_Account__r.Status__c = \'Validated\'' + 
				' AND Billing_Frequency__c <> \'One-Time\'';
			insert bConfig;

			Billing_Configuration_Detail__c bConfigDet = new Billing_Configuration_Detail__c();
			bConfigDet.Dimension_1__c = bConfig.Dimension_1__c;
			bConfigDet.Billing_Configuration__c = bConfig.id;
			bConfigDet.Billing_Account__c = bProd.Billing_Account__c;
			insert bConfigDet;

			try
			{
				batchAccountingBridge batchBrd = new batchAccountingBridge();
				database.executebatch(batchBrd, 1);
			}
			catch ( exception er )
			{
				system.debug(er);
			}
		}
		Test.stopTest();
	}

	public static testMethod void testCustomInvoiceDate()
	{
		Test.startTest();

		user u = getUser();
		System.runas(u)
		{
			Billing_Product__c bProd = setupEnv('8000');
			Billing_Configuration__c bConfig = new Billing_Configuration__c();

			bConfig.Dimension_1__c = bProd.Dimension_1__c;
			bConfig.One_Time_Run__c = true;
			bConfig.Recurring_Day__c = date.today().day();
			bConfig.Billing_Product_WHERE__c = 
				'WHERE Next_Billing_Date__c <= TODAY AND Dimension_1__c = \'' + 
				bProd.Dimension_1__c + 
				'\' AND Billing_Product_Status__c = \'Active\' ' + 
				' AND Billing_Account__r.Status__c = \'Validated\' ' + 
				' AND Billing_Frequency__c <> \'One-Time\'';
			bConfig.Custom_Invoice_Date__c = Date.today().addDays(-7);
			bConfig.Invoice_Description__c = 'Test Description';
			insert bConfig;

			Billing_Configuration_Detail__c bConfigDet = new Billing_Configuration_Detail__c();
			bConfigDet.Dimension_1__c = bConfig.Dimension_1__c;
			bConfigDet.Billing_Configuration__c = bConfig.id;
			bConfigDet.Billing_Account__c = bProd.Billing_Account__c;
			insert bConfigDet;

			try
			{
				batchAccountingBridge batchBrd = new batchAccountingBridge();
				database.executebatch(batchBrd, 1);
			}
			catch ( exception er )
			{
				system.debug(er);
			}
		}
		Test.stopTest();
	}

	public static testMethod void testErrors()
	{
		Test.startTest();

		user u = getUser();
		System.runas(u)
		{
			Billing_Product__c bProd = setupEnv('8000');
			Billing_Configuration__c bConfig = new Billing_Configuration__c();

			bConfig.Dimension_1__c = bProd.Dimension_1__c;
			bConfig.One_Time_Run__c = true;
			bConfig.Recurring_Day__c = date.today().day();
			bConfig.Billing_Product_WHERE__c = 
				'WHERE Next_Billing_Date__c <= TODAY AND Dimension_1__c = \'' + 
				bProd.Dimension_1__c + 
				'\' AND Billing_Product_Status__c = \'Active\' ' + 
				' AND Billing_Account__r.Status__c = \'Validated\' ' + 
				' AND Billing_Frequency__c <> \'One-Time\'';
			bConfig.Custom_Invoice_Date__c = Date.today().addDays(-7);
			bConfig.Invoice_Description__c = 'Test Description';
			insert bConfig;

			Billing_Configuration_Detail__c bConfigDet = new Billing_Configuration_Detail__c();
			bConfigDet.Dimension_1__c = bConfig.Dimension_1__c;
			bConfigDet.Billing_Configuration__c = bConfig.id;
			bConfigDet.Billing_Account__c = bProd.Billing_Account__c;
			insert bConfigDet;

			try
			{
				batchAccountingBridge batchBrd = new batchAccountingBridge();
				batchBrd.failTest = true;
				database.executebatch(batchBrd, 1);
			}
			catch ( exception er )
			{
				system.debug(er);
			}
		}
		Test.stopTest();
	}

	public static testMethod void testErrorLogs()
	{

		Test.startTest();

		user u = getUser();
		System.runas(u)
		{
			batchAccountingBridge.errorLog errLog = new batchAccountingBridge.errorLog('Test');
			errLog = new batchAccountingBridge.errorLog('Test', 'Test');
		}
		Test.stopTest();
	}

	private static User getUser()
	{
		user u = 
		[
			SELECT 
				Id
			FROM User
			WHERE 
				IsActive = true AND 
				Id IN 
				(
					SELECT UserId
					FROM UserPackageLicense
					WHERE PackageLicense.NamespacePrefix = 'c2g'
				) AND 
				Id IN 
				(
					SELECT c2g__User__c
					FROM c2g__codaUserCompany__c
				)
			ORDER BY LastName DESC
			LIMIT 1
		];
		return u;
	}

	private static Billing_Product__c setupEnv(string dim1ReportingCode)
	{
		Billing_Product__c bProd = 
		[
			SELECT 
				Id, 
				Billing_Account__c, 
				Dimension_1__c
			FROM Billing_Product__c
			WHERE 
				Dimension_1__r.c2g__ReportingCode__c = :dim1ReportingCode AND 
				Dimension_2__c != null AND 
				Billing_Account__r.Status__c = 'Validated' AND
				Billing_Product_Status__c = 'Active' AND
				Billing_Frequency__c <> 'One-Time'
			LIMIT 1
		];
		bProd.Next_Billing_Date__c = Date.today().addDays(-1);
		update bProd;

		List<Billing_Product__c> bProds = 
		[
			SELECT 
				Id
			FROM Billing_Product__c
			WHERE 
				Next_Billing_Date__c <= TODAY AND 
				Id <> :bProd.Id AND 
				Billing_Account__c = :bProd.Billing_Account__c
		];
		for ( Billing_Product__c bPrd : bProds )
		{
			bPrd.Next_Billing_Date__c = Date.today().addDays(5);
		}
		Database.update( bProds );

		list<Billing_Configuration__c> bConfigs = 
		[
			SELECT 
				Id
			FROM Billing_Configuration__c
		];
		Database.delete( bConfigs );

		return bProd;
	}
}