unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Recurring_Billing_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Billing_Day__c</fullName>
    <label>Recurring Billing Day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Training_Subscription_Account__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Subscription Account</label>
    <referenceTo>Training_Subscription_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/Training_Subscription__c.object-meta.xml
<CustomObject>
    <label>Training Subscription</label>
    <nameField>
        <label>Training Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Subscriptions</relationshipLabel>
    <relationshipName>Annuals_Training_SubscriptionsD_IE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Subscriptions</relationshipLabel>
    <relationshipName>Annuals_Training_Subscriptions_DIE</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/Training_Subscription_Account__c.object-meta.xml
<CustomObject>
    <description>Accounts authorized to enroll under a Training Subscription</description>
    <label>Training Subscription Account</label>
    <nameField>
        <label>Training Subscription Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Training_Subscription_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Billing Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Training_Subscription_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Subscription_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Account__c/fields/Training_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription__c</fullName>
    <label>Training Subscription Term</label>
    <referenceTo>Training_Subscription_Term__c</referenceTo>
    <relationshipLabel>Training Subscription Accounts</relationshipLabel>
    <relationshipName>Subscription_Sub_Accts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/Training_Subscription_Term__c.object-meta.xml
<CustomObject>
    <description>Institute Training Subscriptions terms and authorized accounts</description>
    <label>Training Subscription Term</label>
    <nameField>
        <label>Training Subscription Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Subscription Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Annuals_Training_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Annuals_Training_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>IF(
    Status_Formula__c = &quot;Inactive&quot;,
    &quot;Termed&quot;,
    RecordType.Name 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>Date set for subscription termination</description>
    <inlineHelpText>Date set for subscription termination</inlineHelpText>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Training_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Training_Subscription__c</fullName>
    <label>Training Subscription</label>
    <referenceTo>Training_Subscription__c</referenceTo>
    <relationshipLabel>Training Subscription Terms</relationshipLabel>
    <relationshipName>Training_Subscription_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Training_Subscription_Term__c/fields/Transitioned_to_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Transitioned_to_Monthly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transitioned to Monthly?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BillingProductsForTermedTST_Test.cls
@isTest
private class BillingProductsForTermedTST_Test {

    @testSetup
    static void generateData() {
        Account act = new Account(Name = 'Test Account');
        insert act;
        Billing_Account__c ba = [SELECT Id FROM Billing_Account__c WHERE Account__c = :act.Id LIMIT 1];
        Contact con = new Contact(FirstName = 'John', LastName = 'Tester', AccountId = act.Id);
        insert con;
        Training_Subscription__c ts = new Training_Subscription__c();
        insert ts;
        Training_Subscription_Term__c tst = new Training_Subscription_Term__c(
            Name = 'Test Term',
            Training_Subscription__c = ts.Id,
            Account__c = act.Id,
            Contact__c = con.Id,
            Transitioned_to_Monthly__c = false,
            Termination_Date__c = Date.today().addDays(-1)
        );
        insert tst;
        Training_Subscription_Account__c tsa = new Training_Subscription_Account__c(Name = 'Test tsa', Training_Subscription__c = tst.Id);
        insert tsa;
        Billing_Product__c bp = new Billing_Product__c(
            Billing_Frequency__c = 'Annually',
            Next_Billing_Date__c = Date.today().addDays(30),
            Billing_Account__c = ba.Id,
            Training_Subscription_Account__c = tsa.Id,
            Billing_Product_Status__c = 'Active',
            Recurring_Billing_day__c = Date.today().day() > 28 ? 28 : Date.today().day()
        );
        insert bp;
    }

    @isTest
    public static void test1() {
        Training_Subscription_Term__c tst = [SELECT Id, Term__c FROM Training_Subscription_Term__c LIMIT 1];
        Test.startTest();
            Database.executeBatch(new BillingProductsForTermedTST());
        Test.stopTest();
        Billing_Product__c bp = [SELECT Id, Billing_Product_Status__c FROM Billing_Product__c LIMIT 1];
        Assert.areEqual('Inactive', bp.Billing_Product_Status__c);
    }
}