unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/CZ_CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CZ_CustomerId__c</fullName>
    <externalId>true</externalId>
    <label>CZ CustomerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Primary contact for all billing related items related to this Billing Account - may be an authorized user, the card holder or finance personnel.</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Accounts</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Last_Billed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Billed_Date__c</fullName>
    <label>Last Billed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ChargeZoomSetup.cls
public class ChargeZoomSetup {
    
    public static void loadCustomers(){

        // Get all Billing Products last billed in May 2024
        AggregateResult[] mayBillingProducts = [select Billing_Account__c, count(id) from Billing_Product__c where Last_Billed_Date__c >= 2024-05-01 and Last_Billed_Date__c <= 2024-05-31 group by Billing_Account__c];
        System.debug('Total May accounts: ' + mayBillingProducts.size());
        Set<Id> billingAcctIdSet = new Set<Id>();

        for(AggregateResult ar:mayBillingProducts){ 
            billingAcctIdSet.add( String.valueOf(ar.get('Billing_Account__c')) ); 
        }


        // Get all Billing Products w/ a Next Bill Date of July 1, 2024.
        AggregateResult[] julyBillingProducts = [select Billing_Account__c, count(id) from Billing_Product__c where Next_Billing_Date__c >= 2024-07-01 group by Billing_Account__c];
        System.debug('Total July accounts: ' + julyBillingProducts.size());
        
        for(AggregateResult ar:julyBillingProducts){ 
            billingAcctIdSet.add( String.valueOf(ar.get('Billing_Account__c')) ); 
        }

        System.debug('There are ' + billingAcctIdSet.size() + ' Billing Accounts to create in Chargezoom.');

        List<Billing_Account__c> baList = [SELECT 
                                            Id, 
                                            Name,
                                            Account__r.Name,
                                            Account__r.ShippingStreet,
                                            Account__r.ShippingCity,
                                            Account__r.ShippingStateCode,
                                            Account__r.ShippingPostalCode,
                                            Account__r.ShippingCountryCode,
                                            Primary_Contact__r.FirstName,
                                            Primary_Contact__r.LastName,
                                            Primary_Contact__r.Phone,
                                            Primary_Contact__r.Email,
                                            Billing_Street__c,
                                            Billing_City__c,
                                            Billing_State_Province__c,
                                            Billing_Zip_Postal_Code__c,
                                            Billing_Country__c
                                        FROM Billing_Account__c
                                        WHERE Id IN :billingAcctIdSet
                                           	AND CZ_CustomerId__c = null];
        System.debug('Creating ' + baList.size() + ' accounts in Chargezoom.');

        // Create the customers in ChargeZoom
        CZ_CreateCustomer_Queueable czCreateJob = new CZ_CreateCustomer_Queueable(baList);
        System.enqueueJob(czCreateJob);
        

    }
}