unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product_Status__c</fullName>
    <label>Billing Product Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Waiting on Sign Off</fullName>
            </value>
            <value>
                <fullName>Reconciliation</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Next_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Billing_Date__c</fullName>
    <label>Next Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/billingConfigurationControllerTest.cls
@isTest(SeeAllData = true)
public class billingConfigurationControllerTest
{
	@IsTest
	static void testBillAccMethods()
	{
		User u = getUser();
		Test.startTest();
		System.runas(u)
		{
			List<Billing_Product__c> bProds = [SELECT Id
			                                   FROM Billing_Product__c
			                                   WHERE Billing_Product_Status__c = 'Active'
			                                   LIMIT 100];
			for ( Billing_Product__c bProd : bProds )
			{
				bProd.Next_Billing_Date__c = Date.today(  ).addDays(-1);
			}
			Database.update( bProds, false );
			Id dim1Id = [SELECT Id
			             FROM c2g__codaDimension1__c
			             WHERE c2g__ReportingCode__c = '8000'].Id;
			string billProdWhere = 'WHERE DIMENSION_1__c = \'' + dim1Id + '\'';
			List<AggregateResult> billAccs = billingConfigurationController.getBillAccs(billProdWhere);
			if(billAccs != null && !billAccs.isEmpty()){
				AggregateResult billAcc = billAccs.get(0);
				Id bAccId = ( Id )billAcc.get('Billing_Account__c');
				Billing_Account__c bAcc = billingConfigurationController.getSelectedBillAcc(bAccId, billProdWhere);
			}
		}
		Test.stopTest();
	}

	@IsTest
	static void testBatchMethods()
	{
		User u = getUser();
		Test.startTest();
		System.runAs(u)
		{
			Id dim1Id = [SELECT Id
			             FROM c2g__codaDimension1__c
			             WHERE c2g__ReportingCode__c = '8000'].Id;
			string billProdWhere = 'WHERE DIMENSION_1__c = \'' + dim1Id + '\'';
			date tDay = date.today(  );
			string descript = 'Test Description';
			billingConfigurationController.runManualBatch(billProdWhere, false, false, tDay, descript);
			List<AsyncApexJob> jobList = [SELECT Id
			              FROM AsyncApexJob
			              LIMIT 1];
            
            if(!jobList.isEmpty()){
	            Id batchId = jobList[0].Id;
				AsyncApexJob batchJob = billingConfigurationController.getBatchStatus(batchId);
			}
            
		}
		Test.stopTest();
	}

	private static User getUser()
	{
		user u = [SELECT id
		          FROM User
		          WHERE IsActive = true and Id in (SELECT UserId
		                                           FROM UserPackageLicense
		                                           WHERE PackageLicense.NamespacePrefix = 'c2g') and Id in (SELECT c2g__User__c
		                                                                                                    FROM c2g__codaUserCompany__c)
		          ORDER BY LastName DESC
		          LIMIT 1];
		return u;
	}
}