unpackaged/main/default/objects/Billing_Account__c/Billing_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Accounts (Account)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Billing_Account__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/Billing_Product__c.object-meta.xml
<CustomObject>
    <label>Billing Product</label>
    <nameField>
        <displayFormat>BP-{YY}{MM}{000000}</displayFormat>
        <label>Billing Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Billing_Product__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_3__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 3</label>
    <referenceTo>c2g__codaDimension3__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Billing_Product__c/fields/Dimension_4__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 4</label>
    <referenceTo>c2g__codaDimension4__c</referenceTo>
    <relationshipLabel>Billing Products</relationshipLabel>
    <relationshipName>Billing_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OEM_Record__c/OEM_Record__c.object-meta.xml
<CustomObject>
    <description>All RFPs for Automotive OEM are generated here.</description>
    <label>OEM Record</label>
    <nameField>
        <displayFormat>OEM-{000000}</displayFormat>
        <label>OEM Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OEM_Record__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>OEM Records</relationshipLabel>
    <relationshipName>OEM_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OEM_Record__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>OEM Records (Billing Contact)</relationshipLabel>
    <relationshipName>OEM_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OEM_Record__c/fields/OEM_Account__c.field-meta.xml
<CustomField>
    <fullName>OEM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Account that requested the OEM project</inlineHelpText>
    <label>OEM Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OEM Records</relationshipLabel>
    <relationshipName>OEM_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <label>Billing Contact</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Code__c</fullName>
    <label>Billing Zip Code</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>DATE(2021,1,31)

TODAY()</description>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <description>Indicates if all the line items for this opportunity have been invoiced.</description>
    <formula>IF( Line_Item_Not_Invoiced__c = 0, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if all the line items for this opportunity have been invoiced.</inlineHelpText>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OEM_Account__c.field-meta.xml
<CustomField>
    <fullName>OEM_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OEM Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM OEM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (OEM Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/OEM_Record__c.field-meta.xml
<CustomField>
    <fullName>OEM_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OEM Record</label>
    <referenceTo>OEM_Record__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <formula>IF(Invoiced__c == true, false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Billing_Account__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Billing_Product__c.field-meta.xml
<CustomField>
    <fullName>Billing_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Product</label>
    <referenceTo>Billing_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_1__c.field-meta.xml
<CustomField>
    <fullName>Dimension_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Departments</inlineHelpText>
    <label>Dimension 1</label>
    <referenceTo>c2g__codaDimension1__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>NCM Employee</inlineHelpText>
    <label>Dimension 2</label>
    <referenceTo>c2g__codaDimension2__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_3__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Marketing Tactic</inlineHelpText>
    <label>Dimension 3</label>
    <referenceTo>c2g__codaDimension3__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Dimension_4__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>20 Group Meeting</inlineHelpText>
    <label>Dimension 4</label>
    <referenceTo>c2g__codaDimension4__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/createFFinvoiceEXT.cls
public class createFFinvoiceEXT {
    public apexpages.standardcontroller stdController;
    public id oppId;
    public Opportunity opp;
    public list<OpportunityLineItem> oppLnItms;
    
	public createFFinvoiceEXT(apexpages.standardcontroller stdController){
        this.stdController = stdController;
        oppId = ApexPages.currentPage().getParameters().get('id');
    }
    
    public Opportunity getopp(){
        opp = [select id, AccountId, OEM_Record__c, Billing_Street__c, Billing_State__c, OEM_Record__r.OEM_Account__c,
               	Billing_Zip_Code__c, Billing_Contact__c, Billing_City__c, Invoice_Date__c, Billing_Account__c, Billing_Account__r.Account__c 
               from Opportunity 
               where id = :oppId];
        
        return opp;
    }
    
    public list<OpportunityLineItem> getoppLnItms(){
        if (opp == null){
            getopp();
        }
        oppLnItms = [select id, Product2Id, Quantity, UnitPrice, Description, Ready_to_Invoice__c, Invoiced__c,
                     	Dimension_1__c, Dimension_2__c, Dimension_3__c, Dimension_4__c, Billing_Product__c
                     from OpportunityLineItem 
                     where OpportunityId = :oppId and Invoiced__c = false];
        
        return oppLnItms;
    }
    
    public PageReference createInvoice(){
        boolean isSuccess = true;
        try{
            update opp;
        } catch(DMLexception er) {
            system.debug(er);
            apexpages.addMessage(new apexpages.message(ApexPages.Severity.ERROR, 'Could not Update Opportunity: ' + er.getMessage()));
            isSuccess = false;
        }
        try{
            update oppLnItms;
        } catch(DMLexception er) {
            system.debug(er);
            apexpages.addMessage(new apexpages.message(ApexPages.Severity.ERROR, 'Could not Update Opportunity Line Items: ' + er.getMessage()));
            isSuccess = false;
        }
        
        boolean hsLineItems = false;
        for (OpportunityLineItem lnItm : oppLnItms){
            if (lnItm.Invoiced__c == false && lnItm.Ready_to_Invoice__c == true) {
                hsLineItems = true;
                break;
            }
        }
        
        c2g__CodaInvoice__c inv = new c2g__CodaInvoice__c();
        if (isSuccess && hsLineItems){
            inv.c2g__Opportunity__c = opp.id;
            inv.c2g__InvoiceDate__c = opp.Invoice_Date__c;
            inv.Billing_City__c = opp.Billing_City__c;
            inv.Billing_Contact2__c = opp.Billing_Contact__c;
            inv.Billing_State__c = opp.Billing_State__c;
            inv.Billing_Street__c = opp.Billing_Street__c;
            inv.Billing_Zip_Code__c = opp.Billing_Zip_Code__c;
            inv.c2g__DeriveCurrency__c = true;
            inv.c2g__DeriveDueDate__c = true;
            inv.c2g__Dimension1__c = oppLnItms.get(0).Dimension_1__c;
            inv.c2g__Dimension2__c = oppLnItms.get(0).Dimension_2__c;
            
            inv.Billing_Account__c = opp.Billing_Account__c;
            if (opp.Billing_Account__c != null){
                inv.c2g__Account__c = opp.Billing_Account__r.Account__c;
            } else if(opp.OEM_Record__c != null){
                inv.c2g__Account__c = opp.OEM_Record__r.OEM_Account__c;
            } else {
                inv.c2g__Account__c = opp.AccountId;
            }
            
            try{
                insert inv;
            } catch(DMLexception er) {
                system.debug(er);
                apexpages.addMessage(new apexpages.message(ApexPages.Severity.ERROR, 'Could not Create Invoice: ' + er.getMessage()));
                isSuccess = false;
            } 
        } else if (hsLineItems == false){
            apexpages.addMessage(new apexpages.message(ApexPages.Severity.WARNING, 'No Line Items were marked to be Invoiced'));
            isSuccess = false;
        }
        
        if (isSuccess){
            PageReference invURL = new PageReference('/' + inv.id);
            invURL.setRedirect(true);
            return invURL;
        } else {
            return null;
        }
        
    }
}