unpackaged/main/default/objects/aXcessa_Store_Metric__b/aXcessa_Store_Metric__b.object-meta.xml
<CustomObject>
    <label>aXcessa Store Metric</label>
    <pluralLabel>aXcessa Store Metrics</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/aXcessa_Store__c.field-meta.xml
<CustomField>
    <fullName>aXcessa_Store__c</fullName>
    <label>aXcessa Store</label>
    <referenceTo>axcessa_Platform_Engagement__c</referenceTo>
    <relationshipLabel>aXcessa Store Metrics</relationshipLabel>
    <relationshipName>aXcessa_Store_Metrics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <label>CIF</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Data_Date__c.field-meta.xml
<CustomField>
    <fullName>Data_Date__c</fullName>
    <label>Data Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <label>Installed?</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Last_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Login__c</fullName>
    <label>Last Login</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/NCM__c.field-meta.xml
<CustomField>
    <fullName>NCM__c</fullName>
    <label>NCM?</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Reports_Count__c.field-meta.xml
<CustomField>
    <fullName>Reports_Count__c</fullName>
    <label>Reports Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <label>Store Id</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Store_Name__c.field-meta.xml
<CustomField>
    <fullName>Store_Name__c</fullName>
    <label>Store Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/aXcessa_Store_Metric__b/fields/Users_Count__c.field-meta.xml
<CustomField>
    <fullName>Users_Count__c</fullName>
    <label>Users Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/axcessaMetricsController.cls
public inherited sharing class axcessaMetricsController
{
	@InvocableMethod
	public static List<List<aXcessa_Store_Metric__b>> getAxcessaStoreMetrics(list<Id> storeIds)
	{
		List<List<aXcessa_Store_Metric__b>> returnList = new List<List<aXcessa_Store_Metric__b>>();

		for ( Id storeId : storeIds )
		{

			List<aXcessa_Store_Metric__b> storeMetrics;

			string query = 'SELECT aXcessa_Store__c, CIF__c, Data_Date__c, Group__c, Installed__c, Last_Login__c, NCM__c, Reports_Count__c, Store_Id__c, Store_Name__c, Users_Count__c ';
			query = query + 'FROM aXcessa_Store_Metric__b WHERE aXcessa_Store__c = \'' + storeId + '\' ORDER BY aXcessa_Store__c, Data_Date__c DESC LIMIT 20 ';
			try
			{
				if ( !Test.isRunningTest() )
				{
					storeMetrics = Database.query(query);
				}
				returnList.add(storeMetrics);
			}
			catch ( Exception er )
			{
				System.debug(er);
			}

		}
		return returnList;
	}
}