unpackaged/main/default/objects/Experient_API__c/Experient_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Experient API Settings</label>
</CustomObject>

unpackaged/main/default/objects/Experient_API__c/fields/actcode__c.field-meta.xml
<CustomField>
    <fullName>actcode__c</fullName>
    <inlineHelpText>Only need to utilize if there are multiple Experient Events active at the same time, otherwise only adjust at the Org Default level</inlineHelpText>
    <label>actcode</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Experient_API__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Org Default only! This activates the Experient API Trigger</description>
    <inlineHelpText>Only works at the Org Default level. Turns the API Trigger on / off</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Experient_API__c/fields/apiKey__c.field-meta.xml
<CustomField>
    <fullName>apiKey__c</fullName>
    <description>the API Key for the Experient App</description>
    <inlineHelpText>Should only be adjusted at the org Default Level</inlineHelpText>
    <label>apiKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Experient_API__c/fields/BadgeId__c.field-meta.xml
<CustomField>
    <fullName>BadgeId__c</fullName>
    <inlineHelpText>The badge ID for the Experient Event that is being utilized</inlineHelpText>
    <label>BadgeId</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Experient_API__c/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <inlineHelpText>Shouldn&#39;t ever have to change. Better to adjust at the Org Default Level</inlineHelpText>
    <label>End Point</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Experient_API__c/fields/Test_Mode__c.field-meta.xml
<CustomField>
    <fullName>Test_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this field is used in order to accomplish test coverage for the Experient API</description>
    <inlineHelpText>NEVER CHANGE THIS VALUE!!!</inlineHelpText>
    <label>Test Mode (Code)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/experientAPITriggerTest.cls
@isTest (seeAllData = true)
public class experientAPITriggerTest {
    static testMethod void TestexperientAPITrigger(){
        test.startTest();
        
        Experient_API__c usrSett = Experient_API__c.getInstance(UserInfo.getUserId());
        Experient_API__c orgDef = Experient_API__c.getOrgDefaults();
        
        orgDef.Active__c = true;
        orgDef.Test_Mode__c = true;
        
        orgDef.BadgeId__c = '0';
        orgDef.actcode__c = '0000000000000000';
        orgDef.apiKey__c = 'CP-kigOXnoIco6Zl3BKQ53-lnWfToRuoDxUzDkap7pSWnPT5JZ7QR5sxiIYhBQ__';
        orgDef.End_Point__c = 'https://developer.experientswap.com/APIv1/LeadInfo';
        
        usrSett.BadgeId__c = '0';
        usrSett.actcode__c = '0000000000000000';
        usrSett.apiKey__c = 'CP-kigOXnoIco6Zl3BKQ53-lnWfToRuoDxUzDkap7pSWnPT5JZ7QR5sxiIYhBQ__';
        usrSett.End_Point__c = 'https://developer.experientswap.com/APIv1/LeadInfo';
        
        upsert orgDef;
        upsert usrSett;
        
        eContacts__Queue_Item__c scnItm = new eContacts__Queue_Item__c();
        scnItm.eContacts__Notes__c = '<a href="#" onclick="window.open(\'HTTPS://L4E.US/589/1001/ATTENDEE-1001/DEMO-1001/DEMOCOMPANY\', \'_system\', \'location=yes\'); return false;" contenteditable="false" title="HTTPS://L4E.US/589/1001/ATTENDEE-1001/DEMO-1001/DEMOCOMPANY">HTTPS://L4E.US/589/1001/ATTENDEE-1001/DEMO-1001/DEMOCOMPANY</a> Created in Test Class';
        
        insert scnItm;
        
        test.stopTest();
    }
}