unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Selection__c/Room_Block_Selection__c.object-meta.xml
<CustomObject>
    <description>The customer&#39;s room selection (ex: Joe Martin from Martin GMC selected 5 Queen rooms, 3 King rooms, and 1 Efficiency room for this engagement)</description>
    <label>Room Block Selection</label>
    <nameField>
        <displayFormat>RBS-{000000}</displayFormat>
        <label>Room Block Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room Block Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Planned_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Planned_Arrival__c</fullName>
    <label>Planned Arrival</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Planned_Departure__c.field-meta.xml
<CustomField>
    <fullName>Planned_Departure__c</fullName>
    <label>Planned Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Room_Block_Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Room_Block_Survey_Response__c</fullName>
    <description>The parent Room Block Survey Response from the customer.</description>
    <label>Room Block Survey Response</label>
    <referenceTo>Room_Block_Survey_Response__c</referenceTo>
    <relationshipLabel>Room Block Selections</relationshipLabel>
    <relationshipName>Room_Block_Selections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Room_Count__c.field-meta.xml
<CustomField>
    <fullName>Room_Count__c</fullName>
    <description>The number of rooms needed for this room type</description>
    <label>Room Count</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/Room_Block_Survey_Response__c.object-meta.xml
<CustomObject>
    <description>After we make the API call to Workato and send the list of member contacts to email.
Store each Member Contact in a Room Block Survey Response record.</description>
    <label>Room Block Survey Response</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Block Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>Master/Detail to the Engagement,</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Room Block Survey Responses</relationshipLabel>
    <relationshipName>RoomBlockSurveyResponses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Planned_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Planned_Arrival__c</fullName>
    <label>Planned Arrival</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Planned_Departure__c.field-meta.xml
<CustomField>
    <fullName>Planned_Departure__c</fullName>
    <label>Planned Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Room_Count__c.field-meta.xml
<CustomField>
    <fullName>Room_Count__c</fullName>
    <label>Room Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Survey_Id__c.field-meta.xml
<CustomField>
    <fullName>Survey_Id__c</fullName>
    <externalId>true</externalId>
    <label>Survey Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/SurveyResponseDate__c.field-meta.xml
<CustomField>
    <fullName>SurveyResponseDate__c</fullName>
    <description>The day and time the contact responded to the selection.</description>
    <label>Survey Response Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/SurveySentDate__c.field-meta.xml
<CustomField>
    <fullName>SurveySentDate__c</fullName>
    <description>Date/Time - The timestamp for the API call to Workato.</description>
    <inlineHelpText>Date/Time - The timestamp for the API call to Workato.</inlineHelpText>
    <label>Survey Sent Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/RoomBlockSurveyResponse_Tests.cls
@isTest
public class RoomBlockSurveyResponse_Tests {

    @testSetup
    static void setupData(){
        
        SampleDataFactory.create20GroupAccountData();
        Twenty_Groups__c test20G = [select id from Twenty_Groups__c limit 1];
        String engRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        String contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId();
        Contact billingContact = [select id, name from Contact where RecordTypeId = :contactRecTypeId LIMIT 1];
        SampleDataFactory.createEngagement_20G(test20G.Id, engRecTypeId, billingContact.Id);
        
    }
    
    @isTest
    static void apiUpdatesResponseRecord(){
        
        Engagement__c eng = [select id from Engagement__c limit 1];
        Room_Block_Survey_Response__c testRec = new Room_Block_Survey_Response__c();
        testRec.Engagement__c = eng.Id;
        testRec.Survey_Id__c = '1234-abcd';
        testRec.SurveySentDate__c = Date.today();
        insert(testRec);
        
        Date arrival = Date.today().addDays(5);
        Date depart = Date.today().addDays(10);
        Integer numRooms = 5;
        String roomType = 'Deluxe Suite';
        RoomBlockModel.RoomBlockSubmitResponse respResult;
        RoomBlockModel.RoomBlockSelectionRequest req = new RoomBlockModel.RoomBlockSelectionRequest();
        req.surveyId = testRec.Survey_Id__c;
        List<RoomBlockModel.RoomSelection> roomSelections = new List<RoomBlockModel.RoomSelection>();
        
        // 1st rooming selection
        RoomBlockModel.RoomSelection roomSel1 = new RoomBlockModel.RoomSelection();
        roomSel1.plannedArrival = Date.today().addDays(30);
        roomSel1.plannedDeparture = Date.today().addDays(35);
        roomSel1.roomCount = 3;
        roomSel1.roomType = 'Deluxe Suite';
        roomSelections.add(roomSel1);
        
        // 2nd rooming selection
        RoomBlockModel.RoomSelection roomSel2 = new RoomBlockModel.RoomSelection();
        roomSel2.plannedArrival = Date.today().addDays(30);
        roomSel2.plannedDeparture = Date.today().addDays(35);
        roomSel2.roomCount = 5;
        roomSel2.roomType = 'Standard Room';
        roomSelections.add(roomSel2);

        req.rooms = roomSelections;


        Test.startTest();
        	respResult = RoomBlockSurveyResponse.submitSurveyResponse(req);
        Test.stopTest();
        
        
        // Did the response have a success result?
        Assert.areEqual('200', respResult.statusCode);
        
        Room_Block_Survey_Response__c testResult = [SELECT 
                                                        Id, 
                                                        Name, 
                                                        SurveyResponseDate__c,
                                                        (select Room_Type__c, Room_Count__c, Planned_Arrival__c, Planned_Departure__c FROM Room_Block_Selections__r)
                                                    FROM Room_Block_Survey_Response__c
                                                    WHERE Survey_Id__c = :testRec.Survey_Id__c];
        
        //Assert.areEqual(DateTime.now(), testResult.SurveyResponseDate__c);
        Assert.areEqual(roomSelections.size(), testResult.Room_Block_Selections__r.size());
    }
    
    
    @isTest
    static void invalidSurveyIdPassedReturns500Code(){
        
        Date arrival = Date.today().addDays(5);
        Date depart = Date.today().addDays(10);
        Integer numRooms = 5;
        String roomType = 'Deluxe Suite';
        RoomBlockModel.RoomBlockSubmitResponse respResult;
        RoomBlockModel.RoomBlockSelectionRequest req = new RoomBlockModel.RoomBlockSelectionRequest();
        req.surveyId = 'Invalid-survey-id';
        
        Test.startTest();
        	respResult = RoomBlockSurveyResponse.submitSurveyResponse(req);
        Test.stopTest();
        
        Assert.areEqual('500', respResult.statusCode);
        
    }
}