unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Room_Block__c/Engagement_Room_Block__c.object-meta.xml
<CustomObject>
    <description>Room Block Survey for a specific Engagement.</description>
    <label>Engagement Room Block</label>
    <nameField>
        <label>Room Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Room Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Room_Block__c/fields/Engagement_Id__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Id__c</fullName>
    <description>Engagement Room Blocks related to the Engagement.</description>
    <inlineHelpText>Engagement Room Blocks related to the Engagement.</inlineHelpText>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Room Blocks</relationshipLabel>
    <relationshipName>EngRoomBlocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Room_Block__c/fields/Room_Rate__c.field-meta.xml
<CustomField>
    <fullName>Room_Rate__c</fullName>
    <description>A meeting specialist can see a tab where they will manage/work on room block survey information for that engagement. Add Room Block Survey Objects and Tab to display on the Engagement page.</description>
    <label>Room Rate</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Room_Block__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <description>Room Type? King Size, Two Queens, Suite, etc...</description>
    <inlineHelpText>Room Type? King Size, Two Queens, Suite, etc...</inlineHelpText>
    <label>Room Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/X20_Group_Member_Contact__c.object-meta.xml
<CustomObject>
    <label>20 Group Member Contact</label>
    <nameField>
        <label>20 Group Member Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Group Member Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/RoomBlockOptionsAPI_Tests.cls
@isTest
public class RoomBlockOptionsAPI_Tests {
    
    @TestSetup
    static void makeData(){
        SampleDataFactory.create20GroupAccountData();
        
    }

    @isTest
    public static void test20GroupEngagement() {
        
        Id twentyGrpId = [select id from Twenty_Groups__c LIMIT 1].Id;
        String ncmContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId();
        String engRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        Contact billingContact = [select id from contact where RecordTypeId = :ncmContactRecTypeId LIMIT 1];
        
        SampleDataFactory.createEngagement_20G(twentyGrpId,engRecTypeId,billingContact.Id);

        Engagement__c testEngagement = [select id from engagement__c limit 1];
        X20_Group_Member_Contact__c gmc = [SELECT Id FROM X20_Group_Member_Contact__c LIMIT 1];
        System.debug('~~~gmc: ' + gmc);
        
        String surveyId = gmc.Id + '-' + testEngagement.Id;

        insert(new Engagement_Room_Block__c(
            Engagement_Id__c = testEngagement.Id,
            Name = 'Test Hotel',
            Room_Rate__c = 10,
            Room_Type__c = 'Test Room'
        ));

        RoomBlockModel.RoomBlockOptionsResponse resp;
        
        Test.startTest();
            resp = RoomBlockOptionsAPI.getRoomBlockOptions(testEngagement.Id, surveyId);
        Test.stopTest();

        Assert.areEqual('200', resp.statusCode);
    }
}