unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Proprietary_Group__c.field-meta.xml
<CustomField>
    <fullName>Proprietary_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietary Group</label>
    <referenceTo>Proprietary_Group__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Account_Contact__c/Proprietary_Account_Contact__c.object-meta.xml
<CustomObject>
    <label>Proprietary Account Contact</label>
    <nameField>
        <label>Proprietary Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Account_Contact__c/fields/Proprietary_Group__c.field-meta.xml
<CustomField>
    <fullName>Proprietary_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietary Group</label>
    <referenceTo>Proprietary_Group__c</referenceTo>
    <relationshipLabel>Proprietary Account Contacts</relationshipLabel>
    <relationshipName>Proprietary_Account_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/Proprietary_Group__c.object-meta.xml
<CustomObject>
    <label>Proprietary Group</label>
    <nameField>
        <label>Proprietary  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/Room_Block_Survey_Response__c.object-meta.xml
<CustomObject>
    <description>After we make the API call to Workato and send the list of member contacts to email.
Store each Member Contact in a Room Block Survey Response record.</description>
    <label>Room Block Survey Response</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Block Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>Master/Detail to the Engagement,</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Room Block Survey Responses</relationshipLabel>
    <relationshipName>RoomBlockSurveyResponses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Proprietary_Account_Contact__c.field-meta.xml
<CustomField>
    <fullName>Proprietary_Account_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietary Account Contact</label>
    <referenceTo>Proprietary_Account_Contact__c</referenceTo>
    <relationshipLabel>Room Block Survey Responses</relationshipLabel>
    <relationshipName>Room_Block_Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/X20_Group_Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>X20_Group_Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group Member Contact</label>
    <referenceTo>X20_Group_Member_Contact__c</referenceTo>
    <relationshipLabel>Room Block Survey Responses</relationshipLabel>
    <relationshipName>Room_Block_Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/X20_Group_Member_Contact__c/X20_Group_Member_Contact__c.object-meta.xml
<CustomObject>
    <label>20 Group Member Contact</label>
    <nameField>
        <label>20 Group Member Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Group Member Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/RoomBlockSurveyRequestTest.cls
@isTest
public class RoomBlockSurveyRequestTest {

    // X20_Group_Member_Contact__c
    @isTest
    static void sendTwentyGroupSurveyTest() {

        // Identify the mock class to use for the WorkatoAPI callout
        Test.setMock(HttpCalloutMock.class, new WorkatoMock());

        // Test setup data.
        SampleDataFactory.create20GroupAccountData();
        Id twentyGroupId = [SELECT Id, Name, NCM_Proprietor__c FROM Twenty_Groups__c LIMIT 1].Id;
        Id engagementRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId(); 
        Id ncmBillingContactId = [SELECT Id FROM Contact WHERE recordtype.name = 'NCM Associates' LIMIT 1].Id;  
        SampleDataFactory.createEngagement_20G(twentyGroupId, engagementRecTypeId, ncmBillingContactId); 
        List<Engagement__c> testEngagement_x20Group = [SELECT Id, Name FROM Engagement__c LIMIT 1];
        List<String> engagementIds = new List<String> {testEngagement_x20Group[0].Id};

        // Execute the sendRoomBlockSurvey() method.
        Test.startTest();
            RoomBlockSurveyRequest.sendRoomBlockSurvey(engagementIds); 
        Test.stopTest();

        // Verify RBS records are created for each contact sent an email.
        String contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();
        List<Contact> testContacts = [SELECT id, name FROM Contact WHERE RecordTypeId = :contactRecTypeId]; // Use this list to verify the number of people added to the RBS list.
        List<Room_Block_Survey_Response__c> rbsResults = [select id, X20_Group_Member_Contact__c FROM Room_Block_Survey_Response__c WHERE Engagement__c = :testEngagement_x20Group[0].Id];
        Assert.areEqual(testContacts.size(), rbsResults.size());
                
    } 
    
    @isTest     
    static void getEngagegmentFor_propGoup() {

        // Identify the mock class to use for the WorkatoAPI callout
        Test.setMock(HttpCalloutMock.class, new WorkatoMock());

        // Test setup data.
        SampleDataFactory.createPropGroupData();
        Id propGroupId = [SELECT Id, Name FROM Proprietary_Group__c LIMIT 1].Id;
        Id engagementRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId(); 
        Id ncmBillingContactId = [SELECT Id FROM Contact WHERE recordtype.name = 'NCM Associates' LIMIT 1].Id;  
        SampleDataFactory.createEngagement_Prop(propGroupId, engagementRecTypeId, ncmBillingContactId); 
        List<Engagement__c> testEngagement_x20Group = [SELECT Id, Name FROM Engagement__c LIMIT 1];
        List<String> engagementIds = new List<String> {testEngagement_x20Group[0].Id};

        // Execute the sendRoomBlockSurvey() method.
        Test.startTest();
             RoomBlockSurveyRequest.sendRoomBlockSurvey(engagementIds);
        Test.stopTest();

        // Verify RBS records are created for each contact sent an email.
        String contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();
        List<Contact> testContacts = [SELECT id, name FROM Contact WHERE RecordTypeId = :contactRecTypeId]; // Use this list to verify the number of people added to the RBS list.
        List<Room_Block_Survey_Response__c> rbsResults = [select id, Proprietary_Account_Contact__c FROM Room_Block_Survey_Response__c WHERE Engagement__c = :testEngagement_x20Group[0].Id];
        Assert.areEqual(testContacts.size(), rbsResults.size());

    } 

    // X20_Group_Member_Contact__c Emails
    @isTest
    static void x20GroupMemberContactEmail() {

        // Identify the mock class to use for the WorkatoAPI callout
        Test.setMock(HttpCalloutMock.class, new WorkatoMock());

        // Test setup data.
        SampleDataFactory.create20GroupAccountData();
        Id twentyGroupId = [SELECT Id, Name, NCM_Proprietor__c FROM Twenty_Groups__c LIMIT 1].Id; 
        Id engagementRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId(); 
        Id ncmBillingContactId = [SELECT Id FROM Contact WHERE recordtype.name = 'NCM Associates' LIMIT 1].Id;  
        SampleDataFactory.createEngagement_20G(twentyGroupId, engagementRecTypeId, ncmBillingContactId); 

        System.debug('Inside RoomBlockSurveyRequestTest: x20GroupMemberContactEmail');
        
        // Get Engagement. Query from SampleDataFactory. 
        List<Engagement__c> testEngagement_propGroup = [SELECT Id, Name FROM Engagement__c LIMIT 1];
        List<String> engagementIds = new List<String> {testEngagement_propGroup[0].Id};

        System.debug('Test getEngagegmentFor_propGoup EngagementIds: ' + engagementIds);
        //System.debug('Test Engagement Prop Group: ' + testEngagement_propGroup[0].Id);
        
        // Call the Invocable Method
        Test.startTest();
                RoomBlockSurveyRequest.sendRoomBlockSurvey(engagementIds);  
        Test.stopTest();
        
        // query for roomblockservice records
    } 
    
} // End of test class