unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Dimension_4__c.field-meta.xml
<CustomField>
    <fullName>Dimension_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dimension 4</label>
    <referenceTo>c2g__codaDimension4__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancellation Inquiry</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancelled – Rebooked</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Engagement Complete</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Re-Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <isActive>false</isActive>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <isActive>false</isActive>
                <label>OPEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>New Group - Acquiring</fullName>
            </value>
            <value>
                <fullName>New Group - Didn&#39;t Start</fullName>
            </value>
            <value>
                <fullName>New Group - Prospecting</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>New Group - Overflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/EngagementDim4NameSyncBatch_Tests.cls
@isTest 
public class EngagementDim4NameSyncBatch_Tests {
    
    @TestSetup
    static void makeData(){

        SampleDataFactory.create20GroupAccountData();

        String twentyGroupId = [SELECT Id FROM Twenty_Groups__c WHERE Status__c = 'Active' LIMIT 1].Id;
        String engagementRT = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        String ncmBillingContactId = [SELECT Id FROM Contact WHERE RecordType.Name = 'NCM Associates' LIMIT 1].Id;

        SampleDataFactory.createEngagement_20G(twentyGroupId, engagementRT, ncmBillingContactId);

    }

    @isTest 
    public static void engagementNameChangedUpdatesDIM4Name(){

        // Get a sample engagement record to work with.
        Engagement__c testEng = [SELECT id, Engagement_Start__c, Dimension_4__c 
                                    FROM Engagement__c 
                                    WHERE Dimension_4__c != null 
                                    LIMIT 1];

        // Update the Engagement Start field to trigger the engagement Name to change.
        testEng.Engagement_Start__c = testEng.Engagement_Start__c.addDays(1); 
        update(testEng);

        // Verify that now the Engagement Name and its Dim4 Name are not the same..
        Engagement__c testEng2 = [SELECT Name, Dimension_4__r.Name 
                                    FROM Engagement__c 
                                    WHERE Id = :testEng.Id];

        Assert.areNotEqual(testEng2.Name, testEng2.Dimension_4__r.Name);


        User sfAdminUser = [select id from User where name = 'SF Admin' and IsActive = true];

        // Execute the batch to update the DIM4 record name
        Test.startTest();

            // We will simulate this batch running as the service account SF Admin which 
            // has the Financial Force license necessary to update the Dimension4 record.
            System.runAs(sfAdminUser){
                Database.executeBatch(new EngagementDim4NameSyncBatch(),1);
            }

        Test.stopTest();


        Engagement__c engResult = [SELECT id, Name, Dimension_4__c, Dimension_4__r.Name FROM Engagement__c WHERE Id = :testEng.Id];
        Assert.areEqual(engResult.Name,engResult.Dimension_4__r.Name);

    }
}