unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <description>Engagement Attendee Type</description>
    <label>Attendee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active Participant</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Co-Member</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Engagement Support</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Guest Presenter</fullName>
            </value>
            <value>
                <fullName>Industry Professional</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Moderator</fullName>
            </value>
            <value>
                <fullName>NCM Guest</fullName>
            </value>
            <value>
                <fullName>NCM Resource</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Visitor</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Associate Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/User/fields/NCM_Associates_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>NCM_Associates_Contact_ID__c</fullName>
    <label>NCM Associates Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/userAvailabilityController.cls
public with sharing class userAvailabilityController {
    
    @AuraEnabled
    public static list<User> getUserAvailability(string roleName, datetime arr, datetime dep) {
        
        If (arr == null || dep == null){
            return null;
        } else{
            list<User> usrs = [select id, Phone, MobilePhone, Name, NCM_Associates_Contact_ID__c, IsProfilePhotoActive, SmallPhotoUrl
                               from User 
                               where UserRole.Name = :roleName and isActive = true
                               order by Name
                              ];

            integer i = 0;
            while (i < usrs.size()){
                User usr = usrs.get(i);
                
                List<Event> evts = [select id 
                                    from Event 
                                    where OwnerId = :usr.id and (StartDateTime < :dep or EndDateTime > :arr)
                                   ];

                if(evts.size() > 0){
                    usrs.remove(i);
                } else{
                    i++;
                }
            }

            System.debug(usrs);
            return usrs;
        }
    }

    @AuraEnabled
    public static list<String> getRoles(){
        list<string> roles = new list<string>();

        list<UserRole> usrRoles = [select Name 
                                   from UserRole
                                   order by Name
                                  ];
        
        for (UserRole usrRole : usrRoles){
            roles.add(usrRole.Name);
        }

        return roles;
    }

    @AuraEnabled
    public static list<string> getAttTypes(){
        
        List<String> lstPickvals=new List<String>();
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get('Engagement_Attendee__c');
        Sobject Object_name = targetType.newSObject();

        Schema.sObjectType sobject_type = Object_name.getSObjectType();
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();

        List<Schema.PicklistEntry> pick_list_values = field_map.get('Attendee_Type__c').getDescribe().getPickListValues(); 
        for (Schema.PicklistEntry a : pick_list_values) { 
            lstPickvals.add(a.getValue());
        }

        return lstPickvals;
    }

    @AuraEnabled
    public static Engagement_Attendee__c upsertAtt(Engagement_Attendee__c att){
        if (att.RecordTypeId == null){
            att.RecordTypeId = Schema.SObjectType.Engagement_Attendee__c.getRecordTypeInfosByName().get('NCM Attendee').getRecordTypeId();
        }
        
        upsert att;
        return att;
    }

    @AuraEnabled
    public static Engagement__c getEngagementValues(id engId){
        Engagement__c eng = [select id, Engagement_Start__c, Engagement_End__c 
                             from Engagement__c 
                             where id = :engId
                            ];

        return eng;
    }

    public static void cheatingTests(){
        integer i = 0;

        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}