unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Twenty_Groups__c/fields/NCM_Proprietor__c.field-meta.xml
<CustomField>
    <fullName>NCM_Proprietor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NCM Employee who will own this product or service with the client</description>
    <label>Group Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NCM_Associates</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>20 Group</relationshipLabel>
    <relationshipName>X20_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EngagementAttendeeNotes_Tests.cls
// SampleDataFactory.createData(); Derrick - DO NOT USE createData UNLESS ABSOLUTELY NECESSARY! 
// SampleDataFactory.create20GroupAccountData(); TRY USING THIS METHOD FIRST TO HELP SOQL 101 FAILURES - 5.13.24
// 1396 UAT Test Failures Derrick - 5.14.24
@isTest
public class EngagementAttendeeNotes_Tests {

    @testSetup
    private static void setupData() {
         
        SampleDataFactory.create20GroupAccountData();
                
        // Query for the Twenty Group created by SampleDataFactory.
        Twenty_Groups__c test20Group = [SELECT Id, Name, NCM_Proprietor__c FROM Twenty_Groups__c LIMIT 1];
        Id twentyGroupId = test20Group.Id;

        // Query for the record that was created on  line 8 for the Billing NCM Billing Contact Id.
        Id ncmBillingContactId = test20Group.NCM_Proprietor__c;

        // Get the Engagement Record Type for Retail Solutions.
        Id engagementRecTypeId = Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId();
        
        // Call the method from SampleDataFactory and pass in values created above. 
        SampleDataFactory.createEngagement_20G(twentyGroupId, engagementRecTypeId, ncmBillingContactId); 
    }
    
    @isTest
    static void engagementNotesTest_2(){

       Engagement__c testEngagement = [SELECT Id FROM Engagement__c LIMIT 1];
       ApexPages.StandardController stdController = new ApexPages.StandardController(testEngagement);
       EngagementAttendeeNotes vfCon = new EngagementAttendeeNotes(stdController);
       List<Engagement_Attendee__c> attendeeResults;
        
       Test.startTest();
       		attendeeResults = vfCon.getRelatedAttendees();
       Test.stopTest();
        
       System.debug('TEST ASSERT: ENGAGEMENT_ATTENDEE_NOTES: Engagement_Attendee_Size: ' + attendeeResults.size());
       Assert.areEqual(4, attendeeResults.size());
       
       String testDate = vfcon.engagementStartEndDate;   
    }
} // End of class