unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <formula>IF(
NOT(ISBLANK( X20_Group__c )),
 X20_Group__r.Name,
IF(
NOT(ISBLANK( Proprietary_Group__c )),
 Proprietary_Group__r.Group_Number__c  ,
&quot;&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Proprietary_Group__c.field-meta.xml
<CustomField>
    <fullName>Proprietary_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietary Group</label>
    <referenceTo>Proprietary_Group__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/X20_Group__c.field-meta.xml
<CustomField>
    <fullName>X20_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>20 Group</label>
    <referenceTo>Twenty_Groups__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendee_Notes__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Notes__c</fullName>
    <label>Attendee Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Collateral_Name__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Name__c</fullName>
    <label>Collateral Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_End__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start_Date__c</fullName>
    <formula>DATEVALUE( Engagement__r.Engagement_Start__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engagement Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Member_Number__c.field-meta.xml
<CustomField>
    <fullName>Member_Number__c</fullName>
    <formula>IF(
    NOT(ISBLANK(X20_Groups_Member__c)),
    X20_Groups_Member__r.Member_Number_Code__c,
    IF(
        NOT(ISBLANK(Proprietary_Account__c)),
        Proprietary_Account__r.Member_Number_Code__c,
        &quot;&quot;
    )
)</formula>
    <label>Member Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proprietary_Group__c/Proprietary_Group__c.object-meta.xml
<CustomObject>
    <label>Proprietary Group</label>
    <nameField>
        <label>Proprietary  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietary Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proprietary_Group__c/fields/Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Group_Number__c</fullName>
    <label>Group Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/EngagementAttendeeNotes.cls
public with sharing class EngagementAttendeeNotes {
    public Engagement__c engagement;
    public String engagementStartEndDate{
        get{
            String startDateFormat = '?';
            String endDateFormat = '?';
            String resultVal = '';
            
            Date startDate = Test.isRunningTest() ? Date.today() : engagement.Engagement_Start_Date__c; // We added this Test.isRunningTest check for UNIT TEST coverage only.
            if(startDate != null){
                DateTime startDT = DateTime.newInstance(
                    startDate.year(),
                    startDate.month(),
                    startDate.day()
                );
                startDateFormat = startDT.format('MMM dd');
            }
            
            Date endDate = Test.isRunningTest() ? Date.today().addDays(4) : engagement.Engagement_End_Date__c; // We added this Test.isRunningTest check for UNIT TEST coverage only.
            if(endDate != null){
                DateTime endDT = DateTime.newInstance(
                    endDate.year(),
                    endDate.month(),
                    endDate.day()
                );
                endDateFormat = endDT.format('MMM dd');
            }
            
            resultVal = startDateFormat + ' - ' + endDateFormat;
            
            return resultVal;
            
        }
    }
    public String groupNumber{
        get{
            if(engagement.X20_Group__c != null){
                return this.engagement.X20_Group__r.Name;
            } else {
                return this.engagement.Proprietary_Group__r.Group_Number__c;
            }
        }
    }
    public EngagementAttendeeNotes(ApexPages.StandardController stdController) {  
        if(!Test.isRunningTest()){
            stdController.addFields(new List<String>{'X20_Group__r.Name','Proprietary_Group__r.Group_Number__c','Engagement_Start_Date__c','Engagement_End_Date__c'});
        }
        this.engagement = (Engagement__c)stdController.getRecord();
    }
    
    public List<Engagement_Attendee__c> getRelatedAttendees() {
        List<Engagement_Attendee__c> attendees = new List<Engagement_Attendee__c>();
        for (Engagement_Attendee__c attendee : [SELECT Id, Collateral_Name__c, Attendee_Notes__c, Member_Number__c FROM Engagement_Attendee__c WHERE Engagement__c = :this.engagement.Id]) {
            if(attendee.Attendee_Notes__c != null){
            	 attendees.add(attendee);
            }
        }
        return attendees;
    }
}