unpackaged/main/default/objects/Room_Block_Selection__c/Room_Block_Selection__c.object-meta.xml
<CustomObject>
    <description>The customer&#39;s room selection (ex: Joe Martin from Martin GMC selected 5 Queen rooms, 3 King rooms, and 1 Efficiency room for this engagement)</description>
    <label>Room Block Selection</label>
    <nameField>
        <displayFormat>RBS-{000000}</displayFormat>
        <label>Room Block Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room Block Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Planned_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Planned_Arrival__c</fullName>
    <label>Planned Arrival</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Planned_Departure__c.field-meta.xml
<CustomField>
    <fullName>Planned_Departure__c</fullName>
    <label>Planned Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Room_Block_Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Room_Block_Survey_Response__c</fullName>
    <description>The parent Room Block Survey Response from the customer.</description>
    <label>Room Block Survey Response</label>
    <referenceTo>Room_Block_Survey_Response__c</referenceTo>
    <relationshipLabel>Room Block Selections</relationshipLabel>
    <relationshipName>Room_Block_Selections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Room_Count__c.field-meta.xml
<CustomField>
    <fullName>Room_Count__c</fullName>
    <description>The number of rooms needed for this room type</description>
    <label>Room Count</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Selection__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/Room_Block_Survey_Response__c.object-meta.xml
<CustomObject>
    <description>After we make the API call to Workato and send the list of member contacts to email.
Store each Member Contact in a Room Block Survey Response record.</description>
    <label>Room Block Survey Response</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Block Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Planned_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Planned_Arrival__c</fullName>
    <label>Planned Arrival</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Planned_Departure__c.field-meta.xml
<CustomField>
    <fullName>Planned_Departure__c</fullName>
    <label>Planned Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Room_Count__c.field-meta.xml
<CustomField>
    <fullName>Room_Count__c</fullName>
    <label>Room Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/Survey_Id__c.field-meta.xml
<CustomField>
    <fullName>Survey_Id__c</fullName>
    <externalId>true</externalId>
    <label>Survey Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Room_Block_Survey_Response__c/fields/SurveyResponseDate__c.field-meta.xml
<CustomField>
    <fullName>SurveyResponseDate__c</fullName>
    <description>The day and time the contact responded to the selection.</description>
    <label>Survey Response Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/RoomBlockSurveyResponse.cls
@RestResource(urlMapping='/RoomBlockSurveyResponse/*')
global class RoomBlockSurveyResponse {


    @HttpPost
    global static RoomBlockModel.RoomBlockSubmitResponse submitSurveyResponse(RoomBlockModel.RoomBlockSelectionRequest req){
        
        RoomBlockModel.RoomBlockSubmitResponse resp = new RoomBlockModel.RoomBlockSubmitResponse();
        String surveyId = String.escapeSingleQuotes(req.surveyId);
        
        // Find the survey id for this response.
        List<Room_Block_Survey_Response__c> rbRespResults = [select id from Room_Block_Survey_Response__c where Survey_Id__c = :surveyId];
        if(rbRespResults.isEmpty()){
            resp.statusCode = '500';
            resp.message = 'No survey found matching ' + surveyId;
            
        } else {
            
            
            Room_Block_Survey_Response__c r = rbRespResults[0];
            resetExistingRoomBlockSelections(r.Id); // Clear out any existing room selections (in case they have submitted their selections previously)
            r.SurveyResponseDate__c = DateTime.now();
            
            try{
                update(r);

                // Create Room Selection records
                List<Room_Block_Selection__c> roomSelections = new List<Room_Block_Selection__c>();
                for(RoomBlockModel.RoomSelection roomSel : req.rooms){
                    if(roomSel.roomCount == null || roomSel.roomCount < 1){
                        resp.statusCode = '500';
                        resp.message = 'Room selection invalid: must have a Room Count value that is a number greater than 0.';
                        return resp;
                    }
                    if(String.isBlank(roomSel.roomType)){
                        resp.statusCode = '500';
                        resp.message = 'Room selection invalid: a RoomType must be specified.';
                        return resp;
                    }

                    Room_Block_Selection__c rbSel = new Room_Block_Selection__c();
                    rbSel.Room_Block_Survey_Response__c = r.Id;
                    rbSel.Room_Count__c = roomSel.roomCount;
                    rbSel.Room_Type__c = roomSel.roomType;
                    rbSel.Planned_Arrival__c = roomSel.plannedArrival;
                    rbSel.Planned_Departure__c = roomSel.plannedDeparture;
                    
                    roomSelections.add(rbSel);
                }
                insert(roomSelections);
                System.debug('Inserted ' + roomSelections.size() + ' new room selections for ' + r.Id);

                resp.statusCode = '200';
                resp.message = 'Room selections saved';

            } catch (DmlException e){
                
                System.debug('Error saving room selections: ' + e.getMessage());
                Logger.logError('RoomBlockSurveyResponse', 'Error', UserInfo.getUserName(), 'Error saving rooming selections', e.getMessage(), e.getStackTraceString());
                
                resp.statusCode = '500';
                resp.message = 'Error updating rooming preferences: ' + e.getMessage();
                
            }
        }
    
        return resp;
    }


    private static void resetExistingRoomBlockSelections(String rbsId){
        List<Room_Block_Selection__c> existingRBS = [select id from Room_Block_Selection__c where Room_Block_Survey_Response__c = :rbsId];
        if(!existingRBS.isEmpty()){
            try{
                delete(existingRBS);
            } catch(DmlException dex){
                System.debug('Error deleting existing room block selections: ' + dex.getMessage());
                Logger.logError('RoomBlockSurveyResponse', 'Error', UserInfo.getUserName(), 'API error', dex.getMessage(), dex.getStackTraceString());
            }
        }
    }
    
}