unpackaged/main/default/objects/Activity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>CSS_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Total_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Participants__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Total Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagements (Account)</relationshipLabel>
    <relationshipName>Engagements_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_End__c.field-meta.xml
<CustomField>
    <fullName>Engagement_End__c</fullName>
    <label>Engagement End</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Owner__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>NCM Associates</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagements (Owner)</relationshipLabel>
    <relationshipName>Engagements_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Engagement_Start__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Start__c</fullName>
    <label>Engagement Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/NCM_Arrival__c.field-meta.xml
<CustomField>
    <fullName>NCM_Arrival__c</fullName>
    <label>NCM Arrival</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/NCM_Departure__c.field-meta.xml
<CustomField>
    <fullName>NCM_Departure__c</fullName>
    <label>NCM Departure</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Rooms_From__c.field-meta.xml
<CustomField>
    <fullName>Rooms_From__c</fullName>
    <label>Room Nights From</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/fields/Rooms_To__c.field-meta.xml
<CustomField>
    <fullName>Rooms_To__c</fullName>
    <label>Room Nights To</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <label>Arrival</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>RM-{00000000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Room__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/User/fields/NCM_Associates_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>NCM_Associates_Contact_ID__c</fullName>
    <label>NCM Associates Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/engagementControllersTest.cls
@isTest (SeeAllData=true)
public class engagementControllersTest {

    static testMethod void testGetRooms() {
        
        Test.startTest();
        
        List<engagementControllers.vars> vars = new List<engagementControllers.vars>();
        engagementControllers.vars var = new engagementControllers.vars();
        var.memCnt = 10;

        id usrConId = [select id, NCM_Associates_Contact_ID__c from User where id = :UserInfo.getUserId()].NCM_Associates_Contact_ID__c;
        Engagement__c eng = createEngagement(usrConId);
        var.eng = eng;
        vars.add(var);

        list<list<Room__c>> roomsRet = new list<list<Room__c>>();
        try{
            roomsRet = engagementControllers.getRooms(vars);
        } catch(exception er){
            system.debug(er);
        }

        list<Room__c> rms = roomsRet.get(0);

        try{
            engagementControllers.updateRooms(rms);
        } catch(exception er){
            system.debug(er);
        }

        try{
            rms = engagementControllers.getRoomsForEngagement(eng.id);
        } catch(exception er){
            system.debug(er);
        }

        Test.stopTest();

    }

    static testMethod void testGetAttendeeActivityParticipation() {

        Test.startTest();

        id usrConId = [select id, NCM_Associates_Contact_ID__c from User where id = :UserInfo.getUserId()].NCM_Associates_Contact_ID__c;
        id ncmAccId = [select id from Account where name = 'NCM Associates'].id;

        Engagement__c eng = createEngagement(usrConId);
        Engagement_Activity__c act = createActivity(eng.id);
        Engagement_Attendee__c att = createAttendee(eng.id, usrConId, ncmAccId);

        engagementControllers.getActivityParticipation(act.id);
        list<Activity_Participation__c> ptcs = engagementControllers.getAttendeeParticipation(att.id);

        for (Activity_Participation__c ptc : ptcs){
            ptc.Total_Number_of_Participants__c = 2;
        }

        engagementControllers.upsertParticipation(ptcs);

        Test.stopTest();

    }

    private static Engagement__c createEngagement(id usrConId){
        Engagement__c eng = new Engagement__c();
        eng.Engagement_Owner__c = usrConId;
        
        eng.Rooms_From__c = date.today();
        eng.Rooms_To__c = date.today().addDays(7);
        
        eng.Engagement_Start__c = Datetime.now().addDays(1);
        eng.Engagement_End__c = datetime.now().addDays(4);

        eng.NCM_Arrival__c = date.today();
        eng.NCM_Departure__c = date.today().addDays(5);

        insert eng;
        return eng;
    }

    private static Engagement_Activity__c createActivity(id engId){
        Engagement_Activity__c act = new Engagement_Activity__c();

        act.Engagement__c = engId;
        act.Name = 'Test Activity';
        act.Start__c = datetime.now();
        act.End_Time__c = datetime.now().addHours(1);
        act.Description__c = 'Created during Test Run';

        insert act;
        return act;
    }

    private static Engagement_Attendee__c createAttendee(id engId, id usrConId, id ncmAccId){
        Engagement_Attendee__c att = new Engagement_Attendee__c();

        att.Contact__c = usrConId;
        att.Account__c = ncmAccId;
        att.Name = 'Test Attendee';
        att.Engagement__c = engId;
        att.Arrival__c = Datetime.now();
        att.Departure__c = datetime.now().addHours(1);

        insert att;
        return att;
    }

}