unpackaged/main/default/objects/Activity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>CSS_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Total_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Participants__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Total Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ActivityParticipationController.cls
public class ActivityParticipationController {
    
    //create a class for an object to return a list of to LWC
    public class Act {
        @AuraEnabled public String Id;
        @AuraEnabled public String attId;
        @AuraEnabled public String Name;
        @AuraEnabled public Boolean Bool;
    }
    
    //this method is wired to the lwc
    @AuraEnabled(cacheable=true)
    public static List<Act> getActivities(String engAttendeeId){
        System.debug('~~~starting getActivities with: ' + engAttendeeId);
        try { 
            List<Act> actList = new List<Act>();
            Map<Id, Activity_Participation__c> apMap = new Map<Id, Activity_Participation__c>();

            //Query to get the list of Activity Participations for this Engagement Attendee
            Engagement_Attendee__c att = [SELECT Id, Engagement__c,
                                                (SELECT Id, 
                                                        Engagement_Activity__c, 
                                                        Total_Number_of_Participants__c 
                                                FROM Activity_Participation__r)
                                            FROM Engagement_Attendee__c
                                            WHERE Id = :engAttendeeId];
            System.debug('~~~att: ' + att);
            System.debug('~~~att.participations: ' + att.Activity_Participation__r);
            //Loop through the list and make a map with key of Id and value of the 
            //Activity Participation. Filter out Activity Participations with 0
            //Total Number of Participants.
            for(Activity_Participation__c ap : att.Activity_Participation__r) {
                if(ap.Total_Number_of_Participants__c > 0) {
                    apMap.put(ap.Engagement_Activity__c,ap);
                }
            }
                        
            //Loop through all activities for the engagement, check if this attendee is participating, 
            //and then create an Act and add it to the list to return.
            for(Engagement_Activity__c a : [SELECT Id, Name
                                                FROM Engagement_Activity__c
                                                WHERE Engagement__c = :att.Engagement__c]) {
                System.debug('~~~current activity: ' + a);
                Act currAct = new Act();
                currAct.attId = engAttendeeId;
                currAct.Id = a.Id;
                currAct.Name = a.Name;
                currAct.Bool = false;
                if(apMap.containsKey(a.Id) && apMap.get(a.Id).Total_Number_of_Participants__c > 0) {
                    currAct.Bool = true;
                }
                actList.add(currAct);
            }
            System.debug('~~~actList: ' + actList);
            return actList;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //this method is called by the lwc when the box is checked
    @AuraEnabled
    public static void makeActivityParticipation(String att, String act){
        try {
            insert new Activity_Participation__c(Engagement_Attendee__c = att, Engagement_Activity__c = act);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //this method is called by the lwc when the box is unchecked. It intentionally deletes all activity participations
    //for this activity and this attendee, in case there is bad data.
    @AuraEnabled
    public static void deleteActivityParticipation(String att, String act){
        try {
            delete [SELECT Id FROM Activity_Participation__c WHERE Engagement_Attendee__c = :att AND Engagement_Activity__c = :act];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}