unpackaged/main/default/objects/Activity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>CSS_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/recordTypes/Reception.recordType-meta.xml
<RecordType>
    <fullName>Reception</fullName>
    <active>true</active>
    <label>Reception</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <description>Added Removed Status. 8.21.2023</description>
    <label>Attendance Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tentative</fullName>
                <default>true</default>
                <label>Tentative</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Registration Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rebooking</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Self Study</fullName>
            </value>
            <value>
                <fullName>Sale Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
            <value>
                <fullName>Pending Class</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Waitlist Expired</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Twenty_Groups__c/Twenty_Groups__c.object-meta.xml
<CustomObject>
    <label>20 Groups</label>
    <nameField>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>20 Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/EngRostPortalServiceTests.cls
@isTest
public class EngRostPortalServiceTests {
    
    @TestSetup
    static void makeData(){

        // Create Accounts and 20G Members
        SampleDataFactory.create20GroupAccountData();
        String twentyGroupId = [SELECT Id FROM Twenty_Groups__c LIMIT 1].Id;
        String ncmAssocRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NCM Associates').getRecordTypeId();
        String ncmBillingContactId = [SELECT Id FROM Contact WHERE RecordTypeId = :ncmAssocRecTypeId LIMIT 1].Id;
        
        // Create Engagement data
        Engagement__c testEngagement = SampleDataFactory.createEngagement_20G(
            twentyGroupId,
            Schema.SObjectType.Engagement__c.getRecordTypeInfosByName().get('Retail Solutions').getRecordTypeId(),
            ncmBillingContactId
        ); 


        // Create Engagement Activities
        Engagement_Activity__c testActivity = new Engagement_Activity__c(
            Engagement__c = testEngagement.Id,
            Name = 'Dinner Reception',
            RecordTypeId = Schema.SObjectType.Engagement_Activity__c.getRecordTypeInfosByName().get('Engagement Activity').getRecordTypeId()
        );
        insert(testActivity);


        // Create Activity Participation records
        List<Activity_Participation__c> apList = new List<Activity_Participation__c>();
        for(Engagement_Attendee__c att:[SELECT Id FROM Engagement_Attendee__c]){
            Activity_Participation__c ap = new Activity_Participation__c(
              Engagement__c = testEngagement.Id,
              Engagement_Attendee__c = att.Id,
              Engagement_Activity__c = testActivity.Id  
            );
            apList.add(ap);
        }
        insert(apList);
    }


    @isTest
    static void rosterTest(){
      
        String engagementId = [SELECT Id FROM Engagement__c LIMIT 1].Id;

        RestRequest req = new RestRequest();
        req.httpMethod = 'GET';
        req.requestURI =  URL.getOrgDomainUrl() + '/services/apexrest/EngRostPortalAPI/' + engagementId;
        RestContext.request = req;

        EngagementRosterModel.EngagementRosterResponse apiResponse;
        

        Test.startTest();
            apiResponse = EngRostPortalService.getEngRostPortal();
        Test.stopTest();

        System.assertNotEquals('500', apiResponse.statusCode);
        System.assertNotEquals(null, apiResponse.engagement);
        System.assertNotEquals(null, apiResponse.engagement.attendees);


    }


    @isTest
    static void cancelledAttendeesAreExcludedTest(){
        
        String engagementId = [SELECT Id, Engagement__c FROM Engagement_Attendee__c LIMIT 1].Engagement__c;
        List<Engagement_Attendee__c> attendeeList = [select id, Attendance_Status__c from Engagement_Attendee__c where Engagement__c = :engagementId];
        System.assertNotEquals(0, attendeeList.size());

        Engagement_Attendee__c testAtt = attendeeList[0];
        testAtt.Attendance_Status__c = 'Cancelled';
        update(testAtt);

        RestRequest req = new RestRequest();
        req.httpMethod = 'GET';
        req.requestURI =  URL.getOrgDomainUrl() + '/services/apexrest/EngRostPortalAPI/' + engagementId;
        RestContext.request = req;

        EngagementRosterModel.EngagementRosterResponse apiResponse;
        

        Test.startTest();
            apiResponse = EngRostPortalService.getEngRostPortal();
        Test.stopTest();

        System.assertNotEquals('500', apiResponse.statusCode);
        System.assertNotEquals(null, apiResponse.engagement);
        System.assertNotEquals(null, apiResponse.engagement.attendees);
        // Important test for this check
        System.assertEquals(attendeeList.size() - 1, apiResponse.engagement.attendees.size()); // The results should not include the cancelled attendee.

    }

    @isTest
    static void rosterWithNoResultTest(){
      
        String engagementId = 'abc123'; // This is not a valid Engagement ID so we should get a 500 response.

        RestRequest req = new RestRequest();
        req.httpMethod = 'GET';
        req.requestURI =  URL.getOrgDomainUrl() + '/services/apexrest/EngRostPortalAPI/' + engagementId;
        RestContext.request = req;

        EngagementRosterModel.EngagementRosterResponse apiResponse;
        

        Test.startTest();
            apiResponse = EngRostPortalService.getEngRostPortal();
        Test.stopTest();

        System.assertEquals('500', apiResponse.statusCode);
        System.assertEquals(null, apiResponse.engagement);

    }


}