unpackaged/main/default/objects/Activity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>CSS_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Total_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Participants__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Total Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <label>Meeting</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Activity__c/recordTypes/Reception.recordType-meta.xml
<RecordType>
    <fullName>Reception</fullName>
    <active>true</active>
    <label>Reception</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/In_Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>In_Meeting_Room__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Meeting Room</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ActivityParticipationUtility_Test.cls
@isTest
private class ActivityParticipationUtility_Test {

    @testSetup
    static void makeData() {
        Account acct = new Account(Name = 'Test');
        insert(acct);
        Contact con = new Contact(LastName = 'Test', FirstName = 'Test', AccountId = acct.Id);
        insert(con);
        Engagement__c eng = new Engagement__c(Name = 'Test Eng');
        insert(eng);
        Engagement_Attendee__c ea = new Engagement_Attendee__c(Name = 'test', Engagement__c = eng.Id,
        Contact__c = con.Id);
        insert ea;
        Id meetingRTId = Schema.SObjectType.Engagement_Activity__c.getRecordTypeInfosByName().get('Meeting').getRecordTypeId();
        Id receptionRTId = Schema.SObjectType.Engagement_Activity__c.getRecordTypeInfosByName().get('Reception').getRecordTypeId();
        Id activityRTId = Schema.SObjectType.Engagement_Activity__c.getRecordTypeInfosByName().get('Engagement Activity').getRecordTypeId();
        Engagement_Activity__c act1 = new Engagement_Activity__c(Name = 'test', Engagement__c = eng.Id, RecordTypeId = meetingRTId);
        Engagement_Activity__c act2 = new Engagement_Activity__c(Name = 'test', Engagement__c = eng.Id, RecordTypeId = meetingRTId);
        Engagement_Activity__c act3 = new Engagement_Activity__c(Name = 'test', Engagement__c = eng.Id, RecordTypeId = receptionRTId);
        Engagement_Activity__c act4 = new Engagement_Activity__c(Name = 'test', Engagement__c = eng.Id, RecordTypeId = activityRTId);
        insert(new List<Engagement_Activity__c>{act1, act2, act3, act4}); 
        
    }

    @isTest
    static void testSinglePositive() {
        Engagement_Attendee__c ea = [SELECT Id FROM Engagement_Attendee__c LIMIT 1];
        List<Engagement_Activity__c> acts = [SELECT Id FROM Engagement_Activity__c];
        Test.startTest();
        insert(new Activity_Participation__c(Engagement_Attendee__c = ea.Id, Engagement_Activity__c = acts[0].Id));
        Test.stopTest();
        Engagement_Attendee__c ea1 = [SELECT Id, In_Meeting_Room__c FROM Engagement_Attendee__c WHERE Id = :ea.Id];
        Assert.isTrue(ea1.In_Meeting_Room__c);
    }

    @isTest
    static void testSingleNegative() {
        Engagement_Attendee__c ea = [SELECT Id FROM Engagement_Attendee__c LIMIT 1];
        List<Engagement_Activity__c> acts = [SELECT Id FROM Engagement_Activity__c];
        Test.startTest();
        Activity_Participation__c ap = new Activity_Participation__c(Engagement_Attendee__c = ea.Id, Engagement_Activity__c = acts[0].Id);
        insert(ap);
        delete(ap);
        Test.stopTest();
        Engagement_Attendee__c ea1 = [SELECT Id, In_Meeting_Room__c FROM Engagement_Attendee__c WHERE Id = :ea.Id];
        Assert.isFalse(ea1.In_Meeting_Room__c);
    }

    @isTest
    static void testEditPositive() {
        Engagement_Attendee__c ea = [SELECT Id FROM Engagement_Attendee__c LIMIT 1];
        List<Engagement_Activity__c> acts = [SELECT Id FROM Engagement_Activity__c];
        Test.startTest();
        Activity_Participation__c ap = new Activity_Participation__c(Engagement_Attendee__c = ea.Id, Engagement_Activity__c = acts[0].Id);
        insert(ap);
        ap.Total_Number_of_Participants__c = 2;
        update(ap);
        Test.stopTest();
        Engagement_Attendee__c ea1 = [SELECT Id, In_Meeting_Room__c FROM Engagement_Attendee__c WHERE Id = :ea.Id];
        Assert.isTrue(ea1.In_Meeting_Room__c);
    }
}