unpackaged/main/default/objects/Activity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>CSS_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/Activity_Participation__c.object-meta.xml
<CustomObject>
    <label>Activity Participation</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Activity Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Activity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Activity__c</fullName>
    <label>Engagement Activity</label>
    <referenceTo>Engagement_Activity__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Activity Participation</relationshipLabel>
    <relationshipName>Activity_Participation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Activity_Participation__c/fields/Total_Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Participants__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Total Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>Shows the Activity and Participants for each Engagement Activity. It also has extra details.</description>
    <label>Engagement Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ActivityParticipationControllerTest.cls
@isTest
public class ActivityParticipationControllerTest {

    @IsTest
    static void getActivitiesTest(){
        
        String acctRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId();
        String contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();

        Account acct = new Account(
            RecordTypeId = acctRecType,
            Name = 'Sample Auto Group',
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            AccountSource = 'Marketing',        // required
            Industry = 'Auto Retail New',       // required
            Franchise_s__c = 'Chevrolet;Dodge;Ford;Jeep'

        );
        insert(acct);
        
        // Contact
        Contact con = new Contact(
                RecordTypeId = contactRecType,
                FirstName = 'Marv',
                LastName = 'Sampleton',
                AccountId = acct.Id,
                Email = 'marv.sampleton@ncmassociates.com',
                MailingStreet = '100 Automotive Way',
                MailingCity = 'Southport',
                MailingState = 'North Carolina',
                MailingPostalCode = '28461'
        );
        insert con;
              
        Engagement__c eng = new Engagement__c(Name = 'Test Engagament');
        insert eng;
        System.debug('~~~engagement inserted');
        Engagement_Activity__c act = new Engagement_Activity__c(Name = 'Test Activity', Engagement__c = eng.Id);
        insert act;
        System.debug('~~~activity inserted');
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(Contact__c = con.Id, Engagement__c = eng.Id);
        insert attendee;
        System.debug('~~~engagement Attendee inserted');
        Activity_Participation__c ap = new Activity_Participation__c(Engagement_Activity__c = act.Id, 
                                                                    Engagement_Attendee__c = attendee.Id,
                                                                    Total_Number_of_Participants__c = 1);
        insert ap;
        List<ActivityParticipationController.Act> acts = ActivityParticipationController.getActivities(attendee.Id);
        System.debug('~~~acts: ' + acts);
        Assert.isTrue(acts[0].Bool);
    }

    @IsTest
    static void makeActivityParticipationTest() {
        
        String acctRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId();
        String contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();

        Account acct = new Account(
            RecordTypeId = acctRecType,
            Name = 'Sample Auto Group',
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            AccountSource = 'Marketing',        // required
            Industry = 'Auto Retail New',       // required
            Franchise_s__c = 'Chevrolet;Dodge;Ford;Jeep'

        );
        insert(acct);
        
        // Contact
        Contact con = new Contact(
                RecordTypeId = contactRecType,
                FirstName = 'Marv',
                LastName = 'Sampleton',
                AccountId = acct.Id,
                Email = 'marv.sampleton@ncmassociates.com',
                MailingStreet = '100 Automotive Way',
                MailingCity = 'Southport',
                MailingState = 'North Carolina',
                MailingPostalCode = '28461'
        );
        insert con;
        
        Engagement__c eng = new Engagement__c(Name = 'Test Engagament');
        insert eng;
        System.debug('~~~engagement inserted');
        Engagement_Activity__c act = new Engagement_Activity__c(Name = 'Test Activity', Engagement__c = eng.Id);
        insert act;
        System.debug('~~~activity inserted');
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(Contact__c = con.Id, Engagement__c = eng.Id);
        insert attendee;
        System.debug('~~~engagement Attendee inserted');
        
        ActivityParticipationController.makeActivityParticipation(attendee.Id, act.Id);

        List<Activity_Participation__c> aps = [SELECT Id 
                                        FROM Activity_Participation__c 
                                        WHERE Engagement_Activity__c = :act.ID 
                                        AND Engagement_Attendee__c = :attendee.Id];
        Assert.areEqual(1, aps.size());
        
    }

    @IsTest
    static void deleteActivityParticipationTest(){

        String acctRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('NCM Client').getRecordTypeId();
        String contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Business Development Contact').getRecordTypeId();

        Account acct = new Account(
            RecordTypeId = acctRecType,
            Name = 'Sample Auto Group',
            BillingStreet = '1 Auto Way',
            BillingCity = 'Sampleton',
            BillingState = 'North Carolina',
            BillingPostalCode = '28461',
            BillingCountry = 'United States',
            AccountSource = 'Marketing',        // required
            Industry = 'Auto Retail New',       // required
            Franchise_s__c = 'Chevrolet;Dodge;Ford;Jeep'

        );
        insert(acct);
        
        Contact con = new Contact(
                RecordTypeId = contactRecType,
                FirstName = 'Marv',
                LastName = 'Sampleton',
                AccountId = acct.Id,
                Email = 'marv.sampleton@ncmassociates.com',
                MailingStreet = '100 Automotive Way',
                MailingCity = 'Southport',
                MailingState = 'North Carolina',
                MailingPostalCode = '28461'
        );
        insert con;

        Engagement__c eng = new Engagement__c(Name = 'Test Engagament');
        insert eng;
        System.debug('~~~engagement inserted');
        Engagement_Activity__c act = new Engagement_Activity__c(Name = 'Test Activity', Engagement__c = eng.Id);
        insert act;
        System.debug('~~~activity inserted');
        Engagement_Attendee__c attendee = new Engagement_Attendee__c(Contact__c = con.Id, Engagement__c = eng.Id);
        insert attendee;
        System.debug('~~~engagement Attendee inserted');
        Activity_Participation__c ap = new Activity_Participation__c(Engagement_Activity__c = act.Id, Engagement_Attendee__c = attendee.Id);
              
        ActivityParticipationController.deleteActivityParticipation(attendee.Id, act.Id);
        
        List<Activity_Participation__c> aps = [SELECT Id 
                                        FROM Activity_Participation__c 
                                        WHERE Engagement_Activity__c = :act.ID 
                                        AND Engagement_Attendee__c = :attendee.Id];
        Assert.areEqual(0, aps.size());
        
    }

}