unpackaged/main/default/objects/Activity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>CSS_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/Concur_Import__c.object-meta.xml
<CustomObject>
    <label>Concur Import</label>
    <nameField>
        <label>Concur Import Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concur Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Concur_Import__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/GL_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Name__c</fullName>
    <label>GL Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Line_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Id__c</fullName>
    <label>Line Item Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/List_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>List_Item_Id__c</fullName>
    <label>List Item Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Payment_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type_Id__c</fullName>
    <label>Payment Type Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Payment_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type_Name__c</fullName>
    <label>Payment Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Spend_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category_Code__c</fullName>
    <label>Spend Category Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Concur_Import__c/fields/Spend_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category_Name__c</fullName>
    <label>Spend Category Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/Engagement_Attendee__c.object-meta.xml
<CustomObject>
    <label>Engagement Attendee</label>
    <nameField>
        <label>Engagement Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Attendee_Code__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Code__c</fullName>
    <formula>Engagement__r.Engagement_Number__c &amp; &quot;-&quot; &amp; Text( Attendee_No__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attendee Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Attendee__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Attendees</relationshipLabel>
    <relationshipName>Engagement_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/Engagement_Expense__c.object-meta.xml
<CustomObject>
    <label>Engagement Expense</label>
    <nameField>
        <displayFormat>EXP-{YYYY}{MM}{DD}:{00000000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Concur_Line_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Concur_Line_Item_Id__c</fullName>
    <label>Concur Line Item Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Concur_Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Concur_Report_Id__c</fullName>
    <label>Concur Report Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Engagement_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement Attendee</label>
    <referenceTo>Engagement_Attendee__c</referenceTo>
    <relationshipLabel>Engagement Expenses</relationshipLabel>
    <relationshipName>Engagement_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/GL_Name__c.field-meta.xml
<CustomField>
    <fullName>GL_Name__c</fullName>
    <label>GL Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Payment_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type_Id__c</fullName>
    <label>Payment Type Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Payment_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type_Name__c</fullName>
    <label>Payment Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Spend_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category_Code__c</fullName>
    <label>Spend Category Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Spend_Category_Name__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category_Name__c</fullName>
    <label>Spend Category Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engagement_Expense__c/fields/Submitted_by__c.field-meta.xml
<CustomField>
    <fullName>Submitted_by__c</fullName>
    <label>Submitted by</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ConcurLoadTransfer.cls
public class ConcurLoadTransfer {
    
    public class vars {
        @InvocableVariable(label='Record Id' Required=true)
        public Id recId;
    }
    
	@InvocableMethod
    public static void ConcurLoadTransfer(List<vars> vars) {
        list<id> ids = new list<id>();
        for (vars var : vars){
            ids.add(var.recId);
        }
        
        List<Engagement_Expense__c> exps = new List<Engagement_Expense__c>();
        list<Concur_Import__c> imps = [select Id, Amount__c, Line_Item_Id__c, Report_Id__c, Item_Description__c, List_Item_Id__c, Transaction_Date__c,
                                              GL_Code__c, GL_Name__c, Spend_Category_Code__c, Spend_Category_Name__c, Payment_Type_Id__c, Payment_Type_Name__c
                                        from Concur_Import__c
                                        where id in :ids
                                      ];

        list<Concur_Import__c> errImps = new List<Concur_Import__c>();
        list<Concur_Import__c> delImps = new List<Concur_Import__c>();

        for(Concur_Import__c imp : imps){
            List<Engagement_Expense__c> dupeExps = [select id 
                                                    from Engagement_Expense__c 
                                                    where Concur_Line_Item_Id__c = :imp.Line_Item_Id__c
                                                   ];
            
            if(dupeExps.size() > 0){
                delImps.add(imp);
            } else{
                Engagement_Expense__c exp = new Engagement_Expense__c();
                exp.RecordTypeId = Schema.SObjectType.Engagement_Expense__c.getRecordTypeInfosByName().get('Activity Expense').getRecordTypeId();
                
                exp.Amount__c = imp.Amount__c;
                exp.Concur_Line_Item_Id__c = imp.Line_Item_Id__c;
                exp.Concur_Report_Id__c = imp.Report_Id__c;
                exp.Expense_Description__c = imp.Item_Description__c;
                exp.Transaction_Date__c = imp.Transaction_Date__c;

                exp.GL_Code__c = imp.GL_Code__c;
                exp.GL_Name__c = imp.GL_Name__c;

                exp.Spend_Category_Code__c = imp.Spend_Category_Code__c;
                exp.Spend_Category_Name__c = imp.Spend_Category_Name__c;
                
                exp.Payment_Type_Id__c = imp.Payment_Type_Id__c;
                exp.Payment_Type_Name__c = imp.Payment_Type_Name__c;
                
                if(imp.List_Item_Id__c == null){
                    imp.Error_Log__c = 'List Item Id is Null: You must provide a value';
                    imp.Error__c = true;
                    errImps.add(imp);
                } else{
                    try{
                        Engagement_Attendee__c att = [select id, name, Engagement__c 
                                                    from Engagement_Attendee__c 
                                                    where Attendee_Code__c = :imp.List_Item_Id__c
                                                    ];
                        exp.Engagement__c = att.Engagement__c;
                        exp.Engagement_Attendee__c = att.id;
                        exp.Submitted_by__c = att.Name;
                        exps.add(exp);
                    } catch (exception er){
                        imp.Error_Log__c = 'Could not find a matching List Item Id';
                        imp.Error__c = true;
                        errImps.add(imp);
                    }
                }
            }
        }

        if(exps.size() > 0 || test.isRunningTest()){
            list<Database.SaveResult> srList = database.insert(exps, false);

            integer i = 0;
            for(Database.SaveResult sr : srList){
                if(sr.isSuccess()){
                    delImps.add(imps.get(i));
                } else{
                    Concur_Import__c imp = imps.get(i);
                    imp.Error__c = true;
                    
                    string errLg = '';
                    for(database.error er : sr.errors){
                        errlg = er.message + ', ';
                    }
                    imp.Error_Log__c = errLg.left(errLg.length() - 2);
                    errImps.add(imp);
                }

                i++;
            }
        }

        if (delImps.size() > 0){
            database.delete(delImps, false);
        }

        if (errImps.size() > 0){
            database.update(errImps, false);
        }
    }

    public static void cheatingTests(){
        integer i = 0;

        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}